/* Developer options of the Nexus 6 (LMY48Y) image (Settings.apk res/xml/development_prefs.xml, SwitchPreference), generated by
   docs/devopts.py shamu from docs/devopts.template.js: the rows in the XML's order, the default summaries
   DevelopmentSettings shows, and the image's own Hungarian, German, French and Spanish texts. */
(() => {
  'use strict';
  const e = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]));
  // [kind, title, summary, setting key, depends on USB debugging, ...]; kind: check (CheckBoxPreference), switch
  // (SwitchPreference), choice (ListPreference: + entries, summaries or null, default index, dialog title), list (a row
  // with its summary: PreferenceScreen, Preference), scale (the animation scale dialog).
  const SECTIONS = [
    [
      "",
      [
        [
          "list",
          "Take bug report",
          ""
        ],
        [
          "list",
          "Desktop backup password",
          "Desktop full backups aren't currently protected"
        ],
        [
          "switch",
          "Stay awake",
          "Screen will never sleep while charging",
          "stayAwake"
        ],
        [
          "choice",
          "HDCP checking",
          "",
          "dev_hdcp_checking",
          false,
          [
            "Never check",
            "Check for DRM content only",
            "Always check"
          ],
          [
            "Never use HDCP checking",
            "Use HDCP checking for DRM content only",
            "Always use HDCP checking"
          ],
          1,
          "Set HDCP checking behavior"
        ],
        [
          "switch",
          "Enable Bluetooth HCI snoop log",
          "Capture all bluetooth HCI packets in a file",
          "btSnoopLog"
        ],
        [
          "switch",
          "OEM unlocking",
          "Allow the bootloader to be unlocked",
          "oemUnlock"
        ],
        [
          "list",
          "Process Stats",
          "Geeky stats about running processes"
        ]
      ]
    ],
    [
      "Debugging",
      [
        [
          "switch",
          "USB debugging",
          "Debug mode when USB is connected",
          "usbDebug"
        ],
        [
          "list",
          "Revoke USB debugging authorizations",
          ""
        ],
        [
          "switch",
          "Local terminal",
          "Enable terminal app that offers local shell access",
          "localTerminal"
        ],
        [
          "switch",
          "Bug report shortcut",
          "Show a button in the power menu for taking a bug report",
          "bugreportPower"
        ],
        [
          "switch",
          "Allow mock locations",
          "Allow mock locations",
          "mockLocations"
        ],
        [
          "switch",
          "Enable view attribute inspection",
          "",
          "viewAttributes"
        ],
        [
          "list",
          "Select debug app",
          "No debug application set"
        ],
        [
          "switch",
          "Wait for debugger",
          "Debugged application waits for debugger to attach before executing",
          "waitDebugger",
          true
        ],
        [
          "switch",
          "Verify apps over USB",
          "Check apps installed via ADB/ADT for harmful behavior.",
          "verifyUsb"
        ],
        [
          "switch",
          "Wireless display certification",
          "Show options for wireless display certification",
          "wifiDisplayCertification"
        ],
        [
          "switch",
          "Enable Wi‑Fi Verbose Logging",
          "",
          "wifiVerboseLogging"
        ],
        [
          "switch",
          "Aggressive Wi‑Fi to Cellular handover",
          "",
          "wifiAggressiveHandover"
        ],
        [
          "switch",
          "Always allow Wi‑Fi Roam Scans",
          "",
          "wifiRoamScans"
        ],
        [
          "choice",
          "Logger buffer sizes",
          "",
          "dev_select_logd_size",
          false,
          [
            "64K",
            "256K",
            "1M",
            "4M",
            "16M"
          ],
          [
            "64K per log buffer",
            "256K per log buffer",
            "1M per log buffer",
            "4M per log buffer",
            "16M per log buffer"
          ],
          1,
          "Select Logger sizes per log buffer"
        ]
      ]
    ],
    [
      "Input",
      [
        [
          "switch",
          "Show touches",
          "Show visual feedback for touches",
          "showTouches"
        ],
        [
          "switch",
          "Pointer location",
          "Screen overlay showing current touch data",
          "pointerLocation"
        ]
      ]
    ],
    [
      "Drawing",
      [
        [
          "switch",
          "Show surface updates",
          "Flash entire window surfaces when they update",
          "surfaceUpdates"
        ],
        [
          "switch",
          "Show layout bounds",
          "Show clip bounds, margins, etc.",
          "layoutBounds"
        ],
        [
          "switch",
          "Force RTL layout direction",
          "Force screen layout direction to RTL for all locales",
          "forceRtl"
        ],
        [
          "scale",
          "Window animation scale",
          "",
          "windowScale"
        ],
        [
          "scale",
          "Transition animation scale",
          "",
          "transitionScale"
        ],
        [
          "scale",
          "Animator duration scale",
          "",
          "animatorScale"
        ],
        [
          "choice",
          "Simulate secondary displays",
          "",
          "dev_overlay_display_devices",
          false,
          [
            "None",
            "720x480 mdpi",
            "720x480 mdpi (secure)",
            "1280x720 tvdpi",
            "1280x720 tvdpi (secure)",
            "1920x1080 xhdpi",
            "1920x1080 xhdpi (secure)",
            "1280x720 tvdpi and 1920x1080 xhdpi"
          ],
          null,
          0,
          "Simulate secondary displays"
        ]
      ]
    ],
    [
      "Hardware accelerated rendering",
      [
        [
          "switch",
          "Force GPU rendering",
          "Force use of GPU for 2d drawing",
          "forceGpu"
        ],
        [
          "switch",
          "Show GPU view updates",
          "Flash views inside windows when drawn with the GPU",
          "gpuUpdates"
        ],
        [
          "switch",
          "Show hardware layers updates",
          "Flash hardware layers green when they update",
          "layerUpdates"
        ],
        [
          "choice",
          "Debug GPU overdraw",
          "",
          "dev_debug_hw_overdraw",
          false,
          [
            "Off",
            "Show overdraw areas",
            "Show areas for Deuteranomaly"
          ],
          null,
          0,
          "Debug GPU overdraw"
        ],
        [
          "choice",
          "Debug non-rectangular clip operations",
          "",
          "dev_show_non_rect_clip",
          false,
          [
            "Off",
            "Draw non-rectangular clip region in blue",
            "Highlight tested drawing commands in green"
          ],
          null,
          0,
          "Debug non-rectangular clip operations"
        ],
        [
          "switch",
          "Force 4x MSAA",
          "Enable 4x MSAA in OpenGL ES 2.0 apps",
          "forceMsaa"
        ],
        [
          "switch",
          "Disable HW overlays",
          "Always use GPU for screen compositing",
          "disableOverlays"
        ],
        [
          "choice",
          "Simulate color space",
          "",
          "dev_simulate_color_space",
          false,
          [
            "Disabled",
            "Monochromacy",
            "Deuteranomaly (red-green)",
            "Protanomaly (red-green)",
            "Tritanomaly (blue-yellow)"
          ],
          null,
          0,
          "Simulate color space"
        ]
      ]
    ],
    [
      "Media",
      [
        [
          "switch",
          "Use AwesomePlayer (deprecated)",
          "Use AwesomePlayer instead of NuPlayer for most media playback",
          "useAwesomePlayer"
        ],
        [
          "switch",
          "Disable USB audio routing",
          "Disable automatic routing to USB audio peripherals",
          "usbAudioRouting"
        ]
      ]
    ],
    [
      "Monitoring",
      [
        [
          "switch",
          "Strict mode enabled",
          "Flash screen when apps do long operations on main thread",
          "strictMode"
        ],
        [
          "switch",
          "Show CPU usage",
          "Screen overlay showing current CPU usage",
          "showCpu"
        ],
        [
          "choice",
          "Profile GPU rendering",
          "",
          "dev_track_frame_time",
          false,
          [
            "Off",
            "On screen as bars",
            "In adb shell dumpsys gfxinfo"
          ],
          null,
          0,
          "Profile GPU rendering"
        ],
        [
          "choice",
          "Enable OpenGL traces",
          "",
          "dev_enable_opengl_traces",
          false,
          [
            "None",
            "Logcat",
            "Systrace (Graphics)",
            "Call stack on glGetError"
          ],
          null,
          0,
          "Enable OpenGL traces"
        ]
      ]
    ],
    [
      "Apps",
      [
        [
          "switch",
          "Don't keep activities",
          "Destroy every activity as soon as the user leaves it",
          "dontKeep"
        ],
        [
          "choice",
          "Background process limit",
          "",
          "dev_app_process_limit",
          false,
          [
            "Standard limit",
            "No background processes",
            "At most 1 process",
            "At most 2 processes",
            "At most 3 processes",
            "At most 4 processes"
          ],
          null,
          0,
          "Background process limit"
        ],
        [
          "switch",
          "Show all ANRs",
          "Show App Not Responding dialog for background apps",
          "showAnrs"
        ]
      ]
    ]
  ];
  // English -> [hu, de, fr, es] as the image's Settings.apk (or framework-res) translates it.
  const STRINGS = {
    "Take bug report":["Hibajelentés készítése","Fehlerbericht abrufen","Créer un rapport de bug","Crear informe de errores"],
    "Desktop backup password":["Asztali mentés jelszava","Desktop-Sicherungspasswort","Mot de passe sauvegarde PC","Contraseña para copias de ordenador"],
    "Desktop full backups aren't currently protected":["Az asztali teljes biztonsági mentések jelenleg nem védettek.","Vollständige Desktop-Sicherungen sind momentan nicht passwortgeschützt.","Les sauvegardes complètes sur PC ne sont pas protégées actuellement.","Las copias de seguridad completas de ordenador no están protegidas"],
    "Stay awake":["Nem kapcsolódik ki","Aktiv lassen","Rester activé","Pantalla activa"],
    "Screen will never sleep while charging":["A képernyő soha nem kapcsol ki töltés során","Display wird beim Laden nie in den Ruhezustand versetzt","L'écran ne se met jamais en veille lors du chargement.","La pantalla nunca entra en modo de suspensión si el dispositivo se está cargando"],
    "HDCP checking":["HDCP ellenőrzés","HDCP-Prüfung","Vérification HDCP","Comprobación de HDCP"],
    "Never check":["Ellenőrzés soha","Nie prüfen","Ne jamais vérifier","No comprobar"],
    "Check for DRM content only":["Csak DRM-tartalom ellenőrzése","Nur auf DRM-Inhalte prüfen","Vérifier le contenu GDN uniquement","Buscar solo contenido DRM"],
    "Always check":["Ellenőrzés mindig","Immer prüfen","Toujours vérifier","Comprobar siempre"],
    "Never use HDCP checking":["Soha ne használjon HDCP ellenőrzést","HDCP-Prüfung nie verwenden","Ne jamais utiliser la vérification HDCP","No utilizar comprobación de HDCP"],
    "Use HDCP checking for DRM content only":["Csak DRM-tartalomhoz használjon HDCP ellenőrzést","HDCP-Prüfung nur für DRM-Inhalte verwenden","Utiliser la vérification HDCP uniquement pour le contenu GDN","Utilizar comprobación de HDCP solo para contenido DRM"],
    "Always use HDCP checking":["Mindig használjon HDCP ellenőrzést","HDCP-Prüfung immer verwenden","Toujours utiliser la vérification HDCP","Utilizar siempre comprobación de HDCP"],
    "Set HDCP checking behavior":["HDCP-ellenőrzés beállítása","HDCP-Prüfverhalten festlegen","Config. vérification HDCP","Definir comprobación HDCP"],
    "Enable Bluetooth HCI snoop log":["Bluetooth HCI snoop napló engedélyezése","Bluetooth HCI-Snoop-Protokoll aktivieren","Activer journaux HCI Bluetooth","Registro de búsqueda de HCI Bluetooth"],
    "Capture all bluetooth HCI packets in a file":["Az összes Bluetooth HCI-csomag rögzítése egy fájlban","Alle Bluetooth HCI-Pakete in einer Datei erfassen","Enregistrer tous les paquets HCI Bluetooth dans un fichier","Capturar todos los paquetes de HCI de Bluetooth HCI en un archivo"],
    "OEM unlocking":["OEM-feloldás","OEM-Entsperrung","Déverrouillage OEM","Desbloqueo de OEM"],
    "Allow the bootloader to be unlocked":["A rendszerbetöltő feloldásának engedélyezése","Bootloader-Entsperrung zulassen","Autoriser le déverrouillage du chargeur d'amorçage","Permitir desbloquear el gestor de arranque"],
    "Process Stats":["Folyamatstatisztikák","Prozessstatistiken","Statistiques relatives aux processus","Estadísticas de procesos"],
    "Geeky stats about running processes":["A futó folyamatok statisztikái","Statistiken zu laufenden Prozessen","Statistiques détaillées relatives aux processus en cours d'exécution","Estadísticas técnicas sobre procesos en ejecución"],
    "Debugging":["Hibakeresés","Debugging","Débogage","Depuración"],
    "USB debugging":["USB hibakeresés","USB-Debugging","Débogage USB","Depuración USB"],
    "Debug mode when USB is connected":["Hibakeresés mód USB csatlakoztatásakor","Debugmodus bei Anschluss über USB","Mode débogage lorsqu'un câble USB est connecté","Activar el modo de depuración cuando el dispositivo esté conectado por USB"],
    "Revoke USB debugging authorizations":["USB-s hibakeresésre vonatkozó engedélyek visszavonása","Autorisierungen für USB-Debugging aufheben","Annuler autorisations pour débog. USB","Revocar autorizaciones depur. USB"],
    "Local terminal":["Helyi végpont","Lokales Terminal","Terminal local","Terminal local"],
    "Enable terminal app that offers local shell access":["Végalkalmazás engedélyezése a helyi rendszerhéj eléréséhez","Terminal-App mit Zugriff auf lokale Shell aktivieren","Activer l'application Terminal permettant l'accès au shell local","Habilitar aplicación de terminal que ofrece acceso a shell local"],
    "Bug report shortcut":["Hibajelentés gyorsparancs","Verknüpfung zu Fehlerbericht","Raccourci vers le rapport d'erreur","Acceso directo a informe de errores"],
    "Show a button in the power menu for taking a bug report":["Gomb megjelenítése az áramellátási menüben hibajelentés készítéséhez","Schaltfläche zum Abrufen von Fehlerberichten im Menü \"Ein/Aus\" anzeigen","Afficher un bouton dans le menu de démarrage permettant de créer un rapport d'erreur","Mostrar un botón en el menú de encendido para recopilar un informe de error"],
    "Allow mock locations":["Helyutánzatok engedélyezése","Simulierte Standorte","Positions fictives","Ubicaciones simuladas"],
    "Enable view attribute inspection":["Nézetattribútum vizsgálatának engedélyezése","Inspektion der Anzeigeattribute aktivieren","Activer l'inspection d'attribut d'affichage","Habilitar inspección de atributos de vista"],
    "Select debug app":["Válassza az alkalmazás hibakeresése lehetőséget","Debugging-App festlegen","Sélectionner une application à déboguer","Aplicación para depurar"],
    "No debug application set":["Nincs beállítva alkalmazás hibakereséshez","Keine Debugging-App festgelegt","Aucune application à déboguer définie","Aplicación de depuración no configurada"],
    "Wait for debugger":["Várjon a hibakeresőre.","Auf Debugger warten","Attendre l'intervention du débogueur","Esperar al depurador"],
    "Debugged application waits for debugger to attach before executing":["A javított alkalmazás a hibakeresőre vár.","App wartet vor der Ausführung auf den Start des Debuggers","Avant de s'exécuter, l'application déboguée doit attendre que le débogueur soit attaché.","La aplicación de depuración espera a que se conecte el depurador para ejecutarse"],
    "Verify apps over USB":["USB-n keresztül telepített alkalmazások ellenőrzése","Apps über USB bestätigen","Vérifier les applis via USB","Verificar aplicaciones por USB"],
    "Check apps installed via ADB/ADT for harmful behavior.":["Az ADB/ADT útján telepített alkalmazások ellenőrzése kártékony viselkedésre.","Überprüft installierte Apps über ADB/ADT auf schädliches Verhalten","Vérifiez que les applications installées par ADB/ADT ne présentent pas de comportement dangereux.","Comprueba las aplicaciones instaladas mediante ADB/ADT para detectar comportamientos dañinos"],
    "Wireless display certification":["Vezeték nélküli kijelző tanúsítványa","Kabellose Übertragung","Certification de l'affichage sans fil","Certificación de pantalla inalámbrica"],
    "Show options for wireless display certification":["Beállítások megjelenítése a vezeték nélküli kijelző tanúsítványával kapcsolatban","Optionen zur Zertifizierung für kabellose Übertragung anzeigen","Afficher les options de la certification de l'affichage sans fil","Mostrar opciones de certificación de pantalla inalámbrica"],
    "Enable Wi‑Fi Verbose Logging":["Részletes Wi-Fi-naplózás engedélyezése","Ausführliche WLAN-Protokolle aktivieren","Autoriser enreg. infos Wi-Fi détaillées","Habilitar registro Wi-Fi detallado"],
    "Aggressive Wi‑Fi to Cellular handover":["Agresszív Wi‑Fi–mobilhálózat átadás","Aggressives Handover von WLAN an Mobilfunk","Passage forcé du Wi-Fi aux données mobiles","Transferencia total de Wi‑Fi a móvil"],
    "Always allow Wi‑Fi Roam Scans":["Wi‑Fi-roaming ellenőrzésének engedélyezése mindig","WLAN-Roamingsuchen immer zulassen","Toujours autoriser la détection de réseaux Wi-Fi en itinérance","Permitir siempre búsquedas de Wi-Fi"],
    "Logger buffer sizes":["Logger pufferméret","Logger-Puffergrößen","Tailles des mémoires tampons Logger","Tamaños de búfer de Logger"],
    "64K":["64 KB","64.000","64 Ko","64 K"],
    "256K":["256 KB","256.000","256 Ko","256 K"],
    "1M":["1 MB","1 Mio.","1 Mo","1 M"],
    "4M":["4 MB","4 Mio.","4 Mo","4 M"],
    "16M":["16 MB","16 Mio.","16 Mo","16 M"],
    "64K per log buffer":["64 KB/naplópuffer","64.000 pro Puffer","64 Ko/tampon journal","64 K/búfer registro"],
    "256K per log buffer":["256 KB/naplópuffer","256.000 pro Puffer","256 Ko/tampon journal","256 K/búfer registro"],
    "1M per log buffer":["1 MB/naplópuffer","1 Mio. pro Puffer","1 Mo/tampon journal","1 M/búfer registro"],
    "4M per log buffer":["4 MB/naplópuffer","4 Mio. pro Puffer","4 Mo/tampon journal","4 M/búfer registro"],
    "16M per log buffer":["16 MB/naplópuffer","16 Mio. pro Puffer","16 Mo/tampon journal","16 M/búfer registro"],
    "Select Logger sizes per log buffer":["Logger naplópufferméret választása","Größe pro Protokollpuffer wählen","Tailles Logger par tampon journal","Elegir tamaños Logger/búfer registro"],
    "Input":["Bevitel","Eingabe","Saisie","Entrada"],
    "Show touches":["Érintések megjelenítése","Berührungen anzeigen","Afficher élément sélectionné","Mostrar pulsaciones"],
    "Show visual feedback for touches":["Érintések vizuális visszajelzésének megjelenítése","Visuelles Feedback für Berührungen anzeigen","Afficher repère visuel pour éléments sélectionnés","Mostrar la ubicación de las pulsaciones en la pantalla"],
    "Pointer location":["Mutató helye","Zeigerposition","Emplacement du curseur","Ubicación del puntero"],
    "Screen overlay showing current touch data":["A fedvény mutatja az aktuális érintési adatokat","Overlay mit aktuellen Daten zu Tippaktionen","Superposition écran indiquant données actuelles","Superponer los datos de las pulsaciones en la pantalla"],
    "Drawing":["Rajz","Zeichnung","Tracé","Dibujo"],
    "Show surface updates":["Képernyőfrissítések megj.","Oberflächenaktualisierungen","Affich. mise à jour surface","Cambios de superficie"],
    "Flash entire window surfaces when they update":["A teljes ablakfelület villogjon frissítéskor.","Flash für gesamte Fensteroberfläche bei Aktualisierung","Faire clignoter les surfaces à chaque mise à jour","Actualizar superficies de ventana al actualizarse"],
    "Show layout bounds":["Elrendezéshatár mutatása","Layoutgrenzen einblenden","Afficher les contours","Mostrar límites de diseño"],
    "Show clip bounds, margins, etc.":["Kliphatárok, margók stb. megjelenítése.","Clip-Begrenzungen, Ränder usw. anzeigen","Afficher les limites, les marges de clip, etc.","Mostrar límites de vídeo, márgenes, etc."],
    "Force RTL layout direction":["Elrendezés jobbról balra","RTL-Layout erzwingen","Forcer droite à gauche","Forzar dirección diseño RTL"],
    "Force screen layout direction to RTL for all locales":["Elrendezés jobbról balra minden nyelvnél","RTL-Bildschirmlayout für alle Sprachen erzwingen","Forcer orient. droite à gauche pour toutes langues","Forzar dirección (RTL) para todas configuraciones"],
    "Window animation scale":["Ablakanimáció mérete","Maßstab Fensteranimation","Échelle animation fenêtres","Escala de animación ventana"],
    "Transition animation scale":["Áttűnési animáció mérete","Maßstab Übergangsanimation","Échelle anim. transitions","Escala de transición-animación"],
    "Animator duration scale":["Animáció léptéke","Maßstab für Animatorzeit","Échelle durée animation","Escala de duración de animador"],
    "Simulate secondary displays":["Másodlagos kijelzők szimulálása","Sekundäre Displays simulieren","Simuler des écrans secondaires","Simular pantallas secundarias"],
    "None":["Egyik sem","Keine","Aucun","Ninguna"],
    "720x480 mdpi":["720x480 mdpi","720 x 480 mdpi","720 x 480 mdpi","720 x 480 mdpi"],
    "720x480 mdpi (secure)":["720x480 mdpi (biztonságos)","720 x 480 mdpi (sicher)","720 x 480 mdpi (sécurisé)","720x480 mdpi (seguro)"],
    "1280x720 tvdpi":["1280x720 tvdpi","1.280 x 720 tvdpi","1 280 x 720 tvdpi","1280 x 720 tvdpi"],
    "1280x720 tvdpi (secure)":["1280x720 tvdpi (biztonságos)","1.280 x 720 tvdpi (sicher)","1 280 x 720 tvdpi (sécurisé)","1280x720 tvdpi (seguro)"],
    "1920x1080 xhdpi":["1920x1080 xhdpi","1.920 x 1.080 xhdpi","1 920 x 1 080 xhdpi","1920x1080 xhdpi"],
    "1920x1080 xhdpi (secure)":["1920x1080 xhdpi (biztonságos)","1.920 x 1.080 xhdpi (sicher)","1 920 x 1 080 xhdpi (sécurisé)","1920x1080 xhdpi (seguro)"],
    "1280x720 tvdpi and 1920x1080 xhdpi":["1280x720 tvdpi és 1920x1080 xhdpi","1.280 x 720 tvdpi und 1.920 x 1.080 xhdpi","1 280 x 720 tvdpi et 1 920 x1 080 xhdpi","1280x720 tvdpi y 1920x1080 xhdpi"],
    "Hardware accelerated rendering":["Hardveres gyorsítású megjelenítés","Hardwarebeschleunigtes Rendering","Accélération matérielle","Renderización acelerada por hardware"],
    "Force GPU rendering":["GPU-megjelenítés","GPU-Rendering erzwingen","Forcer le rendu GPU","Forzar aceleración GPU"],
    "Force use of GPU for 2d drawing":["GPU használatának kényszerítése 2D rajzhoz","Einsatz von GPU für 2D-Zeichnung erzwingen","Forcer l'utilisation du GPU pour le dessin 2D","Forzar uso de GPU para dibujos en 2D"],
    "Show GPU view updates":["GPU-nézetfriss. megjel.","Updates mit GPU-Ansicht","Afficher mises à jour GPU","Actualizaciones GPU"],
    "Flash views inside windows when drawn with the GPU":["Ablakbeli nézetek villognak GPU-s rajznál.","Flash-Ansicht im Fenster, wenn mit GPU dargestellt","Faire clignoter les éléments dessinés avec le GPU","Actualizar vistas de las ventanas creadas con GPU"],
    "Show hardware layers updates":["Hardverréteg-frissítések","Hardwareebenen-Updates","Mises à jour couches matérielles","Ver actualizaciones capas"],
    "Flash hardware layers green when they update":["Frissítéskor a hardverrétegek zölden villognak","Hardwareebenen blinken beim Aktualisieren grün","Couches matérielles en vert une fois mises à jour","Iluminar capas de hardware en verde al actualizarse"],
    "Debug GPU overdraw":["GPU tartalom-felülírási hibakeresés","Debugging – GPU-Überschneidung","Déboguer les conflits GPU","Depurar sobredibujos de GPU"],
    "Off":["Ki","Aus","Désactivé","No"],
    "Show overdraw areas":["Tartalom-felülírási területek mutatása","Überschneidungsbereiche anzeigen","Afficher les zones de conflit","Mostrar áreas sobredibujadas"],
    "Show areas for Deuteranomaly":["A deuteranomália területeinek megjelenítése","Bereiche für Deuteranomalie anzeigen","Afficher couleurs de zones adaptées à deutéranomalie","Mostrar áreas para deuteranomalía"],
    "Debug non-rectangular clip operations":["Nem négyzetes kivágási műveletek hibakeresése","Nicht rechteckige Clip-Operationen debuggen","Déboguer opé. de découpage non rect.","Depurar operaciones de recorte no rectangulares"],
    "Draw non-rectangular clip region in blue":["Nem négyzetes kivágás kékkel","Nicht rechteckigen Clipbereich blau zeichnen","Dessiner zone de découpage non rectangulaire en bleu","Dibujar región de recorte no rectangular en azul"],
    "Highlight tested drawing commands in green":["Tesztelt rajzolási parancsok kiemelése zölddel","Getestete Zeichenbefehle grün hervorheben","Surligner en vert les commandes de dessin testées","Resaltar comandos de dibujo probados en verde"],
    "Force 4x MSAA":["4x MSAA kényszerítése","4x MSAA erzwingen","Forcer MSAA 4x","Forzar MSAA 4x"],
    "Enable 4x MSAA in OpenGL ES 2.0 apps":["A 4x MSAA engedélyezése az OpenGL ES 2.0-nál","4x MSAA in OpenGL ES 2.0-Apps aktivieren","Activer MSAA 4x dans les applications OpenGL ES 2.0","Habilitar MSAA 4x en aplicaciones de OpenGL ES 2.0"],
    "Disable HW overlays":["HW fedvények letiltása","HW-Overlays deaktivieren","Désactiver superpos. matér.","Inhabilitar superposiciones HW"],
    "Always use GPU for screen compositing":["Mindig a GPU használata képernyő-feldolgozáshoz","GPU immer für Bildschirmaufbau verwenden","Toujours utiliser le GPU pour la composition écran","Usar siempre GPU para combinar pantallas"],
    "Simulate color space":["Színtérszimuláció","Farbraum simulieren","Simuler espace colori.","Simular espacio de color"],
    "Disabled":["Letiltva","Deaktiviert","Désactivé","Inhabilitado"],
    "Monochromacy":["Monokromázia","Farbenblindheit","Monochromatisme","Acromatopsia"],
    "Deuteranomaly (red-green)":["Színtévesztés (piros–zöld)","Deuteranomalie (Rot-Grün-Sehschwäche)","Deutéranomalie (rouge/vert)","Deuteronomalía (rojo-verde)"],
    "Protanomaly (red-green)":["Színtévesztés (piros– zöld)","Protanomalie (Rot-Grün-Sehschwäche)","Protanomalie (rouge/vert)","Protanomalía (rojo-verde)"],
    "Tritanomaly (blue-yellow)":["Színtévesztés (kék–sárga)","Tritanomalie (Blau-Gelb-Sehschwäche)","Tritanomalie (bleu-jaune)","Tritanomalía (azul-amarillo)"],
    "Media":["Média","Medien","Multimédia","Multimedia"],
    "Use AwesomePlayer (deprecated)":["AwesomePlayer (megszűnt)","AwesomePlayer (eingestellt) nutzen","Utiliser AwesomePlayer (obsolète)","Usar AwesomePlayer (obsoleto)"],
    "Use AwesomePlayer instead of NuPlayer for most media playback":["Az AwesomePlayer használata a NuPlayer helyett","Für die meisten Medien AwesomePlayer statt NuPlayer verwenden","Utiliser AwesomePlayer au lieu de NuPlayer pour la lecture de la plupart des contenus médias","Reproducir con AwesomePlayer en vez de NuPlayer"],
    "Disable USB audio routing":["Hangátirányítás tiltása","USB-Audiorouting deaktivieren","Désact. routage audio USB","Inhabil enrutam audio USB"],
    "Disable automatic routing to USB audio peripherals":["Hangátirányítás tiltása az USB-s hangeszközöknél","Autom. Routing an externe USB-Audiogeräte deaktivieren","Désactiver routage auto vers périph. audio USB","Inhabil enrutamiento autom a periféricos audio USB"],
    "Monitoring":["Figyelés","Überwachung","Suivi","Supervisión"],
    "Strict mode enabled":["Szigorú mód engedélyezve","Strikter Modus aktiviert","Mode Strict activé","Modo estricto"],
    "Flash screen when apps do long operations on main thread":["Képernyővillogás a fő szál hosszú műveleteinél","Bei längeren Aktionen im Hauptthread Bildschirm kurz einblenden","Afficher un cadre rouge si le thread principal reste occupé","Destellar si las aplicaciones tardan mucho en el proceso principal"],
    "Show CPU usage":["CPU-használat mutatása","CPU-Auslastung anzeigen","Afficher mém. CPU utilisée","Mostrar uso de la CPU"],
    "Screen overlay showing current CPU usage":["Képernyőfedvény a jelenlegi CPU-használattal","Bildschirm-Overlay mit aktueller CPU-Auslastung","Superposition écran indiquant mémoire CPU utilisée","Suporponer el uso de la CPU en la pantalla"],
    "Profile GPU rendering":["Profil GPU-renderelésről","GPU-Rendering für Profil","Rendu GPU du profil","Perfil de renderización de GPU"],
    "On screen as bars":["A képernyőn sávként","Auf Bildschirm als Balken","À l'écran sous forme de barres","En pantalla como barras"],
    "In adb shell dumpsys gfxinfo":["adb shell dumpsys gfxinfo elemben","In adb shell dumpsys gfxinfo","Dans adb shell dumpsys gfxinfo","En adb shell dumpsys gfxinfo"],
    "Enable OpenGL traces":["OpenGL nyomon követése","OpenGL-Traces aktivieren","Activer les traces OpenGL","Habilitar seguimiento OpenGL"],
    "Logcat":["Logcat","Logcat","Logcat","Logcat"],
    "Systrace (Graphics)":["Systrace (grafika)","Systrace (Grafik)","Systrace (graphismes)","Systrace (gráficos)"],
    "Call stack on glGetError":["Verem meghívása glGetError esetén","Aufrufliste für glGetError","Appeler une pile sur glGetError","Pila de llamadas en glGetError"],
    "Apps":["Alkalmazások","Apps","Applications","Aplicaciones"],
    "Don't keep activities":["Törölje a tevékenységeket","Aktionen nicht speichern","Ne pas conserver activités","Destruir actividades"],
    "Destroy every activity as soon as the user leaves it":["Tevékenységek törlése, amint elhagyják azokat","Aktivität löschen, sobald der Nutzer diese beendet","Supprimer immédiatement les activités abandonnées","Destruir actividades cuando el usuario deje de usarlas"],
    "Background process limit":["Háttérfolyamat-korlátozás","Hintergrundprozesslimit","Limite processus arr.-plan","Límitar procesos en segundo plano"],
    "Standard limit":["Normál korlátozás","Standardlimit","Limite standard","Límite estándar"],
    "No background processes":["Nincsenek háttérfolyamatok","Keine Hintergrundprozesse","Aucun processus en arrière-plan","Sin procesos en segundo plano"],
    "At most 1 process":["Legfeljebb 1 folyamat","Höchstens 1 Prozess","Un processus maximum","1 proceso"],
    "At most 2 processes":["Legfeljebb 2 folyamat","Höchstens 2 Prozesse","Deux processus maximum","2 procesos"],
    "At most 3 processes":["Legfeljebb 3 folyamat","Höchstens 3 Prozesse","Trois processus maximum","3 procesos"],
    "At most 4 processes":["Legfeljebb 4 folyamat","Höchstens 4 Prozesse","Quatre processus maximum","4 procesos"],
    "Show all ANRs":["Összes ANR mutatása","Alle ANRS anzeigen","Afficher tous les messages ANR","Errores sin respuesta"],
    "Show App Not Responding dialog for background apps":["Az Alkalmazás nem válaszol ablak megjelenítése","Dialogfeld \"App antwortet nicht\" für Hintergrund-Apps anzeigen","Afficher \"L'application ne répond plus\" pour applis en arrière-plan","Informar de que una aplicación en segundo plano no responde"]
  };
  const LANGS = ['hu', 'de', 'fr', 'es'];
  const DEFAULTS = {developerEnabled: true, verifyUsb: true, animatorScale: 1};
  const keys = () => SECTIONS.flatMap(([, rows]) => rows.map(row => row[3]).filter(Boolean));
  // PreferenceCategory titles: Holo's list separators are all caps, Material's preference_category_material is not.
  const CATEGORY_CAPS = false;

  function render(settings, t, scaleLabel, lang = 'en') {
    const on = settings.developerEnabled !== false, i = LANGS.indexOf(lang);
    const T = text => STRINGS[text] && i >= 0 ? STRINGS[text][i] : STRINGS[text] ? text : t(text);
    return SECTIONS.map(([category, rows]) => `${category ? `<div class="section-label">${e(CATEGORY_CAPS ? T(category).toLocaleUpperCase() : T(category))}</div>` : ''}${rows.map(([kind, title, summary, key, dependent]) => {
      const disabled = !on || (dependent && !settings.usbDebug) || (key === 'waitDebugger');
      const attrs = disabled ? 'disabled aria-disabled="true"' : '';
      const copy = `<span class="row-copy">${e(T(title))}${summary ? `<small>${e(T(summary))}</small>` : ''}</span>`;
      if (kind === 'check') return `<button class="settings-row wireless-row jb-dev-row" data-action="toggle-setting" data-id="${key}" role="checkbox" aria-checked="${!!settings[key]}" ${attrs}>${copy}<img class="holo-checkbox" src="assets/btn_check_${settings[key] ? 'on' : 'off'}_holo_dark.png" alt=""></button>`;
      if (kind === 'switch') return `<button class="settings-row lp-switch-row jb-dev-row" data-action="toggle-setting" data-id="${key}" role="switch" aria-checked="${!!settings[key]}" ${attrs}>${copy}<span class="lp-mswitch${settings[key] ? ' on' : ''}" aria-hidden="true"></span></button>`;
      if (kind === 'choice') { const [, , , , , entries, summaries, fallback] = SECTIONS.flatMap(([, list]) => list).find(row => row[3] === key); const index = settings[key] ?? fallback; return `<button class="settings-row jb-dev-row" data-action="dev-list" data-id="${key}" ${attrs}><span class="row-copy">${e(T(title))}<small>${e(T((summaries || entries)[index] ?? entries[0]))}</small></span></button>`; }
      if (kind === 'scale') return `<button class="settings-row jb-dev-row" data-action="sd-dialog" data-id="${key}" ${attrs}><span class="row-copy">${e(T(title))}<small>${e(t(scaleLabel(settings[key] ?? 1)))}</small></span></button>`;
      return `<button class="settings-row jb-dev-row" data-action="dev-info" data-id="${e(title)}" ${attrs}>${copy}</button>`;
    }).join('')}`).join('');
  }

  // ListPreference's dialog: the title, the entries as single-choice rows, Cancel; a tap picks and closes.
  function dialog(key, settings, t, lang = 'en') {
    const row = SECTIONS.flatMap(([, rows]) => rows).find(item => item[0] === 'choice' && item[3] === key);
    if (!row) return '';
    const i = LANGS.indexOf(lang), T = text => STRINGS[text] && i >= 0 ? STRINGS[text][i] : STRINGS[text] ? text : t(text);
    const [, , , , , entries, , fallback, title] = row, current = settings[key] ?? fallback;
    return `<div class="settings-dialog-scrim" data-action="close-overlay"></div><div class="settings-dialog" role="dialog" aria-label="${e(T(title))}"><h3>${e(T(title))}</h3>${entries.map((entry, n) => `<button class="settings-row wireless-row" data-action="dev-list-pick" data-id="${key}:${n}" role="radio" aria-checked="${n === current}"><span class="row-copy">${e(T(entry))}</span>${CATEGORY_CAPS ? `<img class="holo-radio" src="assets/btn_radio_${n === current ? 'on' : 'off'}_holo_dark.png" alt="">` : `<span class="lp-radio${n === current ? ' on' : ''}" aria-hidden="true"></span>`}</button>`).join('')}<div class="settings-dialog-actions"><button data-action="close-overlay">${e(t('Cancel'))}</button></div></div>`;
  }

  /* Overlays: layout bounds (red clip bounds and blue corner marks), PointerLocationView's top bar, and the
     LoadAverageService panel at the top right. */
  function apply(screen, settings) {
    const on = settings.developerEnabled !== false;
    screen.classList.toggle('dev-layout-bounds', on && !!settings.layoutBounds);
    let pointer = screen.querySelector('.dev-pointer-bar'), cpu = screen.querySelector('.dev-cpu');
    if (on && settings.pointerLocation && !pointer) { pointer = document.createElement('div'); pointer.className = 'dev-pointer-bar'; pointer.setAttribute('aria-hidden', 'true'); pointer.textContent = 'P: 0 / 0   X: 0.0   Y: 0.0   Xv: 0.000   Yv: 0.000   Prs: 0.00   Size: 0.00'; screen.append(pointer); }
    if (!(on && settings.pointerLocation) && pointer) pointer.remove();
    if (on && settings.showCpu && !cpu) { cpu = document.createElement('div'); cpu.className = 'dev-cpu'; cpu.setAttribute('aria-hidden', 'true'); screen.append(cpu); updateCpu(cpu); }
    if (!(on && settings.showCpu) && cpu) cpu.remove();
  }
  function updateCpu(cpu) {
    const t = Date.now() / 1000, load = [0.48 + .12 * Math.sin(t / 7), 0.42 + .06 * Math.sin(t / 19), 0.39];
    const procs = [['system_server', 4 + 3 * Math.abs(Math.sin(t / 3))], ['com.android.systemui', 2 + 2 * Math.abs(Math.sin(t / 5))], ['surfaceflinger', 1.5 + Math.abs(Math.sin(t / 2))], ['com.android.launcher', 1 + Math.abs(Math.sin(t / 4))]];
    cpu.innerHTML = `<b>${load.map(v => v.toFixed(2)).join(' / ')}</b>${procs.map(([name, value]) => `<span><i style="width:${value * 6}px"></i>${name}</span>`).join('')}`;
  }
  function pointerMove(screen, event, down, count) {
    const bar = screen.querySelector('.dev-pointer-bar'); if (!bar) return;
    const box = screen.getBoundingClientRect(), k = box.width / screen.offsetWidth || 1, x = (event.clientX - box.left) / k * 2, y = (event.clientY - box.top) / k * 2;
    bar.textContent = `P: ${down ? 1 : 0} / ${count}   X: ${x.toFixed(1)}   Y: ${y.toFixed(1)}   Xv: 0.000   Yv: 0.000   Prs: ${down ? '1.00' : '0.00'}   Size: ${down ? '0.20' : '0.00'}`;
  }
  window.JBDeveloperOptions = {SECTIONS, STRINGS, DEFAULTS, keys, render, dialog, apply, updateCpu, pointerMove};
})();
