/* Generated by docs/lp-strings.py from the Nexus 6 LMY48Y factory image (values, -hu, -de, -fr, -es). Do not edit. */
window.AndroidI18n?.extend([
  ["Welcome", "Üdvözöljük!", "Hallo!", "Bienvenue", "Te damos la bienvenida"],
  ["Wallpapers, widgets, & settings", "Háttérképek, modulok és beállítások", "Hintergründe, Widgets & Einstellungen", "Fonds d'écran, widgets et paramètres", "Fondos de pantalla, widgets y ajustes"],
  ["Touch & hold background to customize", "Érintse meg és tartsa lenyomva a személyre szabáshoz", "Berühren und halten Sie den Hintergrund, um ihn anzupassen.", "Appuyez de manière prolongée sur l'arrière-plan pour le personnaliser.", "Mantén pulsado el fondo para personalizarlo"],
  ["GOT IT", "MEGÉRTETTEM", "OK", "OK", "ENTENDIDO"],
  ["Wallpapers", "Háttérképek", "Hintergründe", "Fonds d'écran", "Fondos de pantalla"],
  ["Widgets", "Modulok", "Widgets", "Widgets", "Widgets"],
  ["Settings", "Beállítások", "Einstellungen", "Paramètres", "Ajustes"],
  ["Create", "Létrehozás", "Erstellen", "Créer", "Crear"],
  ["Play", "Lejátszás", "Wiedergabe", "Lire", "Reproducir"]
]);
