/* Local preference screens and illustrative system statistics. */
(() => {
  'use strict';
  const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const defaults={mediaVolume:60,ringVolume:70,alarmVolume:80,ringtone:'Orion',notificationTone:'Proxima',vibrateRing:false,dialTones:true,touchSounds:true,lockSounds:true,haptic:true,sleep:30,windowScale:1,transitionScale:1,locationAccess:true,daydream:false,daydreamType:'clock',daydreamWhen:'charging',verifyApps:true,pulse:true,dataLimit:false,dataWarning:2};
  const prefs=data=>({...defaults,...data.settings});
  // Developer options lists from the ICS window_animation_scale arrays.
  const scaleOptions=[[0,'Animation off'],[.5,'Animation scale .5x'],[1,'Animation scale 1x'],[1.5,'Animation scale 1.5x'],[2,'Animation scale 2x'],[5,'Animation scale 5x'],[10,'Animation scale 10x']];
  const animationScaleLabel=value=>(scaleOptions.find(([scale])=>scale===Number(value??1))||scaleOptions[2])[1];
  const sleepOptions=[[15,'15 seconds'],[30,'30 seconds'],[60,'1 minute'],[120,'2 minutes'],[300,'5 minutes'],[600,'10 minutes'],[1800,'30 minutes']];
  const sizes=(data,id,index=0)=>({app:12+index*3,data:1.2,cache:data.appCacheCleared?.includes(id)?0:2.4});
  const label=text=>`<h3 class="section-label">${e(text)}</h3>`;
  const row=(title,subtitle,action='noop',id='')=>`<button class="settings-row" data-action="${action}" data-id="${e(id)}"><span class="row-copy">${e(title)}${subtitle?`<small>${e(subtitle)}</small>`:''}</span></button>`;
  const check=(title,key,value,subtitle='')=>`<button class="settings-row" data-action="toggle-setting" data-id="${key}" role="checkbox" aria-checked="${!!value}"><span class="row-copy">${e(title)}${subtitle?`<small>${e(subtitle)}</small>`:''}</span><img class="holo-checkbox" src="assets/btn_check_${value?'on':'off'}_holo_dark.png" alt=""></button>`;
  const pair=(title,value)=>`<div class="sd-pair"><span>${e(title)}</span><strong>${e(value)}</strong></div>`;
  const chart=(type='data',limit=false)=>`<svg class="sd-chart" viewBox="0 0 300 135" role="img" aria-label="${type==='data'?'Data usage':'Battery'}"><path d="M30 10H288M30 45H288M30 80H288M30 115H288M30 10V115M94 10V115M158 10V115M222 10V115M288 10V115" fill="none" stroke="#40464a" stroke-width=".7"/>${type==='data'?'<path d="M30 114L55 112L78 98L103 92L128 78L150 76L182 53L218 40L248 32L288 15V115H30Z" fill="#33b5e533" stroke="#33b5e5" stroke-width="2"/><path d="M30 39H288" stroke="#e5a63a" stroke-width="1.5"/><text x="0" y="15">300 MB</text><text x="5" y="114">0</text>':'<path d="M30 25L63 29L95 34L129 41L158 45L190 56L224 59L258 68L288 74V115H30Z" fill="#91b55877" stroke="#a9ca71" stroke-width="2"/>'}${limit?'<path d="M30 14H288" stroke="#e64a3b" stroke-width="2"/>':''}</svg>`;
  function render(data,ui,apps,t) {
    const s=ui.sub,p=prefs(data),page=(title,body)=>({title,body});
    // Settings 4.3 sound_settings.xml: no Silent mode row (it moved to the volume keys and power menu), Music effects.
    if(s==='sound')return page('Sound',`${row('Volumes','', 'sd-dialog','volumes')}${row('Music effects','', 'dev-info','Music effects')}${label('CALL RINGTONE & VIBRATE')}${row('Phone ringtone',p.ringtone,'sd-dialog','ringtone')}${check('Vibrate when ringing','vibrateRing',p.vibrateRing)}${label('SYSTEM')}${row('Default notification sound',p.notificationTone,'sd-dialog','notificationTone')}${check('Dial pad touch tones','dialTones',p.dialTones)}${check('Touch sounds','touchSounds',p.touchSounds)}${check('Screen lock sound','lockSounds',p.lockSounds)}${check('Vibrate on touch','haptic',p.haptic)}`);
    if(s==='display')return page('Display',`${row('Brightness',`${p.brightness}%`,'settings-sub','brightness')}${row('Wallpaper','','settings-sub','wallpaper')}${check('Auto-rotate screen','rotate',p.rotate)}${row('Sleep',t(sleepOptions.find(([value])=>value===p.sleep)?.[1]||'30 seconds'),'sd-dialog','sleep')}${row('Daydream',t(!p.daydream?'Off':{charging:'While charging',docked:'While docked',either:'Either'}[p.daydreamWhen||'charging']),'settings-sub','daydream')}${row('Font size',t(p.largeText?'Large':'Normal'),'sd-dialog','font')}${check('Pulse notification light','pulse',p.pulse)}${row('Cast screen',t(!p.wifi?'Disabled':p.wifiDisplay?'On':'Off'),'settings-sub','wifi-display')}`);
    if(s==='data')return page('Data usage',`${check('Mobile data','dataEnabled',p.dataEnabled)}${check('Set mobile data limit','dataLimit',p.dataLimit)}<div class="sd-cycle"><span>Data usage cycle</span><select data-field="data-cycle" aria-label="Data usage cycle"><option value="current" ${ui.dataCycle!=='previous'?'selected':''}>${e(t('Current month'))}</option><option value="previous" ${ui.dataCycle==='previous'?'selected':''}>${e(t('Previous month'))}</option></select></div>${chart('data',p.dataLimit)}<div class="sd-usage-summary">${ui.dataCycle==='previous'?'196':'284'} MB</div>${[['browser',124],['email',48],['gallery',36],['play-store',24],['music',12],['settings',40]].map(([id,amount])=>`<button class="sd-usage-row" data-action="sd-data-app" data-id="${id}"><img src="assets/${id==='play-store'?'play-store.svg':id+'.png'}" alt=""><span>${e(t(apps.find(app=>app[0]===id)?.[1]||id))}<i><b style="width:${amount/124*100}%"></b></i></span><small>${ui.dataCycle==='previous'?Math.round(amount*.69):amount} MB</small></button>`).join('')}`);
    if(s==='data-app') {const total=({browser:124,email:48,gallery:36,'play-store':24,music:12,settings:40}[ui.settingsApp]||0)*(ui.dataCycle==='previous'?.69:1);return page('App data usage',`${label(apps.find(app=>app[0]===ui.settingsApp)?.[1]||'App')}${chart()}${pair(t('Foreground'),Math.round(total*.87)+' MB')}${pair(t('Background'),Math.round(total*.13)+' MB')}${check('Restrict background data','restrictBackground_'+ui.settingsApp,p['restrictBackground_'+ui.settingsApp])}`);}
    if(s==='storage')return page('Storage',`${label('INTERNAL STORAGE')}<div class="sd-storage-bar"><i style="width:14%;background:#33b5e5"></i><i style="width:6%;background:#bb77bb"></i><i style="width:4%;background:#dd8833"></i><i style="width:2%;background:#88aa33"></i></div>${row('Total space','13.33 GB')}${row('Available','9.93 GB')}${[['Apps','1.8 GB','apps','#33b5e5'],['Pictures, videos','0.8 GB','gallery','#bb77bb'],['Audio','0.5 GB','music','#dd8833'],['Misc.','0.3 GB','storage-misc','#88aa33']].map(([name,value,id,color])=>`<button class="settings-row" data-action="sd-storage-open" data-id="${id}"><i class="sd-storage-key" style="background:${color}"></i><span class="row-copy">${e(name)}<small>${value}</small></span></button>`).join('')}`);
    if(s==='storage-misc')return page('Misc.',`${row('System files','240 MB')}${row('Offline pages','60 MB')}`);
    if(s==='apps') {
      const tab=ui.settingsAppsTab||'Downloaded',visible=tab==='Downloaded'?[]:tab==='Running'?apps.filter(app=>ui.recent.includes(app[0])):apps;
      return page('Apps',`<div class="sd-tabs">${['Downloaded','Running','All'].map(name=>`<button data-action="sd-apps-tab" data-id="${name}" class="${tab===name?'selected':''}">${e(t(name))}</button>`).join('')}</div>${visible.map((app,index)=>`<button class="settings-row sd-app-row" data-action="sd-app-info" data-id="${app[0]}"><img src="assets/${app[0]==='play-store'?'play-store.svg':app[0]+'.png'}" alt=""><span class="row-copy">${e(t(app[1]))}<small>${(sizes(data,app[0],apps.indexOf(app)).app+sizes(data,app[0]).data+sizes(data,app[0]).cache).toFixed(1)} MB</small></span></button>`).join('')||'<p class="empty-note">No apps</p>'}<div class="sd-storage-caption"><span>Internal storage</span><div class="sd-storage-bar"><i style="width:26%;background:#33b5e5"></i></div><small>3.4 GB / 13.33 GB</small></div>`);
    }
    if(s==='app-info') {
      const app=apps.find(app=>app[0]===ui.settingsApp);if(!app)return null;const size=sizes(data,app[0],apps.indexOf(app));
      return page('App info',`<div class="sd-app-heading"><img src="assets/${app[0]==='play-store'?'play-store.svg':app[0]+'.png'}" alt=""><span>${e(t(app[1]))}<small>4.3</small></span></div><div class="sd-buttons"><button data-action="sd-force-stop">Force stop</button><button disabled>Uninstall</button></div>${label('STORAGE')}${pair(t('Total'),(size.app+size.data+size.cache).toFixed(1)+' MB')}${pair(t('App'),size.app+' MB')}${pair(t('Data'),size.data+' MB')}<div class="sd-buttons"><button data-action="sd-clear-data" ${app[0]==='settings'?'disabled':''}>Clear data</button></div>${label('CACHE')}${pair(t('Cache'),size.cache.toFixed(1)+' MB')}<div class="sd-buttons"><button data-action="sd-clear-cache" ${!size.cache?'disabled':''}>Clear cache</button></div>${label('LAUNCH BY DEFAULT')}${row('No defaults set','')}${label('PERMISSIONS')}${row('Storage','Modify local demo data')}`);
    }
    if(s==='battery')return page('Battery',`<div class="sd-battery-state">78% – <span>Discharging</span></div><button class="sd-history-button" data-action="sd-battery-history">${chart('battery')}<span>2h 20m 14s on battery</span></button>${[['Screen',21,'settings'],['Android System',11,'settings'],['Phone idle',10,'phone'],['Cell standby',9,'phone'],['Email',9,'email'],['Android OS',9,'settings']].map(([name,percent,icon])=>`<button class="sd-usage-row" data-action="sd-battery-app" data-id="${name}"><img src="assets/${icon}.png" alt=""><span>${e(t(name))}<i><b style="width:${percent*4}%"></b></i></span><small>${percent}%</small></button>`).join('')}`);
    if(s==='battery-history')return page('History details',`${chart('battery')}${['Phone signal','GPS on','Wi-Fi','Awake','Screen on','Charging'].map((name,index)=>`<div class="sd-history-row"><span>${e(t(name))}</span><i style="--fill:${[100,0,85,32,21,0][index]}%"></i></div>`).join('')}`);
    if(s==='battery-detail')return page('Use details',`${label(ui.batteryDetail||'Screen')}${pair(t('Use time'),'29m 25s')}${row('Adjust power use','','settings-sub',ui.batteryDetail==='Screen'?'display':'apps')}`);
    return null;
  }
  function overlay(data,ui,t) {
    const p=prefs(data),field=ui.settingsField;
    const shell=(title,body,form='')=>`<div class="settings-dialog-scrim" data-action="close-overlay"></div><${form?'form':'div'} class="settings-dialog sd-dialog" role="dialog" aria-label="${e(t(title))}" ${form?`data-form="${form}"`:''}><h3>${e(t(title))}</h3>${body}</${form?'form':'div'}>`;
    const actions='<div class="settings-dialog-actions"><button type="button" data-action="close-overlay">Cancel</button><button type="submit">OK</button></div>';
    if(ui.overlay==='sd-clear-data')return shell('Delete app data?',`<p>This resets this app’s local demo content.</p><div class="settings-dialog-actions"><button data-action="close-overlay">Cancel</button><button data-action="sd-confirm-clear">OK</button></div>`);
    if(field==='volumes')return shell('Volumes',`${[['mediaVolume','Music, video, games & other media'],['ringVolume','Ringtone & notifications'],['alarmVolume','Alarms']].map(([key,name])=>`<label><span>${e(t(name))}</span><input type="range" name="${key}" min="0" max="100" value="${p[key]}" aria-label="${e(t(name))}"></label>`).join('')}${actions}`,'sd-volumes');
    let title='',choices=[],value;
    if(field==='sleep'){title='Sleep';choices=sleepOptions;value=p.sleep;}
    if(['windowScale','transitionScale','animatorScale'].includes(field)){title={windowScale:'Window animation scale',transitionScale:'Transition animation scale',animatorScale:'Animator duration scale'}[field];choices=scaleOptions;value=p[field]??1;}
    if(field==='font'){title='Font size';choices=[['normal','Normal'],['large','Large']];value=p.largeText?'large':'normal';}
    if(field==='silent'){title='Silent mode';choices=[['off','Off'],['vibrate','Vibrate'],['mute','Mute']];value=p.silent?(p.silentMode||'mute'):'off';}
    if(field==='ringtone'||field==='notificationTone'){title=field==='ringtone'?'Phone ringtone':'Default notification';choices=['Silent','Andromeda','Arcturus','Capella','Orion','Pegasus','Proxima','Sirius'].map(name=>[name,name]);value=p[field];}
    return shell(title,`<div class="sd-choice-list">${choices.map(([id,name])=>`<label><span>${e(t(name))}</span><input type="radio" name="choice" value="${id}" ${String(id)===String(value)?'checked':''}></label>`).join('')}</div>${actions}`,'sd-choice');
  }
  window.ICSSettingsDetail={defaults,prefs,sizes,render,overlay,animationScaleLabel};
})();
