/* Generated by docs/stock-strings.py from docs/stock-strings.json and the shamu factory image. Do not edit. */
window.StockStrings = {
 "gsettings": {
  "Google Settings": [
   "Google-beállítások",
   "Google Einstellungen",
   "Paramètres Google",
   "Ajustes de Google"
  ],
  "Account": [
   "Fiók",
   "Konto",
   "Compte",
   "Cuenta"
  ],
  "Services": [
   "Szolgáltatások",
   "Dienste",
   "Services",
   "Servicios"
  ],
  "Google+": [
   "Google+",
   "Google+",
   "Google+",
   "Google+"
  ],
  "Account History": [
   "Fiókelőzmények",
   "Kontoverlauf",
   "Historique du compte",
   "Historial de la cuenta"
  ],
  "Ads": [
   "Hirdetések",
   "Anzeigen",
   "Annonces",
   "Anuncios"
  ],
  "Connected apps": [
   "Társított alkalmazások",
   "Verbundene Apps",
   "Applications associées",
   "Aplicaciones conectadas"
  ],
  "Google Fit": [
   "Google Fitnesz",
   "Google Fit",
   "Google Fit",
   "Google Fit"
  ],
  "Play Games": [
   "Play Játékok",
   "Play Spiele",
   "Play Jeux",
   "Play Games"
  ],
  "Data management": [
   "Adatkezelés",
   "Datenverwaltung",
   "Gestion des données",
   "Administración de datos"
  ],
  "Search & Now": [
   "Keresés és Asszisztens",
   "Suche & Google Now",
   "Recherche et Now",
   "Búsqueda y Google Now"
  ],
  "Security": [
   "Biztonság",
   "Sicherheit",
   "Sécurité",
   "Seguridad"
  ],
  "Location": [
   "Hely",
   "Standort",
   "Position",
   "Ubicación"
  ]
 },
 "earth": {
  "Earth": [
   "Earth",
   "Earth",
   "Earth",
   "Earth"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Recherche Google",
   "Buscar"
  ],
  "Example: Pizza": [
   "példa: Pizza",
   "Beispiel: Pizza",
   "Exemple : boulangerie",
   "Ej.: Barcelona"
  ],
  "Clear map": [
   "Térképjelölők törlése",
   "Karte leeren",
   "Effacer la carte",
   "Borrar mapa"
  ],
  "My location": [
   "Saját pozíció",
   "Mein Standort",
   "Ma position",
   "Mi ubicación"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Street View": [
   "Utcakép",
   "Street View",
   "Street View",
   "Street View"
  ],
  "Layers": [
   "Rétegek",
   "Ebenen",
   "Calques",
   "Capas"
  ],
  "Maps Gallery": [
   "Térképgaléria",
   "Maps-Galerie",
   "Galerie Maps",
   "Galería de Maps"
  ],
  "Google+ Photos": [
   "Google+ Fotók",
   "Google+ Fotos",
   "Google+ Photos",
   "Fotos de Google+"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Comentarios"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Tutorial": [
   "Útmutató",
   "Anleitung",
   "Didacticiel",
   "Tutorial"
  ]
 },
 "news": {
  "News & Weather": [
   "Hírek és időjárás",
   "News & Wetter",
   "Actualités et météo",
   "Noticias y tiempo"
  ],
  "Headlines": [
   "Címsorok",
   "Schlagzeilen",
   "À la une",
   "Titulares"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Add section": [
   "Panel hozzáadása",
   "Abschnitt hinzufügen",
   "Ajouter une section",
   "Añadir sección"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Edit weather display…": [
   "Időjárásinformáció-módosítás…",
   "Wetteranzeige bearbeiten…",
   "Modifier l'affichage météo…",
   "Editar pantalla de tiempo…"
  ],
  "Change editions…": [
   "Más kiadás választása…",
   "Ausgaben ändern...",
   "Modifier les éditions…",
   "Cambiar edición…"
  ],
  "Manage sections…": [
   "Szakaszok kezelése…",
   "Bereich verwalten…",
   "Gérer les sections…",
   "Administrar secciones…"
  ],
  "Switch to dark theme": [
   "Váltás sötét témára",
   "Zum dunklen Design wechseln",
   "Passer au thème sombre",
   "Cambiar a tema oscuro"
  ],
  "Section header menu button": [
   "Szakaszfejléc menügombja",
   "Menüschaltfläche für Abschnittsüberschrift",
   "Bouton de menu de l'en-tête de section",
   "Botón de menú del encabezado de la sección"
  ],
  "More stories from %1$s": [
   "További cikkek innen: %1$s",
   "Mehr Nachrichten aus dem Bereich \"%1$s\"",
   "Autres articles de %1$s",
   "Más noticias de %1$s"
  ],
  "Partly Cloudy": [
   "Elszórt felhőzet",
   "Teils bewölkt",
   "Relativement nuageux",
   "Parcialmente nublado"
  ],
  "Precipitation: %1$s%%": [
   "Csapadék: %1$s%%",
   "Niederschlag: %1$s%%",
   "Précipitations : %1$s %%",
   "Probabilidad de lluvia: %1$s%%"
  ],
  "Humidity: %1$s%%": [
   "Páratartalom: %1$s%%",
   "Feuchtigkeit: %1$s%%",
   "Humidité : %1$s %%",
   "Humedad: %1$s%%"
  ],
  "Temp.": [
   "Hőmérs.",
   "Temp.",
   "Température",
   "Temp."
  ],
  "Precip.": [
   "Csapadék",
   "Regen",
   "Précip.",
   "Precip."
  ],
  "Wind": [
   "Szél",
   "Wind",
   "Vent",
   "Viento"
  ],
  "Humidity": [
   "Páratartalom",
   "Feuchtigk.",
   "Humidité",
   "Humedad"
  ],
  "Add and remove sections…": [
   "Részek felvétele és eltávolítása…",
   "Bereiche hinzufügen und entfernen…",
   "Ajouter et supprimer des sections…",
   "Añadir o eliminar secciones…"
  ],
  "Help & feedback": [
   "Súgó és visszajelzés",
   "Hilfe & Feedback",
   "Aide et commentaires",
   "Ayuda y opiniones"
  ],
  "Open navigation drawer": [
   "Navigációs fiók kinyitása",
   "Navigationsleiste öffnen",
   "Ouvrir le panneau de navigation",
   "Abrir panel de navegación"
  ]
 },
 "keep": {
  "Keep": [
   "Keep",
   "Notizen",
   "Keep",
   "Keep"
  ],
  "Add quick note": [
   "Rövid jegyzet hozzáadása",
   "Notiz hinzufügen",
   "Ajouter une note",
   "Añadir una nota rápida"
  ],
  "New note": [
   "Új jegyzet",
   "Neue Notiz",
   "Nouvelle note",
   "Nueva nota"
  ],
  "New list": [
   "Új lista",
   "Neue Liste",
   "Nouvelle liste",
   "Lista nueva"
  ],
  "New recording": [
   "Új felvétel",
   "Neue Aufnahme",
   "Nouvel enregistrement",
   "Nueva grabación"
  ],
  "New photo note": [
   "Új fotójegyzet",
   "Neue Fotonotiz",
   "Nouvelle note photo",
   "Nueva nota de foto"
  ],
  "Notes": [
   "Jegyzetek",
   "Notizen",
   "Notes",
   "Notas"
  ],
  "Reminders": [
   "Emlékeztetők",
   "Erinnerungen",
   "Rappels",
   "Recordatorios"
  ],
  "Archive": [
   "Archívum",
   "Archiv",
   "Archives",
   "Notas archivadas"
  ],
  "Trash": [
   "Kuka",
   "Papierkorb",
   "Corbeille",
   "Papelera"
  ],
  "Help & feedback": [
   "Súgó és visszajelzés",
   "Hilfe & Feedback",
   "Aide et commentaires",
   "Ayuda y enviar sugerencias"
  ],
  "Open navigation drawer": [
   "Navigációs fiók kinyitása",
   "Navigationsleiste öffnen",
   "Ouvrir le panneau de navigation",
   "Abrir control de navegación"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Single-column view": [
   "Egyoszlopos nézet",
   "Ansicht mit einer Spalte",
   "Vue avec colonne unique",
   "Vista de una columna"
  ],
  "Multi-column view": [
   "Többoszlopos nézet",
   "Ansicht mit mehreren Spalten",
   "Vue multicolonne",
   "Vista de varias columnas"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Change color": [
   "Szín módosítása",
   "Farbe ändern",
   "Modifier la couleur",
   "Cambiar color"
  ],
  "Add picture": [
   "Kép hozzáadása",
   "Bild hinzufügen",
   "Ajouter une image",
   "Añadir imagen"
  ],
  "Unarchive": [
   "Archiválás visszavonása",
   "Dearchivieren",
   "Annuler l'archivage",
   "No archivar"
  ],
  "Delete note": [
   "Jegyzet törlése",
   "Notiz löschen",
   "Supprimer la note",
   "Eliminar nota"
  ],
  "Make a copy": [
   "Másolat készítése",
   "Kopie erstellen",
   "Créer une copie",
   "Crear una copia"
  ],
  "Send": [
   "Küldés",
   "Senden",
   "Envoyer",
   "Enviar"
  ],
  "Show checkboxes": [
   "Jelölőnégyzetek megjelenítése",
   "Kontrollkästchen anzeigen",
   "Afficher les cases à cocher",
   "Mostrar casillas de verificación"
  ],
  "Notes with upcoming reminders appear here": [
   "Itt jelennek meg a közelgő emlékeztetőket tartalmazó jegyzetek",
   "Hier werden Notizen mit anstehenden Erinnerungen angezeigt.",
   "Les notes associées à des rappels à venir s'affichent ici.",
   "Las notas con próximos recordatorios aparecerán aquí"
  ],
  "Your archived notes appear here": [
   "Az archivált jegyzetek itt jelennek meg",
   "Ihre archivierten Notizen erscheinen hier.",
   "Vos notes archivées s'affichent ici.",
   "Tus notas archivadas se mostrarán aquí"
  ],
  "No notes in Trash": [
   "Nincs jegyzet a kukában",
   "Keine Notizen im Papierkorb",
   "Aucune note dans la corbeille",
   "No hay notas en la papelera"
  ]
 },
 "maps": {
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Menu": [
   "Menü",
   "Menü",
   "Menu",
   "Menú"
  ],
  "Directions": [
   "Útvonalterv",
   "Route",
   "Itinéraire",
   "Indicaciones"
  ],
  "Move to your location": [
   "Ugrás a saját helyre",
   "Zu Ihrem Standort wechseln",
   "Afficher le lieu",
   "Mover a mi ubicación"
  ],
  "Your places": [
   "Saját helyek",
   "Meine Orte",
   "Vos adresses",
   "Tus lugares"
  ],
  "Traffic": [
   "Forgalom",
   "Verkehrslage",
   "Trafic",
   "Tráfico"
  ],
  "Public transit": [
   "Tömegközlekedés",
   "Öffentl. Verkehrsmittel",
   "Transports en commun",
   "Transporte público"
  ],
  "Bicycling": [
   "Kerékpárral",
   "Fahrrad",
   "Vélo",
   "Rutas en bicicleta"
  ],
  "Satellite": [
   "Műhold",
   "Satellit",
   "Satellite",
   "Satélite"
  ],
  "Terrain": [
   "Terep",
   "Gelände",
   "Relief",
   "Relieve"
  ],
  "Google Earth": [
   "Google Earth",
   "Google Earth",
   "Google Earth",
   "Google Earth"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Configuración"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Enviar comentarios"
  ]
 },
 "drive": {
  "My Drive": [
   "Saját meghajtó",
   "Meine Ablage",
   "Mon Drive",
   "Mi unidad"
  ],
  "Shared with me": [
   "Velem megosztott",
   "Für mich freigegeben",
   "Partagés avec moi",
   "Compartido conmigo"
  ],
  "Starred": [
   "Csillagozott",
   "Markiert",
   "Suivis",
   "Destacados"
  ],
  "Recent": [
   "Legutóbbi",
   "Zuletzt geöffnet",
   "Récents",
   "Recientes"
  ],
  "On device": [
   "Az eszközön",
   "Auf dem Gerät",
   "Sur cet appareil",
   "En el dispositivo"
  ],
  "Uploads": [
   "Feltöltések",
   "Uploads",
   "Importations",
   "Subidas"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "View as Grid": [
   "Rácsnézet",
   "Rasteransicht",
   "Grille",
   "Ver en cuadrícula"
  ],
  "Create": [
   "Létrehozás",
   "Erstellen",
   "Créer",
   "Crear"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Filter by": [
   "Szűrő:",
   "Filtern nach",
   "Filtrer par",
   "Filtrar por"
  ],
  "Sort by": [
   "Rendezési szempont",
   "Sortieren nach",
   "Trier par",
   "Ordenar por"
  ],
  "Open navigation drawer": [
   "Navigációs fiók megnyitása",
   "Navigationsleiste öffnen",
   "Ouvrir le panneau de navigation",
   "Abrir panel de navegación"
  ],
  "Modified: %s": [
   "Módosítva: %s",
   "Geändert: %s",
   "Modifié : %s",
   "Modificado el %s"
  ],
  "Today": [
   "Ma",
   "Heute",
   "Aujourd'hui",
   "Hoy"
  ],
  "Yesterday": [
   "Tegnap",
   "Gestern",
   "Hier",
   "Ayer"
  ],
  "Earlier this Week": [
   "Korábban a héten",
   "Diese Woche",
   "Cette semaine",
   "Principios de semana"
  ],
  "Earlier this Month": [
   "Korábban a hónapban",
   "Diesen Monat",
   "Ce mois-ci",
   "Principios de mes"
  ],
  "Older": [
   "Régebben",
   "Älter",
   "Antérieurs",
   "Anteriores"
  ]
 },
 "youtube": {
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help & feedback": [
   "Súgó és visszajelzés",
   "Hilfe & Feedback",
   "Aide et commentaires",
   "Ayuda y sugerencias"
  ],
  "Watch later": [
   "Megnézendő videók",
   "Später ansehen",
   "À regarder plus tard",
   "Ver más tarde"
  ],
  "Favorites": [
   "Kedvencek",
   "Favoriten",
   "Favoris",
   "Favoritos"
  ],
  "Uploads": [
   "Feltöltések",
   "Uploads",
   "Ajouts",
   "Vídeos subidos"
  ],
  "History": [
   "Előzmények",
   "Verlauf",
   "Historique",
   "Historial"
  ],
  "Offline": [
   "Offline",
   "Offline",
   "Hors connexion",
   "Sin conexión"
  ]
 },
 "gplus": {
  "Home": [
   "Kezdőlap",
   "Übersicht",
   "Accueil",
   "Inicio"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Laisser un avis",
   "Enviar sugerencias"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Sign out": [
   "Kijelentkezés",
   "Abmelden",
   "Déconnexion",
   "Cerrar sesión"
  ]
 },
 "google": {
  "Card menu": [
   "Kártya menü",
   "Kartenmenü",
   "Menu de la carte",
   "Menú de la tarjeta"
  ],
  "View in Calendar": [
   "Megtekintés a Naptárban",
   "Im Kalender ansehen",
   "Afficher dans l'agenda",
   "Ver en Calendar"
  ],
  "More": [
   "Továbbiak",
   "Mehr",
   "Plus",
   "Más"
  ],
  "Reminders": [
   "Emlékeztetők",
   "Erinnerungen",
   "Rappels",
   "Recordatorios"
  ],
  "Customize": [
   "Személyre szabás",
   "Anpassen",
   "Personnaliser",
   "Personalizar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help & feedback": [
   "Súgó és visszajelzés",
   "Hilfe & Feedback",
   "Aide et commentaires",
   "Ayuda y comentarios"
  ],
  "Tap to speak": [
   "Koppintson a beszédhez",
   "Zum Sprechen tippen",
   "Appuyer pour parler",
   "Toca para hablar"
  ]
 }
};
