/* Generated by docs/stock-strings.py from docs/stock-strings.json and the shamu factory image. Do not edit. */
window.StockStrings = {
 "gsettings": {
  "Google Settings": [
   "Google-beállítások",
   "Google Einstellungen",
   "Paramètres Google",
   "Ajustes de Google"
  ],
  "Account": [
   "Fiók",
   "Konto",
   "Compte",
   "Cuenta"
  ],
  "Services": [
   "Szolgáltatások",
   "Dienste",
   "Services",
   "Servicios"
  ],
  "Google+": [
   "Google+",
   "Google+",
   "Google+",
   "Google+"
  ],
  "Account History": [
   "Fiókelőzmények",
   "Kontoverlauf",
   "Historique du compte",
   "Historial de la cuenta"
  ],
  "Ads": [
   "Hirdetések",
   "Anzeigen",
   "Annonces",
   "Anuncios"
  ],
  "Connected apps": [
   "Társított alkalmazások",
   "Verbundene Apps",
   "Applications associées",
   "Aplicaciones conectadas"
  ],
  "Google Fit": [
   "Google Fitnesz",
   "Google Fit",
   "Google Fit",
   "Google Fit"
  ],
  "Play Games": [
   "Play Játékok",
   "Play Spiele",
   "Play Jeux",
   "Play Games"
  ],
  "Data management": [
   "Adatkezelés",
   "Datenverwaltung",
   "Gestion des données",
   "Administración de datos"
  ],
  "Search & Now": [
   "Keresés és Asszisztens",
   "Suche & Google Now",
   "Recherche et Now",
   "Búsqueda y Google Now"
  ],
  "Security": [
   "Biztonság",
   "Sicherheit",
   "Sécurité",
   "Seguridad"
  ],
  "Location": [
   "Hely",
   "Standort",
   "Position",
   "Ubicación"
  ]
 },
 "earth": {
  "Earth": [
   "Earth",
   "Earth",
   "Earth",
   "Earth"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Recherche Google",
   "Buscar"
  ],
  "Example: Pizza": [
   "példa: Pizza",
   "Beispiel: Pizza",
   "Exemple : boulangerie",
   "Ej.: Barcelona"
  ],
  "Clear map": [
   "Térképjelölők törlése",
   "Karte leeren",
   "Effacer la carte",
   "Borrar mapa"
  ],
  "My location": [
   "Saját pozíció",
   "Mein Standort",
   "Ma position",
   "Mi ubicación"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Street View": [
   "Utcakép",
   "Street View",
   "Street View",
   "Street View"
  ],
  "Layers": [
   "Rétegek",
   "Ebenen",
   "Calques",
   "Capas"
  ],
  "Maps Gallery": [
   "Térképgaléria",
   "Maps-Galerie",
   "Galerie Maps",
   "Galería de Maps"
  ],
  "Google+ Photos": [
   "Google+ Fotók",
   "Google+ Fotos",
   "Google+ Photos",
   "Fotos de Google+"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Comentarios"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Tutorial": [
   "Útmutató",
   "Anleitung",
   "Didacticiel",
   "Tutorial"
  ]
 }
};
