const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const context={window:{}};
vm.runInNewContext(fs.readFileSync('versions/4.0.4/calendar.js','utf8'),context);
const cal=context.window.ICSCalendar;
const legacy={id:1,title:'Late meeting',date:'2026-12-31',time:'23:30'};
const overnight=cal.normalize(legacy);
assert.equal(overnight.endDate,'2027-01-01');
assert.equal(overnight.endTime,'00:30');
assert.equal(cal.onDay([legacy],'2027-01-01').length,1);
assert.equal(cal.onDay([{...overnight,endTime:'00:00'}],'2027-01-01').length,0);
assert.equal(cal.onDay([{...overnight,allDay:true}],'2027-01-01').length,1);
assert.equal(cal.valid({...overnight,endDate:legacy.date,endTime:'22:00'}),false);
assert.equal(cal.valid({...overnight,date:'2026-02-30'}),false);
assert.equal(cal.valid({...overnight,allDay:true,endDate:legacy.date}),true);
assert.equal(cal.week('2026-09-30',1)[0],'2026-09-28');
assert.equal(cal.week('2026-09-30',0)[0],'2026-09-27');
assert.ok(cal.month('2024-02-01').includes('2024-02-29'));
const event=(id,time,endTime)=>({...legacy,date:'2026-09-30',endDate:'2026-09-30',id,time,endTime});
const layout=cal.lanes([event(1,'09:00','11:00'),event(2,'10:00','12:00'),event(3,'11:30','13:00'),event(4,'13:00','14:00')],'2026-09-30');
assert.deepEqual(Array.from(layout,item=>[item.lane,item.columns]),[[0,2],[1,2],[0,2],[0,1]]);
const malicious={...overnight,title:'<img onerror=alert(1)>',description:'<script>bad()</script>'};
const html=cal.render({events:[malicious]},{sub:'event',selectedEvent:1,selectedDate:legacy.date},s=>s,'en-US');
assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;img'));
for(const mode of ['Day','Week','Month','Agenda'])assert.ok(cal.render({events:[legacy]},{selectedDate:legacy.date,calendarMode:mode},s=>s,'hu-HU').includes('cal-app'));
console.log('Calendar checks passed: midnight/year boundaries, inclusive all-day dates, validation, week starts, leap day, overlap lanes and escaping.');
