const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const context={window:{},Date};
vm.runInNewContext(fs.readFileSync('versions/4.0.4/desk-clock.js','utf8'),context);
const clock=context.window.ICSDeskClock;
const monday=new Date(2026,8,28,8,0,0);
assert.equal(clock.normalize({time:'99:99'}).time,'07:00');
assert.equal(clock.normalize(null).time,'07:00');
assert.ok(clock.overlay({overlay:'clock-ringing',alarmDraft:null,ringingAlarm:{time:'07:00'}},x=>x).includes('Snooze'));
assert.equal(JSON.stringify(clock.normalize({days:[4,0,4,-1,8]}).days),'[0,4]');
assert.equal(clock.nextOccurrence({time:'07:00',enabled:false},monday),null);
assert.equal(clock.nextOccurrence({time:'07:00'},monday).getDate(),29);
assert.equal(clock.nextOccurrence({time:'07:00',days:[0]},monday).getDate(),5);
assert.equal(clock.nextOccurrence({time:'09:00',days:[0]},monday).getDate(),28);
assert.equal(clock.nextOccurrence({time:'09:00',snoozedUntil:+monday+600000},monday).getTime(),+monday+600000);
assert.equal(clock.due({time:'08:00',days:[0]},monday),true);
assert.equal(clock.due({time:'08:00',days:[1]},monday),false);
assert.equal(clock.due({time:'08:00',lastFiredMinute:Math.floor(+monday/60000)},monday),false);
assert.equal(clock.due({time:'07:00',snoozedUntil:+monday-1},monday),true);
assert.equal(clock.due({time:'08:00',snoozedUntil:+monday+60000},monday),false);
assert.equal(clock.repeatText({days:[0,1,2,3,4,5,6]},x=>x),'Every day');
const html=clock.render({alarms:[]},{sub:'alarm-edit',alarmDraft:{label:'<img src=x onerror=bad()>'}},x=>x,'en-US');
assert.ok(!html.includes('<img src=x'));
console.log('DeskClock checks passed: legacy alarms, validation, next occurrence, weekly rollover, snooze, duplicate suppression and escaping.');
