const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const context={window:{}};
vm.runInNewContext(fs.readFileSync('versions/4.0.4/media.js','utf8'),context);
const media=context.window.ICSMedia;
const data={photos:[{id:1,name:'Legacy picture',colors:['#123456','#abcdef','#112233']},{id:99,name:'Legacy camera',colors:['#123456','#abcdef','#112233']}]};
assert.equal(media.photos(data,'pictures').length,1);
assert.equal(media.photos(data,'camera')[0].id,99);
assert.equal(media.settings(data).zoom,1);
const photo={...media.scene(data),id:100,album:'camera',name:'<script>bad()</script>',rotation:90};
const svg=decodeURIComponent(media.image(photo).split(',').slice(1).join(','));
assert.ok(svg.includes('rotate(90)'));
const poisoned=decodeURIComponent(media.image({...photo,colors:['url(javascript:bad())','#112233','#334455']}).split(',').slice(1).join(','));
assert.ok(!poisoned.includes('javascript:'));
assert.ok(media.art(photo).includes('&lt;script&gt;'));
const saved=JSON.parse(JSON.stringify({...data,photos:[photo,...data.photos],cameraSettings:{front:true,zoom:2,balance:'cloudy',exposure:1}}));
assert.equal(media.scene(saved).front,true);assert.equal(media.scene(saved).zoom,2);
assert.equal(media.photos(saved,'camera').length,2);
assert.ok(!media.gallery(saved,{sub:'photo',selectedPhoto:100,galleryAlbum:'camera'},s=>s).includes('<script>'));
console.log('Media checks passed: legacy albums, saved settings, generated scene, rotation, color validation and escaping.');
