const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = {window:{}};
vm.runInNewContext(fs.readFileSync('versions/4.0.4/messaging.js','utf8'),context);
const m = context.window.ICSMessaging;
assert.equal(m.counter('a'.repeat(160)).count,1);
assert.equal(m.counter('a'.repeat(161)).remaining,145);
assert.equal(m.counter('^'.repeat(80)).count,1);
assert.equal(m.counter('^'.repeat(81)).count,2);
assert.equal(m.counter('ő'.repeat(70)).count,1);
assert.equal(m.counter('ő'.repeat(71)).remaining,63);
assert.equal(m.counter('😀'.repeat(36)).count,2);
const contacts = [{id:1,name:'Alex Morgan',phone:'202-555-0148'}];
assert.equal(m.recipient('alex morgan',contacts).key,'1');
assert.equal(m.recipient('(202) 555-0148',contacts).key,'1');
assert.equal(m.recipient('+36 30 123 4567',contacts).key,'tel:+36301234567');
assert.equal(m.recipient('<img src=x>',contacts),null);
const data = {contacts,messages:[{id:1,contact:1,body:'Coffee?',time:'10:00'},{id:2,contact:'1',body:'Yes',time:'10:01'}],messageDrafts:{'tel:5551234':{body:'Draft',updated:100},new:{body:'Not a thread'}}};
assert.equal(m.threads(data).length,2);
assert.equal(m.threads(data)[0].key,'tel:5551234');
assert.equal(m.threads(data,'coffee')[0].messages.length,2);
assert.equal(m.threads(data,'missing').length,0);
const unfiltered = m.render(data,{sub:'',mmsSearch:'missing'},key=>key,'en-US');
assert.ok(unfiltered.includes('Alex Morgan'), 'Leaving search restores the full list');
const html = m.render({...data,messages:[{id:1,contact:1,body:'<img src=x>',time:'10:00'}]}, {sub:'thread',thread:1},key=>key,'en-US');
assert.ok(html.includes('&lt;img src=x&gt;'));
assert.ok(!html.includes('<img src=x>'));
console.log('Messaging checks passed: SMS segments, recipients, legacy threads, drafts, search and escaping.');
