/* Generated by docs/chrome-pak.py from Chrome 27.0.1453.111's locale .pak files (en-US, hu, de, fr, es). Do not edit. */
window.ChromePak = {
 "otr": [
  "<strong>You've gone incognito.</strong> <br /><br /> Pages you view in this tab won't appear in your browser history or search history, and they won't leave other traces, like cookies, on your mobile device after you close <strong>all</strong> incognito tabs. Any files you download or bookmarks you create will be preserved, however. <br /><br /> <strong>Going incognito doesn't affect the behavior of other people, servers, or software.</strong> Be wary of surveillance by secret agents or people standing behind you. <br /><br /> <span class=\"chr-link\">Learn more</span> about incognito browsing.",
  "<strong>Ön inkognitómódra váltott.</strong><br /><br /> Az itt megtekintett oldalak nem jelennek meg böngészési vagy keresési előzményei között, és más nyomokat -- például cookie-kat -- sem hagynak mobil eszközén, miután az <strong>összes</strong> inkognitólapot bezárta. A letöltött fájlok és a létrehozott könyvjelzők azonban megmaradnak. <br /><br /><strong>Az inkognitómód azonban nincs hatással más személyek, szerverek vagy szoftverek viselkedésére.</strong> Ügyeljen, nehogy megfigyelhessék titkos ügynökök vagy az Ön mögött álló személyek. <br /><br /><span class=\"chr-link\">További információ</span> az inkognitómódban való böngészésről.",
  "<strong>Sie befinden sich im Inkognito-Modus.</strong><br /><br /> Über diesen Tab aufgerufene Seiten werden nicht in Ihrem Browser- oder Suchverlauf gespeichert und hinterlassen keine sonstigen Spuren wie Cookies auf Ihrem Mobilgerät, nachdem Sie <strong>sämtliche</strong> Inkognito-Tabs geschlossen haben. Heruntergeladene Dateien oder gespeicherte Lesezeichen werden jedoch beibehalten. <br /><br /><strong>Der Inkognito-Modus wirkt sich nicht auf das Verhalten anderer Personen, Server oder Software aus.</strong> Vorsicht ist geboten bei der Überwachung durch Spione oder Personen, die hinter Ihnen stehen. <br /><br />Weitere Informationen zum Inkognito-Modus <span class=\"chr-link\">finden Sie hier</span>.",
  "<strong>Vous êtes passé en mode navigation privée.</strong> <br /><br /> Les pages que vous consultez dans cet onglet n'apparaîtront pas dans votre historique de navigation ni dans votre historique des recherches. Elles ne laisseront pas d'autres traces, telles que des cookies, sur votre appareil mobile une fois que vous aurez fermé <strong>tous</strong> les onglets ouverts en mode navigation privée. Toutefois, tous les fichiers téléchargés ou favoris créés seront conservés. <br /><br /> <strong>L'utilisation de la navigation privée n'a pas d'incidence sur le comportement d'autrui, des serveurs ni des logiciels.</strong> Faites attention aux agents secrets susceptibles de vous surveiller ou aux personnes se tenant debout derrière vous. <br /><br /> <span class=\"chr-link\">En savoir plus</span> sur la navigation privée",
  "<strong>Has entrado en el modo de navegación de incógnito.</strong> <br /><br /> Las páginas a las que accedas desde esta pestaña no aparecerán en tu historial de búsqueda ni el historial del navegador ni dejarán ningún otro rastro (por ejemplo, cookies) en tu dispositivo móvil una vez que hayas cerrado <strong>todas</strong> las pestañas de incógnito. Sin embargo, los archivos que descargues y los marcadores que crees sí quedarán almacenados. <br /><br /> <strong>La navegación en modo de incógnito no afecta al comportamiento de otros usuarios, servidores o aplicaciones.</strong> Ten cuidado con el seguimiento que puedan realizar detectives privados o personas que pasen cerca de ti. <br /><br /> Para obtener más información sobre la navegación en modo de incógnito, consulta <span class=\"chr-link\">esta página</span>."
 ],
 "sync": [
  "<p> Tabs you have opened in Chrome on your other devices will appear here. </p> <span class=\"chr-link\"> Enable sync. </span>",
  "<p> A más eszközökön futó Chrome-ban megnyitott oldalak itt jelennek meg. </p> <span class=\"chr-link\"> Szinkronizálás engedélyezése </span>",
  "<p> Hier erscheinen Tabs, die Sie auf anderen Geräten in Chrome geöffnet haben. </p> <span class=\"chr-link\"> Synchronisierung aktivieren </span>",
  "<p> Les onglets Google Chrome ouverts sur d'autres appareils s'affichent ici. </p> <span class=\"chr-link\"> Activer la synchronisation </span>",
  "<p> Las pestañas que hayas abierto en Chrome en otros dispositivos aparecerán aquí. </p> <span class=\"chr-link\"> Habilitar sincronización </span>"
 ],
 "mobile": [
  "Mobile bookmarks",
  "Mobil könyvjelzők",
  "Mobile Lesezeichen",
  "Favoris sur mobile",
  "Marcadores del móvil"
 ]
};
