/* Generated by docs/aosp-music-strings.py from AOSP packages/apps/Music android-4.3_r1.1 (values, -hu, -de, -fr, -es). Do not edit. */
window.AOSPMusicStrings = {
 "party_shuffle": {
  "en": "Party shuffle",
  "hu": "Keverés bulihoz",
  "de": "Party-Mix",
  "fr": "Mode DJ",
  "es": "Sesión aleatoria"
 },
 "party_shuffle_off": {
  "en": "Party shuffle off",
  "hu": "Keverés bulihoz kikapcsolása",
  "de": "Party-Mix aus",
  "fr": "Désactiver le mode DJ",
  "es": "Desactivar sesión aleatoria"
 },
 "shuffle_all": {
  "en": "Shuffle all",
  "hu": "Keverés",
  "de": "Alle zufällig wiedergeben",
  "fr": "Lecture aléatoire",
  "es": "Reproducir aleatoriamente"
 },
 "goto_start": {
  "en": "Library",
  "hu": "Könyvtár",
  "de": "Bibliothek",
  "fr": "Bibliothèque",
  "es": "Biblioteca"
 },
 "ringtone_menu": {
  "en": "Use as phone ringtone",
  "hu": "Felhasználás a telefon csengőhangjaként",
  "de": "Als Klingelton verwenden",
  "fr": "Utiliser comme sonnerie",
  "es": "Usar como tono"
 },
 "delete_item": {
  "en": "Delete",
  "hu": "Törlés",
  "de": "Löschen",
  "fr": "Supprimer",
  "es": "Eliminar"
 },
 "search_title": {
  "en": "Search",
  "hu": "Keresés",
  "de": "Suche",
  "fr": "Rechercher",
  "es": "Buscar"
 },
 "play_selection": {
  "en": "Play",
  "hu": "Lejátszás",
  "de": "Wiedergeben",
  "fr": "Écouter",
  "es": "Reproducir"
 },
 "add_to_playlist": {
  "en": "Add to playlist",
  "hu": "Hozzáadás lejátszási listához",
  "de": "Zu Playlist hinzufügen",
  "fr": "Ajouter à la playlist",
  "es": "Añadir a lista"
 },
 "new_playlist": {
  "en": "New",
  "hu": "Új",
  "de": "Neu",
  "fr": "Nouvelle",
  "es": "Nuevo"
 },
 "queue": {
  "en": "Current playlist",
  "hu": "Jelenlegi lejátszási lista",
  "de": "Aktuelle Playlist",
  "fr": "Playlist actuelle",
  "es": "Lista de reproducción actual"
 },
 "remove_from_playlist": {
  "en": "Remove from playlist",
  "hu": "Eltávolítás a lejátszási listából",
  "de": "Aus Playlist entfernen",
  "fr": "Supprimer de la playlist",
  "es": "Quitar de la lista de reproducción"
 },
 "recentlyadded": {
  "en": "Recently added",
  "hu": "Nemrég hozzáadott",
  "de": "Kürzlich hinzugefügt",
  "fr": "Ajoutés récemment",
  "es": "Añadidas recientemente"
 },
 "podcasts_title": {
  "en": "Podcasts",
  "hu": "Podcastok",
  "de": "Podcasts",
  "fr": "Podcasts",
  "es": "Podcasts"
 },
 "rename_playlist_menu": {
  "en": "Rename",
  "hu": "Átnevezés",
  "de": "Umbenennen",
  "fr": "Renommer",
  "es": "Cambiar nombre"
 },
 "delete_playlist_menu": {
  "en": "Delete",
  "hu": "Törlés",
  "de": "Löschen",
  "fr": "Supprimer",
  "es": "Eliminar"
 },
 "effectspanel": {
  "en": "Sound effects",
  "hu": "Hangeffektek",
  "de": "Toneffekte",
  "fr": "Effets sonores",
  "es": "Efectos sonido"
 },
 "ringtone_set": {
  "en": "\"%s\" set as phone ringtone.",
  "hu": "\"%s\" beállítva a telefon csengőhangjaként.",
  "de": "\"%s\" wurde als Telefonklingelton festgelegt.",
  "fr": "\"%s\" a été défini comme sonnerie.",
  "es": "Se ha establecido \"%s\" como tono del teléfono."
 },
 "delete_song_desc": {
  "en": "Permanently delete \"%s\" from the SD card?",
  "hu": "A(z) \"%s\" végleges törlése az SD-kártyáról?",
  "de": "\"%s\" endgültig von der SD-Karte löschen?",
  "fr": "Supprimer définitivement \"%s\" de la carte SD ?",
  "es": "¿Eliminar \"%s\" de la tarjeta SD de forma permanente?"
 },
 "delete_confirm_button_text": {
  "en": "OK",
  "hu": "OK",
  "de": "OK",
  "fr": "OK",
  "es": "Aceptar"
 }
};
