/* Generated by docs/sounds.py from the mako image (/system/media/audio, sounds.json, build.prop). Do not edit. */
/* The image's own ringtones, notification sounds and alarms (WebM / Opus copies in assets/audio, loaded only when played):
   - a ringtone list plays the tone touched, as RingtonePickerActivity does: the Settings dialogs mark their form with
     data-sound (ringtone / notificationTone, values are titles), Gingerbread's list uses gbset-sound-pick (file names);
     closing the list stops it;
   - a ringing alarm (the AlarmAlert / AlarmActivity screen of each version) loops the image's default alarm
     (ro.config.alarm_alert) until it is dismissed or snoozed.
   Browsers only play sound after the first touch on the page. */
(() => {
  'use strict';
  // category -> file name -> [title, asset]; the build.prop defaults by file name.
  const SOUNDS = {"ringtones": {"Andromeda": ["Andromeda", "Andromeda-a5faf0cc"], "Aquila": ["Aquila", "Aquila-0d9cd468"], "ArgoNavis": ["Argo Navis", "ArgoNavis-ba65cd44"], "Atria": ["Atria", "Atria-8c0cd822"], "Centaurus": ["Centaurus", "Centaurus-2bcd57b1"], "Girtab": ["Girtab", "Girtab-ce33d622"], "Hydra": ["Hydra", "Hydra-8ea61322"], "Kuma": ["Kuma", "Kuma-30cfdeba"], "Machina": ["Machina", "Machina-6066d836"], "Orion": ["Orion", "Orion-72022eec"], "Pegasus": ["Pegasus", "Pegasus-da31be84"], "Pyxis": ["Pyxis", "Pyxis-7ce3517c"], "Rasalas": ["Rasalas", "Rasalas-07feb3aa"], "RobotsforEveryone": ["Robots for Everyone", "RobotsforEveryone-fca971b2"], "Scarabaeus": ["Scarabaeus", "Scarabaeus-8e52b7b6"], "Sceptrum": ["Sceptrum", "Sceptrum-00a1cf9c"], "Solarium": ["Solarium", "Solarium-f21b83c2"], "SpagnolaOrchestration": ["Spagnola Orchestration", "SpagnolaOrchestration-bc8fa0f1"], "Themos": ["Themos", "Themos-f5234c51"], "Zeta": ["Zeta", "Zeta-bcd29d25"]}, "notifications": {"Adara": ["Adara", "Adara-dbd17f88"], "Alya": ["Alya", "Alya-924ce32c"], "Arcturus": ["Arcturus", "Arcturus-581a1cd7"], "Capella": ["Capella", "Capella-dc67c209"], "CetiAlpha": ["Ceti Alpha", "CetiAlpha-d1adb1e3"], "Hojus": ["Hojus", "Hojus-0dd8217d"], "Mira": ["Mira", "Mira-fd66ec72"], "Pollux": ["Pollux", "Pollux-233b125b"], "Procyon": ["Procyon", "Procyon-d8682a9f"], "Shaula": ["Shaula", "Shaula-3e1eca36"], "Spica": ["Spica", "Spica-418919c9"], "Syrma": ["Syrma", "Syrma-f68e5d35"], "Talitha": ["Talitha", "Talitha-ef59efd4"], "Tejat": ["Tejat", "Tejat-fdefead9"], "Vega": ["Vega", "Vega-d0a63a8b"]}, "alarms": {"Argon": ["Argon", "Argon-4b64d8d8"], "Carbon": ["Carbon", "Carbon-d5880b02"], "Helium": ["Helium", "Helium-63882084"], "Krypton": ["Krypton", "Krypton-3422548b"], "Neon": ["Neon", "Neon-a6970cf3"], "Osmium": ["Osmium", "Osmium-f6e4e778"], "Oxygen": ["Oxygen", "Oxygen-61e8cfcc"], "Platinum": ["Platinum", "Platinum-45d5c553"]}};
  const DEFAULTS = {"ringtones": "Themos", "notifications": "Tejat", "alarms": "Oxygen"};
  const RINGING = '.gbdc-ring, .dcal-ics, .dcal-glow, .dcal-lp';
  const asset = (cat, key) => { const list = SOUNDS[cat] || {}; const hit = list[key] || Object.values(list).find(([title]) => title === key); return hit ? hit[1] : null; };
  let preview = null, alarm = null;
  const start = (name, loop) => { const audio = new Audio(`../../assets/audio/${name}.webm`); audio.loop = loop; audio.play().catch(() => {}); return audio; };
  function play(cat, key) { stop(); const name = asset(cat, key); if (name) preview = start(name, false); }
  function stop() { if (preview) { preview.pause(); preview = null; } }
  document.addEventListener('change', event => {
    const input = event.target.closest?.('form[data-sound] input[name="choice"]');
    if (input) play(input.form.dataset.sound === 'ringtone' ? 'ringtones' : 'notifications', input.value);
  });
  document.addEventListener('click', event => {
    const pick = event.target.closest?.('[data-action="gbset-sound-pick"]');
    if (!pick) return;
    const [kind, name] = pick.dataset.id.split(':');
    if (name) play(kind === 'ringtone' ? 'ringtones' : 'notifications', name); else stop();
  }, true);
  // The list closing stops the preview; the ringing screen appearing or leaving starts or stops the alarm.
  let queued = false;
  new MutationObserver(() => {
    if (queued) return; queued = true;
    requestAnimationFrame(() => {
      queued = false;
      if (preview && !document.querySelector('form[data-sound], [data-action="gbset-sound-pick"]')) stop();
      const ringing = !!document.querySelector(RINGING);
      if (ringing && !alarm) { const name = asset('alarms', DEFAULTS.alarms); if (name) alarm = start(name, true); }
      if (!ringing && alarm) { alarm.pause(); alarm = null; }
    });
  }).observe(document.body, {childList: true, subtree: true});
  window.SystemSounds = {SOUNDS, DEFAULTS, asset, play, stop};
})();
