/* Generated by docs/stock-strings.py from docs/stock-strings.json and the mako factory image. Do not edit. */
window.StockStrings = {
 "keep": {
  "Keep": [
   "Keep",
   "Keep",
   "Keep",
   "Keep"
  ],
  "Add quick note": [
   "Rövid jegyzet hozzáadása",
   "Notiz hinzufügen",
   "Ajouter une note",
   "Añadir una nota rápida"
  ],
  "Take a note": [
   "Jegyzetelés",
   "Notiz schreiben",
   "Rédiger une note",
   "Tomar una nota"
  ],
  "There are no archived notes": [
   "Nincsenek archivált jegyzetek",
   "Keine archivierten Notizen vorhanden",
   "Aucune note archivée",
   "No hay notas archivadas"
  ],
  "New note": [
   "Új jegyzet",
   "Neue Notiz",
   "Nouvelle note",
   "Nueva nota"
  ],
  "New list": [
   "Új lista",
   "Neue Liste",
   "Nouvelle liste",
   "Lista nueva"
  ],
  "New recording": [
   "Új felvétel",
   "Neue Aufnahme",
   "Nouvel enregistrement",
   "Nueva grabación"
  ],
  "New photo": [
   "Új fotó",
   "Neues Foto",
   "Nouvelle photo",
   "Nueva foto"
  ],
  "Archive": [
   "Archiválás",
   "Archivieren",
   "Archiver",
   "Archivar"
  ],
  "Delete": [
   "Törlés",
   "Löschen",
   "Supprimer",
   "Eliminar"
  ],
  "Single-column view": [
   "Egyoszlopos nézet",
   "Ansicht mit einer Spalte",
   "Vue avec colonne unique",
   "Vista de una columna"
  ],
  "Multi-column view": [
   "Többoszlopos nézet",
   "Ansicht mit mehreren Spalten",
   "Vue multicolonne",
   "Vista de varias columnas"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Archived notes": [
   "Archivált jegyzetek",
   "Archivierte Notizen",
   "Notes archivées",
   "Notas archivadas"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Note color": [
   "Jegyzet színe",
   "Notizfarbe",
   "Couleur de remarque",
   "Color de la nota"
  ],
  "Unarchive": [
   "Archiválás visszavonása",
   "Dearchivieren",
   "Annuler l'archivage",
   "No archivar"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Show checkboxes": [
   "Jelölőnégyzetek megjelenítése",
   "Kontrollkästchen anzeigen",
   "Afficher les cases à cocher",
   "Mostrar casillas de verificación"
  ]
 },
 "youtube": {
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Add to": [
   "Hozzáadás ide:",
   "Hinzufügen zu",
   "Ajouter à",
   "Añadir a"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Like": [
   "Tetszik",
   "Gefällt mir",
   "J'aime",
   "Me gusta"
  ],
  "Dislike": [
   "Nem tetszik",
   "Mag ich nicht",
   "Je n'aime pas",
   "No me gusta"
  ],
  "Copy URL": [
   "URL másolása",
   "URL kopieren",
   "Copier l'URL",
   "Copiar URL"
  ],
  "Flag": [
   "Megjelölés",
   "Melden",
   "Signaler",
   "Marcar"
  ]
 },
 "maps": {
  "Maps": [
   "Térkép",
   "Maps",
   "Maps",
   "Maps"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Search Maps": [
   "Keresés",
   "Maps-Suche",
   "Rechercher",
   "Buscar en Maps"
  ],
  "Directions": [
   "Útvonalterv",
   "Route",
   "Itinéraire",
   "Indicaciones"
  ],
  "Local": [
   "Helyi Információk",
   "Local",
   "Local",
   "Local"
  ],
  "Layers": [
   "Rétegek",
   "Ebenen",
   "Afficher...",
   "Capas"
  ],
  "Clear map": [
   "Találatok törlése",
   "Karte leeren",
   "Effacer les résultats",
   "Borrar resultados"
  ],
  "My Places": [
   "Saját helyek",
   "Meine Orte",
   "Mes adresses",
   "Mis sitios"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Map": [
   "Térkép",
   "Karte",
   "Plan",
   "Mapa"
  ],
  "Find restaurants, bars & more": [
   "Éttermek, bárok és egyebek keresése",
   "Restaurants, Bars & mehr finden",
   "Trouvez des restaurants, des bars et d'autres lieux",
   "Buscar restaurantes, bares y más"
  ],
  "GPS navigation": [
   "GPS navigáció",
   "GPS-Navigation",
   "Navigation GPS",
   "Navegación GPS"
  ],
  "Traffic": [
   "Forgalom",
   "Verkehrslage",
   "Trafic",
   "Tráfico"
  ],
  "Satellite": [
   "Műhold",
   "Satellit",
   "Satellite",
   "Satélite"
  ],
  "Terrain": [
   "Terep",
   "Gelände",
   "Relief",
   "Relieve"
  ],
  "Bicycling": [
   "Kerékpárral",
   "Mit dem Fahrrad",
   "À vélo",
   "En bici"
  ]
 },
 "gplus": {
  "Home": [
   "Kezdőlap",
   "Übersicht",
   "Accueil",
   "Inicio"
  ],
  "Photo": [
   "Fotó",
   "Foto",
   "Photo",
   "Foto"
  ],
  "Check in": [
   "Bejelentkezés",
   "Check-in",
   "Check-in",
   "Visita"
  ],
  "Mood": [
   "Hangulat",
   "Stimmung",
   "Humeur",
   "Ánimo"
  ],
  "Write": [
   "Írás",
   "Schreiben",
   "Rédiger",
   "Escribir"
  ],
  "New post": [
   "Új bejegyzés",
   "Neuer Beitrag",
   "Nouveau post",
   "Publicar"
  ],
  "Share photos": [
   "Fotók megosztása",
   "Fotos teilen",
   "Partager des photos",
   "Compartir fotos"
  ],
  "Share your location": [
   "Oszd meg a helyedet",
   "Meinen Standort teilen",
   "Partager votre position",
   "Compartir ubicación"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer un commentaire",
   "Danos tu opinión"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Sign out": [
   "Kijelentkezés",
   "Abmelden",
   "Déconnexion",
   "Cerrar sesión"
  ]
 },
 "earth": {
  "Earth": [
   "Earth",
   "Earth",
   "Earth",
   "Earth"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Recherche Google",
   "Buscar"
  ],
  "Example: Pizza": [
   "példa: Pizza",
   "Beispiel: Pizza",
   "Exemple : boulangerie",
   "Ej.: Barcelona"
  ],
  "Reset to north": [
   "Visszaállítás északi irányba",
   "Auf Nordausrichtung zurücksetzen",
   "Rétablir l'orientation (nord en haut)",
   "Restablecer el Norte"
  ],
  "My location": [
   "Saját pozíció",
   "Mein Standort",
   "Ma position",
   "Mi ubicación"
  ],
  "Clear map": [
   "Térképjelölők törlése",
   "Karte leeren",
   "Effacer la carte",
   "Borrar mapa"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Comentarios"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Tutorial": [
   "Útmutató",
   "Anleitung",
   "Didacticiel",
   "Tutorial"
  ]
 },
 "google": {
  "Search…": [
   "Keresés...",
   "Suchen…",
   "Rechercher…",
   "Buscar..."
  ],
  "Tap to speak": [
   "Koppintson a beszédhez",
   "Zum Sprechen tippen",
   "Appuyez pour parler",
   "Toca para hablar."
  ],
  "Show more cards…": [
   "További kártyák...",
   "Mehr Karten anzeigen…",
   "Afficher d'autres cartes",
   "Mostrar más tarjetas…"
  ],
  "Menu": [
   "Menü",
   "Menü",
   "Menu",
   "Menú"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Speak now": [
   "Most beszéljen",
   "Sprechen",
   "Vous pouvez parler",
   "Habla ahora"
  ],
  "Didn't catch that. Try speaking again.": [
   "Nem sikerült értelmezni. Mondja ki újra.",
   "Das wurde nicht verstanden. Bitte sprechen Sie erneut.",
   "Je n'ai pas compris. Veuillez répéter.",
   "No lo he entendido. Prueba a decirlo otra vez."
  ]
 },
 "news": {
  "News & Weather": [
   "Hírek és időjárás",
   "News & Wetter",
   "Actualités et météo",
   "Noticias y tiempo"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Weather": [
   "Időjárás",
   "Wetter",
   "Météo",
   "Tiempo"
  ],
  "Humidity: %s%%": [
   "Páratartalom: %s%%",
   "Luftfeuchtigkeit: %s %%",
   "Humidité : %s%%",
   "Humedad: %s%%"
  ],
  "Wind: %1$s %2$s": [
   "Szélerősség: %1$s %2$s",
   "Wind: %1$s %2$s",
   "Vent : %1$s %2$s",
   "Viento: %1$s %2$s"
  ],
  "km/h": [
   "km/h",
   "km/h",
   "km/h",
   "km/h"
  ],
  "Mon": [
   "H",
   "M",
   "L",
   "L",
   "M"
  ],
  "Tue": [
   "K",
   "D",
   "M",
   "M",
   "T"
  ],
  "Wed": [
   "Sze",
   "M",
   "M",
   "X",
   "W"
  ],
  "Thu": [
   "Cs",
   "D",
   "J",
   "J",
   "T"
  ],
  "Fri": [
   "P",
   "F",
   "V",
   "V",
   "F"
  ],
  "Sat": [
   "Szo",
   "S",
   "S",
   "S",
   "S"
  ],
  "Sun": [
   "V",
   "S",
   "D",
   "D",
   "S"
  ]
 },
 "gsettings": {
  "Google Settings": [
   "Google-beállítások",
   "Google Einstellungen",
   "Paramètres Google",
   "Ajustes de Google"
  ],
  "Apps with Google+ Sign-In": [
   "Alkalmazások Google+-bejelentkezéssel",
   "Apps mit Google+ Log-in",
   "Applications permettant la connexion avec Google+",
   "Aplicaciones con inicio de sesión de Google+"
  ],
  "Google+": [
   "Google+",
   "Google+",
   "Google+",
   "Google+"
  ],
  "Location": [
   "Hely",
   "Standort",
   "Position",
   "Ubicación"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Recherche",
   "Búsqueda"
  ],
  "Ads": [
   "Hirdetések",
   "Anzeigen",
   "Annonces",
   "Anuncios"
  ],
  "Verify apps": [
   "Alkalmazások ellenőrzése",
   "Apps bestätigen",
   "Vérifier les applications",
   "Verificar aplicaciones"
  ]
 },
 "books": {
  "Play Books": [
   "Play Könyvek",
   "Play Books",
   "Play Livres",
   "Play Books"
  ],
  "Read Now": [
   "Olvasson most",
   "Jetzt lesen",
   "Lire",
   "Leer ahora"
  ],
  "My Library": [
   "Könyvtáram",
   "Meine Bibliothek",
   "Ma bibliothèque",
   "Mi biblioteca"
  ],
  "Shop": [
   "Bolt",
   "Bücher kaufen",
   "Boutique",
   "Tienda"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Sort": [
   "Rendezés",
   "Sortieren",
   "Trier",
   "Ordenar"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Recent": [
   "Legújabbak",
   "Neueste Bücher",
   "Récents",
   "Recientes"
  ],
  "All books": [
   "Az összes könyv",
   "Alle Bücher",
   "Tous les livres",
   "Todos los libros"
  ],
  "Purchases": [
   "Vásárlások",
   "Käufe",
   "Achats",
   "Compras"
  ]
 },
 "movies": {
  "Google Play": [
   "Google Play",
   "Google Play",
   "Google Play",
   "Google Play"
  ],
  "Movies": [
   "Filmek",
   "Filme",
   "Films",
   "Películas"
  ],
  "TV shows": [
   "tévéműsorok",
   "TV-Shows",
   "Émissions TV",
   "Series de TV"
  ],
  "Personal videos": [
   "Személyes videók",
   "Persönliche Videos",
   "Vidéos personnelles",
   "Vídeos personales"
  ],
  "My movies": [
   "Saját filmek",
   "Meine Filme",
   "Mes films",
   "Mis películas"
  ],
  "My shows": [
   "Saját műsorok",
   "Meine Sendungen",
   "Mes émissions",
   "Mis programas"
  ],
  "Suggestions": [
   "Javaslatok",
   "Vorschläge",
   "Suggestions",
   "Sugerencias"
  ],
  "See more from Google Play": [
   "Továbbiak a Google Playen",
   "Mehr von Google Play",
   "Plus de locations Google Play",
   "Más en Google Play"
  ],
  "%1$s mins.": [
   "%1$s perc",
   "%1$s Min.",
   "%1$s min",
   "%1$s minutos"
  ],
  "Season %1$s": [
   "%1$s. évad",
   "Staffel %1$s",
   "Saison %1$s",
   "Temporada %1$s"
  ],
  "NO VIDEOS FOUND": [
   "NINCS VIDEÓ\n\n.USB-kábellel másolhatsz videókat.",
   "Keine Videos gefunden\n\nÜber ein USB-Kabel können Sie Videos von Ihrem Computer kopieren.",
   "AUCUNE VIDÉO.\n\nCopiez des vidéos depuis votre ordinateur avec un câble USB.",
   "NO SE HAN ENCONTRADO VÍDEOS.\n\nPuedes copiar vídeos de tu ordenador por USB.",
   "NO VIDEOS FOUND\n\nYou can copy videos from your computer using a USB cable."
  ],
  "Shop": [
   "Vásárlás",
   "Einkaufen",
   "Play Store",
   "Comprar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Contact us": [
   "Kapcsolatfelvétel",
   "Kontakt",
   "Nous contacter",
   "Contacto"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Danos tu opinión"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Accounts": [
   "Fiókok",
   "Accounts",
   "Comptes",
   "Cuentas"
  ],
  "Download": [
   "Letöltés",
   "Herunterladen",
   "Télécharger",
   "Descargar"
  ]
 },
 "music": {
  "Play Music": [
   "Google Play Zene",
   "Google Play Music",
   "Google Play Musique",
   "Google Play Music",
   "Google Play Music"
  ],
  "Listen Now": [
   "Meghallgatás most",
   "Jetzt anhören",
   "Écoute immédiate",
   "Escuchar ahora"
  ],
  "My Library": [
   "Saját könyvtár",
   "Meine Musik",
   "Ma bibliothèque",
   "Mi música"
  ],
  "Playlists": [
   "Lejátszási listák",
   "Playlists",
   "Playlists",
   "Listas de reproducción"
  ],
  "Instant Mixes": [
   "Instant egyvelegek",
   "Schnellmixe",
   "Mix instantanés",
   "Mixes instantáneos"
  ],
  "Shop": [
   "Vásárlás",
   "Einkaufen",
   "Acheter",
   "Tienda"
  ],
  "All music": [
   "Minden zene",
   "Alle Musiktitel",
   "Toute la musique",
   "Toda la música"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Refresh": [
   "Zene frissítése",
   "Musik aktualisieren",
   "Actualiser les titres",
   "Actualizar música",
   "Refresh music"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Genres": [
   "Műfajok",
   "Genres",
   "Genres",
   "Géneros"
  ],
  "Artists": [
   "Előadók",
   "Interpreten",
   "Artistes",
   "Artistas"
  ],
  "Albums": [
   "Albumok",
   "Alben",
   "Albums",
   "Álbumes"
  ],
  "Songs": [
   "Dalok",
   "Titel",
   "Titres",
   "Canciones"
  ],
  "My mixes": [
   "Saját egyvelegek",
   "Meine Mixe",
   "Mes mix",
   "Mis mixes"
  ],
  "Recommended": [
   "Ajánlott",
   "Empfohlen",
   "Recommandations",
   "Recomendados"
  ],
  "Recently played": [
   "Legutóbb lejátszott",
   "Vor Kurzem angehört",
   "Lu récemment",
   "Reproducido recientemente"
  ],
  "Recently added to My Library": [
   "Nemrég hozzáadva a saját könyvtárhoz",
   "Vor Kurzem zu \"Meine Musik\" hinzugefügt",
   "Ajouté récemment à \"Ma bibliothèque\"",
   "Añadido recientemente a Mi música"
  ],
  "Thumbs up": [
   "Tetszik",
   "Mag ich",
   "J'aime",
   "Me gusta"
  ],
  "Last added": [
   "Utoljára hozzáadott",
   "Zuletzt hinzugefügt",
   "Derniers ajouts",
   "Añadidas recientemente"
  ]
 },
 "navigation": {
  "Navigation": [
   "Navigáció",
   "Navigation",
   "Navigation",
   "Navigation"
  ],
  "SHORTCUTS": [
   "GYORSBILLENTYŰK",
   "Schnellauswahl",
   "RACCOURCIS",
   "ACCESOS DIRECTOS"
  ],
  "STARRED": [
   "CSILLAGOZOTT",
   "MARKIERT",
   "FAVORIS",
   "DESTACADOS"
  ],
  "Speak destination": [
   "Cél kimondása",
   "Ziel einsprechen",
   "Énoncer destination",
   "Di el destino"
  ],
  "Type destination": [
   "Cél begépelése",
   "Ziel eintippen",
   "Saisir destination",
   "Escribe el destino"
  ],
  "Contacts": [
   "Kapcsolatok",
   "Kontakte",
   "Contacts",
   "Contactos"
  ],
  "Starred places": [
   "Csillaggal megjelölt helyek",
   "Markierte Orte",
   "Adresses enregistrées",
   "Sitios destacados"
  ]
 }
};
