/* Generated by docs/stock-strings.py from docs/stock-strings.json and the mako factory image. Do not edit. */
window.StockStrings = {
 "keep": {
  "Keep": [
   "Keep",
   "Keep",
   "Keep",
   "Keep"
  ],
  "Add quick note": [
   "Rövid jegyzet hozzáadása",
   "Notiz hinzufügen",
   "Ajouter une note",
   "Añadir una nota rápida"
  ],
  "Take a note": [
   "Jegyzetelés",
   "Notiz schreiben",
   "Rédiger une note",
   "Tomar una nota"
  ],
  "There are no archived notes": [
   "Nincsenek archivált jegyzetek",
   "Keine archivierten Notizen vorhanden",
   "Aucune note archivée",
   "No hay notas archivadas"
  ],
  "New note": [
   "Új jegyzet",
   "Neue Notiz",
   "Nouvelle note",
   "Nueva nota"
  ],
  "New list": [
   "Új lista",
   "Neue Liste",
   "Nouvelle liste",
   "Lista nueva"
  ],
  "New recording": [
   "Új felvétel",
   "Neue Aufnahme",
   "Nouvel enregistrement",
   "Nueva grabación"
  ],
  "New photo": [
   "Új fotó",
   "Neues Foto",
   "Nouvelle photo",
   "Nueva foto"
  ],
  "Archive": [
   "Archiválás",
   "Archivieren",
   "Archiver",
   "Archivar"
  ],
  "Delete": [
   "Törlés",
   "Löschen",
   "Supprimer",
   "Eliminar"
  ],
  "Single-column view": [
   "Egyoszlopos nézet",
   "Ansicht mit einer Spalte",
   "Vue avec colonne unique",
   "Vista de una columna"
  ],
  "Multi-column view": [
   "Többoszlopos nézet",
   "Ansicht mit mehreren Spalten",
   "Vue multicolonne",
   "Vista de varias columnas"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Archived notes": [
   "Archivált jegyzetek",
   "Archivierte Notizen",
   "Notes archivées",
   "Notas archivadas"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Note color": [
   "Jegyzet színe",
   "Notizfarbe",
   "Couleur de remarque",
   "Color de la nota"
  ],
  "Unarchive": [
   "Archiválás visszavonása",
   "Dearchivieren",
   "Annuler l'archivage",
   "No archivar"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Show checkboxes": [
   "Jelölőnégyzetek megjelenítése",
   "Kontrollkästchen anzeigen",
   "Afficher les cases à cocher",
   "Mostrar casillas de verificación"
  ],
  "List item": [
   "Listaelem",
   "Listenelement",
   "Élément de liste",
   "Elemento de lista"
  ],
  "Hide checkboxes": [
   "Jelölőnégyzetek elrejtése",
   "Kontrollkästchen ausblenden",
   "Masquer les cases à cocher",
   "Ocultar casillas de verificación"
  ],
  "Delete checked items?": [
   "Törli a kijelölt elemeket?",
   "Aktivierte Elemente löschen?",
   "Supprimer les éléments sélectionnés ?",
   "¿Eliminar elementos tachados?"
  ],
  "Keep (button)": [
   "Megőrzés",
   "Beibehalten",
   "Conserver",
   "Mantener",
   "Keep"
  ],
  "Delete (button)": [
   "Törlés",
   "Löschen",
   "Supprimer",
   "Eliminar",
   "Delete"
  ],
  "Remove photo?": [
   "Eltávolítja ezt a fotót?",
   "Dieses Foto entfernen?",
   "Supprimer cette photo ?",
   "¿Eliminar esta foto?",
   "Remove this photo?"
  ],
  "Cancel": [
   "Mégse",
   "Abbrechen",
   "Annuler",
   "Cancelar"
  ]
 },
 "youtube": {
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Add to": [
   "Hozzáadás ide:",
   "Hinzufügen zu",
   "Ajouter à",
   "Añadir a"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Like": [
   "Tetszik",
   "Gefällt mir",
   "J'aime",
   "Me gusta"
  ],
  "Dislike": [
   "Nem tetszik",
   "Mag ich nicht",
   "Je n'aime pas",
   "No me gusta"
  ],
  "Copy URL": [
   "URL másolása",
   "URL kopieren",
   "Copier l'URL",
   "Copiar URL"
  ],
  "Flag": [
   "Megjelölés",
   "Melden",
   "Signaler",
   "Marcar"
  ],
  "Search YouTube": [
   "Keresés a YouTube-on",
   "In YouTube suchen",
   "Rechercher sur YouTube",
   "Buscar..."
  ],
  "No videos found": [
   "Nem található videó",
   "Keine Videos gefunden",
   "Aucune vidéo n'a été trouvée.",
   "No se ha encontrado ningún vídeo."
  ],
  "Videos": [
   "Videók",
   "Videos",
   "Vidéos",
   "Vídeos"
  ],
  "All time": [
   "Mindenkori",
   "Gesamte Zeit",
   "Toutes périodes",
   "Todos"
  ],
  "Clear query": [
   "Lekérdezés törlése",
   "Anfrage löschen",
   "Effacer la requête",
   "Borrar consulta"
  ]
 },
 "maps": {
  "Maps": [
   "Térkép",
   "Maps",
   "Maps",
   "Maps"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Search Maps": [
   "Keresés",
   "Maps-Suche",
   "Rechercher",
   "Buscar en Maps"
  ],
  "Directions": [
   "Útvonalterv",
   "Route",
   "Itinéraire",
   "Indicaciones"
  ],
  "Local": [
   "Helyi Információk",
   "Local",
   "Local",
   "Local"
  ],
  "Layers": [
   "Rétegek",
   "Ebenen",
   "Afficher...",
   "Capas"
  ],
  "Clear map": [
   "Találatok törlése",
   "Karte leeren",
   "Effacer les résultats",
   "Borrar resultados"
  ],
  "My Places": [
   "Saját helyek",
   "Meine Orte",
   "Mes adresses",
   "Mis sitios"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Map": [
   "Térkép",
   "Karte",
   "Plan",
   "Mapa"
  ],
  "Find restaurants, bars & more": [
   "Éttermek, bárok és egyebek keresése",
   "Restaurants, Bars & mehr finden",
   "Trouvez des restaurants, des bars et d'autres lieux",
   "Buscar restaurantes, bares y más"
  ],
  "GPS navigation": [
   "GPS navigáció",
   "GPS-Navigation",
   "Navigation GPS",
   "Navegación GPS"
  ],
  "Traffic": [
   "Forgalom",
   "Verkehrslage",
   "Trafic",
   "Tráfico"
  ],
  "Satellite": [
   "Műhold",
   "Satellit",
   "Satellite",
   "Satélite"
  ],
  "Terrain": [
   "Terep",
   "Gelände",
   "Relief",
   "Relieve"
  ],
  "Bicycling": [
   "Kerékpárral",
   "Mit dem Fahrrad",
   "À vélo",
   "En bici"
  ]
 },
 "gplus": {
  "Home": [
   "Kezdőlap",
   "Übersicht",
   "Accueil",
   "Inicio"
  ],
  "Photo": [
   "Fotó",
   "Foto",
   "Photo",
   "Foto"
  ],
  "Check in": [
   "Bejelentkezés",
   "Check-in",
   "Check-in",
   "Visita"
  ],
  "Mood": [
   "Hangulat",
   "Stimmung",
   "Humeur",
   "Ánimo"
  ],
  "Write": [
   "Írás",
   "Schreiben",
   "Rédiger",
   "Escribir"
  ],
  "New post": [
   "Új bejegyzés",
   "Neuer Beitrag",
   "Nouveau post",
   "Publicar"
  ],
  "Share photos": [
   "Fotók megosztása",
   "Fotos teilen",
   "Partager des photos",
   "Compartir fotos"
  ],
  "Share your location": [
   "Oszd meg a helyedet",
   "Meinen Standort teilen",
   "Partager votre position",
   "Compartir ubicación"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer un commentaire",
   "Danos tu opinión"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Sign out": [
   "Kijelentkezés",
   "Abmelden",
   "Déconnexion",
   "Cerrar sesión"
  ],
  "Messenger": [
   "Üzenetküldő",
   "Messenger",
   "Chat +",
   "Messenger"
  ],
  "New conversation": [
   "Új beszélgetés",
   "Neue Unterhaltung",
   "Nouvelle conversation",
   "Nueva conversación"
  ]
 },
 "earth": {
  "Earth": [
   "Earth",
   "Earth",
   "Earth",
   "Earth"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Recherche Google",
   "Buscar"
  ],
  "Example: Pizza": [
   "példa: Pizza",
   "Beispiel: Pizza",
   "Exemple : boulangerie",
   "Ej.: Barcelona"
  ],
  "Reset to north": [
   "Visszaállítás északi irányba",
   "Auf Nordausrichtung zurücksetzen",
   "Rétablir l'orientation (nord en haut)",
   "Restablecer el Norte"
  ],
  "My location": [
   "Saját pozíció",
   "Mein Standort",
   "Ma position",
   "Mi ubicación"
  ],
  "Clear map": [
   "Térképjelölők törlése",
   "Karte leeren",
   "Effacer la carte",
   "Borrar mapa"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Comentarios"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Tutorial": [
   "Útmutató",
   "Anleitung",
   "Didacticiel",
   "Tutorial"
  ]
 },
 "google": {
  "Search…": [
   "Keresés...",
   "Suchen…",
   "Rechercher…",
   "Buscar..."
  ],
  "Tap to speak": [
   "Koppintson a beszédhez",
   "Zum Sprechen tippen",
   "Appuyez pour parler",
   "Toca para hablar."
  ],
  "Show more cards…": [
   "További kártyák...",
   "Mehr Karten anzeigen…",
   "Afficher d'autres cartes",
   "Mostrar más tarjetas…"
  ],
  "Menu": [
   "Menü",
   "Menü",
   "Menu",
   "Menú"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Speak now": [
   "Most beszéljen",
   "Sprechen",
   "Vous pouvez parler",
   "Habla ahora"
  ],
  "Didn't catch that. Try speaking again.": [
   "Nem sikerült értelmezni. Mondja ki újra.",
   "Das wurde nicht verstanden. Bitte sprechen Sie erneut.",
   "Je n'ai pas compris. Veuillez répéter.",
   "No lo he entendido. Prueba a decirlo otra vez."
  ]
 },
 "news": {
  "News & Weather": [
   "Hírek és időjárás",
   "News & Wetter",
   "Actualités et météo",
   "Noticias y tiempo"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Weather": [
   "Időjárás",
   "Wetter",
   "Météo",
   "Tiempo"
  ],
  "Humidity: %s%%": [
   "Páratartalom: %s%%",
   "Luftfeuchtigkeit: %s %%",
   "Humidité : %s%%",
   "Humedad: %s%%"
  ],
  "Wind: %1$s %2$s": [
   "Szélerősség: %1$s %2$s",
   "Wind: %1$s %2$s",
   "Vent : %1$s %2$s",
   "Viento: %1$s %2$s"
  ],
  "km/h": [
   "km/h",
   "km/h",
   "km/h",
   "km/h"
  ],
  "Mon": [
   "H",
   "M",
   "L",
   "L",
   "M"
  ],
  "Tue": [
   "K",
   "D",
   "M",
   "M",
   "T"
  ],
  "Wed": [
   "Sze",
   "M",
   "M",
   "X",
   "W"
  ],
  "Thu": [
   "Cs",
   "D",
   "J",
   "J",
   "T"
  ],
  "Fri": [
   "P",
   "F",
   "V",
   "V",
   "F"
  ],
  "Sat": [
   "Szo",
   "S",
   "S",
   "S",
   "S"
  ],
  "Sun": [
   "V",
   "S",
   "D",
   "D",
   "S"
  ]
 },
 "gsettings": {
  "Google Settings": [
   "Google-beállítások",
   "Google Einstellungen",
   "Paramètres Google",
   "Ajustes de Google"
  ],
  "Apps with Google+ Sign-In": [
   "Alkalmazások Google+-bejelentkezéssel",
   "Apps mit Google+ Log-in",
   "Applications permettant la connexion avec Google+",
   "Aplicaciones con inicio de sesión de Google+"
  ],
  "Google+": [
   "Google+",
   "Google+",
   "Google+",
   "Google+"
  ],
  "Location": [
   "Hely",
   "Standort",
   "Position",
   "Ubicación"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Recherche",
   "Búsqueda"
  ],
  "Ads": [
   "Hirdetések",
   "Anzeigen",
   "Annonces",
   "Anuncios"
  ],
  "Verify apps": [
   "Alkalmazások ellenőrzése",
   "Apps bestätigen",
   "Vérifier les applications",
   "Verificar aplicaciones"
  ]
 },
 "books": {
  "Play Books": [
   "Play Könyvek",
   "Play Books",
   "Play Livres",
   "Play Books"
  ],
  "Read Now": [
   "Olvasson most",
   "Jetzt lesen",
   "Lire",
   "Leer ahora"
  ],
  "My Library": [
   "Könyvtáram",
   "Meine Bibliothek",
   "Ma bibliothèque",
   "Mi biblioteca"
  ],
  "Shop": [
   "Bolt",
   "Bücher kaufen",
   "Boutique",
   "Tienda"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Sort": [
   "Rendezés",
   "Sortieren",
   "Trier",
   "Ordenar"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Recent": [
   "Legújabbak",
   "Neueste Bücher",
   "Récents",
   "Recientes"
  ],
  "All books": [
   "Az összes könyv",
   "Alle Bücher",
   "Tous les livres",
   "Todos los libros"
  ],
  "Purchases": [
   "Vásárlások",
   "Käufe",
   "Achats",
   "Compras"
  ],
  "Search for books": [
   "Könyvek keresése",
   "Nach Büchern suchen",
   "Rechercher livres",
   "Buscar libros"
  ],
  "Search online": [
   "Keresés online",
   "Online suchen",
   "Rechercher en ligne",
   "Buscar online"
  ],
  "Clear query": [
   "Lekérdezés törlése",
   "Anfrage löschen",
   "Effacer la requête",
   "Borrar consulta"
  ]
 },
 "movies": {
  "Google Play": [
   "Google Play",
   "Google Play",
   "Google Play",
   "Google Play"
  ],
  "Movies": [
   "Filmek",
   "Filme",
   "Films",
   "Películas"
  ],
  "TV shows": [
   "tévéműsorok",
   "TV-Shows",
   "Émissions TV",
   "Series de TV"
  ],
  "Personal videos": [
   "Személyes videók",
   "Persönliche Videos",
   "Vidéos personnelles",
   "Vídeos personales"
  ],
  "My movies": [
   "Saját filmek",
   "Meine Filme",
   "Mes films",
   "Mis películas"
  ],
  "My shows": [
   "Saját műsorok",
   "Meine Sendungen",
   "Mes émissions",
   "Mis programas"
  ],
  "Suggestions": [
   "Javaslatok",
   "Vorschläge",
   "Suggestions",
   "Sugerencias"
  ],
  "See more from Google Play": [
   "Továbbiak a Google Playen",
   "Mehr von Google Play",
   "Plus de locations Google Play",
   "Más en Google Play"
  ],
  "%1$s mins.": [
   "%1$s perc",
   "%1$s Min.",
   "%1$s min",
   "%1$s minutos"
  ],
  "Season %1$s": [
   "%1$s. évad",
   "Staffel %1$s",
   "Saison %1$s",
   "Temporada %1$s"
  ],
  "NO VIDEOS FOUND": [
   "NINCS VIDEÓ\n\n.USB-kábellel másolhatsz videókat.",
   "Keine Videos gefunden\n\nÜber ein USB-Kabel können Sie Videos von Ihrem Computer kopieren.",
   "AUCUNE VIDÉO.\n\nCopiez des vidéos depuis votre ordinateur avec un câble USB.",
   "NO SE HAN ENCONTRADO VÍDEOS.\n\nPuedes copiar vídeos de tu ordenador por USB.",
   "NO VIDEOS FOUND\n\nYou can copy videos from your computer using a USB cable."
  ],
  "Shop": [
   "Vásárlás",
   "Einkaufen",
   "Play Store",
   "Comprar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Contact us": [
   "Kapcsolatfelvétel",
   "Kontakt",
   "Nous contacter",
   "Contacto"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Danos tu opinión"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Accounts": [
   "Fiókok",
   "Accounts",
   "Comptes",
   "Cuentas"
  ],
  "Download": [
   "Letöltés",
   "Herunterladen",
   "Télécharger",
   "Descargar"
  ],
  "Search for movies": [
   "Filmkeresés",
   "Nach Filmen suchen",
   "Rechercher un film",
   "Buscar películas"
  ],
  "Clear query": [
   "Lekérdezés törlése",
   "Anfrage löschen",
   "Effacer la requête",
   "Borrar consulta"
  ]
 },
 "music": {
  "Play Music": [
   "Google Play Zene",
   "Google Play Music",
   "Google Play Musique",
   "Google Play Music",
   "Google Play Music"
  ],
  "Listen Now": [
   "Meghallgatás most",
   "Jetzt anhören",
   "Écoute immédiate",
   "Escuchar ahora"
  ],
  "My Library": [
   "Saját könyvtár",
   "Meine Musik",
   "Ma bibliothèque",
   "Mi música"
  ],
  "Playlists": [
   "Lejátszási listák",
   "Playlists",
   "Playlists",
   "Listas de reproducción"
  ],
  "Instant Mixes": [
   "Instant egyvelegek",
   "Schnellmixe",
   "Mix instantanés",
   "Mixes instantáneos"
  ],
  "Shop": [
   "Vásárlás",
   "Einkaufen",
   "Acheter",
   "Tienda"
  ],
  "All music": [
   "Minden zene",
   "Alle Musiktitel",
   "Toute la musique",
   "Toda la música"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Refresh": [
   "Zene frissítése",
   "Musik aktualisieren",
   "Actualiser les titres",
   "Actualizar música",
   "Refresh music"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Genres": [
   "Műfajok",
   "Genres",
   "Genres",
   "Géneros"
  ],
  "Artists": [
   "Előadók",
   "Interpreten",
   "Artistes",
   "Artistas"
  ],
  "Albums": [
   "Albumok",
   "Alben",
   "Albums",
   "Álbumes"
  ],
  "Songs": [
   "Dalok",
   "Titel",
   "Titres",
   "Canciones"
  ],
  "My mixes": [
   "Saját egyvelegek",
   "Meine Mixe",
   "Mes mix",
   "Mis mixes"
  ],
  "Recommended": [
   "Ajánlott",
   "Empfohlen",
   "Recommandations",
   "Recomendados"
  ],
  "Recently played": [
   "Legutóbb lejátszott",
   "Vor Kurzem angehört",
   "Lu récemment",
   "Reproducido recientemente"
  ],
  "Recently added to My Library": [
   "Nemrég hozzáadva a saját könyvtárhoz",
   "Vor Kurzem zu \"Meine Musik\" hinzugefügt",
   "Ajouté récemment à \"Ma bibliothèque\"",
   "Añadido recientemente a Mi música"
  ],
  "Thumbs up": [
   "Tetszik",
   "Mag ich",
   "J'aime",
   "Me gusta"
  ],
  "Last added": [
   "Utoljára hozzáadott",
   "Zuletzt hinzugefügt",
   "Derniers ajouts",
   "Añadidas recientemente"
  ],
  "Search music": [
   "Zene keresése",
   "Musik suchen",
   "Rechercher de la musique",
   "Buscar música"
  ],
  "%d MORE": [
   "%d TOVÁBBI",
   "%d weitere",
   "%d autres",
   "%d MÁS"
  ],
  "No results found.": [
   "Nincs találat.",
   "Keine Ergebnisse gefunden",
   "Aucun résultat trouvé.",
   "No se han encontrado resultados."
  ],
  "Clear query": [
   "Lekérdezés törlése",
   "Suchanfrage löschen",
   "Effacer la requête",
   "Borrar consulta"
  ]
 },
 "navigation": {
  "Navigation": [
   "Navigáció",
   "Navigation",
   "Navigation",
   "Navigation"
  ],
  "SHORTCUTS": [
   "GYORSBILLENTYŰK",
   "Schnellauswahl",
   "RACCOURCIS",
   "ACCESOS DIRECTOS"
  ],
  "STARRED": [
   "CSILLAGOZOTT",
   "MARKIERT",
   "FAVORIS",
   "DESTACADOS"
  ],
  "Speak destination": [
   "Cél kimondása",
   "Ziel einsprechen",
   "Énoncer destination",
   "Di el destino"
  ],
  "Type destination": [
   "Cél begépelése",
   "Ziel eintippen",
   "Saisir destination",
   "Escribe el destino"
  ],
  "Contacts": [
   "Kapcsolatok",
   "Kontakte",
   "Contacts",
   "Contactos"
  ],
  "Starred places": [
   "Csillaggal megjelölt helyek",
   "Markierte Orte",
   "Adresses enregistrées",
   "Sitios destacados"
  ],
  "Local": [
   "Helyi Információk",
   "Local",
   "Local",
   "Local"
  ]
 },
 "currents": {
  "Currents": [
   "Aktualitások",
   "Currents",
   "Flux d'actu",
   "Currents"
  ],
  "Breaking stories": [
   "Legfrissebb történetek",
   "Eilmeldungen",
   "Actualités",
   "Últimas noticias"
  ],
  "Saved": [
   "Mentett",
   "Gespeichert",
   "Enregistré",
   "Guardado"
  ],
  "Customize": [
   "Személyre szabás",
   "Anpassen",
   "Personnaliser",
   "Personalizar"
  ],
  "Sync now": [
   "Szinkronizálás most",
   "Jetzt synchronisieren",
   "Synchroniser maintenant",
   "Sincronizar ahora"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ]
 },
 "magazines": {
  "Google Play Magazines": [
   "Google Play Magazinok",
   "Google Play Magazines",
   "Google Play Magazines",
   "Google Play Magazines"
  ],
  "Read Now": [
   "Olvasson most",
   "Jetzt lesen",
   "Lire maintenant",
   "Leer ahora"
  ],
  "My Library": [
   "Saját könyvtár",
   "Meine Bibliothek",
   "Ma bibliothèque",
   "Mi biblioteca"
  ],
  "Shop": [
   "Áruház",
   "Einkaufen",
   "Acheter",
   "Tienda"
  ],
  "Search magazines": [
   "Magazinok keresése",
   "In Zeitschriften suchen",
   "Rechercher dans les magazines",
   "Buscar revistas"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "On device only": [
   "On device only",
   "On device only",
   "On device only",
   "On device only"
  ],
  "Manage subscriptions": [
   "Előfizetések kezelése",
   "Abonnements verwalten",
   "Gérer les abonnements",
   "Administrar suscripciones"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ]
 },
 "studio": {
  "Create new project": [
   "Új projekt létrehoz.",
   "Neues Projekt erstellen",
   "Créer un projet",
   "Crear nuevo proyecto"
  ]
 },
 "chrome": {
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Configuración"
  ],
  "Navigation error suggestions": [
   "Navigálási hibákkal kapcsolatos javaslatok",
   "Vorschläge bei Navigationsfehlern",
   "Suggestions en cas d'erreur de navigation",
   "Sugerencias para errores de navegación"
  ],
  "Navigation error summary": [
   "Alternatívák megjelenítése, ha egy internetcímet nem lehet feloldani, vagy nem lehet kapcsolódni",
   "Alternativvorschläge einblenden, wenn eine Webadresse nicht aufgelöst oder keine Verbindung hergestellt werden kann",
   "Afficher d'autres solutions lorsqu'une adresse Web ne peut pas être résolue ou qu'une connexion ne peut pas être établie",
   "Muestra sugerencias alternativas cuando no se puede mostrar una dirección web o no se puede establecer conexión.",
   "Show suggestions for alternatives when a web address does not resolve or a connection cannot be made"
  ],
  "Search and URL suggestions": [
   "Keresési és URL-javaslatok",
   "Such- und URL-Vorschläge",
   "Suggestions de recherche et d'URL",
   "Sugerencias de URL y de búsqueda"
  ],
  "Search suggestions summary": [
   "Használjon következtetési szolgáltatást a kapcsolódó lekérdezések és népszerű webhelyek megjelenítéséhez a címsávba történő gépelés során.",
   "Während der Eingabe in die Adressleiste mithilfe eines Vervollständigungsdienstes verwandte Suchanfragen und beliebte Websites einblenden",
   "Utiliser un service de prédiction pour suggérer des requêtes associées et des sites populaires quand vous saisissez des termes dans la barre d'adresse",
   "Se utiliza un servicio de predicción para mostrar consultas relacionadas y sitios web populares a medida que escribes en la barra de direcciones.",
   "Use a prediction service to show related queries and popular websites as you type in the address bar"
  ],
  "Network action predictions": [
   "Hálózati műveletekkel kapcsolatos várható kifejezések",
   "Prognose von Netzwerkaktionen",
   "Prédictions des actions de réseau",
   "Predicciones de acciones de red"
  ],
  "Network predictions summary": [
   "Oldal betöltési idejének javítása",
   "Seiten schneller laden",
   "Améliorer les performances de chargement des pages",
   "Mejorar rendimiento de carga de páginas",
   "Improve page load performance"
  ],
  "Usage and crash reports": [
   "Használati és hibabejelentések",
   "Nutzungs- und Absturzberichte",
   "Statistiques d'utilisation et rapports d'erreur",
   "Informes de uso y de errores"
  ],
  "Always send": [
   "Mindig küldjön",
   "Immer senden",
   "Toujours envoyer",
   "Enviar siempre"
  ],
  "Only send on Wi-Fi": [
   "Csak Wi-Fin keresztül küldjön",
   "Nur bei WLAN senden",
   "Envoyer via Wi-Fi uniquement",
   "Solo enviar en Wi-Fi"
  ],
  "Never send": [
   "Soha ne küldjön",
   "Nie senden",
   "Ne jamais envoyer",
   "No enviar nunca"
  ],
  "'Do Not Track'": [
   "„Nincs nyomon követés”",
   "\"Do Not Track\"",
   "Interdire le suivi",
   "Solicitudes de no seguimiento"
  ],
  "Off": [
   "Kikapcsolva",
   "Aus",
   "Désactivé",
   "Desactivado"
  ],
  "On": [
   "Be",
   "An",
   "Activ.",
   "On"
  ],
  "Clear browsing data": [
   "Böngészési adatok törl.",
   "Browserdaten löschen",
   "Effacer données navigation",
   "Borrar datos de navegación"
  ],
  "Clear browsing history": [
   "Előzmények törlése",
   "Browserverlauf löschen",
   "Effacer historique navigation",
   "Borrar historial de navegación"
  ],
  "Clear the cache": [
   "Gyorsítótár ürítése",
   "Cache leeren",
   "Vider le cache",
   "Borrar la caché"
  ],
  "Clear cookies, site data": [
   "Cookie-k, webhelyek törl",
   "Cookies/Daten löschen",
   "Eff. cookies/données site",
   "Cookies y datos sitios"
  ],
  "Clear saved passwords": [
   "Mentett jelszavak törlése",
   "Passwörter löschen",
   "Eff. mots passe enregistrés",
   "Borrar contraseñas guardadas"
  ],
  "Clear autofill data": [
   "Aut. kitöltési adatok törl.",
   "AutoFill-Daten löschen",
   "Eff. données saisie auto",
   "Borrar datos de autocomp"
  ],
  "Clear": [
   "Törlés",
   "Löschen",
   "Effacer",
   "Borrar"
  ],
  "Clearing browsing data": [
   "Böngészési adatok törlése",
   "Browserdaten löschen",
   "Effacement des données de navigation en cours…",
   "Borrando datos de navegación"
  ],
  "Please wait…": [
   "Kérjük, várjon...",
   "Bitte warten...",
   "Veuillez patienter…",
   "Espera...",
   "Please wait..."
  ],
  "Application version": [
   "Alkalmazás verziószáma",
   "App-Version",
   "Version de l'application",
   "Versión de la aplicación"
  ],
  "Operating system": [
   "OS",
   "OS",
   "OS",
   "OS",
   "OS"
  ],
  "Legal information": [
   "Jogi információk",
   "Rechtliche Hinweise",
   "Informations légales",
   "Información legal"
  ],
  "Cancel": [
   "Mégse",
   "Abbruch",
   "Annuler",
   "Cancelar"
  ],
  "Basics": [
   "Alapok",
   "Grundeinstellungen",
   "Général",
   "Básicos"
  ],
  "Advanced": [
   "Haladó",
   "Erweitert",
   "Avancés",
   "Avanzada"
  ],
  "Search engine": [
   "Keresőmotor",
   "Suchmaschine",
   "Moteur de recherche",
   "Motor de búsqueda"
  ],
  "Autofill forms": [
   "Űrlapok automatikus kitöltése",
   "AutoFill-Formulare",
   "Form. saisie auto",
   "Autocomp formularios"
  ],
  "Save passwords": [
   "Jelszavak mentése",
   "Passwörter speichern",
   "Enregistrer les mots de passe",
   "Guardar contraseñas"
  ],
  "Privacy": [
   "Adatvédelem",
   "Datenschutz",
   "Confidentialité",
   "Privacidad"
  ],
  "Accessibility": [
   "Kisegítő lehetőségek",
   "Bedienungshilfen",
   "Accessibilité",
   "Accesibilidad"
  ],
  "Content settings": [
   "Tartalombeállítások",
   "Inhaltseinstellungen",
   "Paramètres de contenu",
   "Ajustes de contenido"
  ],
  "Bandwidth management": [
   "Sávszélesség kezelése",
   "Bandbreitenverwaltung",
   "Gestion bande passante",
   "Gestión de ancho de banda"
  ],
  "Developer tools": [
   "Fejlesztői eszközök",
   "Entwickler-Tools",
   "Outils de développement",
   "Herram desarrolladores"
  ],
  "About Chrome": [
   "A Chrome névjegye",
   "Über Chrome",
   "À propos de Chrome",
   "Acerca de Chrome"
  ]
 },
 "gmailprefs": {
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "General settings": [
   "Általános beállítások",
   "Allgemeine Einstellungen",
   "Paramètres généraux",
   "Ajustes generales"
  ],
  "Archive & delete actions": [
   "Műveletek archiválás és törlése",
   "Aktionen \"Archivieren\" und \"Löschen\"",
   "Actions d'archivage et de suppression",
   "Archivar y eliminar"
  ],
  "Swipe to archive": [
   "Csúsztassa ujját az archiváláshoz",
   "Zum Archivieren wischen",
   "Faire glisser les éléments pour les archiver",
   "Desliza para archivar"
  ],
  "In conversation list": [
   "Beszélgetéslistában",
   "In einer Unterhaltungsliste",
   "Dans la liste des conversations",
   "En la lista de conversaciones"
  ],
  "Sender image": [
   "Küldő képe",
   "Bild des Absenders",
   "Image de l'expéditeur",
   "Imagen del remitente"
  ],
  "Sender image summary": [
   "Megjelenítés a név mellett a beszélgetések listájában",
   "Neben Namen in der Konversationsliste anzeigen",
   "Afficher à côté du nom dans la liste des conversations",
   "Mostrar junto al nombre en la lista de conversaciones",
   "Show beside name in conversation list"
  ],
  "Reply all": [
   "Válasz mindenkinek",
   "Allen antworten",
   "Répondre à tous",
   "Responder a todos"
  ],
  "Reply all summary": [
   "Használat alapértelmezettként értesítő üzenetekhez",
   "Als Standard für Antworten auf Benachrichtigungen verwenden",
   "Utiliser par défaut pour les réponses aux notifications de messages",
   "Usar como predeterminada para responder a notificaciones de mensajes",
   "Use as default for replies to message notifications"
  ],
  "Auto-fit messages": [
   "Üzenet automatikus méretezése",
   "Nachrichten autom. anpassen",
   "Ajustement auto des messages",
   "Ajuste de mensajes"
  ],
  "Auto-fit summary": [
   "Üzenetek kicsinyítése, hogy elférjenek a képernyőn.",
   "Nachrichten für die Anzeige auf dem Bildschirm verkleinern",
   "Ajuster la taille des messages à celle de l'écran",
   "Adaptar mensajes al tamaño de la pantalla",
   "Shrink messages to fit the screen"
  ],
  "Auto-advance": [
   "Automatikus léptetés",
   "Automatisch fortfahren",
   "Avance automatique",
   "Avance automático"
  ],
  "Action Confirmations": [
   "Művelet megerősítései",
   "Aktionsbestätigungen",
   "Confirmations des actions",
   "Confirmaciones de acciones"
  ],
  "Confirm before deleting": [
   "Megerősítés kérése törlés előtt",
   "Vor Löschen bestätigen",
   "Confirmer avant suppression",
   "Confirmar para eliminar"
  ],
  "Confirm before archiving": [
   "Megerősítés kérése archiválás előtt",
   "Vor Archivieren bestätigen",
   "Confirmer avant archivage",
   "Confirmar para archivar"
  ],
  "Confirm before sending": [
   "Megerősítés kérése küldés előtt",
   "Vor Senden bestätigen",
   "Confirmer avant envoi",
   "Confirmar para enviar"
  ],
  "Inbox type": [
   "Postaládatípus",
   "Art des Posteingangs",
   "Type de boîte de réception",
   "Tipo de bandeja de entrada"
  ],
  "Inbox categories": [
   "Beérkező levelek kategóriái",
   "Kategorien des Posteingangs",
   "Catégories de boîte de réception",
   "Categorías de Recibidos"
  ],
  "Notifications": [
   "Értesítések",
   "Benachrichtigungen",
   "Notifications",
   "Notificaciones"
  ],
  "Inbox sound & vibrate": [
   "Hang és rezgés beérkező üzenetekhez",
   "Ton & Vibration für Posteingang",
   "Sonnerie et vibreur de la boîte de réception",
   "Vibración y sonido de Recibidos"
  ],
  "Signature": [
   "Aláírás",
   "Signatur",
   "Signature",
   "Firma"
  ],
  "Signature dialog": [
   "Aláírás",
   "Signatur",
   "Signature",
   "Firma",
   "Signature"
  ],
  "Not set": [
   "Nincs megadva",
   "Nicht definiert",
   "Non définie",
   "No definida"
  ],
  "Data usage": [
   "Adathasználat",
   "Datenverbrauch",
   "Consommation des données",
   "Uso de datos"
  ],
  "Sync Gmail": [
   "Gmail szinkronizálása",
   "Gmail synchronisieren",
   "Synchroniser Gmail",
   "Sincronizar Gmail"
  ],
  "Days of mail to sync": [
   "Ennyi nap leveleinek szinkronizálása",
   "E-Mails: zu synchronisierende Tage",
   "Nombre de jours à synchroniser",
   "Días para sincronizar correo"
  ],
  "Manage labels": [
   "Címkék kezelése",
   "Labels verwalten",
   "Gérer les libellés",
   "Administrar etiquetas"
  ],
  "Download attachments": [
   "Mellékletek letöltése",
   "Anhänge herunterladen",
   "Télécharger les pièces jointes",
   "Descargar adjuntos"
  ],
  "Download attachments summary": [
   "Mellékletek automatikus letöltése az üzenetekbe Wi-Fin keresztül",
   "Anhänge neuer Nachrichten automatisch über WLAN herunterladen",
   "Télécharger automatiquement les pièces jointes aux messages récents via Wi-Fi",
   "Descargar automáticamente adjuntos de mensajes recientes por Wi-Fi",
   "Auto-download attachments to recent messages via Wi-Fi"
  ],
  "Primary": [
   "Elsődleges",
   "Allgemein",
   "Principale",
   "Principal"
  ],
  "Primary summary": [
   "A más kategóriákban meg nem jelenő személyes beszélgetések és üzenetek.",
   "Persönliche Konversationen und Nachrichten, die in keiner anderen Kategorie angezeigt werden",
   "Conversations et messages entre deux personnes non affichés dans les autres catégories",
   "Conversaciones y mensajes entre diferentes personas que no aparecen en otras categorías",
   "Person-to-person conversations and messages that don't appear in other categories."
  ],
  "Social": [
   "Közösségi",
   "Soziale Netzwerke",
   "Social",
   "Social"
  ],
  "Social summary": [
   "Üzenetek társasági hálózatokból, médiafájl-megosztó webhelyekről és online társkeresőktől.",
   "Nachrichten von sozialen Netzwerken, Foto- und Videoplattformen und Online-Partnerbörsen",
   "Messages provenant de réseaux sociaux, de sites de partage de fichiers multimédias et de sites de rencontre en ligne",
   "Mensajes de medios sociales, sitios donde se comparte contenido multimedia y servicios de citas online",
   "Messages from social networks, media sharing sites, online dating services."
  ],
  "Promotions": [
   "Promóciók",
   "Werbung",
   "Promotions",
   "Promociones"
  ],
  "Promotions summary": [
   "Üzletek, ajánlatok és más marketing jellegű e-mailek.",
   "Angebots- und andere Werbe-E-Mails",
   "Promotions, offres et autres e-mails commerciaux",
   "Promociones, ofertas y otros correos de marketing",
   "Deals, offers, and other marketing email."
  ],
  "Updates": [
   "Frissítések",
   "Benachrichtigungen",
   "Mises à jour",
   "Notificaciones"
  ],
  "Updates summary": [
   "Személyes, automatikusan generált frissítések, például visszaigazolások, nyugták, számlák és kimutatások.",
   "Automatisch erzeugte Statusinformationen persönlicher Art, zum Beispiel Bestätigungen, Belege, Rechnungen oder Kontoauszüge",
   "Mises à jour personnelles générées automatiquement, telles que les confirmations, les reçus, les factures et les relevés",
   "Notificaciones personales generadas automáticamente: confirmaciones, recibos, facturas y extractos de cuentas",
   "Personal, auto-generated updates, including confirmations, receipts, bills, and statements."
  ],
  "Forums": [
   "Fórumok",
   "Foren",
   "Forums",
   "Foros"
  ],
  "Forums summary": [
   "Üzenetek online csoportoktól, vitafórumokból és levelezési listákból.",
   "Nachrichten aus Online-Gruppen, Diskussionsforen und Mailinglisten",
   "Messages provenant de groupes en ligne, de forums de discussion et de listes de diffusion",
   "Mensajes de grupos online, grupos de debate y listas de distribución",
   "Messages from online groups, discussion boards, and mailing lists."
  ],
  "Include starred in Primary": [
   "Csillagozott üzenetek az Elsődleges lapon",
   "Markierte Nachrichten im Bereich \"Allgemein\" anzeigen",
   "Messages suivis dans \"Principale\"",
   "Mostrar destacados en Principal"
  ],
  "Starred category": [
   "Csillagozott üzenetek",
   "Markierte Nachrichten",
   "Messages suivis",
   "Mensajes destacados",
   "Starred messages"
  ],
  "Changes appear after sync": [
   "Csillagozott üzenetek",
   "Markierte Nachrichten",
   "Messages suivis",
   "Mensajes destacados",
   "Starred messages"
  ],
  "Default Inbox": [
   "Normál levelek",
   "Standard-Posteingang",
   "Boîte de réception par défaut",
   "Carpeta Recibidos predeterminada"
  ],
  "Priority Inbox": [
   "Fontos levelek",
   "Sortierter Eingang",
   "Prioritaire",
   "Prioritarios"
  ],
  "Newer": [
   "Újabb",
   "Neuer",
   "Plus récente",
   "Más reciente"
  ],
  "Older": [
   "Korábbi",
   "Älter",
   "Plus ancienne",
   "Más antigua"
  ],
  "Conversation list": [
   "Beszélgetéslista",
   "Konversationsliste",
   "Liste des conversations",
   "Lista de conversaciones"
  ],
  "About Gmail": [
   "A Gmail névjegye",
   "Über Gmail",
   "À propos de Gmail",
   "Acerca de Gmail"
  ],
  "Message text size": [
   "Üzenet szövegének mérete",
   "Nachrichtentextgröße",
   "Taille du texte des messages",
   "Tamaño de texto del mensaje"
  ],
  "Message actions": [
   "Üzenetműveletek",
   "E-Mail-Aktionen",
   "Actions relatives aux messages",
   "Acciones de mensajes"
  ],
  "Show archive only": [
   "Csak az archiválás megjelenítése",
   "Nur \"Archivieren\" anzeigen",
   "N'afficher que le bouton \"Archiver\"",
   "Mostrar solo archivados"
  ],
  "Show delete only": [
   "Csak a törlés megjelenítése",
   "Nur \"Löschen\" anzeigen",
   "N'afficher que le bouton \"Supprimer\"",
   "Mostrar solo eliminados"
  ],
  "Show archive & delete": [
   "Archiválás és törlés megjelenítése",
   "\"Archivieren\" und \"Löschen\" anzeigen",
   "Afficher les boutons \"Archiver\" et \"Supprimer\"",
   "Mostrar archivados y eliminados"
  ],
  "Tiny": [
   "Apró",
   "Sehr klein",
   "Très petite",
   "Muy pequeño"
  ],
  "Small": [
   "Kicsi",
   "Klein",
   "Petite",
   "Pequeño"
  ],
  "Normal": [
   "Normál",
   "Normal",
   "Normale",
   "Normal"
  ],
  "Large": [
   "Nagy",
   "Groß",
   "Grande",
   "Grande"
  ],
  "Huge": [
   "Óriási",
   "Sehr groß",
   "Très grande",
   "Enorme"
  ],
  "Always show": [
   "Mindig látszik",
   "Immer anzeigen",
   "Toujours afficher",
   "Mostrar siempre"
  ],
  "Only show in portrait": [
   "Megjelenítés csak álló tájolásban",
   "Nur im Hochformat anzeigen",
   "Afficher uniquement en mode Portrait",
   "Mostrar solo en modo vertical"
  ],
  "Don't show": [
   "Ne jelenjen meg",
   "Nicht anzeigen",
   "Ne pas afficher",
   "No mostrar"
  ]
 },
 "a11y": {
  "Touch & hold delay": [
   "Érintés és tartási késleltetés",
   "Reaktionszeit Berühren/Halten",
   "Délai de pression",
   "Retraso pulsación prolongada"
  ],
  "Short": [
   "Rövid",
   "Kurz",
   "Court",
   "Corto"
  ],
  "Medium": [
   "Közepes",
   "Mittel",
   "Moyen",
   "Medio"
  ],
  "Long": [
   "Hosszú",
   "Lang",
   "Long",
   "Largo"
  ],
  "Magnification gestures": [
   "Nagyítási kézmozdulatok",
   "Vergrößerungsbewegungen",
   "Gestes d'agrandissement",
   "Gestos de ampliación"
  ],
  "Magnification summary": [
   "Ha a funkció be van kapcsolva, úgy kicsinyíthet/nagyíthat, hogy háromszor rákoppint a képernyőre.\n\nNagyított állapotban:\nPásztázhat: Két vagy több ujját húzza végig a képernyőn.\nMódosíthatja a nagyítási szintet: Két ujját húzza össze vagy távolítsa el egymástól.\n\nIdeiglenesen felnagyíthatja az ujja alatt lévő részt is, úgy hogy hármat koppint és lenyomva hagyja ujját. A nagyított nézetben az ujját húzva fedezheti fel a képernyő más részeit is. Az ujja felemelésével visszatérhet az előző állapotra.\n\nMegjegyzés: A háromszoros koppintással való nagyítás a billentyűzet és a navigációs sáv kivételével mindenhol működik.",
   "Wenn diese Funktion aktiviert ist, können Sie heranzoomen und herauszoomen, indem Sie drei Mal auf den Bildschirm tippen.\n\nWenn Sie herangezoomt haben, können Sie:\nSchwenken: mindestens 2 Finger über den Bildschirm ziehen\nZoomstufe anpassen: mindestens 2 Finger zusammen- oder auseinanderziehen\n\nSie können auch das, was sich unter Ihrem Finger befindet, vorübergehend vergrößern, indem Sie drei Mal tippen und halten. In diesem vergrößerten Zustand können Sie Ihren Finger ziehen, um verschiedene Bereiche des Bildschirms zu erkunden. Heben Sie Ihren Finger an, um zum vorherigen Zustand zurückzukehren.\n\nHinweis: Das dreimalige Tippen zur Vergrößerung funktioniert überall außer in der Tastatur und in der Navigationsleiste.",
   "Lorsque cette fonctionnalité est activée, vous pouvez effectuer des zooms avant et arrière en appuyant trois fois sur l'écran.\n\nLorsque vous effectuez un zoom avant, vous pouvez :\nEffectuer un panoramique : faites glisser deux doigts ou plus sur l'écran.\nRégler le niveau de zoom : pincez deux doigts ou plus, ou écartez-les.\n\nVous pouvez également agrandir le contenu se trouvant sous votre doigt en appuyant trois fois sur l'écran et en prolongeant la troisième pression. Lorsque la loupe est activée, vous pouvez faire glisser votre doigt sur l'écran pour en explorer les différentes parties. Relevez votre doigt pour revenir à l'état précédent.\n\nRemarque : vous pouvez appuyer trois fois sur l'écran pour agrandir le contenu partout, sauf sur le clavier et la barre de navigation.",
   "Cuando esta función está activada, puedes acercar y alejar la imagen con solo tocar tres veces la pantalla.\n\nA continuación se indican las acciones que puedes hacer con la imagen acercada.\nDesplazar la imagen: arrastra dos o más dedos por la pantalla.\nModificar el nivel de zoom: une dos o más dedos o sepáralos.\n\nTambién puedes ampliar el contenido seleccionado de forma temporal con solo tocar la pantalla tres veces y mantenerla pulsada. Con el contenido ampliado, puedes arrastrar el dedo para explorar diferentes partes de la pantalla. Levanta el dedo para volver al estado anterior.\n\nNota: puedes tocar tres veces la pantalla para ampliar el contenido en cualquier parte, excepto en el teclado y en la barra de navegación.",
   "When this feature is turned on, you can zoom in and out by triple-tapping the screen.\n\nWhile zoomed in, you can:\nPan: Drag two or more fingers across the screen.\nAdjust zoom level: Pinch two or more fingers together or spread them apart.\n\nYou can also temporarily magnify what's under your finger by triple-tapping and holding. In this magnified state, you can drag your finger to explore different parts of the screen. Lift your finger to return to your previous state.\n\nNote: Triple-tap for magnification works everywhere except the keyboard and navigation bar."
  ],
  "Accessibility shortcut": [
   "Hozzáférési gyorskombináció",
   "Bedienungshilfenverknüpfung",
   "Raccourci d'accessibilité",
   "Acceso directo a accesibilidad"
  ],
  "Accessibility shortcut summary": [
   "Ha a funkció engedélyezve van, gyorsan elérheti a kisegítő lehetőségeket két lépésben:\n\n1. lépés: tartsa lenyomva a bekapcsológombot a hangjelzésig vagy rezgésig.\n\n2. lépés: két ujját tartsa lenyomva a hangjelzéssel történő jóváhagyásig.\n\nHa az eszközt több felhasználó is használja, akkor e kombináció zárolási képernyőn való használatával ideiglenesen hozzáférhetővé válik az eszköz, amíg fel nem oldják azt.",
   "Wenn diese Funktion aktiviert ist, können Sie Bedienungshilfen schnell in zwei Schritten aktivieren:\n\nSchritt 1: Drücken und halten Sie die Ein-/Austaste, bis Sie einen Ton hören oder eine Vibration spüren.\n\nSchritt 2: Berühren und halten Sie mit zwei Fingern, bis Sie eine Audiobestätigung hören.\n\nFalls das Gerät mehrere Nutzer hat, werden die Bedienungshilfen durch Verwendung dieser Verknüpfung in der Bildschirmsperre solange aktiviert, bis das Gerät entsperrt ist.",
   "Lorsque cette fonctionnalité est activée, vous pouvez rapidement activer les fonctionnalités d'accessibilité en deux étapes :\n\nÉtape 1 : Appuyez de manière prolongée sur le bouton Marche/Arrêt jusqu'à ce que le téléphone sonne ou vibre.\n\nÉtape 2 : Appuyez de manière prolongée avec deux doigts jusqu'à ce que vous entendiez la confirmation audio.\n\nSi l'appareil est utilisé par plusieurs personnes, l’utilisation de ce raccourci sur l'écran de verrouillage active l'accessibilité de manière temporaire jusqu'au déverrouillage de l'appareil.",
   "Cuando esta función está activada, puedes habilitar las funciones de accesibilidad rápidamente en dos pasos.\n\nPaso 1: mantén pulsado el botón de encendido hasta que escuches un sonido o notes una vibración.\n\nPaso 2: mantén la pantalla pulsada con dos dedos hasta que escuches una confirmación.\n\nSi hay varios usuarios en el dispositivo, este acceso directo en la pantalla de bloqueo permite habilitar la accesibilidad de forma temporal hasta que el dispositivo se desbloquea.",
   "When this feature is turned on, you can quickly enable accessibility features in two steps:\n\nStep 1: Press and hold the power button until you hear a sound or feel a vibration.\n\nStep 2: Touch and hold two fingers until you hear audio confirmation.\n\nIf the device has multiple users, using this shortcut on the lock screen temporarily enables accessibility until the device is unlocked."
  ],
  "On": [
   "be",
   "An",
   "Activé",
   "Activado"
  ],
  "Off": [
   "Ki",
   "Aus",
   "Désactivé",
   "Desactivado"
  ]
 },
 "calendar": {
  "Time zone": [
   "Időzóna",
   "Zeitzone",
   "Fuseau horaire",
   "Zona horaria"
  ],
  "Show me as": [
   "Állapotjelzés",
   "Mein Status",
   "Ma disponibilité",
   "Mostrarme como"
  ],
  "Busy": [
   "Elfoglalt",
   "Beschäftigt",
   "Occupé",
   "Ocupado"
  ],
  "Available": [
   "Elérhető",
   "Verfügbar",
   "Disponible",
   "Disponible"
  ],
  "Guests": [
   "Résztvevők",
   "Gäste",
   "Invités",
   "Invitados"
  ],
  "Privacy": [
   "Adatvédelem",
   "Datenschutz",
   "Confidentialité",
   "Privacidad"
  ],
  "Default": [
   "Alapértelmezett",
   "Standard",
   "Par défaut",
   "Predeterminado"
  ],
  "Private": [
   "Privát",
   "Privat",
   "Privé",
   "Privado"
  ],
  "Public": [
   "Nyilvános",
   "Öffentlich",
   "Public",
   "Público"
  ]
 }
};
