/* Generated by docs/stock-strings.py from docs/stock-strings.json and the mako factory image. Do not edit. */
window.StockStrings = {
 "keep": {
  "Keep": [
   "Keep",
   "Keep",
   "Keep",
   "Keep"
  ],
  "Add quick note": [
   "Rövid jegyzet hozzáadása",
   "Notiz hinzufügen",
   "Ajouter une note",
   "Añadir una nota rápida"
  ],
  "Take a note": [
   "Jegyzetelés",
   "Notiz schreiben",
   "Rédiger une note",
   "Tomar una nota"
  ],
  "There are no archived notes": [
   "Nincsenek archivált jegyzetek",
   "Keine archivierten Notizen vorhanden",
   "Aucune note archivée",
   "No hay notas archivadas"
  ],
  "New note": [
   "Új jegyzet",
   "Neue Notiz",
   "Nouvelle note",
   "Nueva nota"
  ],
  "New list": [
   "Új lista",
   "Neue Liste",
   "Nouvelle liste",
   "Lista nueva"
  ],
  "New recording": [
   "Új felvétel",
   "Neue Aufnahme",
   "Nouvel enregistrement",
   "Nueva grabación"
  ],
  "New photo": [
   "Új fotó",
   "Neues Foto",
   "Nouvelle photo",
   "Nueva foto"
  ],
  "Archive": [
   "Archiválás",
   "Archivieren",
   "Archiver",
   "Archivar"
  ],
  "Delete": [
   "Törlés",
   "Löschen",
   "Supprimer",
   "Eliminar"
  ],
  "Single-column view": [
   "Egyoszlopos nézet",
   "Ansicht mit einer Spalte",
   "Vue avec colonne unique",
   "Vista de una columna"
  ],
  "Multi-column view": [
   "Többoszlopos nézet",
   "Ansicht mit mehreren Spalten",
   "Vue multicolonne",
   "Vista de varias columnas"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Archived notes": [
   "Archivált jegyzetek",
   "Archivierte Notizen",
   "Notes archivées",
   "Notas archivadas"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Note color": [
   "Jegyzet színe",
   "Notizfarbe",
   "Couleur de remarque",
   "Color de la nota"
  ],
  "Unarchive": [
   "Archiválás visszavonása",
   "Dearchivieren",
   "Annuler l'archivage",
   "No archivar"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Show checkboxes": [
   "Jelölőnégyzetek megjelenítése",
   "Kontrollkästchen anzeigen",
   "Afficher les cases à cocher",
   "Mostrar casillas de verificación"
  ]
 },
 "youtube": {
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Add to": [
   "Hozzáadás ide:",
   "Hinzufügen zu",
   "Ajouter à",
   "Añadir a"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Like": [
   "Tetszik",
   "Gefällt mir",
   "J'aime",
   "Me gusta"
  ],
  "Dislike": [
   "Nem tetszik",
   "Mag ich nicht",
   "Je n'aime pas",
   "No me gusta"
  ],
  "Copy URL": [
   "URL másolása",
   "URL kopieren",
   "Copier l'URL",
   "Copiar URL"
  ],
  "Flag": [
   "Megjelölés",
   "Melden",
   "Signaler",
   "Marcar"
  ]
 },
 "maps": {
  "Maps": [
   "Térkép",
   "Maps",
   "Maps",
   "Maps"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Search Maps": [
   "Keresés",
   "Maps-Suche",
   "Rechercher",
   "Buscar en Maps"
  ],
  "Directions": [
   "Útvonalterv",
   "Route",
   "Itinéraire",
   "Indicaciones"
  ],
  "Local": [
   "Helyi Információk",
   "Local",
   "Local",
   "Local"
  ],
  "Layers": [
   "Rétegek",
   "Ebenen",
   "Afficher...",
   "Capas"
  ],
  "Clear map": [
   "Találatok törlése",
   "Karte leeren",
   "Effacer les résultats",
   "Borrar resultados"
  ],
  "My Places": [
   "Saját helyek",
   "Meine Orte",
   "Mes adresses",
   "Mis sitios"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Map": [
   "Térkép",
   "Karte",
   "Plan",
   "Mapa"
  ],
  "Find restaurants, bars & more": [
   "Éttermek, bárok és egyebek keresése",
   "Restaurants, Bars & mehr finden",
   "Trouvez des restaurants, des bars et d'autres lieux",
   "Buscar restaurantes, bares y más"
  ],
  "GPS navigation": [
   "GPS navigáció",
   "GPS-Navigation",
   "Navigation GPS",
   "Navegación GPS"
  ],
  "Traffic": [
   "Forgalom",
   "Verkehrslage",
   "Trafic",
   "Tráfico"
  ],
  "Satellite": [
   "Műhold",
   "Satellit",
   "Satellite",
   "Satélite"
  ],
  "Terrain": [
   "Terep",
   "Gelände",
   "Relief",
   "Relieve"
  ],
  "Bicycling": [
   "Kerékpárral",
   "Mit dem Fahrrad",
   "À vélo",
   "En bici"
  ]
 },
 "gplus": {
  "Home": [
   "Kezdőlap",
   "Übersicht",
   "Accueil",
   "Inicio"
  ],
  "Photo": [
   "Fotó",
   "Foto",
   "Photo",
   "Foto"
  ],
  "Check in": [
   "Bejelentkezés",
   "Check-in",
   "Check-in",
   "Visita"
  ],
  "Mood": [
   "Hangulat",
   "Stimmung",
   "Humeur",
   "Ánimo"
  ],
  "Write": [
   "Írás",
   "Schreiben",
   "Rédiger",
   "Escribir"
  ],
  "New post": [
   "Új bejegyzés",
   "Neuer Beitrag",
   "Nouveau post",
   "Publicar"
  ],
  "Share photos": [
   "Fotók megosztása",
   "Fotos teilen",
   "Partager des photos",
   "Compartir fotos"
  ],
  "Share your location": [
   "Oszd meg a helyedet",
   "Meinen Standort teilen",
   "Partager votre position",
   "Compartir ubicación"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer un commentaire",
   "Danos tu opinión"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Sign out": [
   "Kijelentkezés",
   "Abmelden",
   "Déconnexion",
   "Cerrar sesión"
  ]
 },
 "earth": {
  "Earth": [
   "Earth",
   "Earth",
   "Earth",
   "Earth"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Recherche Google",
   "Buscar"
  ],
  "Example: Pizza": [
   "példa: Pizza",
   "Beispiel: Pizza",
   "Exemple : boulangerie",
   "Ej.: Barcelona"
  ],
  "Reset to north": [
   "Visszaállítás északi irányba",
   "Auf Nordausrichtung zurücksetzen",
   "Rétablir l'orientation (nord en haut)",
   "Restablecer el Norte"
  ],
  "My location": [
   "Saját pozíció",
   "Mein Standort",
   "Ma position",
   "Mi ubicación"
  ],
  "Clear map": [
   "Térképjelölők törlése",
   "Karte leeren",
   "Effacer la carte",
   "Borrar mapa"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Comentarios"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Tutorial": [
   "Útmutató",
   "Anleitung",
   "Didacticiel",
   "Tutorial"
  ],
  "Fly to": [
   "Repíts ide",
   "Anfliegen",
   "Aller à",
   "Volar a"
  ]
 },
 "google": {
  "Search…": [
   "Keresés...",
   "Suchen…",
   "Rechercher…",
   "Buscar..."
  ],
  "Tap to speak": [
   "Koppintson a beszédhez",
   "Zum Sprechen tippen",
   "Appuyez pour parler",
   "Toca para hablar."
  ],
  "Show more cards…": [
   "További kártyák...",
   "Mehr Karten anzeigen…",
   "Afficher d'autres cartes",
   "Mostrar más tarjetas…"
  ],
  "Menu": [
   "Menü",
   "Menü",
   "Menu",
   "Menú"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Speak now": [
   "Most beszéljen",
   "Sprechen",
   "Vous pouvez parler",
   "Habla ahora"
  ],
  "Didn't catch that. Try speaking again.": [
   "Nem sikerült értelmezni. Mondja ki újra.",
   "Das wurde nicht verstanden. Bitte sprechen Sie erneut.",
   "Je n'ai pas compris. Veuillez répéter.",
   "No lo he entendido. Prueba a decirlo otra vez."
  ]
 }
};
