/* Developer options of the Galaxy Nexus (IMM76I) image (Settings.apk res/xml/development_prefs.xml, CheckBoxPreference), generated by
   docs/devopts.py maguro from docs/devopts.template.js: the rows in the XML's order, the default summaries
   DevelopmentSettings shows, and the image's own Hungarian, German, French and Spanish texts. */
(() => {
  'use strict';
  const e = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]));
  // [kind, title, summary, setting key, depends on USB debugging, ...]; kind: check (CheckBoxPreference), switch
  // (SwitchPreference), choice (ListPreference: + entries, summaries or null, default index, dialog title), list (a row
  // with its summary: PreferenceScreen, Preference), scale (the animation scale dialog).
  const SECTIONS = [
    [
      "",
      [
        [
          "check",
          "USB debugging",
          "Debug mode when USB is connected",
          "usbDebug"
        ],
        [
          "list",
          "Development device ID",
          "Device information not available"
        ],
        [
          "check",
          "Stay awake",
          "Screen will never sleep while charging",
          "stayAwake"
        ],
        [
          "check",
          "Allow mock locations",
          "Allow mock locations",
          "mockLocations"
        ],
        [
          "choice",
          "HDCP checking",
          "",
          "dev_hdcp_checking",
          false,
          [
            "Never check",
            "Check for DRM content only",
            "Always check"
          ],
          [
            "Never use HDCP checking",
            "Use HDCP checking for DRM content only",
            "Always use HDCP checking"
          ],
          1,
          "Set HDCP checking behavior"
        ],
        [
          "list",
          "Desktop backup password",
          "Desktop full backups aren't currently protected."
        ]
      ]
    ],
    [
      "User interface",
      [
        [
          "check",
          "Strict mode enabled",
          "Flash screen when apps do long operations on main thread",
          "strictMode"
        ],
        [
          "check",
          "Pointer location",
          "Screen overlay showing current touch data",
          "pointerLocation"
        ],
        [
          "check",
          "Show touches",
          "Show visual feedback for touches",
          "showTouches"
        ],
        [
          "check",
          "Show screen updates",
          "Flash areas of screen when they update",
          "surfaceUpdates"
        ],
        [
          "check",
          "Show CPU usage",
          "Screen overlay showing current CPU usage",
          "showCpu"
        ],
        [
          "check",
          "Force GPU rendering",
          "Use 2D hardware acceleration in applications",
          "forceGpu"
        ],
        [
          "scale",
          "Window animation scale",
          "",
          "windowScale"
        ],
        [
          "scale",
          "Transition animation scale",
          "",
          "transitionScale"
        ]
      ]
    ],
    [
      "Apps",
      [
        [
          "check",
          "Don't keep activities",
          "Destroy every activity as soon as the user leaves it",
          "dontKeep"
        ],
        [
          "choice",
          "Background process limit",
          "",
          "dev_app_process_limit",
          false,
          [
            "Standard limit",
            "No background processes",
            "At most 1 process",
            "At most 2 processes",
            "At most 3 processes",
            "At most 4 processes"
          ],
          null,
          0,
          "Background process limit"
        ],
        [
          "check",
          "Show all ANRs",
          "Show App Not Responding dialog for background apps",
          "showAnrs"
        ]
      ]
    ]
  ];
  // English -> [hu, de, fr, es] as the image's Settings.apk (or framework-res) translates it.
  const STRINGS = {
    "USB debugging":["USB hibakeresés","USB-Debugging","Débogage USB","Depuración USB"],
    "Debug mode when USB is connected":["Hibakeresés mód USB csatlakoztatásakor","Debugmodus bei Anschluss über USB","Mode débogage lorsqu'un câble USB est connecté","Modo de depuración cuando el dispositivo está conectado por USB"],
    "Development device ID":["Fejlesztési eszköz azonosítója","Entwicklungsgerät-ID","ID appareil de développement","ID del dispositivo de desarrollo"],
    "Device information not available":["Nem áll rendelkezésre eszközinformáció","Geräteinformationen nicht verfügbar","Informations sur l'appareil non disponibles.","Información de dispositivo no disponible"],
    "Stay awake":["Nem kapcsolódik ki","Aktiv lassen","Rester activé","Pantalla activa"],
    "Screen will never sleep while charging":["A képernyő soha nem kapcsol ki töltés során","Display wird beim Laden nie in den Ruhezustand versetzt","L'écran ne se met jamais en veille lors du chargement","La pantalla nunca entra en modo de suspensión durante la carga"],
    "Allow mock locations":["Helyutánzatok engedélyezése","Falsche Standorte","Positions fictives","Ubicaciones simuladas"],
    "HDCP checking":["HDCP ellenőrzés","HDCP-Prüfung","Vérification HDCP","Comprobación de HDCP"],
    "Never check":["Ellenőrzés soha","Nie prüfen","Ne jamais vérifier","No comprobar"],
    "Check for DRM content only":["Csak DRM-tartalom ellenőrzése","Nur auf DRM-Inhalte prüfen","Vérifier le contenu GDN uniquement","Buscar solo contenido DRM"],
    "Always check":["Ellenőrzés mindig","Immer prüfen","Toujours vérifier","Comprobar siempre"],
    "Never use HDCP checking":["Soha ne használjon HDCP ellenőrzést","HDCP-Prüfung nie verwenden","Ne jamais utiliser la vérification HDCP","No utilizar comprobación de HDCP"],
    "Use HDCP checking for DRM content only":["Csak DRM-tartalomhoz használjon HDCP ellenőrzést","HDCP-Prüfung nur für DRM-Inhalte verwenden","Utiliser la vérification HDCP uniquement pour le contenu GDN","Utilizar comprobación de HDCP solo para contenido DRM"],
    "Always use HDCP checking":["Mindig használjon HDCP ellenőrzést","HDCP-Prüfung immer verwenden","Toujours utiliser la vérification HDCP","Utilizar siempre comprobación de HDCP"],
    "Set HDCP checking behavior":["HDCP-ellenőrzés beállítása","HDCP-Prüfverhalten festl.","Config. vérification HDCP","Definir comprobación HDCP"],
    "Desktop backup password":["Asztali mentés jelszava","Desktop-Sicherungspasswort","M. de passe sauv. ordinateur","Contraseña copias ordenador"],
    "Desktop full backups aren't currently protected.":["Az asztali teljes biztonsági mentések jelenleg nem védettek.","Vollständige Desktop-Sicherungen sind derzeit nicht passwortgeschützt.","Les sauvegardes complètes sur ordinateur ne sont actuellement pas protégées.","Las copias de seguridad completas de ordenador no están protegidas"],
    "User interface":["Felhasználói felület","Benutzeroberfläche","Interface utilisateur","Interfaz de usuario"],
    "Strict mode enabled":["Szigorú mód engedélyezve","Strikter Modus aktiviert","Mode Strict activé","Modo estricto"],
    "Flash screen when apps do long operations on main thread":["Képernyővillogás a fő szál hosszú műveleteinél","Bei längeren Aktionen im Hauptthread Bildschirm kurz einblenden","Faire clignoter écran en cas de longues opérations","Destellar si las aplicaciones tardan mucho en el proceso principal"],
    "Pointer location":["Mutató helye","Zeigerposition","Emplacement du curseur","Ubicación del puntero"],
    "Screen overlay showing current touch data":["A fedvény mutatja az aktuális érintési adatokat","Overlay mit aktuellen Daten zu Tippaktionen","Superposition écran indiquant données actuelles","Superponer los datos de las pulsaciones en la pantalla"],
    "Show touches":["Érintések megjelenítése","Berührungen anzeigen","Afficher élément sélectionné","Mostrar toques"],
    "Show visual feedback for touches":["Érintések vizuális visszajelzésének megjelenítése","Visuelles Feedback für Berührungen anzeigen","Afficher repère visuel pour éléments sélectionnés","Mostrar la ubicación de las pulsaciones en la pantalla"],
    "Show screen updates":["Képernyőfrissítések","Updates anzeigen","Afficher mises à jour écran","Ver cambios pantalla"],
    "Flash areas of screen when they update":["A képernyőterületek villognak, amikor frissülnek","Bildschirmbereiche beim Update kurz einblenden","Faire clignoter les mises à jour sur l'écran","Destellar zonas de la pantalla al actualizarse"],
    "Show CPU usage":["CPU-használat mutatása","CPU-Auslastung anzeigen","Afficher mém. CPU utilisée","Mostrar uso de CPU"],
    "Screen overlay showing current CPU usage":["Képernyőfedvény a jelenlegi CPU-használattal","Bildschirm-Overlay mit aktueller CPU-Auslastung","Superposition écran indiquant mémoire CPU utilisée","Suporponer el uso de la CPU en la pantalla"],
    "Force GPU rendering":["GPU-megjelenítés","GPU-Rendering erzwingen","Forcer le rendu GPU","Forzar aceleración GPU"],
    "Use 2D hardware acceleration in applications":["2D hardvergyorsítás használata az alkalmazásokban","2D-Hardwarebeschleunigung in Apps verwenden","Utiliser accélération matérielle 2D dans applis","Usar aceleración de hardware 2D en aplicaciones"],
    "Window animation scale":["Ablakanimáció mérete","Maßstab Fensteranimation","Échelle animation fenêtres","Escala de animación ventana"],
    "Transition animation scale":["Áttűnési animáció mérete","Maßstab Übergangsanimation","Échelle anim. transitions","Escala de transición-animación"],
    "Apps":["Alkalmazások","Apps","Applications","Aplicaciones"],
    "Don't keep activities":["Törölje a tevékenységeket","Aktionen nicht speichern","Ne pas conserver activités","Destruir actividades"],
    "Destroy every activity as soon as the user leaves it":["Tevékenységek törlése, amint elhagyják azokat","Aktivität löschen, sobald der Nutzer diese beendet","Supprimer immédiatement les activités abandonnées","Destruir actividades cuando el usuario las deje"],
    "Background process limit":["Háttérfolyamat-korlátozás","Hintergrundprozesslimit","Limite processus arr.-plan","Límite de procesos en segundo plano"],
    "Standard limit":["Normál korlátozás","Standardlimit","Limite standard","Límite estándar"],
    "No background processes":["Nincsenek háttérfolyamatok","Keine Hintergrundprozesse","Aucun processus en arrière-plan","Sin procesos en segundo plano"],
    "At most 1 process":["Legfeljebb 1 folyamat","Höchstens ein Prozess","Un processus maximum","1 proceso"],
    "At most 2 processes":["Legfeljebb 2 folyamat","Höchstens zwei Prozesse","Deux processus maximum","2 procesos"],
    "At most 3 processes":["Legfeljebb 3 folyamat","Höchstens drei Prozesse","Trois processus maximum","3 procesos"],
    "At most 4 processes":["Legfeljebb 4 folyamat","Höchstens vier Prozesse","Quatre processus maximum","4 procesos"],
    "Show all ANRs":["Összes ANR mutatása","Alle ANRS anzeigen","Afficher tous les messages \"L'application ne répond pas\"","Errores sin respuesta"],
    "Show App Not Responding dialog for background apps":["Az Alkalmazás nem válaszol ablak megjelenítése","Dialogfeld \"App antwortet nicht\" für Hintergrund-Apps anzeigen","Afficher \"L'application ne répond plus\" pour applis en arrière-plan","Mostrar error de que la aplicación no responde para aplicaciones en segundo plano"]
  };
  const LANGS = ['hu', 'de', 'fr', 'es'];
  const DEFAULTS = {developerEnabled: true, verifyUsb: true, animatorScale: 1};
  const keys = () => SECTIONS.flatMap(([, rows]) => rows.map(row => row[3]).filter(Boolean));
  // PreferenceCategory titles: Holo's list separators are all caps, Material's preference_category_material is not.
  const CATEGORY_CAPS = true;

  function render(settings, t, scaleLabel, lang = 'en') {
    const on = settings.developerEnabled !== false, i = LANGS.indexOf(lang);
    const T = text => STRINGS[text] && i >= 0 ? STRINGS[text][i] : STRINGS[text] ? text : t(text);
    return SECTIONS.map(([category, rows]) => `${category ? `<div class="section-label">${e(CATEGORY_CAPS ? T(category).toLocaleUpperCase() : T(category))}</div>` : ''}${rows.map(([kind, title, summary, key, dependent]) => {
      const disabled = !on || (dependent && !settings.usbDebug) || (key === 'waitDebugger');
      const attrs = disabled ? 'disabled aria-disabled="true"' : '';
      const copy = `<span class="row-copy">${e(T(title))}${summary ? `<small>${e(T(summary))}</small>` : ''}</span>`;
      if (kind === 'check') return `<button class="settings-row wireless-row jb-dev-row" data-action="toggle-setting" data-id="${key}" role="checkbox" aria-checked="${!!settings[key]}" ${attrs}>${copy}<img class="holo-checkbox" src="assets/btn_check_${settings[key] ? 'on' : 'off'}_holo_dark.png" alt=""></button>`;
      if (kind === 'switch') return `<button class="settings-row lp-switch-row jb-dev-row" data-action="toggle-setting" data-id="${key}" role="switch" aria-checked="${!!settings[key]}" ${attrs}>${copy}<span class="lp-mswitch${settings[key] ? ' on' : ''}" aria-hidden="true"></span></button>`;
      if (kind === 'choice') { const [, , , , , entries, summaries, fallback] = SECTIONS.flatMap(([, list]) => list).find(row => row[3] === key); const index = settings[key] ?? fallback; return `<button class="settings-row jb-dev-row" data-action="dev-list" data-id="${key}" ${attrs}><span class="row-copy">${e(T(title))}<small>${e(T((summaries || entries)[index] ?? entries[0]))}</small></span></button>`; }
      if (kind === 'scale') return `<button class="settings-row jb-dev-row" data-action="sd-dialog" data-id="${key}" ${attrs}><span class="row-copy">${e(T(title))}<small>${e(t(scaleLabel(settings[key] ?? 1)))}</small></span></button>`;
      return `<button class="settings-row jb-dev-row" data-action="dev-info" data-id="${e(title)}" ${attrs}>${copy}</button>`;
    }).join('')}`).join('');
  }

  // ListPreference's dialog: the title, the entries as single-choice rows, Cancel; a tap picks and closes.
  function dialog(key, settings, t, lang = 'en') {
    const row = SECTIONS.flatMap(([, rows]) => rows).find(item => item[0] === 'choice' && item[3] === key);
    if (!row) return '';
    const i = LANGS.indexOf(lang), T = text => STRINGS[text] && i >= 0 ? STRINGS[text][i] : STRINGS[text] ? text : t(text);
    const [, , , , , entries, , fallback, title] = row, current = settings[key] ?? fallback;
    return `<div class="settings-dialog-scrim" data-action="close-overlay"></div><div class="settings-dialog" role="dialog" aria-label="${e(T(title))}"><h3>${e(T(title))}</h3>${entries.map((entry, n) => `<button class="settings-row wireless-row" data-action="dev-list-pick" data-id="${key}:${n}" role="radio" aria-checked="${n === current}"><span class="row-copy">${e(T(entry))}</span>${CATEGORY_CAPS ? `<img class="holo-radio" src="assets/btn_radio_${n === current ? 'on' : 'off'}_holo_dark.png" alt="">` : `<span class="lp-radio${n === current ? ' on' : ''}" aria-hidden="true"></span>`}</button>`).join('')}<div class="settings-dialog-actions"><button data-action="close-overlay">${e(t('Cancel'))}</button></div></div>`;
  }

  /* Overlays: layout bounds (red clip bounds and blue corner marks), PointerLocationView's top bar, and the
     LoadAverageService panel at the top right. */
  function apply(screen, settings) {
    const on = settings.developerEnabled !== false;
    screen.classList.toggle('dev-layout-bounds', on && !!settings.layoutBounds);
    let pointer = screen.querySelector('.dev-pointer-bar'), cpu = screen.querySelector('.dev-cpu');
    if (on && settings.pointerLocation && !pointer) { pointer = document.createElement('div'); pointer.className = 'dev-pointer-bar'; pointer.setAttribute('aria-hidden', 'true'); pointer.textContent = 'P: 0 / 0   X: 0.0   Y: 0.0   Xv: 0.000   Yv: 0.000   Prs: 0.00   Size: 0.00'; screen.append(pointer); }
    if (!(on && settings.pointerLocation) && pointer) pointer.remove();
    if (on && settings.showCpu && !cpu) { cpu = document.createElement('div'); cpu.className = 'dev-cpu'; cpu.setAttribute('aria-hidden', 'true'); screen.append(cpu); updateCpu(cpu); }
    if (!(on && settings.showCpu) && cpu) cpu.remove();
  }
  function updateCpu(cpu) {
    const t = Date.now() / 1000, load = [0.48 + .12 * Math.sin(t / 7), 0.42 + .06 * Math.sin(t / 19), 0.39];
    const procs = [['system_server', 4 + 3 * Math.abs(Math.sin(t / 3))], ['com.android.systemui', 2 + 2 * Math.abs(Math.sin(t / 5))], ['surfaceflinger', 1.5 + Math.abs(Math.sin(t / 2))], ['com.android.launcher', 1 + Math.abs(Math.sin(t / 4))]];
    cpu.innerHTML = `<b>${load.map(v => v.toFixed(2)).join(' / ')}</b>${procs.map(([name, value]) => `<span><i style="width:${value * 6}px"></i>${name}</span>`).join('')}`;
  }
  function pointerMove(screen, event, down, count) {
    const bar = screen.querySelector('.dev-pointer-bar'); if (!bar) return;
    const box = screen.getBoundingClientRect(), k = box.width / screen.offsetWidth || 1, x = (event.clientX - box.left) / k * 2, y = (event.clientY - box.top) / k * 2;
    bar.textContent = `P: ${down ? 1 : 0} / ${count}   X: ${x.toFixed(1)}   Y: ${y.toFixed(1)}   Xv: 0.000   Yv: 0.000   Prs: ${down ? '1.00' : '0.00'}   Size: ${down ? '0.20' : '0.00'}`;
  }
  window.JBDeveloperOptions = {SECTIONS, STRINGS, DEFAULTS, keys, render, dialog, apply, updateCpu, pointerMove};
})();
