/* Generated by docs/apk-strings.py from the maguro image's Mms.apk (docs/mms-strings.template.js): the Messaging
   words of the menus (conversation_list_menu, ComposeMessageActivity.onPrepareOptionsMenu and the message context menu),
   the confirmation and details dialogs (ConversationList.confirmDeleteThreadDialog, confirmDeleteDialog,
   MessageUtils.getTextMessageDetails) and the Insert smiley list (default_smiley_names / default_smiley_texts with
   SmileyParser's emo_im_* icons, in that order). MmsStrings.t(english) answers in the simulator's language. */
(() => {
  'use strict';
  const LANGS = ['hu', 'de', 'fr', 'es'];
  const STRINGS = {
      "Messaging": [
          "Üzenetek",
          "SMS/MMS",
          "SMS/MMS",
          "Mensajes"
      ],
      "New message": [
          "Új üzenet",
          "Neue Nachricht",
          "Nouveau message",
          "Mensaje nuevo"
      ],
      "Search messaging": [
          "Keresés az üzenetekben",
          "SMS/MMS durchsuchen",
          "Rechercher dans les messages",
          "Buscar mensajes"
      ],
      "To": [
          "Címzett",
          "An",
          "À",
          "Para"
      ],
      "Type message": [
          "Írja be az üzenetet",
          "Nachricht schreiben",
          "Saisissez un message",
          "Escribir mensaje"
      ],
      "Draft": [
          "Piszkozat",
          "Entwurf",
          "Brouillon",
          "Borrador"
      ],
      "No conversations.": [
          "Nincsenek beszélgetések.",
          "Keine Konversationen",
          "Aucune conversation",
          "No hay conversaciones."
      ],
      "Attach": [
          "Csatolás",
          "Anhängen",
          "Pièce jointe",
          "Adjuntar"
      ],
      "Call": [
          "Hívás",
          "Anrufen",
          "Appeler",
          "Llamar"
      ],
      "Send": [
          "Küldés",
          "Senden",
          "Envoyer",
          "Enviar"
      ],
      "MMS": [
          "MMS",
          "MMS",
          "MMS",
          "MMS"
      ],
      "Settings": [
          "Beállítások",
          "Einstellungen",
          "Paramètres",
          "Ajustes"
      ],
      "Delete all threads": [
          "Összes beszélgetés törlése",
          "Alle Threads löschen",
          "Supprimer tous les fils de discussion",
          "Eliminar todas las conversaciones"
      ],
      "Add subject": [
          "Tárgy hozzáadása",
          "Betreff hinzufügen",
          "Ajouter un objet",
          "Añadir asunto"
      ],
      "Insert smiley": [
          "Hangulatjel beszúrása",
          "Smiley einfügen",
          "Insérer une émoticône",
          "Insertar emoticono"
      ],
      "Delete thread": [
          "Szál törlése",
          "Konversation löschen",
          "Supprimer le fil",
          "Eliminar cadena"
      ],
      "Discard": [
          "Elvetés",
          "Verwerfen",
          "Supprimer",
          "Descartar"
      ],
      "Add to People": [
          "Hozzáadás a névjegyekhez",
          "Zu Kontakten hinzufügen",
          "Ajouter aux contacts",
          "Añadir a Contactos"
      ],
      "Message options": [
          "Üzenetbeállítások",
          "Nachrichtenoptionen",
          "Options du message",
          "Opciones del mensaje"
      ],
      "Copy text": [
          "Szöveg másolása",
          "Text kopieren",
          "Copier le texte",
          "Copiar texto"
      ],
      "Forward": [
          "Továbbítás",
          "Weiterleiten",
          "Transférer",
          "Reenviar"
      ],
      "Lock": [
          "Zárolás",
          "Sperren",
          "Verrouiller",
          "Bloquear"
      ],
      "Unlock": [
          "Feloldás",
          "Entsperren",
          "Déverrouiller",
          "Desbloquear"
      ],
      "View details": [
          "Részletek megjelenítése",
          "Details anzeigen",
          "Afficher les détails",
          "Ver detalles"
      ],
      "Delete": [
          "Törlés",
          "Löschen",
          "Supprimer",
          "Eliminar"
      ],
      "Delete?": [
          "Törli?",
          "Löschen?",
          "Supprimer ?",
          "¿Eliminar?"
      ],
      "The entire thread will be deleted.": [
          "Az egész szál törlésre kerül.",
          "Der gesamte Thread wird gelöscht.",
          "L'intégralité du fil de discussion va être supprimée.",
          "Se eliminará toda la cadena."
      ],
      "All threads will be deleted.": [
          "Az összes szál törlésre kerül.",
          "Alle Threads werden gelöscht.",
          "Tous les fils de discussion vont être supprimés.",
          "Se eliminarán todas las conversaciones."
      ],
      "Delete locked messages": [
          "Zárolt üzenetek törlése",
          "Gesperrte Nachrichten löschen",
          "Supprimer les messages verrouillés",
          "Eliminar mensajes bloqueados"
      ],
      "The message will be deleted.": [
          "Az üzenet törlésre kerül.",
          "Die Nachricht wird gelöscht.",
          "Le message va être supprimé.",
          "Se eliminará el mensaje."
      ],
      "Delete this locked message?": [
          "Törli ezt a zárolt üzenetet?",
          "Diese gesperrte Nachricht löschen?",
          "Supprimer ce message verrouillé ?",
          "¿Seguro que quieres eliminar este mensaje bloqueado?"
      ],
      "Cancel": [
          "Mégse",
          "Abbrechen",
          "Annuler",
          "Cancelar"
      ],
      "Message details": [
          "Üzenet részletei",
          "Nachrichtendetails",
          "Détails du message",
          "Detalles del mensaje"
      ],
      "Type: ": [
          "Típus: ",
          "Typ: ",
          "Type : ",
          "Tipo: "
      ],
      "Text message": [
          "Szöveges üzenet",
          "SMS",
          "Message SMS",
          "Mensaje de texto"
      ],
      "Multimedia message": [
          "Multimédiás üzenet",
          "Multimedia-Nachricht",
          "Message multimédia",
          "Mensaje multimedia"
      ],
      "From: ": [
          "Feladó: ",
          "Von: ",
          "De : ",
          "De: "
      ],
      "To: ": [
          "Címzett: ",
          "An: ",
          "À : ",
          "Para: "
      ],
      "Sent: ": [
          "Elküldve: ",
          "Gesendet: ",
          "Date d'envoi : ",
          "Enviado: "
      ],
      "Received: ": [
          "Kézbesítve: ",
          "Empfangen: ",
          "Date de réception : ",
          "Recibido: "
      ],
      "Happy": [
          "Mosoly",
          "Glücklich",
          "Content",
          "Contento"
      ],
      "Sad": [
          "Szomorú",
          "Traurig",
          "Triste",
          "Triste"
      ],
      "Winking": [
          "Kacsintás",
          "Zwinkern",
          "Clin d'œil",
          "Guiño"
      ],
      "Tongue sticking out": [
          "Nyelvnyújtás",
          "Frech",
          "Tire la langue",
          "Sacando la lengua"
      ],
      "Surprised": [
          "Meglepődött",
          "Überrascht",
          "Surpris",
          "Sorprendido"
      ],
      "Kissing": [
          "Csók",
          "Kuss",
          "Bisou",
          "Besando"
      ],
      "Yelling": [
          "Kiabálás",
          "Schreien",
          "Hurle",
          "Sorpresa"
      ],
      "Cool": [
          "Laza",
          "Cool",
          "Cool",
          "Atractivo"
      ],
      "Money mouth": [
          "Pénz beszél",
          "Dollarzeichen",
          "Argent",
          "Dinero en la boca"
      ],
      "Foot in mouth": [
          "Ha hallgattam volna...",
          "Fettnäpfchen",
          "Embarrassé",
          "Metedura de pata"
      ],
      "Embarrassed": [
          "Zavarban",
          "Peinlich berührt",
          "Gêné",
          "Avergonzado"
      ],
      "Angel": [
          "Angyal",
          "Engel",
          "Ange",
          "Ángel"
      ],
      "Undecided": [
          "Határozatlan",
          "Unentschlossen",
          "Indécis",
          "Indeciso"
      ],
      "Crying": [
          "Sírás",
          "Weinen",
          "Pleure",
          "Llorando"
      ],
      "Lips are sealed": [
          "Szót se szólok",
          "Versiegelte Lippen",
          "Motus",
          "Labios sellados"
      ],
      "Laughing": [
          "Nevetés",
          "Fröhlich",
          "Rigole",
          "Riendo"
      ],
      "Confused": [
          "Összezavarodva",
          "Verwirrt",
          "Confus",
          "Confuso"
      ],
      "Heart": [
          "Szív",
          "Verliebt",
          "Cœur",
          "Corazón"
      ],
      "Mad": [
          "Mérges",
          "Verärgert",
          "Mécontent",
          "Enfadado"
      ],
      "Smirk": [
          "Kacsintás",
          "Grinsen",
          "Sourire en coin",
          "No mola"
      ],
      "Poker face": [
          "Pókerarc",
          "Pokergesicht",
          "Lunettes de soleil",
          "Cara de póquer"
      ]
  };
  const SMILEYS = [['Happy', ':-)', 'happy'], ['Sad', ':-(', 'sad'], ['Winking', ';-)', 'winking'], ['Tongue sticking out', ':-P', 'tongue_sticking_out'],
    ['Surprised', '=-O', 'surprised'], ['Kissing', ':-*', 'kissing'], ['Yelling', ':O', 'yelling'], ['Cool', 'B-)', 'cool'], ['Money mouth', ':-$', 'money_mouth'],
    ['Foot in mouth', ':-!', 'foot_in_mouth'], ['Embarrassed', ':-[', 'embarrassed'], ['Angel', 'O:-)', 'angel'], ['Undecided', ':-\\', 'undecided'],
    ['Crying', ":'(", 'crying'], ['Lips are sealed', ':-X', 'lips_are_sealed'], ['Laughing', ':-D', 'laughing'], ['Confused', 'o_O', 'wtf'], ['Heart', '<3', 'heart'],
    ['Mad', 'x-(', 'mad'], ['Smirk', ':-/', 'smirk'], ['Poker face', ':-I', 'pokerface']];
  const t = (key, lang = window.AndroidI18n?.language || 'en') => { const row = STRINGS[key], i = LANGS.indexOf(lang); return row ? i >= 0 ? row[i] : row[4] || key : key; };
  window.MmsStrings = {t, has: key => key in STRINGS, SMILEYS};
})();
