/* Generated by docs/apk-strings.py from the maguro image's contacts app (docs/people-strings.template.js): the menu
   words of view_contact / quickcontact and people_options, and ContactDeletionInteraction's confirmation (its message
   with the framework's Cancel / OK; Ice Cream Sandwich adds the Delete title). PeopleStrings.t(english) answers in the
   simulator's language; has() tells which items this release's menus carry. */
(() => {
  'use strict';
  const LANGS = ['hu', 'de', 'fr', 'es'];
  const STRINGS = {
      "Edit": [
          "Szerkesztés",
          "Bearbeiten",
          "Modifier",
          "Editar"
      ],
      "Share": [
          "Megosztás",
          "Teilen",
          "Partager",
          "Compartir"
      ],
      "Delete": [
          "Törlés",
          "Löschen",
          "Supprimer",
          "Eliminar"
      ],
      "Set ringtone": [
          "Csengőhang",
          "Klingeltonwahl",
          "Régler sonnerie",
          "Establecer tono"
      ],
      "All calls to voicemail": [
          "Minden hívás a hangpostára",
          "Alle Anrufe an Mailbox",
          "Tous appels vers messag. voc.",
          "Llamadas al buzón de voz"
      ],
      "Contacts to display": [
          "Megjelenítendő névjegyek",
          "Kontakte zum Anzeigen",
          "Contacts à afficher",
          "Contactos que mostrar"
      ],
      "Import/export": [
          "Importálás/exportálás",
          "Importieren/Exportieren",
          "Importer/Exporter",
          "Importar/exportar"
      ],
      "Accounts": [
          "Fiókok",
          "Konten",
          "Comptes",
          "Cuentas"
      ],
      "Settings": [
          "Beállítások",
          "Einstellungen",
          "Paramètres",
          "Ajustes"
      ],
      "Delete contact?": [
          "Törli a névjegyet?",
          "Kontakt löschen?",
          "Supprimer contact ?",
          "¿Eliminar contacto?"
      ],
      "This contact will be deleted.": [
          "A névjegy törlésre kerül.",
          "Dieser Kontakt wird gelöscht.",
          "Ce contact sera supprimé.",
          "El contacto se eliminará."
      ],
      "OK": [
          "OK",
          "OK",
          "OK",
          "Aceptar"
      ],
      "Cancel": [
          "Mégse",
          "Abbruch",
          "Annuler",
          "Cancelar"
      ]
  };
  const t = (key, lang = window.AndroidI18n?.language || 'en') => { const row = STRINGS[key], i = LANGS.indexOf(lang); return row ? i >= 0 ? row[i] : row[4] || key : key; };
  window.PeopleStrings = {t, has: key => key in STRINGS, device: 'maguro'};
})();
