/* Settings sub-screens of the maguro factory image, generated by docs/apk-strings.py from
   docs/settings-system.template.js: Date & time, Security (4.x; Lollipop draws its own), Device administrators,
   Tethering & portable hotspot, Advanced Wi-Fi, VPN, the mobile network settings, Available networks and APNs, each with
   the rows its preference XML and settings code build on a GSM phone (world_phone off), in that image's words (Settings,
   Phone / TeleService). The dialogs behind the rows are local forms; network profiles never open real connections. */
(() => {
  'use strict';
  const DEVICE='maguro',ICS=DEVICE==='maguro',KK=DEVICE==='hammerhead',LP=DEVICE==='shamu';
  const STRINGS={
      "Date & time": [
          "Dátum és idő",
          "Datum & Uhrzeit",
          "Date et heure",
          "Fecha y hora"
      ],
      "Automatic date & time": [
          "Automatikus dátum és idő",
          "Autom. Datum/Uhrzeit",
          "Date/Heure automatique",
          "Fecha y hora automáticas"
      ],
      "Use network-provided time": [
          "Hálózat által megadott idő használata",
          "Zeit aus Netzwerk beziehen",
          "Utiliser la date et l'heure fournies par le réseau",
          "Usar hora proporcionada por la red"
      ],
      "Automatic time zone": [
          "Automatikus időzóna",
          "Automatische Zeitzone",
          "Fuseau horaire automatique",
          "Zona horaria automática"
      ],
      "Use network-provided time zone": [
          "Hálózat által megadott időzóna használata",
          "Vom Netzwerk angegebene Zeitzone beibehalten",
          "Utiliser le fuseau horaire fourni par le réseau",
          "Usar zona horaria proporcionada por la red"
      ],
      "Set date": [
          "Dátum beállítása",
          "Datum festlegen",
          "Définir la date",
          "Establecer fecha"
      ],
      "Set time": [
          "Idő beállítása",
          "Uhrzeit festlegen",
          "Définir l'heure",
          "Establecer hora"
      ],
      "Select time zone": [
          "Időzóna kiválasztása",
          "Zeitzone auswählen",
          "Définir le fuseau horaire",
          "Seleccionar zona horaria"
      ],
      "Use 24-hour format": [
          "24 órás formátum használata",
          "24-Stunden-Format",
          "Utiliser le format 24 h",
          "Formato de 24 horas"
      ],
      "13:00": [
          "13:00",
          "13:00",
          "13:00",
          "13:00"
      ],
      "1:00 pm": [
          "du. 1:00",
          "1:00",
          "1:00 pm",
          "1:00 p.m."
      ],
      "Choose date format": [
          "Dátumformátum kiválasztása",
          "Datumsformat",
          "Choisir le format de date",
          "Formato de fecha",
          "Select date format"
      ],
      "Security": [
          "Biztonság",
          "Sicherheit",
          "Sécurité",
          "Seguridad"
      ],
      "Screen security": [
          "Képernyővédelem",
          "Bildschirmsicherheit",
          "Sécurité de l'écran",
          "Pantalla de seguridad"
      ],
      "Screen lock": [
          "Képernyő zárolása",
          "Bildschirmsperre",
          "Verrouillage de l'écran",
          "Bloqueo de pantalla"
      ],
      "None": [
          "Nincs",
          "Keine",
          "Aucun",
          "Ninguno"
      ],
      "Slide": [
          "Csúsztatás",
          "Finger bewegen",
          "Faire glisser",
          "Deslizar"
      ],
      "Pattern": [
          "Mintával biztosítva",
          "Durch Muster geschützt",
          "Sécurisé par un schéma",
          "Protegida con patrón",
          "Secured with pattern"
      ],
      "PIN": [
          "PIN kóddal biztosítva",
          "Durch PIN geschützt",
          "Sécurisé par un code PIN",
          "Protegida con PIN",
          "Secured with PIN"
      ],
      "Password": [
          "Jelszóval biztosítva",
          "Durch Passwort geschützt",
          "Sécurisé par mot de passe",
          "Protegida con contraseña",
          "Secured with password"
      ],
      "Make pattern visible": [
          "Minta láthatóvá tétele",
          "Muster sichtbar machen",
          "Faire apparaître le schéma",
          "Mostrar el patrón"
      ],
      "Automatically lock": [
          "Automatikus zárolás",
          "Automatisch sperren",
          "Verrouiller automatiquement",
          "Bloquear automáticamente"
      ],
      "%1$s after sleep": [
          "%1$s alvó mód után",
          "Nach %1$s im Ruhezustand",
          "Après %1$s de veille",
          "%1$s tras suspender"
      ],
      "Immediately": [
          "Azonnal",
          "Sofort",
          "Immédiatement",
          "Inmediatamente"
      ],
      "5 seconds": [
          "5 másodperc",
          "5 Sekunden",
          "5 secondes",
          "5 segundos"
      ],
      "15 seconds": [
          "15 másodperc",
          "15 Sekunden",
          "15 secondes",
          "15 segundos"
      ],
      "30 seconds": [
          "30 másodperc",
          "30 Sekunden",
          "30 secondes",
          "30 segundos"
      ],
      "1 minute": [
          "1 perc",
          "1 Minute",
          "1 minute",
          "1 minuto"
      ],
      "2 minutes": [
          "2 perc",
          "2 Minuten",
          "2 minutes",
          "2 minutos"
      ],
      "5 minutes": [
          "5 perc",
          "5 Minuten",
          "5 minutes",
          "5 minutos"
      ],
      "10 minutes": [
          "10 perc",
          "10 Minuten",
          "10 minutes",
          "10 minutos"
      ],
      "30 minutes": [
          "30 perc",
          "30 Minuten",
          "30 minutes",
          "30 minutos"
      ],
      "Power button instantly locks": [
          "Bekapcsoló gomb azonnal zár",
          "Ein-/Aus sperrt Gerät sofort",
          "Verr. auto bouton MARCHE-ARRÊT",
          "Bloquear al encender"
      ],
      "Vibrate on touch": [
          "Érintéskor rezegjen",
          "Bei Berührung vibrieren",
          "Vibrer au toucher",
          "Vibrar al pulsar"
      ],
      "Owner info": [
          "Tulajdonosi adatok",
          "Inhaberinformationen",
          "Infos propriétaire",
          "Información del propietario"
      ],
      "Encryption": [
          "Titkosítás",
          "Verschlüsselung",
          "Chiffrement",
          "Encriptación"
      ],
      "Encrypt phone": [
          "Telefon titkosítása",
          "Telefon verschlüsseln",
          "Chiffrer le téléphone",
          "Encriptar teléfono"
      ],
      "Require a numeric PIN or password to decrypt your phone each time you power it on": [
          "A telefon titkosításának feloldásához kérjen minden bekapcsoláskor egy számokból álló PIN kódot vagy jelszót",
          "Eine numerische PIN oder ein Passwort einrichten, mit dem das Telefon beim Einschalten entschlüsselt werden muss.",
          "Exiger un code PIN ou un mot de passe numérique pour déchiffrer le téléphone à chaque fois qu'il est allumé",
          "Solicitar una contraseña o un PIN numérico para descifrar el teléfono cada vez que se encienda"
      ],
      "SIM card lock": [
          "SIM-kártya zárolása",
          "SIM-Kartensperre",
          "Verrouillage de la SIM",
          "Bloqueo de tarjeta SIM"
      ],
      "Set up SIM card lock": [
          "SIM-kártya zárolásának beállítása",
          "SIM-Sperre einrichten",
          "Configurer verrouillage carte SIM",
          "Bloqueo de tarjeta SIM"
      ],
      "Passwords": [
          "Jelszavak",
          "Passwörter",
          "Mots de passe",
          "Contraseñas"
      ],
      "Make passwords visible": [
          "Jelszó láthatóvá tétele",
          "Passwörter sichtbar",
          "Faire apparaître les mots de passe",
          "Mostrar las contraseñas"
      ],
      "Device administration": [
          "Eszközfelügyelet",
          "Geräteverwaltung",
          "Gestion de l'appareil",
          "Administración de dispositivos"
      ],
      "Device administrators": [
          "Eszköz-rendszergazdák",
          "Geräteadministratoren",
          "Administrateurs de l'appareil",
          "Administradores de dispositivos"
      ],
      "View or deactivate device administrators": [
          "Az eszköz rendszergazdáinak megtekintése vagy deaktiválása",
          "Geräteadministratoren abrufen oder deaktivieren",
          "Afficher ou désactiver les administrateurs de l'appareil",
          "Ver o desactivar administradores de dispositivo"
      ],
      "Unknown sources": [
          "Ismeretlen források",
          "Unbekannte Herkunft",
          "Sources inconnues",
          "Orígenes desconocidos"
      ],
      "Allow installation of apps from unknown sources": [
          "Nem a Marketről származó alkalmazások telepítésének engedélyezése",
          "Installation von Nicht-Market-Apps zulassen",
          "Autoriser l'installation d'applications ne provenant pas de l'Android Market",
          "Permitir instalar aplicaciones que no estén en Android Market",
          "Allow installation of non-Market apps"
      ],
      "Credential storage": [
          "Hitelesítési adatok tárolója",
          "Anmeldedatenspeicher",
          "Stockage des identifiants",
          "Almacenamiento de credenciales"
      ],
      "Trusted credentials": [
          "Megbízható hitelesítő adatok",
          "Vertrauensw. Anmeldedaten",
          "Certificats de confiance",
          "Credenciales de confianza"
      ],
      "Display trusted CA certificates": [
          "Megbízható CA tanúsítványok megjelenítése",
          "Vertrauenswürdige CA-Zertifikate anzeigen",
          "Afficher les certificats d'autorité de confiance",
          "Mostrar certificados de CA de confianza"
      ],
      "Install from storage": [
          "Telepítés tárhelyről",
          "Von Speicher installieren",
          "Installer depuis la mémoire",
          "Instalar desde almacenamiento"
      ],
      "Install certificates from storage": [
          "Tanúsítványok telepítése tárhelyről",
          "Zertifikate von Speicher installieren",
          "Installer les certificats depuis la mémoire de stockage",
          "Instalar certificados desde almacenamiento"
      ],
      "Clear credentials": [
          "Hitelesítési adatok törlése",
          "Anmeldedaten löschen",
          "Effacer les identifiants",
          "Borrar credenciales"
      ],
      "Remove all certificates": [
          "Összes tanúsítvány eltávolítása",
          "Alle Zertifikate entfernen",
          "Supprimer tous les certificats",
          "Eliminar todos los certificados"
      ],
      "No available device administrators": [
          "Nincs elérhető eszközkezelő",
          "Keine Geräteadministratoren verfügbar",
          "Aucun administrateur disponible.",
          "No hay ningún administrador de dispositivos disponible."
      ],
      "Tethering & portable hotspot": [
          "Megosztás és hord. csatl. pont",
          "Tethering & mobiler Hotspot",
          "Partage de connexion",
          "Anclaje a red y zona Wi-Fi"
      ],
      "USB tethering": [
          "USB megosztás",
          "USB-Tethering",
          "Via USB",
          "Anclaje de USB"
      ],
      "USB not connected": [
          "Nincs USB-kapcsolat",
          "Keine USB-Verbindung",
          "USB non connecté",
          "USB no conectado"
      ],
      "Portable Wi-Fi hotspot": [
          "Hordozható Wi-Fi hotspot",
          "Mobiler WLAN-Hotspot",
          "Point d'accès Wi-Fi",
          "Zona Wi-Fi portátil"
      ],
      "Set up Wi-Fi hotspot": [
          "Wi-Fi hotspot konfigurálása",
          "WLAN-Hotspot konfigurieren",
          "Configurer le point d'accès Wi-Fi",
          "Configurar zona Wi-Fi",
          "Configure Wi-Fi hotspot"
      ],
      "Bluetooth tethering": [
          "Bluetooth megosztása",
          "Bluetooth-Tethering",
          "Via Bluetooth",
          "Anclaje de Bluetooth"
      ],
      "Help": [
          "Súgó",
          "Hilfe",
          "Aide",
          "Ayuda"
      ],
      "Advanced Wi-Fi": [
          "Haladó Wi-Fi",
          "Erweiterte WLAN-Einstellungen",
          "Paramètres Wi-Fi avancés",
          "Ajustes avanzados de Wi-Fi"
      ],
      "Network notification": [
          "Hálózati értesítés",
          "Netzwerkhinweis",
          "Notification de réseau",
          "Notificación de red"
      ],
      "Notify me when an open network is available": [
          "Értesítést kérek az elérhető nyitott hálózatokról",
          "Benachrichtigen, wenn ein offenes Netzwerk verfügbar ist",
          "Me notifier lorsqu'un réseau ouvert est disponible",
          "Informarme cuando haya una red abierta disponible"
      ],
      "Keep Wi-Fi on during sleep": [
          "Tartsa bekapcsolva a Wi-Fit alvás közben",
          "WLAN im Standby-Modus aktiviert lassen",
          "Wi-Fi actif en veille",
          "Usar Wi-Fi en suspensión"
      ],
      "Always": [
          "Mindig",
          "Immer",
          "Toujours",
          "Siempre"
      ],
      "Only when plugged in": [
          "Csak ha csatlakoztatva van",
          "Nur wenn angeschlossen",
          "Uniquement si l'appareil est branché",
          "Solo si se está cargando"
      ],
      "Never (increases data usage)": [
          "Soha (növeli az adatforgalmat)",
          "Nie (erhöht den Datenverbrauch)",
          "Jamais (utilise plus de données)",
          "Nunca (aumenta el uso de datos)"
      ],
      "Avoid poor connections": [
          "Kerülje a rossz minőségű kapcsolatokat",
          "Schlechte Internetverbindungen vermeiden",
          "Éviter mauvaises connexions",
          "Solo conexiones buenas"
      ],
      "Don't use a Wi-Fi network unless it has a good Internet connection": [
          "Csak akkor használjon Wi-Fi hálózatot, ha jó internetkapcsolatot tud biztosítani",
          "WLAN nur bei guter Internetverbindung verwenden",
          "Ne pas utiliser de réseau Wi-Fi, sauf en cas de connexion Internet de bonne qualité",
          "No usar una red Wi-Fi a menos que tenga una buena conexión a Internet"
      ],
      "Wi-Fi frequency band": [
          "Wi-Fi frekvenciasáv",
          "WLAN-Frequenzband",
          "Plage de fréquences Wi-Fi",
          "Banda de frecuencia WiFi"
      ],
      "Specify the frequency range of operation": [
          "Adja meg a működési frekvenciatartományt",
          "Frequenzbereich für Betrieb festlegen",
          "Définir la plage de fréquences",
          "Especificar intervalo frecuencia de funcionamiento"
      ],
      "Automatic": [
          "Automatikus",
          "Automatisch",
          "Automatique",
          "Automático",
          "Auto"
      ],
      "5 GHz only": [
          "Csak 5 GHz",
          "Nur 5 GHz",
          "5 GHz uniquement",
          "Solo 5 GHz"
      ],
      "2.4 GHz only": [
          "Csak 2,4 GHz",
          "Nur 2,4 GHz",
          "2,4 GHz uniquement",
          "Solo 2,4 GHz"
      ],
      "MAC address": [
          "MAC-cím",
          "MAC-Adresse",
          "Adresse MAC",
          "Dirección MAC"
      ],
      "IP address": [
          "IP-cím",
          "IP-Adresse",
          "Adresse IP",
          "Dirección IP"
      ],
      "Unavailable": [
          "Nem érhető el",
          "Nicht verfügbar",
          "Non disponible",
          "No disponible"
      ],
      "VPN": [
          "VPN",
          "VPN",
          "VPN",
          "VPN"
      ],
      "Add VPN profile": [
          "VPN-hálózat hozzáadása",
          "VPN hinzufügen",
          "Ajouter un réseau VPN",
          "Añadir red VPN",
          "Add VPN network"
      ],
      "Mobile network settings": [
          "Mobilhálózati beállítások",
          "Einstellungen für Mobilfunknetze",
          "Paramètres du réseau mobile",
          "Configuración de red móvil"
      ],
      "Data enabled": [
          "Adatok engedélyezése",
          "Daten aktiviert",
          "Données activées",
          "Habilitar datos"
      ],
      "Enable data access over Mobile network": [
          "Adathozzáférés engedélyezése mobilhálózatokon",
          "Datenzugriff über Mobilfunknetz aktivieren",
          "Activer l'accès aux données sur le réseau mobile",
          "Permitir el acceso a los datos a través de la red móvil"
      ],
      "Data roaming": [
          "Adatbarangolás",
          "Daten-Roaming",
          "Itinérance des données",
          "Itinerancia de datos"
      ],
      "Connect to data services when roaming": [
          "Csatlakozás adatszolgáltatásokhoz barangolás során",
          "Bei Roaming mit Datendienst verbinden",
          "Se connecter aux services de données lors de l'itinérance",
          "Establecer conexión con servicios de datos en itinerancia"
      ],
      "Preferred network type": [
          "Hálózati mód",
          "Netzwerkmodus",
          "Mode réseau",
          "Modo de red",
          "Network Mode"
      ],
      "Access Point Names": [
          "Hozzáférési pontok nevei",
          "Zugangspunkte",
          "Noms des points d'accès",
          "APN"
      ],
      "Use only 2G networks": [
          "Csak 2G hálózatok használata",
          "Nur 2G-Netzwerke",
          "Réseau 2G seulement",
          "Utilizar solo redes 2G"
      ],
      "Saves battery": [
          "Spórol az energiával",
          "Energiesparend",
          "Économise la batterie",
          "Ahorrar batería"
      ],
      "Network operators": [
          "Mobilszolgáltatók",
          "Mobilfunkanbieter",
          "Opérateur de réseau",
          "Operadores de red"
      ],
      "Choose a network operator": [
          "Mobilszolgáltató választása",
          "Netzbetreiber auswählen",
          "Choisir un opérateur de réseau",
          "Seleccionar un operador de red",
          "Select a network operator"
      ],
      "Available networks": [
          "Elérhető hálózatok",
          "Verfügbare Netzwerke",
          "Réseaux disponibles",
          "Redes disponibles"
      ],
      "Search networks": [
          "Hálózatkeresés",
          "Netzwerke suchen",
          "Rechercher les réseaux",
          "Buscar redes"
      ],
      "Search for all available networks": [
          "Az összes elérhető hálózat megkeresése",
          "Nach allen verfügbaren Netzwerken suchen",
          "Chercher tous les réseaux disponibles",
          "Buscar todas las redes disponibles"
      ],
      "Choose automatically": [
          "Automatikus kiválasztás",
          "Automatisch auswählen",
          "Sélection automatique",
          "Seleccionar automáticamente",
          "Select automatically"
      ],
      "Automatically choose preferred network": [
          "Preferált hálózat automatikus kiválasztása",
          "Bevorzugtes Netzwerk automatisch auswählen",
          "Sélectionner automatiquement",
          "Seleccionar la red preferida de forma automática",
          "Automatically select preferred network"
      ],
      "APNs": [
          "APN-ek",
          "APNs",
          "APN",
          "APN"
      ],
      "New APN": [
          "Új APN",
          "Neuer APN",
          "Nouvel APN",
          "APN nuevo"
      ]
  };
  const LANGS=['hu','de','fr','es'];
  const S=key=>{const row=STRINGS[key];if(!row)return key;const i=LANGS.indexOf(window.AndroidI18n?.language);return (i>=0?row[i]:row[4])||key;};
  const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const defaults={autoTime:true,autoZone:true,timeOffset:0,timeZone:'Europe/Budapest',hour24:true,dateFormat:'locale',screenLock:'slide',ownerInfo:'',showOwner:false,lockAfter:'5000',powerInstantLock:true,lockTactile:true,kgWidgets:false,hotspotName:'AndroidAP',hotspotSecurity:'WPA2',bluetoothTether:false,wifiSleep:'always',wifiScanAlways:false,wifiPoorAvoid:false,wifiBand:'auto',wifiOptimize:true,networkOperator:'Telekom',networkAuto:true,networkType:'lte',only2g:false};
  const prefs=data=>({...defaults,...data.settings});
  const zones=['Europe/Budapest','Europe/London','Europe/Berlin','Europe/Paris','Europe/Madrid','America/New_York','America/Los_Angeles','Asia/Tokyo','UTC'];
  const zone=data=>prefs(data).autoZone?Intl.DateTimeFormat().resolvedOptions().timeZone:prefs(data).timeZone;
  function parts(data,now=Date.now()) {
    const p=prefs(data),stamp=now+(p.autoTime?0:Number(p.timeOffset)||0);
    return Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:zone(data),year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(stamp).filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)]));
  }
  function wallDate(data,now=Date.now()){const p=parts(data,now);return new Date(p.year,p.month-1,p.day,p.hour,p.minute,p.second);}
  const isoDate=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
  const isoTime=date=>`${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`;
  function setWall(data,date,time,now=Date.now()) {
    const wanted=Date.parse(`${date}T${time}:00Z`);if(!Number.isFinite(wanted)||new Date(wanted).toISOString().slice(0,16)!==`${date}T${time}`)return false;
    let candidate=wanted;
    for(let i=0;i<3;i++){const p=parts({...data,settings:{...data.settings,autoTime:true}},candidate);candidate+=wanted-Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);}
    const p=parts({...data,settings:{...data.settings,autoTime:true}},candidate);
    if(Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second)!==wanted)return false;
    data.settings.autoTime=false;data.settings.timeOffset=candidate-now;return true;
  }
  function dateText(data,locale,now=Date.now()) {
    const p=prefs(data),d=wallDate(data,now),day=String(d.getDate()).padStart(2,'0'),month=String(d.getMonth()+1).padStart(2,'0'),year=d.getFullYear();
    return p.dateFormat==='ymd'?`${year}/${month}/${day}`:p.dateFormat==='dmy'?`${day}/${month}/${year}`:p.dateFormat==='mdy'?`${month}/${day}/${year}`:d.toLocaleDateString(locale);
  }
  // DateTimeSettings.getTimeZoneText: the GMT offset in effect, then the zone's long name ("GMT+01:00, Central European Standard Time").
  function zoneText(data,locale,now=Date.now()) {
    const id=zone(data),name=part=>new Intl.DateTimeFormat(locale,{timeZone:id,timeZoneName:part}).formatToParts(now).find(x=>x.type==='timeZoneName')?.value||'';
    const offset=name('longOffset').replace(/^GMT$/,'GMT+00:00').replace('UTC','GMT');
    return `${offset}, ${name('long')}`;
  }
  const row=(title,subtitle='',action='sx-dialog',id='',disabled=false)=>`<button class="settings-row" data-action="${action}" data-id="${e(id)}" ${disabled?'disabled':''}><span class="row-copy">${e(title)}${subtitle?`<small>${e(subtitle)}</small>`:''}</span></button>`;
  // CheckBoxPreference up to 4.4, SwitchPreference in Lollipop.
  const check=(title,key,on,subtitle='',disabled=false)=>LP
    ?`<button class="settings-row lp-switch-row" data-action="toggle-setting" data-id="${key}" role="switch" aria-checked="${!!on}" ${disabled?'disabled':''}><span class="row-copy">${e(title)}${subtitle?`<small>${e(subtitle)}</small>`:''}</span><span class="lp-mswitch${on?' on':''}" aria-hidden="true"></span></button>`
    :`<button class="settings-row" data-action="toggle-setting" data-id="${key}" role="checkbox" aria-checked="${!!on}" ${disabled?'disabled':''}><span class="row-copy">${e(title)}${subtitle?`<small>${e(subtitle)}</small>`:''}</span><img class="holo-checkbox" src="assets/btn_check_${on?'on':'off'}_holo_dark.png" alt=""></button>`;
  const section=title=>`<h3 class="section-label">${e(title)}</h3>`;
  const sleepNames={always:'Always',charging:'Only when plugged in',never:'Never (increases data usage)'};
  const bandNames={auto:'Automatic','5':'5 GHz only','2.4':'2.4 GHz only'};
  const lockAfterNames={0:'Immediately',5000:'5 seconds',15000:'15 seconds',30000:'30 seconds',60000:'1 minute',120000:'2 minutes',300000:'5 minutes',600000:'10 minutes',1800000:'30 minutes'};
  const networkNames={lte:'LTE (recommended)','3g':'3G','2g':'2G'};
  const lockModes={none:'None',slide:'Slide',pattern:'Pattern',pin:'PIN',password:'Password'};
  function render(data,ui,t,locale) {
    const p=prefs(data),page=(title,body,right='')=>({title,body,right}),now=wallDate(data),secure=['pattern','pin','password'].includes(p.screenLock);
    // date_time_prefs.xml: the 24-hour summary samples were dropped in 4.1 and the date format list in 5.0.
    if(ui.sub==='date')return page(S('Date & time'),`${check(S('Automatic date & time'),'autoTime',p.autoTime,S('Use network-provided time'))}${check(S('Automatic time zone'),'autoZone',p.autoZone,S('Use network-provided time zone'))}${row(S('Set date'),dateText(data,locale),'sx-dialog','date',p.autoTime)}${row(S('Set time'),now.toLocaleTimeString(locale,{hour:'numeric',minute:'2-digit',hour12:!p.hour24}),'sx-dialog','time',p.autoTime)}${row(S('Select time zone'),zoneText(data,locale),'sx-dialog','zone',p.autoZone)}${check(S('Use 24-hour format'),'hour24',p.hour24,ICS?S(p.hour24?'13:00':'1:00 pm'):'')}${LP?'':row(S('Choose date format'),dateText(data,locale),'sx-dialog','date-format')}`);
    // SecuritySettings: the lock screen XML for the current quality (chooser / lockscreen / pattern / pin / password), the
    // encryption category, then security_settings_misc.xml. Verify apps came with 4.2; Notification access (4.3) is removed
    // while no listener is installed; Enable widgets is KitKat's (off by default, LockPatternUtils.getWidgetsEnabled).
    if(ui.sub==='security')return page(S('Security'),`${section(S('Screen security'))}${row(S('Screen lock'),S(lockModes[p.screenLock]||'Slide'),'sx-dialog','screen-lock')}${p.screenLock==='pattern'?check(S('Make pattern visible'),'patternVisible',p.patternVisible!==false):''}${secure?`${row(S('Automatically lock'),S('%1$s after sleep').replace('%1$s',S(lockAfterNames[p.lockAfter]||'5 seconds')),'sx-dialog','lock-after')}${check(S('Power button instantly locks'),'powerInstantLock',p.powerInstantLock)}`:''}${ICS&&['pattern','pin'].includes(p.screenLock)?check(S('Vibrate on touch'),'lockTactile',p.lockTactile):''}${KK?check(S('Enable widgets'),'kgWidgets',p.kgWidgets):''}${row(S('Owner info'),p.showOwner?p.ownerInfo:'','sx-dialog','owner')}${section(S('Encryption'))}${row(S('Encrypt phone'),S('Require a numeric PIN or password to decrypt your phone each time you power it on'),'noop','',true)}${section(S('SIM card lock'))}${row(S('Set up SIM card lock'),'','noop','',true)}${section(S('Passwords'))}${check(S('Make passwords visible'),'visiblePasswords',p.visiblePasswords)}${section(S('Device administration'))}${row(S('Device administrators'),S('View or deactivate device administrators'),'settings-sub','device-admin')}${check(S('Unknown sources'),'unknownSources',p.unknownSources,S('Allow installation of apps from unknown sources'))}${ICS?'':check(S('Verify apps'),'verifyApps',p.verifyApps!==false,S('Disallow or warn before installation of apps that may cause harm'))}${section(S('Credential storage'))}${ICS?'':row(S('Storage type'),S('Hardware-backed'),'noop','',true)}${row(S('Trusted credentials'),S('Display trusted CA certificates'),'noop','',true)}${row(S('Install from storage'),S('Install certificates from storage'),'noop','',true)}${row(S('Clear credentials'),S('Remove all certificates'),'noop','',true)}`);
    if(ui.sub==='device-admin')return page(S('Device administrators'),`<p class="empty-note">${e(S('No available device administrators'))}</p>`);
    // tether_prefs.xml: 4.0's Help row left with 4.1 (it moved to the menu).
    if(ui.sub==='tethering')return page(S('Tethering & portable hotspot'),`${check(S('USB tethering'),'usbTether',false,S('USB not connected'),true)}${check(S('Portable Wi-Fi hotspot'),'portableHotspot',p.portableHotspot,p.portableHotspot?p.hotspotName:'')}${row(S('Set up Wi-Fi hotspot'),`${p.hotspotName} ${p.hotspotSecurity==='Open'?'':'WPA2 PSK'}`.trim(),'sx-dialog','hotspot')}${check(S('Bluetooth tethering'),'bluetoothTether',p.bluetoothTether)}${ICS?row(S('Help'),'','settings-sub','tether-help'):''}`);
    if(ui.sub==='tether-help')return page(S('Tethering & portable hotspot'),'<div class="detail-pad"><p>Portable Wi-Fi hotspot shares the phone’s data connection with nearby devices.</p><p>This simulator stores demo settings only. It does not share your connection.</p></div>');
    // wifi_advanced_settings.xml of this image: 4.0 has no scanning, certificates or optimization; 5.1 reorders it and moves
    // Wi-Fi Direct and WPS here from the menu (its Wi-Fi assistant row only shows with a network scorer app installed).
    if(ui.sub==='wifi-advanced'){
      const notify=check(S('Network notification'),'wifiNotify',p.wifiNotify,S('Notify me when an open network is available'),!p.wifi),sleep=row(S('Keep Wi-Fi on during sleep'),S(sleepNames[p.wifiSleep]||'Always'),'sx-dialog','wifi-sleep');
      const scan=check(S('Scanning always available'),'wifiScanAlways',p.wifiScanAlways,S("Let Google's location service and other apps scan for networks, even when Wi-Fi is off"));
      const band=row(S('Wi-Fi frequency band'),S(bandNames[p.wifiBand]||'Automatic'),'sx-dialog','wifi-band'),certs=row(S('Install certificates'),'','dev-info','Install certificates');
      const addresses=`${row(S('MAC address'),'02:00:00:40:04:01','noop')}${row(S('IP address'),p.wifi&&p.wifiNetwork?'192.0.2.4':S('Unavailable'),'noop')}`;
      if(ICS)return page(S('Advanced Wi-Fi'),`${notify}${sleep}${check(S('Avoid poor connections'),'wifiPoorAvoid',p.wifiPoorAvoid,S("Don't use a Wi-Fi network unless it has a good Internet connection"))}${band}${addresses}`);
      if(LP)return page(S('Advanced Wi-Fi'),`${notify}${scan}${sleep}${band}${certs}${row(S('Wi-Fi Direct'),'','noop')}${row(S('WPS Push Button'),'','noop')}${row(S('WPS Pin Entry'),'','noop')}${addresses}`);
      return page(S('Advanced Wi-Fi'),`${notify}${sleep}${scan}${check(S('Avoid poor connections'),'wifiPoorAvoid',p.wifiPoorAvoid,S("Don't use a Wi-Fi network unless it has a good Internet connection"))}${band}${certs}${check(S('Wi-Fi optimization'),'wifiOptimize',p.wifiOptimize,S('Minimize battery usage when Wi-Fi is on'))}${addresses}`);
    }
    // VpnSettings: 4.0 lists "Add VPN network" (vpn_settings2.xml); from 4.1 it is the action bar's add item.
    if(ui.sub==='vpn')return page(S('VPN'),`${ICS?row(S('Add VPN profile'),'','sx-vpn-new'):''}${(data.vpnProfiles||[]).map(profile=>row(profile.name,ui.vpnConnected===profile.id?t('Connected'):profile.type,'sx-vpn-open',profile.id)).join('')}`,ICS?'':`<button class="sx-add" data-action="sx-vpn-new" aria-label="${e(S('Add VPN profile'))}">+</button>`);
    // MobileNetworkSettings on a GSM phone: up to 4.3 Data enabled, roaming and GsmUmtsOptions (APNs, 2G only, operators);
    // 4.4 shows the enabled-networks list instead of 2G only; 5.0 moved Data enabled to Data usage.
    if(ui.sub==='mobile-networks'){
      const type=row(S('Preferred network type'),S(networkNames[p.networkType]||'LTE (recommended)'),'sx-dialog','network-type');
      return page(S('Mobile network settings'),`${LP?'':check(S('Data enabled'),'dataEnabled',p.dataEnabled,S('Enable data access over Mobile network'))}${check(S('Data roaming'),'dataRoaming',p.dataRoaming,S('Connect to data services when roaming'))}${KK||LP?type:''}${row(S('Access Point Names'),'','settings-sub','apn')}${KK||LP?'':check(S('Use only 2G networks'),'only2g',p.only2g,S('Saves battery'))}${row(S('Network operators'),S('Choose a network operator'),'settings-sub','operators')}`);
    }
    if(ui.sub==='operators')return page(S('Available networks'),`${row(S('Search networks'),S('Search for all available networks'),'sx-network-scan')}${row(S('Choose automatically'),p.networkAuto?t('Selected'):S('Automatically choose preferred network'),'sx-network-auto')}${ui.networkScanned?['Telekom','Demo Mobile'].map(name=>row(name,p.networkOperator===name?t('Registered on network'):'','sx-network-select',name)).join(''):''}`);
    if(ui.sub==='apn')return page(S('APNs'),`${(data.apnProfiles||[{id:'default',name:'Telekom',apn:'internet.telekom',mcc:'216',mnc:'30'}]).map(profile=>`<div class="sx-apn-row">${row(profile.name,profile.apn,'sx-apn-open',profile.id)}<button data-action="sx-apn-select" data-id="${e(profile.id)}" role="radio" aria-label="${e(profile.name)}" aria-checked="${(p.apnId||'default')===profile.id}"><i></i></button></div>`).join('')}`,`<button class="sx-add" data-action="sx-apn-new" aria-label="${e(S('New APN'))}">+</button>`);
    return null;
  }
  function overlay(data,ui,t) {
    const p=prefs(data),field=ui.systemField;
    const input=(title,name,value='',type='text',required=false,max=100)=>`<label><span>${e(t(title))}</span><input name="${name}" type="${type}" value="${e(ui.systemValues?.[name]??value)}" ${required?'required':''} maxlength="${max}" autocomplete="off"></label>`;
    const choice=(title,name,options,value)=>`<label><span>${e(t(title))}</span><select name="${name}">${options.map(([id,label])=>`<option value="${id}" ${id===value?'selected':''}>${e(t(label))}</option>`).join('')}</select></label>`;
    const shell=(title,body,form='sx-save',extra='',submitLabel='Save')=>`<div class="settings-dialog-scrim" data-action="close-overlay"></div><form class="settings-dialog sx-dialog" role="dialog" aria-label="${e(t(title))}" data-form="${form}"><h3>${e(t(title))}</h3><div class="sx-fields">${body}</div>${ui.systemError?`<p class="sx-error" role="alert">${e(t(ui.systemError))}</p>`:''}<div class="settings-dialog-actions">${extra}<button type="button" data-action="close-overlay">Cancel</button><button type="submit">${e(t(submitLabel))}</button></div></form>`;
    const radios=(title,options,value)=>shell(title,options.map(([id,label,disabled])=>`<label class="sx-radio"><span>${e(t(label))}</span><input type="radio" name="choice" value="${id}" ${id===value?'checked':''} ${disabled?'disabled':''}></label>`).join(''));
    if(field==='profile-delete')return shell('Delete profile?',`<p>${e(ui.systemDraft?.name||'')}</p>`,'sx-profile-delete','','Delete');
    if(field==='screen-lock')return radios('Choose screen lock',[['none','None'],['slide','Slide'],['face','Face Unlock',true],['pattern','Pattern',true],['pin','PIN',true],['password','Password',true]],p.screenLock);
    if(field==='owner')return shell('Owner info',`<label class="sx-radio"><span>${e(t('Show owner info on lock screen'))}</span><input type="checkbox" name="show" ${p.showOwner?'checked':''}></label>${input('Owner info','owner',p.ownerInfo,'text',false,100)}`);
    if(field==='date'||field==='time'){const d=wallDate(data);return shell(field==='date'?'Set date':'Set time',input(field==='date'?'Date':'Time',field,field==='date'?isoDate(d):isoTime(d),field,true));}
    if(field==='zone')return shell(S('Select time zone'),choice('Time zone','zone',[...new Set([...zones,p.timeZone])].map(zone=>[zone,zone]),p.timeZone));
    if(field==='date-format')return radios(S('Choose date format'),[['locale','Regional (default)'],['mdy','MM/DD/YYYY'],['dmy','DD/MM/YYYY'],['ymd','YYYY/MM/DD']],p.dateFormat);
    if(field==='wifi-sleep')return radios(S('Keep Wi-Fi on during sleep'),Object.entries(sleepNames).map(([id,label])=>[id,S(label)]),p.wifiSleep);
    if(field==='wifi-band')return radios(S('Wi-Fi frequency band'),Object.entries(bandNames).map(([id,label])=>[id,S(label)]),p.wifiBand);
    if(field==='lock-after')return radios(S('Automatically lock'),Object.entries(lockAfterNames).map(([id,label])=>[id,S(label)]),String(p.lockAfter));
    if(field==='network-type')return radios(S('Preferred network type'),Object.entries(networkNames).map(([id,label])=>[id,S(label)]),p.networkType);
    if(field==='hotspot')return shell(S('Set up Wi-Fi hotspot'),`${input('Network SSID','ssid',p.hotspotName,'text',true,32)}${choice('Security','security',[['Open','None'],['WPA2','WPA2 PSK']],p.hotspotSecurity)}${input('Password','password','android404','password',false,63)}<p class="sx-note">${e(t('Demo settings only; no network connection is created.'))}</p>`);
    if(field==='vpn-edit'){const profile=ui.systemDraft||{};return shell('Edit VPN network',`${input('Name','name',profile.name,'text',true,50)}${choice('Type','type',[['PPTP','PPTP'],['L2TP/IPSec PSK','L2TP/IPSec PSK']],profile.type||'PPTP')}${input('Server address','server',profile.server||'vpn.example.test','text',true)}<p class="sx-note">${e(t('Demo settings only; no network connection is created.'))}</p>`,'sx-save',profile.id?'<button type="button" data-action="sx-profile-delete" data-id="vpn">Delete</button>':'');}
    if(field==='vpn-connect'){const profile=(data.vpnProfiles||[]).find(profile=>profile.id===ui.systemId);return shell(profile?.name||'VPN',`${input('Username','username','demo')}${input('Password','password','','password')}<p>${e(t(ui.vpnConnected===ui.systemId?'Connected':'Disconnected'))}</p>`,'sx-vpn-connect','<button type="button" data-action="sx-vpn-edit">Edit</button>',ui.vpnConnected===ui.systemId?'Disconnect':'Connect');}
    if(field==='apn-edit'){const profile=ui.systemDraft||{};return shell('Edit access point',`${input('Name','name',profile.name,'text',true,50)}${input('APN','apn',profile.apn||'internet.example.test','text',true)}${input('MCC','mcc',profile.mcc||'216','text',true,3)}${input('MNC','mnc',profile.mnc||'30','text',true,3)}`,'sx-save',profile.id?'<button type="button" data-action="sx-profile-delete" data-id="apn">Delete</button>':'');}
    return '';
  }
  function submit(data,ui,values,now=Date.now()) {
    const p=data.settings,field=ui.systemField,value=name=>String(values.get(name)||'').trim();
    if(field==='date'||field==='time'){const d=wallDate(data,now);if(!setWall(data,field==='date'?value('date'):isoDate(d),field==='time'?value('time'):isoTime(d),now))return 'Invalid date or time';}
    if(field==='zone'&&zones.includes(value('zone')))p.timeZone=value('zone');
    if(field==='date-format'&&['locale','mdy','dmy','ymd'].includes(value('choice')))p.dateFormat=value('choice');
    if(field==='wifi-sleep'&&sleepNames[value('choice')])p.wifiSleep=value('choice');
    if(field==='wifi-band'&&bandNames[value('choice')])p.wifiBand=value('choice');
    if(field==='lock-after'&&lockAfterNames[value('choice')])p.lockAfter=value('choice');
    if(field==='network-type'&&networkNames[value('choice')])p.networkType=value('choice');
    if(field==='screen-lock'&&['none','slide'].includes(value('choice')))p.screenLock=value('choice');
    if(field==='owner'){p.ownerInfo=value('owner').slice(0,100);p.showOwner=values.has('show');}
    if(field==='hotspot'){
      if(!value('ssid'))return 'Enter a network name';
      if(value('security')!=='Open'&&value('password').length<8)return 'Password must have at least 8 characters';
      p.hotspotName=value('ssid').slice(0,32);p.hotspotSecurity=value('security')==='Open'?'Open':'WPA2';
    }
    if(field==='vpn-edit'){
      if(!value('name')||!value('server'))return 'Complete all required fields';
      data.vpnProfiles||=[];const profile={id:ui.systemDraft?.id||`vpn-${now}`,name:value('name').slice(0,50),type:value('type')==='L2TP/IPSec PSK'?'L2TP/IPSec PSK':'PPTP',server:value('server').slice(0,100)};
      const index=data.vpnProfiles.findIndex(item=>item.id===profile.id);if(index<0)data.vpnProfiles.push(profile);else data.vpnProfiles[index]=profile;
    }
    if(field==='apn-edit'){
      if(!value('name')||!value('apn')||!/^\d{3}$/.test(value('mcc'))||!/^\d{2,3}$/.test(value('mnc')))return 'Complete all required fields';
      data.apnProfiles||=[{id:'default',name:'Telekom',apn:'internet.telekom',mcc:'216',mnc:'30'}];const profile={id:ui.systemDraft?.id||`apn-${now}`,name:value('name').slice(0,50),apn:value('apn').slice(0,100),mcc:value('mcc'),mnc:value('mnc')};
      const index=data.apnProfiles.findIndex(item=>item.id===profile.id);if(index<0)data.apnProfiles.push(profile);else data.apnProfiles[index]=profile;
    }
    return '';
  }
  function removeProfile(data,ui) {
    const key=ui.systemDeleteKind==='vpn'?'vpnProfiles':'apnProfiles',id=ui.systemDraft?.id;
    data[key]=(data[key]||(key==='apnProfiles'?[{id:'default'}]:[])).filter(profile=>profile.id!==id);
    if(key==='vpnProfiles'&&ui.vpnConnected===id)ui.vpnConnected=null;
    if(key==='apnProfiles'&&(data.settings.apnId||'default')===id)data.settings.apnId=data.apnProfiles[0]?.id||'';
  }
  window.ICSSystemSettings={defaults,prefs,zones,zone,parts,wallDate,isoDate,isoTime,setWall,dateText,zoneText,render,overlay,submit,removeProfile};
})();
