/* Generated by docs/stock-strings.py from docs/stock-strings.json and the maguro factory image. Do not edit. */
window.StockStrings = {
 "navigation": {
  "Navigation": [
   "Navigáció",
   "Navigation",
   "Navigation",
   "Navigation"
  ],
  "Map": [
   "Térkép",
   "Karte",
   "Plan",
   "Mapa"
  ],
  "Speak destination": [
   "Cél kimondása",
   "Ziel einsprechen",
   "Énoncer destination",
   "Di el destino"
  ],
  "Type destination": [
   "Cél begépelése",
   "Ziel eintippen",
   "Saisir destination",
   "Escribe el destino"
  ],
  "Contacts": [
   "Kapcsolatok",
   "Kontakte",
   "Contacts",
   "Contactos"
  ],
  "Starred places": [
   "Csillaggal megjelölt helyek",
   "Markierte Orte",
   "Adresses enregistrées",
   "Sitios destacados"
  ],
  "Places": [
   "Helyek",
   "Places",
   "Adresses",
   "Sitios"
  ]
 },
 "studio": {
  "Create new project": [
   "Új projekt létrehozása",
   "Neues Projekt",
   "Créer un projet",
   "Crear proyecto nuevo",
   "Create New Project"
  ]
 },
 "gplus": {
  "Messenger": [
   "Messenger",
   "Messenger",
   "Chat +",
   "Messenger"
  ],
  "New conversation": [
   "Új beszélgetés",
   "Neue Unterhaltung",
   "Nouvelle conversation",
   "Nueva conversación"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Configuración"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer un commentaire",
   "Enviar comentarios"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ]
 },
 "earth": {
  "Earth": [
   "Earth",
   "Earth",
   "Earth",
   "Earth"
  ],
  "Search": [
   "Search",
   "Suche",
   "Recherche Google",
   "Buscar"
  ],
  "Layers": [
   "Layers",
   "Ebenen",
   "Données géographiques",
   "Capas"
  ],
  "My Location": [
   "My Location",
   "Mein Standort",
   "Ma position",
   "Mi ubicación"
  ],
  "Settings": [
   "Settings",
   "Einstellungen",
   "Paramètres",
   "Configuración"
  ],
  "Help": [
   "Help",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Terms Of Service": [
   "Terms Of Service",
   "Nutzungsbedingungen",
   "Conditions d'utilisation",
   "Condiciones del servicio"
  ]
 }
};
