/* Generated by docs/stock-strings.py from docs/stock-strings.json and the maguro factory image. Do not edit. */
window.StockStrings = {
 "navigation": {
  "Navigation": [
   "Navigáció",
   "Navigation",
   "Navigation",
   "Navigation"
  ],
  "Map": [
   "Térkép",
   "Karte",
   "Plan",
   "Mapa"
  ],
  "Speak destination": [
   "Cél kimondása",
   "Ziel einsprechen",
   "Énoncer destination",
   "Di el destino"
  ],
  "Type destination": [
   "Cél begépelése",
   "Ziel eintippen",
   "Saisir destination",
   "Escribe el destino"
  ],
  "Contacts": [
   "Kapcsolatok",
   "Kontakte",
   "Contacts",
   "Contactos"
  ],
  "Starred places": [
   "Csillaggal megjelölt helyek",
   "Markierte Orte",
   "Adresses enregistrées",
   "Sitios destacados"
  ],
  "Places": [
   "Helyek",
   "Places",
   "Adresses",
   "Sitios"
  ]
 },
 "studio": {
  "Create new project": [
   "Új projekt létrehozása",
   "Neues Projekt",
   "Créer un projet",
   "Crear proyecto nuevo",
   "Create New Project"
  ]
 }
};
