/* Generated by docs/stock-strings.py from docs/stock-strings.json and the maguro factory image. Do not edit. */
window.StockStrings = {
 "navigation": {
  "Navigation": [
   "Navigáció",
   "Navigation",
   "Navigation",
   "Navigation"
  ],
  "Map": [
   "Térkép",
   "Karte",
   "Plan",
   "Mapa"
  ],
  "Speak destination": [
   "Cél kimondása",
   "Ziel einsprechen",
   "Énoncer destination",
   "Di el destino"
  ],
  "Type destination": [
   "Cél begépelése",
   "Ziel eintippen",
   "Saisir destination",
   "Escribe el destino"
  ],
  "Contacts": [
   "Kapcsolatok",
   "Kontakte",
   "Contacts",
   "Contactos"
  ],
  "Starred places": [
   "Csillaggal megjelölt helyek",
   "Markierte Orte",
   "Adresses enregistrées",
   "Sitios destacados"
  ],
  "Places": [
   "Helyek",
   "Places",
   "Adresses",
   "Sitios"
  ]
 },
 "studio": {
  "Create new project": [
   "Új projekt létrehozása",
   "Neues Projekt",
   "Créer un projet",
   "Crear proyecto nuevo",
   "Create New Project"
  ]
 },
 "gplus": {
  "Messenger": [
   "Messenger",
   "Messenger",
   "Chat +",
   "Messenger"
  ],
  "New conversation": [
   "Új beszélgetés",
   "Neue Unterhaltung",
   "Nouvelle conversation",
   "Nueva conversación"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Configuración"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer un commentaire",
   "Enviar comentarios"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ]
 },
 "earth": {
  "Earth": [
   "Earth",
   "Earth",
   "Earth",
   "Earth"
  ],
  "Search": [
   "Search",
   "Suche",
   "Recherche Google",
   "Buscar"
  ],
  "Layers": [
   "Layers",
   "Ebenen",
   "Données géographiques",
   "Capas"
  ],
  "My Location": [
   "My Location",
   "Mein Standort",
   "Ma position",
   "Mi ubicación"
  ],
  "Settings": [
   "Settings",
   "Einstellungen",
   "Paramètres",
   "Configuración"
  ],
  "Help": [
   "Help",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Terms Of Service": [
   "Terms Of Service",
   "Nutzungsbedingungen",
   "Conditions d'utilisation",
   "Condiciones del servicio"
  ]
 },
 "maps": {
  "Maps": [
   "Térkép",
   "Maps",
   "Maps",
   "Maps"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Search Maps": [
   "Keresés",
   "Maps-Suche",
   "Rechercher",
   "Buscar en Maps"
  ],
  "Directions": [
   "Útvonalterv",
   "Route",
   "Itinéraire",
   "Indicaciones"
  ],
  "Local": [
   "Helyek",
   "Places",
   "Google Adresses",
   "Places",
   "Places"
  ],
  "Layers": [
   "Rétegek",
   "Ebenen",
   "Afficher...",
   "Capas"
  ],
  "Clear map": [
   "Találatok törlése",
   "Karte leeren",
   "Effacer les résultats",
   "Borrar resultados"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Configuración"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Map": [
   "Térkép",
   "Karte",
   "Plan",
   "Mapa"
  ],
  "Find restaurants, bars & more": [
   "Éttermek, bárok és egyebek keresése",
   "Restaurants, Bars & mehr finden",
   "Trouvez des restaurants, des bars et d'autres lieux",
   "Buscar restaurantes, bares y otros"
  ],
  "GPS navigation": [
   "GPS navigáció",
   "GPS-Navigation",
   "Navigation GPS",
   "Navegación GPS"
  ],
  "Traffic": [
   "Forgalom",
   "Verkehrslage",
   "Trafic",
   "Tráfico"
  ],
  "Satellite": [
   "Műhold",
   "Satellit",
   "Satellite",
   "Satélite"
  ],
  "Terrain": [
   "Terep",
   "Gelände",
   "Relief",
   "Relieve"
  ],
  "Bicycling": [
   "Kerékpárral",
   "Mit dem Fahrrad",
   "À vélo",
   "En bici"
  ],
  "Get directions": [
   "Útvonaltervezés",
   "Route berechnen",
   "Itinéraire",
   "Cómo llegar"
  ],
  "Navigation": [
   "Navigáció",
   "Navigation",
   "Navigation",
   "Navigation"
  ],
  "Route options": [
   "Útvonalopciók",
   "Routenoptionen",
   "Options itinéraire",
   "Opciones ruta"
  ],
  "Avoiding highways": [
   "Autópályák kikerülése",
   "Ohne Autobahn",
   "Itinéraire sans autoroutes",
   "Sin autopistas"
  ],
  "Avoiding tolls": [
   "Útdíjak kikerülése",
   "Ohne Mautpflicht",
   "Itinéraire sans péages",
   "Sin peajes"
  ],
  "Head %1$s on %2$s": [
   "Menjen %1$si irányba a(z) %2$s úton",
   "Richtung %1$s auf %2$s fahren",
   "Suivre la direction %1$s sur %2$s",
   "Dirección %1$s por %2$s"
  ],
  "north": [
   "észak",
   "Norden",
   "nord",
   "norte"
  ],
  "south": [
   "dél",
   "Süden",
   "sud",
   "sur"
  ],
  "Turn right onto %1$s": [
   "Forduljon jobbra erre: %1$s",
   "Rechts auf %1$s abbiegen",
   "Prendre %1$s complètement à droite",
   "Gira a la derecha hacia %1$s."
  ],
  "Turn left onto %1$s": [
   "Forduljon balra erre: %1$s",
   "Links auf %1$s abbiegen",
   "Prendre à gauche sur %1$s",
   "Gira a la izquierda hacia %1$s."
  ],
  "Continue onto %1$s": [
   "Tovább erre: %1$s",
   "Weiter auf %1$s",
   "Continuer sur %1$s",
   "Continúa por %1$s."
  ],
  "Your destination is on the right.": [
   "Az úti cél a jobb oldalon található.",
   "Das Ziel befindet sich auf der rechten Seite.",
   "Votre destination se trouve sur la droite.",
   "Tu destino está a la derecha."
  ],
  "You have arrived.": [
   "Megérkezett.",
   "Sie haben das Ziel erreicht.",
   "Vous êtes arrivé.",
   "Has llegado."
  ],
  "%1$s min": [
   "%1$s perc",
   "%1$s Min.",
   "%1$s mn",
   "%1$s min"
  ],
  "%1$s hr  %2$s min": [
   "%1$s óra %2$s perc",
   "%1$s h %2$s min",
   "%1$s h %2$s mn",
   "%1$s h %2$s min"
  ],
  "{0} km": [
   "{0} km",
   "{0} km",
   "{0} km",
   "{0} km"
  ],
  "{0} m": [
   "{0} m",
   "{0} m",
   "{0} m",
   "{0} m"
  ],
  "{0} mi": [
   "{0} mf",
   "{0} mi",
   "{0} mi",
   "{0} mi"
  ],
  "{0} ft": [
   "{0} láb",
   "{0} ft",
   "{0} pieds",
   "{0} pie(s)"
  ],
  "imperial": [
   "metric",
   "metric",
   "metric",
   "metric"
  ],
  "Exit navigation?": [
   "Kilép a navigációból?",
   "Navigation beenden?",
   "Quitter le mode Navigation ?",
   "¿Salir de Navigation?"
  ],
  "Exit navigation": [
   "Kilépés a navigációból",
   "Navigation beenden",
   "Quitter le mode Navigation",
   "Salir de la navegación"
  ],
  "OK": [
   "OK",
   "OK",
   "OK",
   "Aceptar"
  ],
  "Cancel": [
   "Mégse",
   "Abbrechen",
   "Annuler",
   "Cancelar"
  ],
  "Avoid tolls": [
   "Útdíjak kikerülése",
   "Mautpflichtige Straßen meiden",
   "Éviter les péages",
   "Evitar peajes"
  ],
  "east": [
   "kelet",
   "Osten",
   "est",
   "este"
  ],
  "west": [
   "nyugat",
   "Westen",
   "ouest",
   "oeste"
  ],
  "Latitude": [
   "Koordináták",
   "Latitude",
   "Latitude",
   "Latitude"
  ],
  "Find family & friends": [
   "Családtagok és ismerősök keresése",
   "Familie & Freunde finden",
   "Trouvez les membres de votre famille et vos amis",
   "Buscar familiares y amigos"
  ]
 },
 "news": {
  "News & Weather": [
   "Hírek és időjárás",
   "News & Wetter",
   "Actualités et météo",
   "Noticias y tiempo"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Weather": [
   "Időjárás",
   "Google Wetter",
   "Météo",
   "Tiempo"
  ],
  "Humidity: %s%%": [
   "Páratartalom: %s%%",
   "Luftfeuchtigkeit: %s %%",
   "Humidité : %s%%",
   "Humedad: %s%%"
  ],
  "Wind: %1$s %2$s": [
   "Szélerősség: %1$s %2$s",
   "Wind: %1$s %2$s",
   "Vent : %1$s %2$s",
   "Viento: %1$s %2$s"
  ],
  "km/h": [
   "km/h",
   "km/h",
   "km/h",
   "km/h"
  ],
  "Mon": [
   "H",
   "M",
   "Lun",
   "L",
   "M"
  ],
  "Tue": [
   "K",
   "D",
   "Mar",
   "M",
   "T"
  ],
  "Wed": [
   "Sz",
   "M",
   "Mer",
   "X",
   "W"
  ],
  "Thu": [
   "Cs",
   "D",
   "Jeu",
   "J",
   "T"
  ],
  "Fri": [
   "P",
   "F",
   "Ven",
   "J",
   "F"
  ],
  "Sat": [
   "Sz",
   "S",
   "Sam",
   "S",
   "S"
  ],
  "Sun": [
   "V",
   "S",
   "Dim",
   "D",
   "S"
  ],
  "Share story": [
   "Hír megosztása",
   "Beitrag teilen",
   "Partager l'histoire",
   "Compartir noticia"
  ],
  "News isn't available right now.": [
   "Sajnáljuk, a hírek jelenleg nem érhetők el.",
   "Zurzeit sind leider keine Nachrichten verfügbar.",
   "Désolé, les actualités sont indisponibles actuellement.",
   "No hay datos disponibles en este momento.",
   "Sorry, news currently unavailable."
  ],
  "Updating news topics…": [
   "A témakörök frissítése...",
   "Nachrichtenthemen werden aktualisiert...",
   "Mise à jour des sujets d'actualités en cours...",
   "Actualizando temas de noticias...",
   "Updating news topics..."
  ],
  "Weather settings": [
   "Időjárás -- beállítások",
   "Google Wetter-Einstellungen",
   "Paramètres de la météo",
   "Ajustes de Tiempo"
  ],
  "Set location, units": [
   "Hely és mértékegység megadása",
   "Standort und Maßeinheiten festlegen",
   "Définir le lieu et le système de mesure",
   "Establecer ubicación, unidades"
  ],
  "News settings": [
   "Hírek -- beállítások",
   "Google News-Einstellungen",
   "Paramètres de l'actualité",
   "Ajustes de Noticias"
  ],
  "Choose topics, manage downloads": [
   "Témák kiválasztása, letöltések kezelése",
   "Themen auswählen, Downloads verwalten",
   "Choisir des sujets, gérer les téléchargements",
   "Seleccionar temas, administrar descargas",
   "Pick topics, manage downloads"
  ],
  "Refresh settings": [
   "Frissítési beállítások",
   "Aktualisierungs-Einstellungen",
   "Paramètres d'actualisation",
   "Ajustes de actualización"
  ],
  "Set up auto-refresh, refresh interval": [
   "Az automatikus frissítés és a frissítés gyakoriságának beállítása",
   "Automatische Aktualisierung, Aktualisierungsintervall festlegen",
   "Définir l'actualisation automatique, la fréquence d'actualisation",
   "Establecer actualización automática, intervalo de actualización"
  ],
  "App version": [
   "Alkalmazás verziószáma",
   "App-Version",
   "Version de l'application",
   "Versión de la aplicación",
   "Application version"
  ],
  "Use my location": [
   "Saját pozíció használata",
   "Standort verwenden",
   "Utiliser ma position",
   "Utilizar Mi ubicación"
  ],
  "Automatically determine location": [
   "Hely automatikus megállapítása",
   "Standort automatisch bestimmen",
   "Déterminer automatiquement ma position",
   "Identificar ubicación automáticamente"
  ],
  "Set location": [
   "Hely beállítása",
   "Standort manuell festlegen",
   "Définir un lieu",
   "Establecer ubicación"
  ],
  "Specify your location": [
   "Adja meg tartózkodási helyét",
   "Meinen Standort angeben",
   "Indiquer un lieu",
   "Especifica tu ubicación"
  ],
  "Use metric": [
   "Metrikus mértékegység használata",
   "Metrische Einheiten",
   "Utiliser le système métrique",
   "Usar sistema métrico"
  ],
  "Toggle metric/imperial units": [
   "Metrikus/angolszász mértékegység váltása",
   "Zwischen metrischen und angloamerikanischen Einheiten umschalten",
   "Système métrique/Système impérial",
   "Alternar unidades métricas/imperiales"
  ],
  "Choose news topics": [
   "Témakörök kiválasztása",
   "Themen auswählen",
   "Sélectionner des sujets",
   "Seleccionar temas de noticias",
   "Select news topics"
  ],
  "Manage news topics": [
   "Témakörök kezelése",
   "Nachrichtenthemen verwalten",
   "Gérer les sujets d'actualités",
   "Administrar temas de noticias"
  ],
  "Prefetch articles": [
   "Cikkek előzetes lekérése",
   "Artikel vorabrufen",
   "Prélire les articles",
   "Recopilar artículos previamente"
  ],
  "Prefetch articles for faster access": [
   "A cikkek előzetes lekérése a gyorsabb elérés érdekében",
   "Artikel für schnelleren Zugriff vorabrufen",
   "Prélire les articles pour un accès plus rapide",
   "Recopilar artículos previamente para acceder más rápido"
  ],
  "Prefetch images": [
   "Képek előzetes lekérése",
   "Bilder vorabrufen",
   "Prélire les images",
   "Recopilar imágenes previamente"
  ],
  "Prefetch images for faster access": [
   "A képek előzetes lekérése a gyorsabb elérés érdekében",
   "Bilder für schnelleren Zugriff vorabrufen",
   "Prélire les images pour un accès plus rapide",
   "Recopilar imágenes previamente para acceder más rápido"
  ],
  "News terms of service": [
   "Hírek általános szerződési feltételek",
   "Nutzungsbedingungen",
   "Conditions d'utilisation",
   "Condiciones del servicio de Noticias"
  ],
  "Mobile privacy policy": [
   "Mobil adatvédelmi irányelvek",
   "Google Mobile-Datenschutzbestimmungen",
   "Règles de confidentialité Google Mobile",
   "Política de privacidad para móviles"
  ],
  "Custom topics": [
   "Egyéni témák",
   "Benutzerdefinierte Themen",
   "Sujets personnalisés",
   "Personalizar temas",
   "Custom Topics"
  ],
  "Custom topic": [
   "Egyéni téma",
   "Benutzerdefiniert",
   "Sujet personnalisé",
   "Personalizar tema"
  ],
  "Add a custom news topic here": [
   "Itt adhat hozzá egyéni témaköröket",
   "Ein benutzerdefiniertes Nachrichtenthema hinzufügen",
   "Ajouter un sujet d'actualités personnalisé ici",
   "Añade aquí un tema de noticias personalizado"
  ],
  "News topics": [
   "Témakörök",
   "Nachrichtenthemen",
   "Sujets d'actualités",
   "Temas de noticias",
   "News Topics"
  ],
  "Auto-refresh": [
   "Automatikus frissítés",
   "Automat. Aktualisieren",
   "Automatique",
   "Actualizar automáticamente"
  ],
  "Auto-refresh summary": [
   "Hírek és időjárás automatikus frissítése",
   "News und Wetter automatisch aktualisieren",
   "Actualiser automatiquement les actualités et la météo",
   "Actualizar automáticamente la información sobre noticias y tiempo",
   "Automatically refresh news and weather"
  ],
  "Refresh interval": [
   "Frissítés gyakorisága",
   "Aktualisierungsintervall",
   "Fréquence d'actualisation",
   "Intervalo de actualización"
  ],
  "Refresh status": [
   "Frissítés állapota",
   "Status aktualisieren",
   "État de l'actualisation",
   "Actualizar estado"
  ],
  "Last refresh %s": [
   "Utolsó frissítés: %s",
   "Letzte Aktualisierung: %s",
   "Dernière actualisation %s",
   "Última actualización: %s"
  ],
  "Last refresh %1$s \nNext refresh %2$s": [
   "Utolsó frissítés: %1$s \nKövetkező frissítés: %2$s",
   "Letzte Aktualisierung: %1$s \nNächste Aktualisierung: %2$s",
   "Dernière actualisation le %1$s \nNouvelle actualisation le %2$s",
   "Última actualización %1$s \nPróxima actualización %2$s"
  ],
  "Type a city or postal code:": [
   "Adjon meg egy irányítószámot:",
   "Geben Sie eine Stadt oder eine Postleitzahl ein:",
   "Saisissez une ville ou un code postal :",
   "Introduce una ciudad o un código postal:",
   "Enter a city or postal code:"
  ],
  "Type a custom topic:": [
   "Adjon meg egyéni témát:",
   "Geben Sie ein benutzerdefiniertes Thema ein:",
   "Entrez un sujet personnalisé :",
   "Introduce un tema personalizado:",
   "Enter a custom topic:"
  ],
  "Half an hour": [
   "Fél óra",
   "30 Minuten",
   "Une demi-heure",
   "Media hora"
  ],
  "1 hour": [
   "1 óra",
   "1 Stunde",
   "1 heure",
   "1 hora"
  ],
  "3 hours": [
   "3 óra",
   "3 Stunden",
   "3 heures",
   "3 horas"
  ],
  "6 hours": [
   "6 óra",
   "6 Stunden",
   "6 heures",
   "6 horas"
  ],
  "12 hours": [
   "12 óra",
   "12 Stunden",
   "12 heures",
   "12 horas"
  ],
  "One day": [
   "Egy nap",
   "24 Stunden",
   "Un jour",
   "Un día"
  ]
 },
 "a11y": {
  "Touch & hold delay": [
   "Érintés és tartási késleltetés",
   "Reaktionszeit Berühren/Halten",
   "Délai de pression",
   "Retraso pulsación prolongada"
  ],
  "Short": [
   "Rövid",
   "Kurz",
   "Court",
   "Corto"
  ],
  "Medium": [
   "Közepes",
   "Mittel",
   "Moyen",
   "Medio"
  ],
  "Long": [
   "Hosszú",
   "Lang",
   "Long",
   "Largo"
  ]
 },
 "calendar": {
  "Time zone": [
   "Időzóna",
   "Zeitzone",
   "Fuseau horaire",
   "Zona horaria"
  ],
  "Show me as": [
   "Állapotjelzés",
   "Mich anzeigen als",
   "Ma disponibilité",
   "Mostrarme como"
  ],
  "Busy": [
   "Elfoglalt",
   "Beschäftigt",
   "Occupé",
   "Ocupado"
  ],
  "Available": [
   "Elérhető",
   "Verfügbar",
   "Disponible",
   "Disponible"
  ],
  "Guests": [
   "Résztvevők",
   "Gäste",
   "Invités",
   "Invitados"
  ],
  "Privacy": [
   "Adatvédelem",
   "Datenschutz",
   "Confidentialité",
   "Privacidad"
  ],
  "Default": [
   "Alapértelmezett",
   "Standard",
   "Par défaut",
   "Predeterminado"
  ],
  "Private": [
   "Privát",
   "Privat",
   "Privé",
   "Privado"
  ],
  "Public": [
   "Nyilvános",
   "Öffentlich",
   "Public",
   "Público"
  ]
 },
 "gallery": {
  "Crop": [
   "Körbevágás",
   "Zuschneiden",
   "Rogner",
   "Recortar"
  ],
  "Crop picture": [
   "Kép levágása",
   "Bild zuschneiden",
   "Rogner l'image",
   "Recortar"
  ],
  "Crop save": [
   "Körülvágás",
   "Zuschneiden",
   "Rogner",
   "Recortar",
   "Crop"
  ],
  "Cancel": [
   "Mégse",
   "Abbrechen",
   "Annuler",
   "Cancelar"
  ],
  "Saving picture…": [
   "Kép mentése...",
   "Bild wird gespeichert...",
   "Enregistrement de l'image",
   "Guardando imagen..."
  ]
 },
 "books": {
  "Contents": [
   "Tartalom",
   "Inhaltsverzeichnis",
   "Table des matières",
   "Índice"
  ],
  "Display options": [
   "Megjelenítési beállítások",
   "Anzeigeoptionen",
   "Options d'affichage",
   "Mostrar opciones"
  ],
  "THEME": [
   "TÉMA",
   "Design",
   "THÈME",
   "TEMA"
  ],
  "TYPEFACE": [
   "BETŰKÉP",
   "Schriftart",
   "POLICE",
   "TIPO DE LETRA"
  ],
  "TEXT ALIGNMENT": [
   "SZÖVEG IGAZÍTÁSA",
   "Textausrichtung",
   "ALIGNEMENT DU TEXTE",
   "ALINEACIÓN DEL TEXTO"
  ],
  "BRIGHTNESS": [
   "FÉNYERŐ",
   "Helligkeit",
   "LUMINOSITÉ",
   "BRILLO"
  ],
  "FONT SIZE": [
   "BETŰMÉRET",
   "Schriftgröße",
   "TAILLE DE POLICE",
   "TAMAÑO DE FUENTE"
  ],
  "LINE HEIGHT": [
   "SORMAGASSÁG",
   "Zeilenhöhe",
   "HAUTEUR DE LIGNE",
   "INTERLINEADO"
  ],
  "AUTO": [
   "AUTO",
   "Autom.",
   "AUTO",
   "AUTO"
  ],
  "Day": [
   "Nappal",
   "Tag",
   "Jour",
   "Día"
  ],
  "Night": [
   "Éjszaka",
   "Nacht",
   "Nuit",
   "Noche"
  ],
  "Default": [
   "Alapbeállítás",
   "Standard",
   "Par défaut",
   "Predeterminado"
  ],
  "Sans": [
   "Sans",
   "Sans",
   "Sans",
   "Sans"
  ],
  "Serif": [
   "Serif",
   "Serif",
   "Serif",
   "Serif"
  ],
  "Left": [
   "Balra",
   "Links",
   "Gauche",
   "Izquierda"
  ],
  "Justify": [
   "Sorkizárás",
   "Blocksatz",
   "Justifier",
   "Justificar"
  ],
  "Decrease font size": [
   "Betűméret csökkentése",
   "Schrift verkleinern",
   "Diminuer la taille de la police",
   "Reducir el tamaño de la fuente"
  ],
  "Increase font size": [
   "Betűméret növelése",
   "Schrift vergrößern",
   "Augmenter la taille de la police",
   "Aumentar el tamaño de la fuente"
  ],
  "Decrease line height": [
   "Sormagasság csökkentése",
   "Zeilenhöhe verkleinern",
   "Diminuer la hauteur de ligne",
   "Disminuir la altura de la línea"
  ],
  "Increase line height": [
   "Sormagasság növelése",
   "Zeilenhöhe vergrößern",
   "Augmenter la hauteur de ligne",
   "Aumentar altura de la línea"
  ],
  "About the book": [
   "Információ a könyvről",
   "Über das Buch",
   "À propos du livre",
   "Acerca del libro"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Available offline": [
   "Elérhető offline állapotban",
   "Offline verfügbar",
   "Disponible hors connexion",
   "Disponible sin conexión"
  ],
  "Read aloud": [
   "Hangos felolvasás",
   "Vorlesen",
   "Lire à voix haute",
   "Leer en voz alta"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Accounts": [
   "Fiókok",
   "Konten",
   "Comptes",
   "Cuentas"
  ],
  "Make available offline": [
   "Offline elérhető albumok",
   "Offline bereitstellen",
   "Consulter hors connexion",
   "Disponible sin conexión"
  ],
  "View as carousel": [
   "Megtekintés körhintaként",
   "In Karussellansicht anzeigen",
   "Afficher sous forme de carrousel",
   "Ver como carrusel"
  ],
  "View as list": [
   "Megtekintés listaként",
   "Als Liste anzeigen",
   "Afficher sous forme de liste",
   "Ver como lista"
  ]
 },
 "camera": {
  "pref_camera_flashmode_title": [
   "Vakumód",
   "Blitzmodus",
   "Mode Flash",
   "Flash",
   "Flash mode"
  ],
  "pref_camera_flashmode_entry_auto": [
   "Automatikus",
   "Automatisch",
   "Automatique",
   "Automático",
   "Auto"
  ],
  "pref_camera_flashmode_entry_on": [
   "Be",
   "An",
   "Activé",
   "Activado",
   "On"
  ],
  "pref_camera_flashmode_entry_off": [
   "Ki",
   "Aus",
   "Désactivé",
   "Desactivado",
   "Off"
  ],
  "pref_camera_whitebalance_title": [
   "Fehéregyensúly",
   "Weißabgleich",
   "Balance des blancs",
   "Balance de blancos",
   "White balance"
  ],
  "pref_camera_whitebalance_entry_auto": [
   "Automatikus",
   "Automatisch",
   "Automatique",
   "Automático",
   "Auto"
  ],
  "pref_camera_whitebalance_entry_incandescent": [
   "Izzólámpa",
   "Glühlampenlicht",
   "Incandescent",
   "Incandescente",
   "Incandescent"
  ],
  "pref_camera_whitebalance_entry_daylight": [
   "Nappali fény",
   "Tageslicht",
   "Lumière du jour",
   "Luz natural",
   "Daylight"
  ],
  "pref_camera_whitebalance_entry_fluorescent": [
   "Fénycső",
   "Neonlicht",
   "Fluorescent",
   "Fluorescente",
   "Fluorescent"
  ],
  "pref_camera_whitebalance_entry_cloudy": [
   "Felhős",
   "Bewölkt",
   "Nuageux",
   "Nublado",
   "Cloudy"
  ],
  "pref_camera_scenemode_title": [
   "Kép jellege",
   "Szenenmodus",
   "Mode Scène",
   "Modo de escena",
   "Scene mode"
  ],
  "pref_camera_scenemode_entry_auto": [
   "Automatikus",
   "Automatisch",
   "Automatique",
   "Automático",
   "Auto"
  ],
  "pref_camera_scenemode_entry_action": [
   "Akció",
   "Action",
   "Action",
   "Acción",
   "Action"
  ],
  "pref_camera_scenemode_entry_night": [
   "Éjszakai",
   "Nachtaufnahme",
   "Nuit",
   "Nocturno",
   "Night"
  ],
  "pref_camera_scenemode_entry_sunset": [
   "Napnyugta",
   "Sonnenuntergang",
   "Coucher de soleil",
   "Atardecer",
   "Sunset"
  ],
  "pref_camera_scenemode_entry_party": [
   "Buli",
   "Party",
   "Fête",
   "Fiesta",
   "Party"
  ],
  "pref_camera_settings_category": [
   "Kamera beállításai",
   "Kameraeinstellungen",
   "Paramètres appareil photo",
   "Configuración de cámara",
   "Camera settings"
  ],
  "pref_camera_recordlocation_title": [
   "Hely tárolása",
   "Ort speichern",
   "Enregist. position",
   "Añadir ubicación",
   "Store location"
  ],
  "pref_camera_picturesize_title": [
   "Képméret",
   "Bildgröße",
   "Taille d'image",
   "Tamaño imagen",
   "Picture size"
  ],
  "pref_camera_picturesize_entry_2592x1936": [
   "5 megapixel",
   "5 Millionen Pixel",
   "5 M pixels",
   "5 Mpx",
   "5M pixels"
  ],
  "pref_camera_picturesize_entry_2048x1536": [
   "3 megapixel",
   "3 Millionen Pixel",
   "3 M pixels",
   "3 Mpx",
   "3M pixels"
  ],
  "pref_camera_picturesize_entry_1600x1200": [
   "2 megapixel",
   "2 Millionen Pixel",
   "2 M pixels",
   "2 Mpx",
   "2M pixels"
  ],
  "pref_camera_picturesize_entry_1280x960": [
   "1,3 megapixel",
   "1,3 Megapixel",
   "1,3 M pixels",
   "1,3 Mpx",
   "1.3M pixels"
  ],
  "pref_camera_picturesize_entry_1024x768": [
   "1 megapixel",
   "1 Million Pixel",
   "1 M pixels",
   "1 Mpx",
   "1M pixels"
  ],
  "pref_camera_picturesize_entry_640x480": [
   "VGA",
   "VGA",
   "VGA",
   "VGA",
   "VGA"
  ],
  "pref_camera_picturesize_entry_320x240": [
   "QVGA",
   "QVGA",
   "QVGA",
   "QVGA",
   "QVGA"
  ],
  "pref_camera_focusmode_title": [
   "Fókuszálás módja",
   "Fokussierungsmodus",
   "Mise au point",
   "Modo de enfoque",
   "Focus mode"
  ],
  "pref_camera_focusmode_entry_auto": [
   "Automatikus",
   "Automatisch",
   "Auto",
   "Auto",
   "Auto"
  ],
  "pref_camera_focusmode_entry_infinity": [
   "Végtelen",
   "Unendlich",
   "Infini",
   "Infinito",
   "Infinity"
  ],
  "pref_camera_focusmode_entry_macro": [
   "Makró",
   "Makro",
   "Macro",
   "Macro",
   "Macro"
  ],
  "pref_exposure_title": [
   "Expozíció",
   "Belichtung",
   "Exposition",
   "Exposición",
   "Exposure"
  ],
  "switch_to_camera_label": [
   "Váltás kamerára",
   "Zu Kamera wechseln",
   "Passer en mode photo",
   "Cambiar a cámara",
   "Switch to camera"
  ],
  "switch_to_video_label": [
   "Váltás videóra",
   "Zu Video wechseln",
   "Passer en mode vidéo",
   "Cambiar a vídeo",
   "Switch to video"
  ],
  "switch_to_panorama_label": [
   "Váltás panoráma módra",
   "Zu Panorama wechseln",
   "Passer en mode panoramique",
   "Cambiar a modo panorámico",
   "Switch to panorama"
  ]
 }
};
