/* AOSP frameworks/opt/datetimepicker as CalendarGoogle 201308023 ships it (Nexus 5 KTU84P): Calendar's DatePickerDialog and TimePickerDialog.
   Generated by docs/datetimepicker.py from docs/datetimepicker.template.js; values from the APK's resources:
   - date_picker_dialog.xml (270 dp wide): the #999999 day-of-week header (30 dp, 14 dp white), the white selected date
     (month 30 dp, day 75 dp, year 30 dp; date_picker_selector: blue #33b5e5 for the active part, #999999 otherwise),
     the #f2f2f2 animator (270 dp) with SimpleMonthView (the 50 dp month title, 10 sp day letters, 16 sp days in
     date_picker_text_normal #999999, today in blue, the selected day on a blue circle at alpha 60, 16 dp) or the year
     list (64 dp rows, 22 dp), and Done (14 sp #333333).
   - time_picker_dialog.xml: the white 96 dp header (hours : minutes in 60 sp #8c8c8c, the active one blue; AM / PM in
     16 sp bold caps) over RadialPickerLayout (270 dp on #f2f2f2): a white circle (0.82 of the half size, 0.85 on a
     24-hour clock), the numbers at 0.81 (outer 0.83 / inner 0.6 on 24 hours) in 0.17 (0.11 / 0.14) of the radius, the
     blue selector line and its 0.16 circle, the AM / PM circles (0.19), and Done.
   Hours come first, then minutes; Done writes the value back. State: {kind: 'date', y, m, d, view, vy, vm} or
   {kind: 'time', h, min, hour24, mode}. */
(() => {
  'use strict';
  const e = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]));
  const STRINGS = {"Done": ["Kész", "Fertig", "OK", "Listo"], "Set time": ["Idő beállítása", "Uhrzeit festlegen", "Définir l'heure", "Establecer hora"]};
  const LANGS = ['hu', 'de', 'fr', 'es'];
  const T = (locale, key) => { const i = LANGS.indexOf(String(locale).slice(0, 2)); return i >= 0 && STRINGS[key] ? STRINGS[key][i] : key; };
  const two = n => String(n).padStart(2, '0');
  const daysIn = (y, m) => new Date(y, m + 1, 0).getDate();
  const wrap = (v, lo, hi) => v < lo ? hi : v > hi ? lo : v;
  const done = (locale, action) => `<button type="button" class="dtp-done" data-action="${action}">${e(T(locale, 'Done'))}</button>`;
  const scrim = '<div class="settings-dialog-scrim" data-action="close-overlay"></div>';
  // SimpleMonthView: the month title, the day letters from the locale's first weekday, six rows of days.
  function monthView(state, locale, today) {
    const {vy, vm} = state, first = locale === 'en-US' ? 0 : 1, start = (new Date(vy, vm, 1).getDay() - first + 7) % 7, n = daysIn(vy, vm);
    const letters = Array.from({length: 7}, (_, i) => new Date(2012, 0, 1 + ((first + i) % 7)).toLocaleDateString(locale, {weekday: 'narrow'}).toUpperCase());
    const cells = [];
    for (let i = 0; i < start; i++) cells.push('<span></span>');
    for (let d = 1; d <= n; d++) {
      const isSel = vy === state.y && vm === state.m && d === state.d, isToday = vy === today.getFullYear() && vm === today.getMonth() && d === today.getDate();
      cells.push(`<button type="button" class="${isSel ? 'sel' : ''}${isToday ? ' today' : ''}" data-action="dtp-day" data-id="${vy}-${two(vm + 1)}-${two(d)}">${d}</button>`);
    }
    return `<div class="dtp-month" data-dtp-wheel="month"><b class="dtp-month-title">${e(new Date(vy, vm, 1).toLocaleDateString(locale, {month: 'long', year: 'numeric'}))}</b><div class="dtp-letters">${letters.map(l => `<span>${e(l)}</span>`).join('')}</div><div class="dtp-days">${cells.join('')}</div></div>`;
  }
  function renderDate(state, locale, today) {
    const date = new Date(state.y, state.m, state.d), years = state.view === 'year';
    const head = `<div class="dtp-header">${e(date.toLocaleDateString(locale, {weekday: 'long'}).toUpperCase())}</div><div class="dtp-selected"><button type="button" class="dtp-md${years ? '' : ' on'}" data-action="dtp-view" data-id="day"><span>${e(date.toLocaleDateString(locale, {month: 'short'}).replace('.', '').toUpperCase())}</span><b>${state.d}</b></button><button type="button" class="dtp-year${years ? ' on' : ''}" data-action="dtp-view" data-id="year">${state.y}</button></div>`;
    const body = years
      ? `<div class="dtp-years">${Array.from({length: 201}, (_, i) => 1900 + i).map(y => `<button type="button" class="${y === state.y ? 'sel' : ''}" data-action="dtp-year" data-id="${y}">${y}</button>`).join('')}</div>`
      : monthView(state, locale, today);
    return `${scrim}<div class="dtp dtp-date" role="dialog" aria-label="${e(date.toLocaleDateString(locale))}">${head}<div class="dtp-animator">${body}</div><i class="dtp-line"></i>${done(locale, state.setAction)}<button type="button" class="dtp-hit" hidden data-action="dtp-month"></button></div>`;
  }
  // RadialPickerLayout in an SVG of 100 x 100 units.
  function renderTime(state, locale) {
    const {h, min, hour24, mode} = state, hours = mode !== 'minute';
    const am = new Date(2012, 0, 1, 9).toLocaleTimeString(locale, {hour: 'numeric', hour12: true}).replace(/[\d\s]/g, '') || 'AM';
    const pm = new Date(2012, 0, 1, 21).toLocaleTimeString(locale, {hour: 'numeric', hour12: true}).replace(/[\d\s]/g, '') || 'PM';
    const R = 50 * (hour24 && hours ? .85 : .82), cx = 50, cy = 50, pos = (deg, r) => [cx + r * Math.sin(deg * Math.PI / 180), cy - r * Math.cos(deg * Math.PI / 180)];
    const ring = (labels, rMul, sizeMul) => labels.map((label, i) => { const [x, y] = pos(i * 30, R * rMul); return `<text x="${x.toFixed(2)}" y="${y.toFixed(2)}" font-size="${(R * sizeMul).toFixed(2)}">${label}</text>`; }).join('');
    let numbers, selDeg, selR;
    if (hours) {
      const outer = ['12', ...Array.from({length: 11}, (_, i) => String(i + 1))];
      if (hour24) { numbers = ring(outer, .83, .11) + ring(['00', ...Array.from({length: 11}, (_, i) => String(i + 13))], .6, .14); const inner = h === 0 || h > 12; selDeg = (h % 12) * 30; selR = R * (inner ? .6 : .83); }
      else { numbers = ring(outer, .81, .17); selDeg = (h % 12) * 30; selR = R * .81; }
    } else { numbers = ring(Array.from({length: 12}, (_, i) => two(i * 5)), .81, .17); selDeg = min * 6; selR = R * .81; }
    const [sx, sy] = pos(selDeg, selR);
    const ampm = hour24 ? '' : [[am, 0, h < 12], [pm, 1, h >= 12]].map(([label, i, on]) => { const r = R * .19, x = i ? 100 - r - 3 : r + 3, y = 100 - r - 1; return `<circle class="dtp-ampm${on ? ' on' : ''}" cx="${x}" cy="${y.toFixed(2)}" r="${r.toFixed(2)}"/><text class="dtp-ampm-t${on ? ' on' : ''}" x="${x}" y="${y.toFixed(2)}" font-size="${(r * .55).toFixed(2)}">${e(label.toUpperCase())}</text>`; }).join('');
    const face = `<svg class="dtp-radial" viewBox="0 0 100 100" data-dtp-radial="${hours ? 'hour' : 'minute'}"><circle cx="50" cy="50" r="${R.toFixed(2)}" fill="#fff"/><line x1="50" y1="50" x2="${sx.toFixed(2)}" y2="${sy.toFixed(2)}" class="dtp-hand"/><circle cx="${sx.toFixed(2)}" cy="${sy.toFixed(2)}" r="${(R * .16).toFixed(2)}" class="dtp-sel"/><circle cx="50" cy="50" r="1" class="dtp-dot"/>${numbers}${ampm}</svg>`;
    const shown = hour24 ? two(h) : String((h % 12) || 12);
    return `${scrim}<div class="dtp dtp-time" role="dialog" aria-label="${e(T(locale, 'Set time'))}"><div class="dtp-theader"><button type="button" class="${hours ? 'on' : ''}" data-action="dtp-mode" data-id="hour">${shown}</button><span>:</span><button type="button" class="${hours ? '' : 'on'}" data-action="dtp-mode" data-id="minute">${two(min)}</button>${hour24 ? '' : `<button type="button" class="dtp-ampm-label" data-action="dtp-ampm">${e((h < 12 ? am : pm).toUpperCase())}</button>`}</div><div class="dtp-face">${face}</div><i class="dtp-line"></i>${done(locale, state.setAction)}<button type="button" class="dtp-hit" hidden data-action="dtp-radial"></button></div>`;
  }
  function render(state, locale, today = new Date()) { return !state ? '' : state.kind === 'date' ? renderDate(state, locale, today) : renderTime(state, locale); }
  // The dialog's own actions; true when the state changed.
  function handle(action, id, state) {
    if (!state) return false;
    switch (action) {
      case 'dtp-view': state.view = id; if (id === 'day') { state.vy = state.y; state.vm = state.m; } return true;
      case 'dtp-day': { const [y, m, d] = id.split('-').map(Number); Object.assign(state, {y, m: m - 1, d, vy: y, vm: m - 1}); return true; }
      case 'dtp-year': state.y = Number(id); state.d = Math.min(state.d, daysIn(state.y, state.m)); state.view = 'day'; state.vy = state.y; state.vm = state.m; return true;
      case 'dtp-month': { const t = new Date(state.vy, state.vm + Number(id), 1); if (t.getFullYear() < 1900 || t.getFullYear() > 2100) return false; state.vy = t.getFullYear(); state.vm = t.getMonth(); return true; }
      case 'dtp-mode': state.mode = id; return true;
      case 'dtp-ampm': state.h = (state.h + 12) % 24; return true;
      case 'dtp-radial': {
        const [kind, value] = id.split(':');
        if (kind === 'ampm') { const pmPick = value === '1'; if (pmPick !== (state.h >= 12)) state.h = (state.h + 12) % 24; return true; }
        if (state.mode === 'minute') { state.min = Number(value); return true; }
        state.h = Number(value); state.mode = 'minute'; return true;
      }
    }
    return false;
  }
  const iso = s => `${s.y}-${two(s.m + 1)}-${two(s.d)}`;
  const hhmm = s => `${two(s.h)}:${two(s.min)}`;
  function fromValue(kind, value, extra = {}) {
    if (kind === 'date') { const [y, m, d] = String(value).split('-').map(Number); const s = {kind, y: y || 2013, m: (m || 1) - 1, d: d || 1, view: 'day', ...extra}; s.vy = s.y; s.vm = s.m; return s; }
    const [h, min] = String(value).split(':').map(Number); return {kind, h: h || 0, min: min || 0, mode: 'hour', ...extra};
  }
  // A tap on the radial face picks the nearest hour (30°; on 24 hours the inner or outer ring) or minute (6°), or AM / PM;
  // the month list turns with the wheel or a vertical drag.
  function radialValue(svg, event) {
    const r = svg.getBoundingClientRect(), x = (event.clientX - r.left) / r.width * 100, y = (event.clientY - r.top) / r.height * 100;
    const hour24 = !svg.querySelector('.dtp-ampm'), Rr = 50 * (hour24 && svg.dataset.dtpRadial === 'hour' ? .85 : .82);
    for (const c of svg.querySelectorAll('circle.dtp-ampm')) if (Math.hypot(x - c.cx.baseVal.value, y - c.cy.baseVal.value) <= c.r.baseVal.value) return `ampm:${c.cx.baseVal.value > 50 ? 1 : 0}`;
    const dist = Math.hypot(x - 50, y - 50); if (dist > Rr) return '';
    const deg = (Math.atan2(x - 50, 50 - y) * 180 / Math.PI + 360) % 360;
    if (svg.dataset.dtpRadial === 'minute') return `min:${Math.round(deg / 6) % 60}`;
    let hour = Math.round(deg / 30) % 12;
    if (hour24) { const inner = dist < Rr * .715; hour = inner ? (hour === 0 ? 0 : hour + 12) : (hour === 0 ? 12 : hour); return `hour:${hour}`; }
    const pmNow = svg.querySelector('.dtp-ampm.on')?.cx.baseVal.value > 50; return `hour:${hour + (pmNow ? 12 : 0)}`;
  }
  document.addEventListener('click', event => {
    const svg = event.target.closest?.('svg.dtp-radial'); if (!svg) return;
    const v = radialValue(svg, event); if (!v) return;
    const hit = svg.closest('.dtp').querySelector('.dtp-hit'); hit.dataset.id = v; hit.click();
  });
  const turn = (el, dir) => { const hit = el.closest('.dtp').querySelector('.dtp-hit[data-action="dtp-month"]'); if (!hit) return; hit.dataset.id = String(dir); hit.click(); };
  document.addEventListener('wheel', event => { const el = event.target.closest?.('[data-dtp-wheel]'); if (!el) return; event.preventDefault(); turn(el, event.deltaY > 0 ? 1 : -1); }, {passive: false});
  let drag = null;
  document.addEventListener('pointerdown', event => { const el = event.target.closest?.('[data-dtp-wheel]'); drag = el ? {y: event.clientY, el} : null; });
  document.addEventListener('pointerup', event => { if (!drag) return; const dy = event.clientY - drag.y; if (Math.abs(dy) > 40) { const stop = ev => { ev.stopPropagation(); ev.preventDefault(); }; document.addEventListener('click', stop, {capture: true, once: true}); setTimeout(() => document.removeEventListener('click', stop, {capture: true}), 50); turn(drag.el, dy < 0 ? 1 : -1); } drag = null; });
  // YearPickerView opens centred on the selected year.
  new MutationObserver(() => {
    const list = document.querySelector('.dtp-years:not([data-scrolled])'); if (!list) return;
    list.dataset.scrolled = '1'; const sel = list.querySelector('.sel'); if (sel) list.scrollTop = sel.offsetTop - list.offsetTop - list.clientHeight / 2 + sel.offsetHeight / 2;
  }).observe(document.documentElement, {childList: true, subtree: true});
  window.DateTimePicker = {render, handle, iso, hhmm, fromValue, T};
})();
