/* Offline mailboxes and a Holo Light Email presentation. No network transport. */
(() => {
  'use strict';
  const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const account='demo@example.com';
  const folders=['Inbox','Starred','Drafts','Sent','Trash'];
  const img=name=>`<img src="assets/email-${name}.png" alt="">`;
  function restore(saved,samples=[],sent=[]) {
    if(Array.isArray(saved))return saved.map(item=>({...item,id:String(item.id),body:String(item.body||''),subject:String(item.subject||''),to:String(item.to||''),cc:String(item.cc||''),bcc:String(item.bcc||''),read:!!item.read,starred:!!item.starred}));
    return [...samples.map((item,i)=>({...item,id:'inbox-'+item.id,address:['android@example.com','alex@example.com','calendar@example.com'][i]||'hello@example.com',to:account,folder:'Inbox',read:false,starred:false})),...sent.map(item=>({...item,id:'sent-'+item.id,from:account,address:account,folder:'Sent',read:true,starred:false}))];
  }
  function list(mail,folder='Inbox',query='') {const search=query.toLocaleLowerCase();return mail.filter(item=>(folder==='Starred'?item.starred&&item.folder!=='Trash':item.folder===folder)&&(!search||[item.from,item.to,item.subject,item.body].join(' ').toLocaleLowerCase().includes(search)));}
  function recipients(value) {return String(value||'').split(/[;,]/).map(x=>x.trim()).filter(Boolean);}
  function validRecipients(draft) {const to=recipients(draft.to),all=[...to,...recipients(draft.cc),...recipients(draft.bcc)];return to.length>0&&all.every(x=>/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(x));}
  function draft(source,forward=false,now=Date.now()) {
    return {id:'draft-'+now,folder:'Drafts',from:account,address:account,to:source&&!forward?(source.folder==='Sent'?source.to:source.address):'',cc:'',bcc:'',subject:source?`${forward?'Fwd':'Re'}: ${source.subject.replace(/^(Re|Fwd):\s*/i,'')}`:'',body:source?`\n\n${source.from}:\n${source.body}`:'',read:true,starred:false,created:now,...(forward&&source?.attachment?{attachment:JSON.parse(JSON.stringify(source.attachment))}:{})};
  }
  function trash(items,ids) {for(const item of items)if(ids.includes(item.id)&&item.folder!=='Trash'){item.previousFolder=item.folder;item.folder='Trash';}}
  function untrash(item) {item.folder=['Inbox','Drafts','Sent'].includes(item.previousFolder)?item.previousFolder:'Inbox';delete item.previousFolder;}
  function send(item,now=Date.now()) {if(!validRecipients(item))return false;item.folder='Sent';item.read=true;item.created=now;delete item.previousFolder;return true;}
  function render(mail,ui,t,locale) {
    const folder=ui.emailFolder||'Inbox',selected=ui.emailSelected||[],item=mail.find(item=>item.id===ui.emailId);
    const btn=(action,label,asset,id='')=>`<button type="button" data-action="${action}" ${id?`data-id="${e(id)}"`:''} aria-label="${e(t(label))}">${img(asset)}</button>`;
    const title=label=>`<button class="email-up" data-action="email-list" aria-label="${e(t('Back'))}">‹<img src="assets/email.png" alt=""></button><strong>${e(t(label))}</strong>`;
    const stamp=item=>item.created?new Date(item.created).toLocaleDateString(locale,{month:'short',day:'numeric'}):t(item.time||'');
    if(ui.sub==='compose'&&item) {
      const field=(key,label,type='text')=>`<label><span>${e(t(label))}</span><input type="${type}" name="${key}" value="${e(item[key]||'')}" aria-label="${e(t(label))}" ${key==='subject'?'maxlength="160"':''}></label>`;
      return `<form class="app-view stock-email email-compose" data-form="email"><header class="email-bar">${title('Compose')}<button type="submit" aria-label="${e(t('Send'))}">${img('ic_menu_send_holo_light')}</button><button type="button" data-action="email-menu" aria-label="${e(t('Menu'))}">⋮</button></header><div class="email-scroll"><p class="email-from">${e(t('From'))}: ${account}</p>${field('to','To')}${ui.emailCc||item.cc||item.bcc?field('cc','Cc')+field('bcc','Bcc'):''}${field('subject','Subject')}<label class="email-body-field"><textarea name="body" aria-label="${e(t('Message'))}" placeholder="${e(t('Message'))}" maxlength="10000">${e(item.body)}</textarea></label>${item.attachment?`<div class="email-attachment">${window.ICSMedia.art(item.attachment)}<button type="button" data-action="email-remove-attachment">Remove attachment</button></div>`:''}<p class="email-error" role="alert">${ui.emailError?e(t(ui.emailError)):''}</p></div></form>`;
    }
    if(ui.sub==='read'&&item)return `<div class="app-view stock-email"><header class="email-bar">${title(folder)}${btn(item.folder==='Trash'?'email-restore':'email-trash',item.folder==='Trash'?'Restore':'Delete',item.folder==='Trash'?'ic_menu_refresh_holo_light':'ic_menu_trash_holo_light')}<button data-action="email-menu" aria-label="${e(t('Menu'))}">⋮</button></header><div class="email-scroll email-reader"><h2>${e(item.subject||t('(No subject)'))}</h2><div class="email-reader-from"><span><strong>${e(item.from)}</strong><small>${e(item.address||account)}</small><small>${e(t('To'))}: ${e(item.to||account)}</small>${item.cc?`<small>Cc: ${e(item.cc)}</small>`:''}<small>${e(stamp(item))}</small></span>${btn('email-star',item.starred?'Remove star':'Star',`btn_star_${item.starred?'on':'off'}_normal_email_holo_light`,item.id)}</div><div class="email-message-body">${e(item.body)}</div>${item.attachment?`<div class="email-attachment">${window.ICSMedia.art(item.attachment)}<small>${e(item.attachment.name)}</small></div>`:''}</div><footer class="email-bottom">${btn('email-reply','Reply','ic_reply')}${btn('email-forward','Forward message','ic_forward_holo_dark')}${btn('email-unread','Mark as unread','ic_menu_mark_unread_holo_light')}</footer></div>`;
    const rows=list(mail,folder,ui.emailQuery||'');
    const header=selected.length?`<button data-action="email-clear-selection" aria-label="${e(t('Cancel'))}">✓</button><strong>${selected.length}</strong>${btn('email-selected-read','Mark as read','ic_menu_mark_unread_holo_light')}${btn(folder==='Trash'?'email-selected-restore':'email-selected-trash',folder==='Trash'?'Restore':'Delete',folder==='Trash'?'ic_menu_refresh_holo_light':'ic_menu_trash_holo_light')}`:`<img class="email-app-icon" src="assets/email.png" alt=""><button class="email-folder-title" data-action="email-folders"><strong>${e(t(folder))} ▾</strong><small>${account}</small></button>`;
    return `<div class="app-view stock-email"><header class="email-bar">${header}</header>${ui.emailQuery!==undefined?`<form class="email-search" data-form="email-search"><input name="query" value="${e(ui.emailQuery)}" placeholder="Search mail" aria-label="Search mail"><button type="submit">Search</button></form>`:''}<div class="email-scroll">${rows.map(item=>`<div class="email-message-row ${item.read?'':'unread'} ${selected.includes(item.id)?'selected':''}"><button class="email-select" data-action="email-select" data-id="${e(item.id)}" aria-label="${e(t('Select message')+': '+item.subject)}" role="checkbox" aria-checked="${selected.includes(item.id)}"><img src="assets/btn_check_${selected.includes(item.id)?'on':'off'}_holo_light.png" alt=""></button><button class="email-open" data-action="email-read" data-id="${e(item.id)}"><strong>${e(item.folder==='Sent'||item.folder==='Drafts'?item.to||t('Draft'):item.from)}</strong><span>${e(item.subject||t('(No subject)'))}</span><small>${e(item.body.replace(/\s+/g,' ').slice(0,110))}</small></button><div class="email-row-side"><time>${e(stamp(item))}</time>${btn('email-star',item.starred?'Remove star':'Star',`btn_star_${item.starred?'on':'off'}_normal_email_holo_light`,item.id)}</div></div>`).join('')||'<p class="empty-note">No messages</p>'}</div><footer class="email-bottom">${btn('email-compose','Compose email','ic_menu_compose_normal_holo_light')}${btn('email-search','Search','ic_menu_search_holo_light')}${btn('email-refresh','Refresh','ic_menu_refresh_holo_light')}<button data-action="email-menu" aria-label="${e(t('Menu'))}">⋮</button></footer></div>`;
  }
  function overlay(mail,ui,photos,t) {
    const menu=content=>`<div class="menu-scrim" data-action="close-overlay"></div><div class="holo-menu email-menu">${content}</div>`;
    if(ui.overlay==='email-folders')return menu(folders.map(folder=>`<button data-action="email-folder" data-id="${folder}"><span>${e(t(folder))}</span><small>${list(mail,folder).length}</small></button>`).join(''));
    if(ui.overlay==='email-menu')return menu(ui.sub==='compose'?'<button data-action="email-attach">Attach picture</button><button data-action="email-cc">Add Cc/Bcc</button><button data-action="email-list">Save draft</button><button data-action="email-discard">Discard</button>':ui.sub==='read'?'<button data-action="email-unread">Mark as unread</button><button data-action="email-forward">Forward message</button>':'<button data-action="email-folders">Folders</button>');
    if(ui.overlay==='email-attach')return `<div class="settings-dialog-scrim" data-action="close-overlay"></div><div class="settings-dialog email-photo-picker" role="dialog" aria-label="${e(t('Attach picture'))}"><h3>Attach picture</h3><div>${photos.map(photo=>`<button data-action="email-attach-photo" data-id="${photo.id}">${window.ICSMedia.art(photo)}<span>${e(photo.name)}</span></button>`).join('')}</div><button data-action="close-overlay">Cancel</button></div>`;
    if(ui.overlay==='email-discard')return `<div class="settings-dialog-scrim" data-action="close-overlay"></div><div class="settings-dialog" role="dialog" aria-label="${e(t('Discard draft?'))}"><h3>Discard draft?</h3><div class="settings-dialog-actions"><button data-action="close-overlay">Cancel</button><button data-action="email-confirm-discard">Discard</button></div></div>`;
    return '';
  }
  window.ICSEmail={account,restore,list,recipients,validRecipients,draft,trash,untrash,send,render,overlay};
})();
