/* News & Weather 1.3.11 (GenieWidget.apk of the hammerhead (KTU84P) image): Preferences (xml/preferences.xml, with the
   "Weather settings" entry its onCreate puts first) and LocationPreferences (xml/location_preferences.xml), the
   EditTextPreference and ListPreference dialogs, the refresh status, and the story page (webview_menu.xml's Share
   story). Generated by docs/news-prefs.py from docs/news-prefs.template.js; the texts are the APK's
   (stock-strings.js, group news). Each version styles the nwp- classes in its own CSS. */
(() => {
  'use strict';
  const e = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]));
  // array_refresh_interval_descs / _values; the default interval is 21600 (6 hours).
  const INTERVALS = [['Half an hour', '1800'], ['1 hour', '3600'], ['3 hours', '10800'], ['6 hours', '21600'], ['12 hours', '43200'], ['One day', '86400']];
  const DEFAULTS = {useMyLocation: true, location: '', celsius: null, topics: {}, custom: [], prefetchPages: false, prefetchImages: false, autoRefresh: true, interval: '21600', lastRefresh: 0};
  const prefs = data => ({...DEFAULTS, ...(data.newsPrefs || {})});
  // Use metric follows the language until it is set (Fahrenheit for English).
  const metric = (data, lang) => { const p = prefs(data); return p.celsius === null ? lang !== 'en' : p.celsius; };
  // The topics the tabs show: the standard ones still ticked, then the custom ones.
  const topics = (data, standard) => { const p = prefs(data); return [...standard.filter(name => p.topics[name] !== false), ...p.custom]; };
  const city = (data, fallback) => { const p = prefs(data); return !p.useMyLocation && p.location ? p.location : fallback; };

  // A preference row: title and summary, a CheckBox or a nested screen.
  const row = ({action, id = '', title, summary = '', check = null, disabled = false}) => `<button class="nwp-row${disabled ? ' disabled' : ''}" data-action="${disabled ? '' : action}" data-id="${e(id)}"${disabled ? ' disabled' : ''}><span><b>${e(title)}</b>${summary ? `<small>${e(summary)}</small>` : ''}</span>${check === null ? '' : `<i class="nwp-check${check ? ' on' : ''}"></i>`}</button>`;
  const category = title => `<h4 class="nwp-category">${e(title)}</h4>`;
  function dialog(ctx, p) {
    const N = ctx.N, kind = ctx.ui.nwpDialog;
    if (!kind) return '';
    const shell = (title, body, buttons) => `<div class="nwp-scrim" data-action="nwp-cancel"></div><div class="nwp-dialog" role="dialog" aria-label="${e(title)}"><h3>${e(title)}</h3>${body}${buttons ? `<div class="nwp-buttons">${buttons}</div>` : ''}</div>`;
    const okCancel = `<button data-action="nwp-cancel">${e(ctx.t('Cancel'))}</button><button data-action="nwp-ok">${e(ctx.t('OK'))}</button>`;
    if (kind === 'location') return shell(N('Type a city or postal code:'), `<p>${e(N('Type a city or postal code:'))}</p><input data-nwp-input autocomplete="off" value="${e(p.location)}">`, okCancel);
    if (kind === 'custom') return shell(N('Custom topic'), `<p>${e(N('Type a custom topic:'))}</p><input data-nwp-input autocomplete="off" value="">`, okCancel);
    if (kind === 'interval') return shell(N('Refresh interval'), `<div class="nwp-choices">${INTERVALS.map(([label, value]) => `<button data-action="nwp-choose" data-id="${value}"><span>${e(N(label))}</span><i class="nwp-radio${p.interval === value ? ' on' : ''}"></i></button>`).join('')}</div>`, `<button data-action="nwp-cancel">${e(ctx.t('Cancel'))}</button>`);
    return '';
  }
  // ctx: {data, ui, lang, locale, now, N (the APK's texts), t (the image's), standard (the topic names), version, bar(title)}.
  function render(ctx) {
    const {N, ui, data} = ctx, p = prefs(data), screen = ui.nwpScreen || 'root', when = ms => new Date(ms).toLocaleString(ctx.locale, {month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit'});
    let body = '', title = N('Settings');
    if (screen === 'root') {
      body = row({action: 'nwp-open', id: 'weather', title: N('Weather settings'), summary: N('Set location, units')})
        + row({action: 'nwp-open', id: 'news', title: N('News settings'), summary: N('Choose topics, manage downloads')})
        + row({action: 'nwp-open', id: 'refresh', title: N('Refresh settings'), summary: N('Set up auto-refresh, refresh interval')})
        + row({title: N('App version'), summary: ctx.version, disabled: true});
    } else if (screen === 'weather') {
      title = N('Weather settings');
      body = row({action: 'nwp-toggle', id: 'useMyLocation', title: N('Use my location'), summary: N('Automatically determine location'), check: p.useMyLocation})
        + row({action: 'nwp-dialog', id: 'location', title: N('Set location'), summary: p.location || N('Specify your location'), disabled: p.useMyLocation})
        + row({action: 'nwp-toggle', id: 'celsius', title: N('Use metric'), summary: N('Toggle metric/imperial units'), check: metric(data, ctx.lang)});
    } else if (screen === 'news') {
      title = N('News settings');
      body = row({action: 'nwp-open', id: 'topics', title: N('Choose news topics'), summary: N('Manage news topics')})
        + row({action: 'nwp-toggle', id: 'prefetchPages', title: N('Prefetch articles'), summary: N('Prefetch articles for faster access'), check: p.prefetchPages})
        + row({action: 'nwp-toggle', id: 'prefetchImages', title: N('Prefetch images'), summary: N('Prefetch images for faster access'), check: p.prefetchImages})
        + row({action: 'nwp-unsupported', title: N('News terms of service')})
        + row({action: 'nwp-unsupported', title: N('Mobile privacy policy')});
    } else if (screen === 'topics') {
      title = N('Choose news topics');
      body = category(N('Custom topics')) + row({action: 'nwp-dialog', id: 'custom', title: N('Custom topic'), summary: N('Add a custom news topic here')})
        + p.custom.map(name => row({action: 'nwp-remove', id: name, title: name, check: true})).join('')
        + category(N('News topics')) + ctx.standard.map(name => row({action: 'nwp-topic', id: name, title: ctx.topic(name), check: p.topics[name] !== false})).join('');
    } else if (screen === 'refresh') {
      title = N('Refresh settings');
      const interval = INTERVALS.find(([, v]) => v === p.interval) || INTERVALS[3];
      const status = p.lastRefresh ? (p.autoRefresh ? N('Last refresh %1$s \nNext refresh %2$s').replace('%1$s', when(p.lastRefresh)).replace('%2$s', when(p.lastRefresh + Number(p.interval) * 1000)) : N('Last refresh %s').replace('%s', when(p.lastRefresh))) : '';
      body = row({action: 'nwp-toggle', id: 'autoRefresh', title: N('Auto-refresh'), summary: N('Auto-refresh summary') === 'Auto-refresh summary' ? '' : N('Auto-refresh summary'), check: p.autoRefresh})
        + row({action: 'nwp-dialog', id: 'interval', title: N('Refresh interval'), summary: N(interval[0]), disabled: !p.autoRefresh})
        + row({title: N('Refresh status'), summary: status, disabled: true});
    }
    return `<div class="app-view nwp nwp-${screen}" data-no-translate>${ctx.bar(title)}<div class="nwp-list">${body}</div>${dialog(ctx, p)}</div>`;
  }
  // Settings actions; ctx.input() reads the dialog's field. Returns true when the action was the settings'.
  function handle(action, id, ctx) {
    const {ui, data} = ctx, p = prefs(data), set = change => { data.newsPrefs = {...p, ...change}; ctx.save(); };
    switch (action) {
      case 'nwp-open': ui.nwpScreen = id; break;
      case 'nwp-toggle': set({[id]: id === 'celsius' ? !metric(data, ctx.lang) : !p[id]}); break;
      case 'nwp-topic': set({topics: {...p.topics, [id]: p.topics[id] === false}}); break;
      case 'nwp-remove': set({custom: p.custom.filter(name => name !== id)}); break;
      case 'nwp-dialog': ui.nwpDialog = id; break;
      case 'nwp-cancel': ui.nwpDialog = ''; break;
      case 'nwp-choose': set({interval: id}); ui.nwpDialog = ''; break;
      case 'nwp-ok': {
        const value = String(ctx.input() || '').trim();
        if (ui.nwpDialog === 'location') set({location: value});
        if (ui.nwpDialog === 'custom' && value && !p.custom.includes(value)) set({custom: [...p.custom, value]});
        ui.nwpDialog = ''; break;
      }
      case 'nwp-unsupported': ctx.unsupported(); return true;
      default: return false;
    }
    ctx.render(); return true;
  }
  // Back: a dialog, then a nested screen, then the settings themselves.
  function back(ui) {
    if (ui.nwpDialog) { ui.nwpDialog = ''; return true; }
    if (ui.nwpScreen && ui.nwpScreen !== 'root') { ui.nwpScreen = ui.nwpScreen === 'topics' ? 'news' : 'root'; return true; }
    return false;
  }
  // MainActivity's Refresh: the last refresh time the status shows.
  const refresh = (data, now) => { data.newsPrefs = {...prefs(data), lastRefresh: now}; };
  // The story page: the title, the source and time, the picture of the first story and the text; Share story is in its menu.
  const story = ({title, source, time, snippet, picture}) => `<article class="nwp-story"><h2>${e(title)}</h2><small>${e(source)}${time ? ` - ${e(time)}` : ''}</small>${picture || ''}<p>${e(snippet || title)}</p></article>`;
  window.NewsPrefs = {INTERVALS, prefs, metric, topics, city, render, handle, back, refresh, story};
})();
