/* Generated by docs/sounds.py from the hammerhead image (/system/media/audio, sounds.json, build.prop). Do not edit. */
/* The image's own ringtones, notification sounds and alarms (WebM / Opus copies in assets/audio, loaded only when played):
   - a ringtone list plays the tone touched, as RingtonePickerActivity does: the Settings dialogs mark their form with
     data-sound (ringtone / notificationTone, values are titles), Gingerbread's list uses gbset-sound-pick (file names);
     closing the list stops it;
   - a ringing alarm (the AlarmAlert / AlarmActivity screen of each version) loops the image's default alarm
     (ro.config.alarm_alert) until it is dismissed or snoozed.
   Browsers only play sound after the first touch on the page. */
(() => {
  'use strict';
  // category -> file name -> [title, asset]; the build.prop defaults by file name.
  const SOUNDS = {"ringtones": {"Callisto": ["Callisto", "Callisto-b04ff5e4"], "Dione": ["Dione", "Dione-bbce3133"], "Ganymede": ["Ganymede", "Ganymede-abf2cf94"], "Luna": ["Luna", "Luna-1010803c"], "Oberon": ["Oberon", "Oberon-6bdb275e"], "Phobos": ["Phobos", "Phobos-e61cce6f"], "RobotsforEveryone": ["Robots for Everyone", "RobotsforEveryone-ab01ee99"], "Sedna": ["Sedna", "Sedna-60128929"], "SpagnolaOrchestration": ["Spagnola Orchestration", "SpagnolaOrchestration-bc8fa0f1"], "Titania": ["Titania", "Titania-2316b40f"], "Triton": ["Triton", "Triton-519bd6b6"], "Umbriel": ["Umbriel", "Umbriel-9215fa18"]}, "notifications": {"Ariel": ["Ariel", "Ariel-afda46cf"], "Carme": ["Carme", "Carme-d4c93b1c"], "Ceres": ["Ceres", "Ceres-a2120442"], "Elara": ["Elara", "Elara-2061b41e"], "Europa": ["Europa", "Europa-4f2bf017"], "Iapetus": ["Iapetus", "Iapetus-0ecf840f"], "Io": ["Io", "Io-9befd39c"], "Rhea": ["Rhea", "Rhea-1238eb9c"], "Salacia": ["Salacia", "Salacia-648a3931"], "Tethys": ["Tethys", "Tethys-45661712"], "Titan": ["Titan", "Titan-d1477246"]}, "alarms": {"Argon": ["Argon", "Argon-4b64d8d8"], "Carbon": ["Carbon", "Carbon-d5880b02"], "Helium": ["Helium", "Helium-63882084"], "Krypton": ["Krypton", "Krypton-3422548b"], "Neon": ["Neon", "Neon-a6970cf3"], "Osmium": ["Osmium", "Osmium-f6e4e778"], "Oxygen": ["Oxygen", "Oxygen-61e8cfcc"], "Platinum": ["Platinum", "Platinum-45d5c553"]}};
  const DEFAULTS = {"ringtones": "Titania", "notifications": "Tethys", "alarms": "Oxygen"};
  const RINGING = '.gbdc-ring, .dcal-ics, .dcal-glow, .dcal-lp';
  const asset = (cat, key) => { const list = SOUNDS[cat] || {}; const hit = list[key] || Object.values(list).find(([title]) => title === key); return hit ? hit[1] : null; };
  let preview = null, alarm = null;
  const start = (name, loop) => { const audio = new Audio(`../../assets/audio/${name}.webm`); audio.loop = loop; audio.play().catch(() => {}); return audio; };
  function play(cat, key) { stop(); const name = asset(cat, key); if (name) preview = start(name, false); }
  function stop() { if (preview) { preview.pause(); preview = null; } }
  document.addEventListener('change', event => {
    const input = event.target.closest?.('form[data-sound] input[name="choice"]');
    if (input) play(input.form.dataset.sound === 'ringtone' ? 'ringtones' : 'notifications', input.value);
  });
  document.addEventListener('click', event => {
    const pick = event.target.closest?.('[data-action="gbset-sound-pick"]');
    if (!pick) return;
    const [kind, name] = pick.dataset.id.split(':');
    if (name) play(kind === 'ringtone' ? 'ringtones' : 'notifications', name); else stop();
  }, true);
  // The list closing stops the preview; the ringing screen appearing or leaving starts or stops the alarm.
  let queued = false;
  new MutationObserver(() => {
    if (queued) return; queued = true;
    requestAnimationFrame(() => {
      queued = false;
      if (preview && !document.querySelector('form[data-sound], [data-action="gbset-sound-pick"]')) stop();
      const ringing = !!document.querySelector(RINGING);
      if (ringing && !alarm) { const name = asset('alarms', DEFAULTS.alarms); if (name) alarm = start(name, true); }
      if (!ringing && alarm) { alarm.pause(); alarm = null; }
    });
  }).observe(document.body, {childList: true, subtree: true});
  window.SystemSounds = {SOUNDS, DEFAULTS, asset, play, stop};
})();
