/* Generated by docs/stock-strings.py from docs/stock-strings.json and the hammerhead factory image. Do not edit. */
window.StockStrings = {
 "news": {
  "News & Weather": [
   "Hírek és időjárás",
   "News & Wetter",
   "Actualités et météo",
   "Noticias y tiempo"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Weather": [
   "Időjárás",
   "Wetter",
   "Météo",
   "Tiempo"
  ],
  "Humidity: %s%%": [
   "Páratartalom: %s%%",
   "Luftfeuchtigkeit: %s %%",
   "Humidité : %s%%",
   "Humedad: %s%%"
  ],
  "Wind: %1$s %2$s": [
   "Szélerősség: %1$s %2$s",
   "Wind: %1$s %2$s",
   "Vent : %1$s %2$s",
   "Viento: %1$s %2$s"
  ],
  "km/h": [
   "km/h",
   "km/h",
   "km/h",
   "km/h"
  ],
  "Mon": [
   "H",
   "M",
   "L",
   "L",
   "M"
  ],
  "Tue": [
   "K",
   "D",
   "M",
   "M",
   "T"
  ],
  "Wed": [
   "Sze",
   "M",
   "M",
   "X",
   "W"
  ],
  "Thu": [
   "Cs",
   "D",
   "J",
   "J",
   "T"
  ],
  "Fri": [
   "P",
   "F",
   "V",
   "V",
   "F"
  ],
  "Sat": [
   "Szo",
   "S",
   "S",
   "S",
   "S"
  ],
  "Sun": [
   "V",
   "S",
   "D",
   "D",
   "S"
  ]
 },
 "earth": {
  "Earth": [
   "Earth",
   "Earth",
   "Earth",
   "Earth"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Recherche Google",
   "Buscar"
  ],
  "Example: Pizza": [
   "példa: Pizza",
   "Beispiel: Pizza",
   "Exemple : boulangerie",
   "Ej.: Barcelona"
  ],
  "Reset to north": [
   "Visszaállítás északi irányba",
   "Auf Nordausrichtung zurücksetzen",
   "Rétablir l'orientation (nord en haut)",
   "Restablecer el Norte"
  ],
  "My location": [
   "Saját pozíció",
   "Mein Standort",
   "Ma position",
   "Mi ubicación"
  ],
  "Clear map": [
   "Térképjelölők törlése",
   "Karte leeren",
   "Effacer la carte",
   "Borrar mapa"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Comentarios"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Tutorial": [
   "Útmutató",
   "Anleitung",
   "Didacticiel",
   "Tutorial"
  ]
 },
 "gsettings": {
  "Google Settings": [
   "Google-beállítások",
   "Google Einstellungen",
   "Paramètres Google",
   "Ajustes de Google"
  ],
  "Apps with Google+ Sign-In": [
   "Társított alkalmazások",
   "Verbundene Apps",
   "Applications associées",
   "Aplicaciones conectadas",
   "Connected apps"
  ],
  "Google+": [
   "Google+",
   "Google+",
   "Google+",
   "Google+"
  ],
  "Play Games": [
   "Play Játékok",
   "Play Games",
   "Play Jeux",
   "Play Games"
  ],
  "Location": [
   "Hely",
   "Standort",
   "Position",
   "Ubicación"
  ],
  "Search & Now": [
   "Keresés és Asszisztens",
   "Suche & Google Now",
   "Recherche et Now",
   "Búsqueda y Google Now"
  ],
  "Ads": [
   "Hirdetések",
   "Anzeigen",
   "Annonces",
   "Anuncios"
  ],
  "Verify apps": [
   "Alkalmazások ellenőrzése",
   "Apps bestätigen",
   "Vérifier les applications",
   "Verificar aplicaciones"
  ],
  "Android Device Manager": [
   "Android Eszközkezelő",
   "Android Geräte-Manager",
   "Gestionnaire d'appareils Android",
   "Administrador de dispositivos"
  ],
  "Drive apps": [
   "Drive apps",
   "Drive apps",
   "Drive apps",
   "Drive apps"
  ]
 },
 "google": {
  "Card menu": [
   "Kártya menü",
   "Kartenmenü",
   "Menu de la carte",
   "Menú de la tarjeta"
  ],
  "View in Calendar": [
   "Megtekintés a Naptárban",
   "Im Kalender ansehen",
   "Afficher dans l'agenda",
   "Ver en Calendar"
  ],
  "More": [
   "Továbbiak",
   "Mehr",
   "Plus",
   "Más"
  ],
  "Reminders": [
   "Emlékeztetők",
   "Erinnerungen",
   "Rappels",
   "Recordatorios"
  ],
  "Train Google Now": [
   "A Google Asszisztens betanítása",
   "Interessen in Google Now festlegen",
   "Améliorer Google Now",
   "Enseñar a Google Now"
  ],
  "Menu": [
   "Menü",
   "Menü",
   "Menu",
   "Menú"
  ],
  "Tap to speak": [
   "Koppintson a beszédhez",
   "Zum Sprechen tippen",
   "Appuyez pour parler",
   "Toca para hablar."
  ]
 }
};
