/* Generated by docs/stock-strings.py from docs/stock-strings.json and the hammerhead factory image. Do not edit. */
window.StockStrings = {
 "news": {
  "News & Weather": [
   "Hírek és időjárás",
   "News & Wetter",
   "Actualités et météo",
   "Noticias y tiempo"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Weather": [
   "Időjárás",
   "Wetter",
   "Météo",
   "Tiempo"
  ],
  "Humidity: %s%%": [
   "Páratartalom: %s%%",
   "Luftfeuchtigkeit: %s %%",
   "Humidité : %s%%",
   "Humedad: %s%%"
  ],
  "Wind: %1$s %2$s": [
   "Szélerősség: %1$s %2$s",
   "Wind: %1$s %2$s",
   "Vent : %1$s %2$s",
   "Viento: %1$s %2$s"
  ],
  "km/h": [
   "km/h",
   "km/h",
   "km/h",
   "km/h"
  ],
  "Mon": [
   "H",
   "M",
   "L",
   "L",
   "M"
  ],
  "Tue": [
   "K",
   "D",
   "M",
   "M",
   "T"
  ],
  "Wed": [
   "Sze",
   "M",
   "M",
   "X",
   "W"
  ],
  "Thu": [
   "Cs",
   "D",
   "J",
   "J",
   "T"
  ],
  "Fri": [
   "P",
   "F",
   "V",
   "V",
   "F"
  ],
  "Sat": [
   "Szo",
   "S",
   "S",
   "S",
   "S"
  ],
  "Sun": [
   "V",
   "S",
   "D",
   "D",
   "S"
  ]
 },
 "earth": {
  "Earth": [
   "Earth",
   "Earth",
   "Earth",
   "Earth"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Recherche Google",
   "Buscar"
  ],
  "Example: Pizza": [
   "példa: Pizza",
   "Beispiel: Pizza",
   "Exemple : boulangerie",
   "Ej.: Barcelona"
  ],
  "Reset to north": [
   "Visszaállítás északi irányba",
   "Auf Nordausrichtung zurücksetzen",
   "Rétablir l'orientation (nord en haut)",
   "Restablecer el Norte"
  ],
  "My location": [
   "Saját pozíció",
   "Mein Standort",
   "Ma position",
   "Mi ubicación"
  ],
  "Clear map": [
   "Térképjelölők törlése",
   "Karte leeren",
   "Effacer la carte",
   "Borrar mapa"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Comentarios"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Tutorial": [
   "Útmutató",
   "Anleitung",
   "Didacticiel",
   "Tutorial"
  ]
 },
 "gsettings": {
  "Google Settings": [
   "Google-beállítások",
   "Google Einstellungen",
   "Paramètres Google",
   "Ajustes de Google"
  ],
  "Apps with Google+ Sign-In": [
   "Társított alkalmazások",
   "Verbundene Apps",
   "Applications associées",
   "Aplicaciones conectadas",
   "Connected apps"
  ],
  "Google+": [
   "Google+",
   "Google+",
   "Google+",
   "Google+"
  ],
  "Play Games": [
   "Play Játékok",
   "Play Games",
   "Play Jeux",
   "Play Games"
  ],
  "Location": [
   "Hely",
   "Standort",
   "Position",
   "Ubicación"
  ],
  "Search & Now": [
   "Keresés és Asszisztens",
   "Suche & Google Now",
   "Recherche et Now",
   "Búsqueda y Google Now"
  ],
  "Ads": [
   "Hirdetések",
   "Anzeigen",
   "Annonces",
   "Anuncios"
  ],
  "Verify apps": [
   "Alkalmazások ellenőrzése",
   "Apps bestätigen",
   "Vérifier les applications",
   "Verificar aplicaciones"
  ],
  "Android Device Manager": [
   "Android Eszközkezelő",
   "Android Geräte-Manager",
   "Gestionnaire d'appareils Android",
   "Administrador de dispositivos"
  ],
  "Drive apps": [
   "Drive apps",
   "Drive apps",
   "Drive apps",
   "Drive apps"
  ]
 },
 "google": {
  "Card menu": [
   "Kártya menü",
   "Kartenmenü",
   "Menu de la carte",
   "Menú de la tarjeta"
  ],
  "View in Calendar": [
   "Megtekintés a Naptárban",
   "Im Kalender ansehen",
   "Afficher dans l'agenda",
   "Ver en Calendar"
  ],
  "More": [
   "Továbbiak",
   "Mehr",
   "Plus",
   "Más"
  ],
  "Reminders": [
   "Emlékeztetők",
   "Erinnerungen",
   "Rappels",
   "Recordatorios"
  ],
  "Train Google Now": [
   "A Google Asszisztens betanítása",
   "Interessen in Google Now festlegen",
   "Améliorer Google Now",
   "Enseñar a Google Now"
  ],
  "Menu": [
   "Menü",
   "Menü",
   "Menu",
   "Menú"
  ],
  "Tap to speak": [
   "Koppintson a beszédhez",
   "Zum Sprechen tippen",
   "Appuyez pour parler",
   "Toca para hablar."
  ],
  "Speak now": [
   "Most beszéljen",
   "Sprechen",
   "Parlez maintenant",
   "Habla ahora"
  ],
  "Didn't catch that. Try speaking again.": [
   "Nem sikerült értelmezni. Mondja ki újra.",
   "Das wurde nicht verstanden. Bitte sprechen Sie erneut.",
   "Je n'ai pas compris. Veuillez répéter.",
   "No lo he entendido. Prueba a decirlo otra vez."
  ]
 },
 "maps": {
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Directions": [
   "Útvonalterv",
   "Route",
   "Itinéraire",
   "Indicaciones"
  ],
  "Traffic": [
   "Forgalom",
   "Verkehrslage",
   "Trafic",
   "Tráfico"
  ],
  "Public transit": [
   "Tömegközlekedés",
   "Öffentliche Verkehrsmittel",
   "Transports en commun",
   "Transporte público"
  ],
  "Bicycling": [
   "Kerékpárral",
   "Fahrrad",
   "Vélo",
   "Rutas en bicicleta"
  ],
  "Satellite": [
   "Műhold",
   "Satellit",
   "Satellite",
   "Satélite"
  ],
  "Google Earth": [
   "Google Earth",
   "Google Earth",
   "Google Earth",
   "Google Earth"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Configuración"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Enviar comentarios"
  ],
  "Move to my location": [
   "Ugrás a saját pozíciómra",
   "Zu meinem Standort wechseln",
   "Centrer sur ma position",
   "Mover a mi ubicación"
  ],
  "Menu": [
   "Menü",
   "Menü",
   "Menu",
   "Menú"
  ]
 },
 "keep": {
  "Keep": [
   "Keep",
   "Keep",
   "Keep",
   "Keep"
  ],
  "Add quick note": [
   "Rövid üzenet hozzáadása",
   "Kurze Notiz hinzufügen",
   "Ajouter une note rapide",
   "Añadir nota rápida"
  ],
  "New note": [
   "Új jegyzet",
   "Neue Notiz",
   "Nouvelle note",
   "Nueva nota"
  ],
  "New list": [
   "Új lista",
   "Neue Liste",
   "Nouvelle liste",
   "Lista nueva"
  ],
  "New recording": [
   "Új felvétel",
   "Neue Aufnahme",
   "Nouvel enregistrement",
   "Nueva grabación"
  ],
  "New photo": [
   "Új fotó",
   "Neues Foto",
   "Nouvelle photo",
   "Foto nueva"
  ],
  "Take a note": [
   "Jegyzetelés",
   "Notiz schreiben",
   "Rédiger une note",
   "Tomar una nota"
  ],
  "There are no archived notes": [
   "Nincsenek archivált jegyzetek",
   "Keine archivierten Notizen vorhanden",
   "Aucune note archivée",
   "No hay notas archivadas"
  ],
  "Create a reminder": [
   "Emlékeztető létrehozása",
   "Erinnerung erstellen",
   "Créer un rappel",
   "Crear un recordatorio"
  ],
  "Notes": [
   "Jegyzetek",
   "Notizen",
   "Notes",
   "Notas"
  ],
  "Archive (drawer)": [
   "Archívum",
   "Archiv",
   "Notes archivées",
   "Archivadas",
   "Archive"
  ],
  "Reminders": [
   "Emlékeztetők",
   "Erinnerungen",
   "Rappels",
   "Recordatorios"
  ],
  "Open navigation drawer": [
   "Navigációs fiók kinyitása",
   "Navigationsleiste öffnen",
   "Ouvrir le panneau de navigation",
   "Abrir control de navegación"
  ],
  "Note color…": [
   "Jegyzet színe…",
   "Notizfarbe…",
   "Couleur de la note…",
   "Color de la nota…"
  ],
  "Add picture": [
   "Kép hozzáadása",
   "Bild hinzufügen",
   "Ajouter une image",
   "Añadir imagen"
  ],
  "Archive": [
   "Archiválás",
   "Archivieren",
   "Archiver",
   "Archivar"
  ],
  "Unarchive": [
   "Archiválás visszavonása",
   "Dearchivieren",
   "Annuler l'archivage",
   "No archivar"
  ],
  "Delete": [
   "Törlés",
   "Löschen",
   "Supprimer",
   "Eliminar"
  ],
  "Show checkboxes": [
   "Jelölőnégyzetek megjelenítése",
   "Kontrollkästchen anzeigen",
   "Afficher les cases à cocher",
   "Mostrar casillas de verificación"
  ],
  "Share…": [
   "Megosztás…",
   "Teilen…",
   "Partager…",
   "Compartir…"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Single-column view": [
   "Egyoszlopos nézet",
   "Ansicht mit einer Spalte",
   "Vue avec colonne unique",
   "Vista de una columna"
  ],
  "Multi-column view": [
   "Többoszlopos nézet",
   "Ansicht mit mehreren Spalten",
   "Vue multicolonne",
   "Vista de varias columnas"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ]
 },
 "youtube": {
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Uploads": [
   "Feltöltések",
   "Uploads",
   "Vidéos mises en ligne",
   "Vídeos subidos"
  ],
  "History": [
   "Előzmények",
   "Verlauf",
   "Historique",
   "Historial"
  ],
  "Favorites": [
   "Kedvencek",
   "Favoriten",
   "Favoris",
   "Favoritos"
  ],
  "Playlists": [
   "Lejátszási listák",
   "Playlists",
   "Playlists",
   "Listas"
  ],
  "Watch later": [
   "Megnézendő videók",
   "Später ansehen",
   "À regarder plus tard",
   "Ver más tarde"
  ],
  "Subscriptions": [
   "Előfizetések",
   "Abos",
   "Abonnements",
   "Suscripciones"
  ],
  "What to watch": [
   "Megtekintendő videók",
   "Empfohlene Videos",
   "Vidéos à regarder",
   "Actividad"
  ],
  "My subscriptions": [
   "Feliratkozásaim",
   "Meine Abos",
   "Mes abonnements",
   "Mis suscripciones"
  ],
  "Browse channels": [
   "Csatornák tallózása",
   "Kanäle finden",
   "Parcourir les chaînes",
   "Buscar canales"
  ],
  "From YouTube": [
   "A YouTube-ról",
   "Beliebt auf YouTube",
   "Sur YouTube",
   "Visto en YouTube"
  ],
  "Recommended": [
   "Ajánlott",
   "Empfohlen",
   "Recommandations",
   "Recomendados"
  ],
  "Trending": [
   "Felkapott",
   "Trends",
   "Tendances",
   "Tendencias"
  ],
  "Open guide": [
   "A segéd megnyitása",
   "Anleitung öffnen",
   "Ouvrir le guide",
   "Abrir guía"
  ],
  "More": [
   "Több",
   "Mehr",
   "Plus",
   "Más"
  ],
  "Like": [
   "Tetszik",
   "Mag ich",
   "J'aime",
   "Me gusta"
  ],
  "Dislike": [
   "Nem tetszik",
   "Mag ich nicht",
   "Je n'aime pas",
   "No me gusta"
  ]
 },
 "drive": {
  "My Drive": [
   "Saját meghajtó",
   "Meine Ablage",
   "Mon Drive",
   "Mi unidad"
  ],
  "Shared with me": [
   "Velem megosztottak",
   "Für mich freigegeben",
   "Partagés avec moi",
   "Compartido conmigo"
  ],
  "Starred": [
   "Csillagozott elemek",
   "Markiert",
   "Suivis",
   "Destacado"
  ],
  "Recent": [
   "Legutóbbi",
   "Zuletzt geöffnet",
   "Récents",
   "Reciente"
  ],
  "Offline": [
   "Offline",
   "Offline",
   "Hors connexion",
   "Sin conexión"
  ],
  "Uploads": [
   "Feltöltések",
   "Uploads",
   "Importations",
   "Subidas"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "View as Grid": [
   "Rácsnézet",
   "Als Raster anzeigen",
   "Grille",
   "Ver como cuadrícula"
  ],
  "Add new": [
   "Új hozzáadása",
   "Neu hinzufügen",
   "Ajouter",
   "Nuevo"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Filter by": [
   "Szűrés:",
   "Filtern nach",
   "Filtrer par",
   "Filtrar por"
  ],
  "Sort by": [
   "Rendezési szempont:",
   "Sortieren nach",
   "Trier par",
   "Ordenar por"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Product Tour": [
   "Termékbemutató",
   "Produkttour",
   "Visite guidée",
   "Visita del producto"
  ],
  "Open navigation drawer": [
   "Navigálási fiók megnyitása",
   "Navigationsleiste öffnen",
   "Ouvrir le panneau de navigation",
   "Abrir control de navegación"
  ],
  "Show item properties": [
   "Elemtulajdonságok megjelenítése",
   "Dokumenteigenschaften anzeigen",
   "Afficher les propriétés de l'élément",
   "Mostrar propiedades de los elementos"
  ],
  "Modified: %s": [
   "Módosítva: %s",
   "Geändert: %s",
   "Modifié : %s",
   "Modificado: %s"
  ],
  "Today": [
   "Ma",
   "Heute",
   "Aujourd'hui",
   "Hoy"
  ],
  "Yesterday": [
   "Tegnap",
   "Gestern",
   "Hier",
   "Ayer"
  ],
  "Earlier this Week": [
   "Korábban a héten",
   "In dieser Woche",
   "Cette semaine",
   "Anteriormente esta semana"
  ],
  "Earlier this Month": [
   "Korábban a hónapban",
   "In diesem Monat",
   "Ce mois-ci",
   "Anteriormente este mes"
  ],
  "Older": [
   "Régebbiek",
   "Ältere",
   "Plus anciens",
   "Más antiguos"
  ]
 },
 "gplus": {
  "Home": [
   "Kezdőlap",
   "Übersicht",
   "Accueil",
   "Inicio"
  ],
  "Photo": [
   "Fotó",
   "Foto",
   "Photo",
   "Foto"
  ],
  "Location": [
   "Hely",
   "Standort",
   "Position",
   "Ubicación"
  ],
  "Write": [
   "Írás",
   "Schreiben",
   "Rédiger",
   "Escribir"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer un commentaire",
   "Danos tu opinión"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Sign out": [
   "Kijelentkezés",
   "Abmelden",
   "Déconnexion",
   "Cerrar sesión"
  ]
 },
 "music": {
  "Play Music": [
   "Google Play Zene",
   "Google Play Music",
   "Google Play Musique",
   "Google Play Music",
   "Google Play Music"
  ],
  "Listen Now": [
   "Zeneajánló",
   "Jetzt anhören",
   "À écouter",
   "Escuchar ahora"
  ],
  "My Library": [
   "Saját könyvtár",
   "Meine Musik",
   "Ma bibliothèque",
   "Mi música"
  ],
  "Playlists": [
   "Lejátszási listák",
   "Playlists",
   "Playlists",
   "Listas de reproducción"
  ],
  "Instant Mixes": [
   "Instant egyvelegek",
   "Schnellmixe",
   "Mix instantanés",
   "Mixes instantáneos"
  ],
  "Shop": [
   "Vásárlás",
   "Einkaufen",
   "Acheter",
   "Tienda"
  ],
  "All music": [
   "Minden zene",
   "Alle Musiktitel",
   "Toute la musique",
   "Toda la música"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Enviar comentarios"
  ],
  "Genres": [
   "Műfajok",
   "Genres",
   "Genres",
   "Géneros"
  ],
  "Artists": [
   "Előadók",
   "Interpreten",
   "Artistes",
   "Artistas"
  ],
  "Albums": [
   "Albumok",
   "Alben",
   "Albums",
   "Álbumes"
  ],
  "Songs": [
   "Dalok",
   "Titel",
   "Titres",
   "Canciones"
  ],
  "My mixes": [
   "Saját egyvelegek",
   "Meine Mixe",
   "Mes mix",
   "Mis mixes"
  ],
  "Recommended": [
   "Ajánlott",
   "Empfohlen",
   "Recommandations",
   "Recomendadas"
  ],
  "Recently played": [
   "Legutóbb lejátszott",
   "Vor Kurzem angehört",
   "Écouté récemment",
   "Reproducido recientemente"
  ],
  "Recently added to My Library": [
   "Nemrég hozzáadva a Saját könyvtárhoz",
   "Vor Kurzem zu \"Meine Musik\" hinzugefügt",
   "Ajouté récemment à ma biblio.",
   "Añadido recientemente a Mi música"
  ],
  "Thumbs up": [
   "Tetszik",
   "Mag ich",
   "J'aime",
   "Me gusta"
  ],
  "Last added": [
   "Utoljára hozzáadott",
   "Zuletzt hinzugefügt",
   "Derniers ajouts",
   "Añadidas recientemente"
  ]
 },
 "movies": {
  "Google Play": [
   "Google Play Filmek",
   "Google Play Movies",
   "Google Play Films",
   "Google Play Movies",
   "Google Play Movies"
  ],
  "Open navigation drawer": [
   "Navigációs fiók kinyitása",
   "Navigationsleiste öffnen",
   "Ouvrir le panneau de navigation",
   "Abrir control de navegación"
  ],
  "Watch Now": [
   "Megnézem",
   "Jetzt ansehen",
   "À voir",
   "Ver ahora"
  ],
  "My Movies": [
   "Saját filmek",
   "Meine Filme",
   "Mes films",
   "Mis películas"
  ],
  "My TV Shows": [
   "Saját tévéműsorok",
   "Meine TV-Sendungen",
   "Mes émissions télévisées",
   "Mis programas de TV"
  ],
  "On Device": [
   "Az eszközön",
   "Auf dem Gerät",
   "Sur l'appareil",
   "En el dispositivo"
  ],
  "Shop": [
   "Vásárlás",
   "Einkaufen",
   "Play Store",
   "Comprar"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Contact us": [
   "Kapcsolatfelvétel",
   "Kontakt",
   "Nous contacter",
   "Contacto"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Danos tu opinión"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Personal videos": [
   "Személyes videók",
   "Persönliche Videos",
   "Vidéos personnelles",
   "Vídeos personales"
  ],
  "Now Playing": [
   "Éppen lejátszott",
   "Läuft gerade",
   "En cours de lecture",
   "Reproduciendo"
  ],
  "Recommended for You": [
   "Önnek ajánlott",
   "Empfehlungen für mich",
   "Recommandés pour vous",
   "Recomendaciones personalizadas"
  ],
  "Nothing downloaded": [
   "Nincs letöltött tartalom",
   "Keine heruntergeladenen Inhalte",
   "Aucun contenu téléchargé",
   "No hay contenido descargado"
  ]
 },
 "books": {
  "Play Books": [
   "Play Könyvek",
   "Play Books",
   "Play Livres",
   "Play Books"
  ],
  "Read Now": [
   "Olvasson most",
   "Jetzt lesen",
   "À lire",
   "Leer ahora"
  ],
  "My Library": [
   "Könyvtáram",
   "Meine Bücher",
   "Ma bibliothèque",
   "Mi biblioteca"
  ],
  "Shop": [
   "Bolt",
   "Bücher kaufen",
   "Boutique",
   "Tienda"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help & feedback": [
   "Súgó és visszajelzés",
   "Hilfe und Feedback",
   "Aide et commentaires",
   "Ayuda y opiniones"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Sort": [
   "Rendezés",
   "Sortieren",
   "Trier",
   "Ordenar"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Recent": [
   "Legújabbak",
   "Neueste Bücher",
   "Livres achetés récemment",
   "Recientes"
  ],
  "SEE ALL": [
   "ÖSSZES",
   "Alle ansehen",
   "TOUT AFFICHER",
   "VER TODO"
  ],
  "All books": [
   "Az összes könyv",
   "Alle Bücher",
   "Tous les livres",
   "Todos los libros"
  ]
 },
 "games": {
  "Play Games": [
   "Play Játékok",
   "Play Games",
   "Play Jeux",
   "Play Games"
  ],
  "Open navigation drawer": [
   "Navigációs fiók kinyitása",
   "Navigationsleiste öffnen",
   "Ouvrir le panneau de navigation",
   "Abrir control de navegación"
  ],
  "Play Now": [
   "Játék indítása",
   "Jetzt spielen",
   "Jouer",
   "Reproducir ahora"
  ],
  "My Games": [
   "Saját játékok",
   "Meine Spiele",
   "Mes jeux",
   "Mis juegos"
  ],
  "My Activity": [
   "Saját tevékenység",
   "Meine Aktivitäten",
   "Mon activité",
   "Mi actividad"
  ],
  "Players": [
   "Játékosok",
   "Spieler",
   "Joueurs",
   "Jugadores"
  ],
  "Recommended Games": [
   "Ajánlott játékok",
   "Empfohlene Spiele",
   "Jeux recommandés",
   "Juegos recomendados"
  ],
  "Shop": [
   "Áruház",
   "Einkaufen",
   "Boutique",
   "Tienda"
  ],
  "Accounts": [
   "Fiókok",
   "Konten",
   "Comptes",
   "Cuentas"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Welcome!": [
   "Üdvözöljük!",
   "Willkommen!",
   "Bienvenue !",
   "Te damos la bienvenida"
  ],
  "Discover new games by seeing what your friends are playing on Google Play Games.": [
   "Fedezzen fel új játékokat azáltal, hogy megnézi, mivel játszanak ismerősei a Google Play Játékokban.",
   "Entdecken Sie neue Spiele, indem Sie sich ansehen, welche Spiele Ihre Freunde bei Google Play spielen.",
   "Découvrez de nouveaux jeux en voyant ceux auxquels jouent vos amis sur Google Play Jeux.",
   "Observa a qué juegan tus amigos en Google Play Games para descubrir nuevos juegos."
  ],
  "My games": [
   "Saját játékok",
   "Meine Spiele",
   "Mes jeux",
   "Mis juegos"
  ],
  "SEE MORE": [
   "TOVÁBBIAK",
   "Mehr",
   "PLUS",
   "VER MÁS"
  ],
  "FEATURED": [
   "KIEMELT",
   "Angesagt",
   "SÉLECTION",
   "DESTACADOS"
  ],
  "POPULAR": [
   "NÉPSZERŰ",
   "Beliebt",
   "POPULAIRES",
   "POPULARES"
  ],
  "POPULAR MULTIPLAYER": [
   "NÉPSZERŰ TÖBBSZEREPLŐS",
   "Beliebte Multiplayer",
   "JEUX MULTIJOUEURS POPULAIRES",
   "MULTIJUGADOR POPULARES"
  ],
  "PURCHASED": [
   "MEGVÁSÁROLVA",
   "Gekauft",
   "ACHETÉ",
   "COMPRADO"
  ],
  "FREE": [
   "INGYENES",
   "Kostenlos",
   "GRATUIT",
   "GRATIS"
  ],
  "Achievements": [
   "Megszerezhető jutalmak",
   "Erfolge",
   "Réussites",
   "Logros"
  ],
  "PLAY": [
   "JÁTÉK",
   "Spielen",
   "DÉMARRER",
   "JUGAR"
  ],
  "%1$d/%2$d unlocked": [
   "%2$d/%1$d megszerezve",
   "%1$d/%2$d erreicht",
   "%1$d/%2$d réussites déverrouillées",
   "%1$d/%2$d desbloqueados"
  ]
 }
};
