/* Generated by docs/stock-strings.py from docs/stock-strings.json and the hammerhead factory image. Do not edit. */
window.StockStrings = {
 "news": {
  "News & Weather": [
   "Hírek és időjárás",
   "News & Wetter",
   "Actualités et météo",
   "Noticias y tiempo"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Weather": [
   "Időjárás",
   "Wetter",
   "Météo",
   "Tiempo"
  ],
  "Humidity: %s%%": [
   "Páratartalom: %s%%",
   "Luftfeuchtigkeit: %s %%",
   "Humidité : %s%%",
   "Humedad: %s%%"
  ],
  "Wind: %1$s %2$s": [
   "Szélerősség: %1$s %2$s",
   "Wind: %1$s %2$s",
   "Vent : %1$s %2$s",
   "Viento: %1$s %2$s"
  ],
  "km/h": [
   "km/h",
   "km/h",
   "km/h",
   "km/h"
  ],
  "Mon": [
   "H",
   "M",
   "L",
   "L",
   "M"
  ],
  "Tue": [
   "K",
   "D",
   "M",
   "M",
   "T"
  ],
  "Wed": [
   "Sze",
   "M",
   "M",
   "X",
   "W"
  ],
  "Thu": [
   "Cs",
   "D",
   "J",
   "J",
   "T"
  ],
  "Fri": [
   "P",
   "F",
   "V",
   "V",
   "F"
  ],
  "Sat": [
   "Szo",
   "S",
   "S",
   "S",
   "S"
  ],
  "Sun": [
   "V",
   "S",
   "D",
   "D",
   "S"
  ]
 },
 "earth": {
  "Earth": [
   "Earth",
   "Earth",
   "Earth",
   "Earth"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Recherche Google",
   "Buscar"
  ],
  "Example: Pizza": [
   "példa: Pizza",
   "Beispiel: Pizza",
   "Exemple : boulangerie",
   "Ej.: Barcelona"
  ],
  "Reset to north": [
   "Visszaállítás északi irányba",
   "Auf Nordausrichtung zurücksetzen",
   "Rétablir l'orientation (nord en haut)",
   "Restablecer el Norte"
  ],
  "My location": [
   "Saját pozíció",
   "Mein Standort",
   "Ma position",
   "Mi ubicación"
  ],
  "Clear map": [
   "Térképjelölők törlése",
   "Karte leeren",
   "Effacer la carte",
   "Borrar mapa"
  ],
  "Share": [
   "Megosztás",
   "Teilen",
   "Partager",
   "Compartir"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Comentarios"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Tutorial": [
   "Útmutató",
   "Anleitung",
   "Didacticiel",
   "Tutorial"
  ]
 },
 "gsettings": {
  "Google Settings": [
   "Google-beállítások",
   "Google Einstellungen",
   "Paramètres Google",
   "Ajustes de Google"
  ],
  "Apps with Google+ Sign-In": [
   "Társított alkalmazások",
   "Verbundene Apps",
   "Applications associées",
   "Aplicaciones conectadas",
   "Connected apps"
  ],
  "Google+": [
   "Google+",
   "Google+",
   "Google+",
   "Google+"
  ],
  "Play Games": [
   "Play Játékok",
   "Play Games",
   "Play Jeux",
   "Play Games"
  ],
  "Location": [
   "Hely",
   "Standort",
   "Position",
   "Ubicación"
  ],
  "Search & Now": [
   "Keresés és Asszisztens",
   "Suche & Google Now",
   "Recherche et Now",
   "Búsqueda y Google Now"
  ],
  "Ads": [
   "Hirdetések",
   "Anzeigen",
   "Annonces",
   "Anuncios"
  ],
  "Verify apps": [
   "Alkalmazások ellenőrzése",
   "Apps bestätigen",
   "Vérifier les applications",
   "Verificar aplicaciones"
  ],
  "Android Device Manager": [
   "Android Eszközkezelő",
   "Android Geräte-Manager",
   "Gestionnaire d'appareils Android",
   "Administrador de dispositivos"
  ],
  "Drive apps": [
   "Drive apps",
   "Drive apps",
   "Drive apps",
   "Drive apps"
  ]
 },
 "google": {
  "Card menu": [
   "Kártya menü",
   "Kartenmenü",
   "Menu de la carte",
   "Menú de la tarjeta"
  ],
  "View in Calendar": [
   "Megtekintés a Naptárban",
   "Im Kalender ansehen",
   "Afficher dans l'agenda",
   "Ver en Calendar"
  ],
  "More": [
   "Továbbiak",
   "Mehr",
   "Plus",
   "Más"
  ],
  "Reminders": [
   "Emlékeztetők",
   "Erinnerungen",
   "Rappels",
   "Recordatorios"
  ],
  "Train Google Now": [
   "A Google Asszisztens betanítása",
   "Interessen in Google Now festlegen",
   "Améliorer Google Now",
   "Enseñar a Google Now"
  ],
  "Menu": [
   "Menü",
   "Menü",
   "Menu",
   "Menú"
  ],
  "Tap to speak": [
   "Koppintson a beszédhez",
   "Zum Sprechen tippen",
   "Appuyez pour parler",
   "Toca para hablar."
  ],
  "Speak now": [
   "Most beszéljen",
   "Sprechen",
   "Parlez maintenant",
   "Habla ahora"
  ],
  "Didn't catch that. Try speaking again.": [
   "Nem sikerült értelmezni. Mondja ki újra.",
   "Das wurde nicht verstanden. Bitte sprechen Sie erneut.",
   "Je n'ai pas compris. Veuillez répéter.",
   "No lo he entendido. Prueba a decirlo otra vez."
  ],
  "Upcoming": [
   "Aktuálisak",
   "Demnächst",
   "À venir",
   "Próximos"
  ],
  "Past": [
   "Korábbiak",
   "Vergangene",
   "Passés",
   "Anteriores"
  ],
  "Add a title": [
   "Adjon hozzá címet",
   "Titel hinzufügen",
   "Ajouter un titre",
   "Añade un título"
  ],
  "Set": [
   "Beállítás",
   "Festlegen",
   "Définir",
   "Definir"
  ],
  "Cancel": [
   "Mégse",
   "Abbrechen",
   "Annuler",
   "Cancelar"
  ],
  "When": [
   "Időpont",
   "Wann",
   "Date et heure",
   "Cuándo"
  ],
  "Where": [
   "Helyszín",
   "Wo",
   "Lieu",
   "Dónde"
  ],
  "One-time": [
   "Egyszeri",
   "Einmal",
   "Une seule fois",
   "Una vez"
  ],
  "Today, %1$s": [
   "Ma, %1$s",
   "Heute um %1$s",
   "Aujourd'hui à %1$s",
   "Hoy a las %1$s"
  ],
  "Tomorrow, %1$s": [
   "Holnap, %1$s",
   "Morgen um %1$s Uhr",
   "Demain à %1$s",
   "Mañana a las %1$s"
  ],
  "Delete this reminder?": [
   "Törli ezt az emlékeztetőt?",
   "Diese Erinnerung löschen?",
   "Supprimer ce rappel ?",
   "¿Eliminar este recordatorio?"
  ],
  "Delete": [
   "Törlés",
   "Löschen",
   "Supprimer",
   "Eliminar"
  ],
  "Edit reminder": [
   "Emlékeztető szerkesztése",
   "Erinnerung bearbeiten",
   "Modifier le rappel",
   "Editar recordatorio"
  ],
  "No upcoming reminders": [
   "Nincsenek közelgő emlékeztetők. Emlékeztető beállításához koppintson a „+” gombra.",
   "Sie haben keine anstehenden Erinnerungen. Um eine Erinnerung einzurichten, tippen Sie auf die Schaltfläche \"+\".",
   "Vous n'avez aucun rappel à venir. Pour définir un rappel, appuyez sur le bouton \"+\".",
   "No hay próximos recordatorios. Para añadir un recordatorio, toca el botón +.",
   "You don't have any upcoming reminders. To set a reminder, tap on the '+' button."
  ],
  "Reminder saved": [
   "Emlékeztető mentve",
   "Erinnerung gespeichert",
   "Rappel enregistré.",
   "Recordatorio guardado"
  ],
  "Weather units": [
   "Mértékegységek az időjáráshoz",
   "Wettereinheiten",
   "Système d'unités de mesure météorologiques",
   "Unidades de temperatura"
  ],
  "Celsius": [
   "Celsius",
   "Celsius",
   "Celsius",
   "Grados Celsius"
  ],
  "Fahrenheit": [
   "Fahrenheit",
   "Fahrenheit",
   "Fahrenheit",
   "Grados Fahrenheit"
  ],
  "Reminder list": [
   "Emlékeztetők",
   "Erinnerungen",
   "Rappels",
   "Recordatorios",
   "Reminders"
  ],
  "Day 0": [
   "Ma",
   "Heute",
   "Aujourd'hui",
   "Hoy",
   "Today"
  ],
  "Day 1": [
   "Holnap",
   "Morgen",
   "Demain",
   "Mañana",
   "Tomorrow"
  ],
  "Day 2": [
   "Hétvége",
   "Wochenende",
   "Week-end",
   "Fin de semana",
   "Weekend"
  ],
  "Day 3": [
   "Dátum beállítása…",
   "Datum festlegen...",
   "Définir la date…",
   "Establecer fecha…",
   "Set date…"
  ],
  "Time 0": [
   "Reggel",
   "Morgens",
   "Matin",
   "Por la mañana",
   "Morning"
  ],
  "Time 1": [
   "Délután",
   "Nachmittags",
   "Après-midi",
   "Al mediodía",
   "Afternoon"
  ],
  "Time 2": [
   "Este",
   "Abends",
   "Soirée",
   "Por la tarde",
   "Evening"
  ],
  "Time 3": [
   "Éjszaka",
   "Nachts",
   "Nuit",
   "Por la noche",
   "Night"
  ],
  "Time 4": [
   "Egész nap",
   "Ganztägig",
   "Toute la journée",
   "Todo el día",
   "All day"
  ],
  "Time 5": [
   "Idő beállítása…",
   "Uhrzeit festlegen…",
   "Définir l'heure…",
   "Establecer hora…",
   "Set time…"
  ]
 },
 "maps": {
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Directions": [
   "Útvonalterv",
   "Route",
   "Itinéraire",
   "Indicaciones"
  ],
  "Traffic": [
   "Forgalom",
   "Verkehrslage",
   "Trafic",
   "Tráfico"
  ],
  "Public transit": [
   "Tömegközlekedés",
   "Öffentliche Verkehrsmittel",
   "Transports en commun",
   "Transporte público"
  ],
  "Bicycling": [
   "Kerékpárral",
   "Fahrrad",
   "Vélo",
   "Rutas en bicicleta"
  ],
  "Satellite": [
   "Műhold",
   "Satellit",
   "Satellite",
   "Satélite"
  ],
  "Google Earth": [
   "Google Earth",
   "Google Earth",
   "Google Earth",
   "Google Earth"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Configuración"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Enviar comentarios"
  ],
  "Move to my location": [
   "Ugrás a saját pozíciómra",
   "Zu meinem Standort wechseln",
   "Centrer sur ma position",
   "Mover a mi ubicación"
  ],
  "Menu": [
   "Menü",
   "Menü",
   "Menu",
   "Menú"
  ]
 },
 "keep": {
  "Keep": [
   "Keep",
   "Keep",
   "Keep",
   "Keep"
  ],
  "Add quick note": [
   "Rövid üzenet hozzáadása",
   "Kurze Notiz hinzufügen",
   "Ajouter une note rapide",
   "Añadir nota rápida"
  ],
  "New note": [
   "Új jegyzet",
   "Neue Notiz",
   "Nouvelle note",
   "Nueva nota"
  ],
  "New list": [
   "Új lista",
   "Neue Liste",
   "Nouvelle liste",
   "Lista nueva"
  ],
  "New recording": [
   "Új felvétel",
   "Neue Aufnahme",
   "Nouvel enregistrement",
   "Nueva grabación"
  ],
  "New photo": [
   "Új fotó",
   "Neues Foto",
   "Nouvelle photo",
   "Foto nueva"
  ],
  "Take a note": [
   "Jegyzetelés",
   "Notiz schreiben",
   "Rédiger une note",
   "Tomar una nota"
  ],
  "There are no archived notes": [
   "Nincsenek archivált jegyzetek",
   "Keine archivierten Notizen vorhanden",
   "Aucune note archivée",
   "No hay notas archivadas"
  ],
  "Create a reminder": [
   "Emlékeztető létrehozása",
   "Erinnerung erstellen",
   "Créer un rappel",
   "Crear un recordatorio"
  ],
  "Notes": [
   "Jegyzetek",
   "Notizen",
   "Notes",
   "Notas"
  ],
  "Archive (drawer)": [
   "Archívum",
   "Archiv",
   "Notes archivées",
   "Archivadas",
   "Archive"
  ],
  "Reminders": [
   "Emlékeztetők",
   "Erinnerungen",
   "Rappels",
   "Recordatorios"
  ],
  "Open navigation drawer": [
   "Navigációs fiók kinyitása",
   "Navigationsleiste öffnen",
   "Ouvrir le panneau de navigation",
   "Abrir control de navegación"
  ],
  "Note color…": [
   "Jegyzet színe…",
   "Notizfarbe…",
   "Couleur de la note…",
   "Color de la nota…"
  ],
  "Add picture": [
   "Kép hozzáadása",
   "Bild hinzufügen",
   "Ajouter une image",
   "Añadir imagen"
  ],
  "Archive": [
   "Archiválás",
   "Archivieren",
   "Archiver",
   "Archivar"
  ],
  "Unarchive": [
   "Archiválás visszavonása",
   "Dearchivieren",
   "Annuler l'archivage",
   "No archivar"
  ],
  "Delete": [
   "Törlés",
   "Löschen",
   "Supprimer",
   "Eliminar"
  ],
  "Show checkboxes": [
   "Jelölőnégyzetek megjelenítése",
   "Kontrollkästchen anzeigen",
   "Afficher les cases à cocher",
   "Mostrar casillas de verificación"
  ],
  "Share…": [
   "Megosztás…",
   "Teilen…",
   "Partager…",
   "Compartir…"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Single-column view": [
   "Egyoszlopos nézet",
   "Ansicht mit einer Spalte",
   "Vue avec colonne unique",
   "Vista de una columna"
  ],
  "Multi-column view": [
   "Többoszlopos nézet",
   "Ansicht mit mehreren Spalten",
   "Vue multicolonne",
   "Vista de varias columnas"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "List item": [
   "Listaelem",
   "Listeneintrag",
   "Élément de liste",
   "Elemento de lista"
  ],
  "Hide checkboxes": [
   "Jelölőnégyzetek elrejtése",
   "Kontrollkästchen ausblenden",
   "Masquer les cases à cocher",
   "Ocultar casillas de verificación"
  ],
  "Delete checked items?": [
   "Törli a kijelölt elemeket?",
   "Aktivierte Elemente löschen?",
   "Supprimer les éléments sélectionnés ?",
   "¿Eliminar elementos tachados?"
  ],
  "Keep (button)": [
   "Megőrzés",
   "Beibehalten",
   "Conserver",
   "Mantener",
   "Keep"
  ],
  "Delete (button)": [
   "Törlés",
   "Löschen",
   "Supprimer",
   "Eliminar",
   "Delete"
  ],
  "Remove photo?": [
   "Eltávolítja ezt a fotót?",
   "Dieses Foto entfernen?",
   "Supprimer cette photo ?",
   "¿Eliminar esta foto?",
   "Remove this photo?"
  ],
  "Cancel": [
   "Mégse",
   "Abbrechen",
   "Annuler",
   "Cancelar"
  ],
  "Take photo": [
   "Fotó készítése",
   "Foto aufnehmen",
   "Prendre une photo",
   "Hacer foto"
  ],
  "Choose photo": [
   "Fotó kiválasztása",
   "Foto auswählen",
   "Sélectionner une photo",
   "Elegir foto"
  ]
 },
 "youtube": {
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Feedback": [
   "Visszajelzés",
   "Feedback",
   "Commentaires",
   "Danos tu opinión"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Uploads": [
   "Feltöltések",
   "Uploads",
   "Vidéos mises en ligne",
   "Vídeos subidos"
  ],
  "History": [
   "Előzmények",
   "Verlauf",
   "Historique",
   "Historial"
  ],
  "Favorites": [
   "Kedvencek",
   "Favoriten",
   "Favoris",
   "Favoritos"
  ],
  "Playlists": [
   "Lejátszási listák",
   "Playlists",
   "Playlists",
   "Listas"
  ],
  "Watch later": [
   "Megnézendő videók",
   "Später ansehen",
   "À regarder plus tard",
   "Ver más tarde"
  ],
  "Subscriptions": [
   "Előfizetések",
   "Abos",
   "Abonnements",
   "Suscripciones"
  ],
  "What to watch": [
   "Megtekintendő videók",
   "Empfohlene Videos",
   "Vidéos à regarder",
   "Actividad"
  ],
  "My subscriptions": [
   "Feliratkozásaim",
   "Meine Abos",
   "Mes abonnements",
   "Mis suscripciones"
  ],
  "Browse channels": [
   "Csatornák tallózása",
   "Kanäle finden",
   "Parcourir les chaînes",
   "Buscar canales"
  ],
  "From YouTube": [
   "A YouTube-ról",
   "Beliebt auf YouTube",
   "Sur YouTube",
   "Visto en YouTube"
  ],
  "Recommended": [
   "Ajánlott",
   "Empfohlen",
   "Recommandations",
   "Recomendados"
  ],
  "Trending": [
   "Felkapott",
   "Trends",
   "Tendances",
   "Tendencias"
  ],
  "Open guide": [
   "A segéd megnyitása",
   "Anleitung öffnen",
   "Ouvrir le guide",
   "Abrir guía"
  ],
  "More": [
   "Több",
   "Mehr",
   "Plus",
   "Más"
  ],
  "Like": [
   "Tetszik",
   "Mag ich",
   "J'aime",
   "Me gusta"
  ],
  "Dislike": [
   "Nem tetszik",
   "Mag ich nicht",
   "Je n'aime pas",
   "No me gusta"
  ],
  "Search YouTube": [
   "Keresés a YouTube-on",
   "In YouTube suchen",
   "Rechercher sur YouTube",
   "Buscar..."
  ],
  "No videos found": [
   "Nem található videó",
   "Keine Videos gefunden",
   "Aucune vidéo n'a été trouvée.",
   "No se ha encontrado ningún vídeo."
  ],
  "Videos": [
   "Videók",
   "Videos",
   "Vidéos",
   "Vídeos"
  ],
  "All time": [
   "Mindenkori",
   "Gesamte Zeit",
   "Toutes périodes",
   "Todos"
  ],
  "Clear query": [
   "Lekérdezés törlése",
   "Anfrage löschen",
   "Effacer la requête",
   "Borrar consulta"
  ]
 },
 "drive": {
  "My Drive": [
   "Saját meghajtó",
   "Meine Ablage",
   "Mon Drive",
   "Mi unidad"
  ],
  "Shared with me": [
   "Velem megosztottak",
   "Für mich freigegeben",
   "Partagés avec moi",
   "Compartido conmigo"
  ],
  "Starred": [
   "Csillagozott elemek",
   "Markiert",
   "Suivis",
   "Destacado"
  ],
  "Recent": [
   "Legutóbbi",
   "Zuletzt geöffnet",
   "Récents",
   "Reciente"
  ],
  "Offline": [
   "Offline",
   "Offline",
   "Hors connexion",
   "Sin conexión"
  ],
  "Uploads": [
   "Feltöltések",
   "Uploads",
   "Importations",
   "Subidas"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "View as Grid": [
   "Rácsnézet",
   "Als Raster anzeigen",
   "Grille",
   "Ver como cuadrícula"
  ],
  "Add new": [
   "Új hozzáadása",
   "Neu hinzufügen",
   "Ajouter",
   "Nuevo"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Filter by": [
   "Szűrés:",
   "Filtern nach",
   "Filtrer par",
   "Filtrar por"
  ],
  "Sort by": [
   "Rendezési szempont:",
   "Sortieren nach",
   "Trier par",
   "Ordenar por"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Product Tour": [
   "Termékbemutató",
   "Produkttour",
   "Visite guidée",
   "Visita del producto"
  ],
  "Open navigation drawer": [
   "Navigálási fiók megnyitása",
   "Navigationsleiste öffnen",
   "Ouvrir le panneau de navigation",
   "Abrir control de navegación"
  ],
  "Show item properties": [
   "Elemtulajdonságok megjelenítése",
   "Dokumenteigenschaften anzeigen",
   "Afficher les propriétés de l'élément",
   "Mostrar propiedades de los elementos"
  ],
  "Modified: %s": [
   "Módosítva: %s",
   "Geändert: %s",
   "Modifié : %s",
   "Modificado: %s"
  ],
  "Today": [
   "Ma",
   "Heute",
   "Aujourd'hui",
   "Hoy"
  ],
  "Yesterday": [
   "Tegnap",
   "Gestern",
   "Hier",
   "Ayer"
  ],
  "Earlier this Week": [
   "Korábban a héten",
   "In dieser Woche",
   "Cette semaine",
   "Anteriormente esta semana"
  ],
  "Earlier this Month": [
   "Korábban a hónapban",
   "In diesem Monat",
   "Ce mois-ci",
   "Anteriormente este mes"
  ],
  "Older": [
   "Régebbiek",
   "Ältere",
   "Plus anciens",
   "Más antiguos"
  ],
  "Search: \"%s\"": [
   "Keresés: \"%s\"",
   "Suchen: %s",
   "Rechercher : \"%s\"",
   "Buscar: \"%s\""
  ],
  "No Items": [
   "Nincsenek elemek",
   "Keine Dokumente",
   "Aucun élément",
   "No hay documentos"
  ]
 },
 "gplus": {
  "Home": [
   "Kezdőlap",
   "Übersicht",
   "Accueil",
   "Inicio"
  ],
  "Photo": [
   "Fotó",
   "Foto",
   "Photo",
   "Foto"
  ],
  "Location": [
   "Hely",
   "Standort",
   "Position",
   "Ubicación"
  ],
  "Write": [
   "Írás",
   "Schreiben",
   "Rédiger",
   "Escribir"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer un commentaire",
   "Danos tu opinión"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Sign out": [
   "Kijelentkezés",
   "Abmelden",
   "Déconnexion",
   "Cerrar sesión"
  ]
 },
 "music": {
  "Play Music": [
   "Google Play Zene",
   "Google Play Music",
   "Google Play Musique",
   "Google Play Music",
   "Google Play Music"
  ],
  "Listen Now": [
   "Zeneajánló",
   "Jetzt anhören",
   "À écouter",
   "Escuchar ahora"
  ],
  "My Library": [
   "Saját könyvtár",
   "Meine Musik",
   "Ma bibliothèque",
   "Mi música"
  ],
  "Playlists": [
   "Lejátszási listák",
   "Playlists",
   "Playlists",
   "Listas de reproducción"
  ],
  "Instant Mixes": [
   "Instant egyvelegek",
   "Schnellmixe",
   "Mix instantanés",
   "Mixes instantáneos"
  ],
  "Shop": [
   "Vásárlás",
   "Einkaufen",
   "Acheter",
   "Tienda"
  ],
  "All music": [
   "Minden zene",
   "Alle Musiktitel",
   "Toute la musique",
   "Toda la música"
  ],
  "Search": [
   "Keresés",
   "Suchen",
   "Rechercher",
   "Buscar"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Enviar comentarios"
  ],
  "Genres": [
   "Műfajok",
   "Genres",
   "Genres",
   "Géneros"
  ],
  "Artists": [
   "Előadók",
   "Interpreten",
   "Artistes",
   "Artistas"
  ],
  "Albums": [
   "Albumok",
   "Alben",
   "Albums",
   "Álbumes"
  ],
  "Songs": [
   "Dalok",
   "Titel",
   "Titres",
   "Canciones"
  ],
  "My mixes": [
   "Saját egyvelegek",
   "Meine Mixe",
   "Mes mix",
   "Mis mixes"
  ],
  "Recommended": [
   "Ajánlott",
   "Empfohlen",
   "Recommandations",
   "Recomendadas"
  ],
  "Recently played": [
   "Legutóbb lejátszott",
   "Vor Kurzem angehört",
   "Écouté récemment",
   "Reproducido recientemente"
  ],
  "Recently added to My Library": [
   "Nemrég hozzáadva a Saját könyvtárhoz",
   "Vor Kurzem zu \"Meine Musik\" hinzugefügt",
   "Ajouté récemment à ma biblio.",
   "Añadido recientemente a Mi música"
  ],
  "Thumbs up": [
   "Tetszik",
   "Mag ich",
   "J'aime",
   "Me gusta"
  ],
  "Last added": [
   "Utoljára hozzáadott",
   "Zuletzt hinzugefügt",
   "Derniers ajouts",
   "Añadidas recientemente"
  ],
  "Search music": [
   "Zene keresése",
   "Musik suchen",
   "Rechercher de la musique",
   "Buscar música"
  ],
  "%d MORE": [
   "%d TOVÁBBI",
   "%d weitere",
   "%d autres",
   "%d MÁS"
  ],
  "No results found.": [
   "Nincs találat.",
   "Keine Ergebnisse gefunden",
   "Aucun résultat trouvé.",
   "No se han encontrado resultados."
  ],
  "Clear query": [
   "Clear query",
   "Clear query",
   "Clear query",
   "Clear query"
  ]
 },
 "movies": {
  "Google Play": [
   "Google Play",
   "Google Play",
   "Google Play",
   "Google Play"
  ],
  "Open navigation drawer": [
   "Navigációs fiók kinyitása",
   "Navigationsleiste öffnen",
   "Ouvrir le panneau de navigation",
   "Abrir control de navegación"
  ],
  "Watch Now": [
   "Megnézem",
   "Jetzt ansehen",
   "À voir",
   "Ver ahora"
  ],
  "My Movies": [
   "Saját filmek",
   "Meine Filme",
   "Mes films",
   "Mis películas"
  ],
  "My TV Shows": [
   "Saját tévéműsorok",
   "Meine TV-Sendungen",
   "Mes émissions télévisées",
   "Mis programas de TV"
  ],
  "On Device": [
   "Az eszközön",
   "Auf dem Gerät",
   "Sur l'appareil",
   "En el dispositivo"
  ],
  "Shop": [
   "Vásárlás",
   "Einkaufen",
   "Play Store",
   "Comprar"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Contact us": [
   "Kapcsolatfelvétel",
   "Kontakt",
   "Nous contacter",
   "Contacto"
  ],
  "Send feedback": [
   "Visszajelzés küldése",
   "Feedback geben",
   "Envoyer des commentaires",
   "Danos tu opinión"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Personal videos": [
   "Személyes videók",
   "Persönliche Videos",
   "Vidéos personnelles",
   "Vídeos personales"
  ],
  "Now Playing": [
   "Éppen lejátszott",
   "Läuft gerade",
   "En cours de lecture",
   "Reproduciendo"
  ],
  "Recommended for You": [
   "Önnek ajánlott",
   "Empfehlungen für mich",
   "Recommandés pour vous",
   "Recomendaciones personalizadas"
  ],
  "Nothing downloaded": [
   "Nincs letöltött tartalom",
   "Keine heruntergeladenen Inhalte",
   "Aucun contenu téléchargé",
   "No hay contenido descargado"
  ],
  "Search for movies & shows": [
   "Filmek és sorozatok keresése",
   "Nach Filmen & Sendungen suchen",
   "Rechercher films et émissions",
   "Buscar películas y programas"
  ],
  "Clear query": [
   "Lekérdezés törlése",
   "Anfrage löschen",
   "Effacer la requête",
   "Borrar consulta"
  ]
 },
 "books": {
  "Play Books": [
   "Play Könyvek",
   "Play Books",
   "Play Livres",
   "Play Books"
  ],
  "Read Now": [
   "Olvasson most",
   "Jetzt lesen",
   "À lire",
   "Leer ahora"
  ],
  "My Library": [
   "Könyvtáram",
   "Meine Bücher",
   "Ma bibliothèque",
   "Mi biblioteca"
  ],
  "Shop": [
   "Bolt",
   "Bücher kaufen",
   "Boutique",
   "Tienda"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help & feedback": [
   "Súgó és visszajelzés",
   "Hilfe und Feedback",
   "Aide et commentaires",
   "Ayuda y opiniones"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Sort": [
   "Rendezés",
   "Sortieren",
   "Trier",
   "Ordenar"
  ],
  "Refresh": [
   "Frissítés",
   "Aktualisieren",
   "Actualiser",
   "Actualizar"
  ],
  "Recent": [
   "Legújabbak",
   "Neueste Bücher",
   "Livres achetés récemment",
   "Recientes"
  ],
  "SEE ALL": [
   "ÖSSZES",
   "Alle ansehen",
   "TOUT AFFICHER",
   "VER TODO"
  ],
  "All books": [
   "Az összes könyv",
   "Alle Bücher",
   "Tous les livres",
   "Todos los libros"
  ],
  "Search for books": [
   "Könyvek keresése",
   "Nach Büchern suchen",
   "Rechercher livres",
   "Buscar libros"
  ],
  "Search online": [
   "Keresés online",
   "Online suchen",
   "Rechercher en ligne",
   "Buscar online"
  ],
  "Clear query": [
   "Lekérdezés törlése",
   "Anfrage löschen",
   "Effacer la requête",
   "Borrar consulta"
  ]
 },
 "games": {
  "Play Games": [
   "Play Játékok",
   "Play Games",
   "Play Jeux",
   "Play Games"
  ],
  "Open navigation drawer": [
   "Navigációs fiók kinyitása",
   "Navigationsleiste öffnen",
   "Ouvrir le panneau de navigation",
   "Abrir control de navegación"
  ],
  "Play Now": [
   "Játék indítása",
   "Jetzt spielen",
   "Jouer",
   "Reproducir ahora"
  ],
  "My Games": [
   "Saját játékok",
   "Meine Spiele",
   "Mes jeux",
   "Mis juegos"
  ],
  "My Activity": [
   "Saját tevékenység",
   "Meine Aktivitäten",
   "Mon activité",
   "Mi actividad"
  ],
  "Players": [
   "Játékosok",
   "Spieler",
   "Joueurs",
   "Jugadores"
  ],
  "Recommended Games": [
   "Ajánlott játékok",
   "Empfohlene Spiele",
   "Jeux recommandés",
   "Juegos recomendados"
  ],
  "Shop": [
   "Áruház",
   "Einkaufen",
   "Boutique",
   "Tienda"
  ],
  "Accounts": [
   "Fiókok",
   "Konten",
   "Comptes",
   "Cuentas"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "Welcome!": [
   "Üdvözöljük!",
   "Willkommen!",
   "Bienvenue !",
   "Te damos la bienvenida"
  ],
  "Discover new games by seeing what your friends are playing on Google Play Games.": [
   "Fedezzen fel új játékokat azáltal, hogy megnézi, mivel játszanak ismerősei a Google Play Játékokban.",
   "Entdecken Sie neue Spiele, indem Sie sich ansehen, welche Spiele Ihre Freunde bei Google Play spielen.",
   "Découvrez de nouveaux jeux en voyant ceux auxquels jouent vos amis sur Google Play Jeux.",
   "Observa a qué juegan tus amigos en Google Play Games para descubrir nuevos juegos."
  ],
  "My games": [
   "Saját játékok",
   "Meine Spiele",
   "Mes jeux",
   "Mis juegos"
  ],
  "SEE MORE": [
   "TOVÁBBIAK",
   "Mehr",
   "PLUS",
   "VER MÁS"
  ],
  "FEATURED": [
   "KIEMELT",
   "Angesagt",
   "SÉLECTION",
   "DESTACADOS"
  ],
  "POPULAR": [
   "NÉPSZERŰ",
   "Beliebt",
   "POPULAIRES",
   "POPULARES"
  ],
  "POPULAR MULTIPLAYER": [
   "NÉPSZERŰ TÖBBSZEREPLŐS",
   "Beliebte Multiplayer",
   "JEUX MULTIJOUEURS POPULAIRES",
   "MULTIJUGADOR POPULARES"
  ],
  "PURCHASED": [
   "MEGVÁSÁROLVA",
   "Gekauft",
   "ACHETÉ",
   "COMPRADO"
  ],
  "FREE": [
   "INGYENES",
   "Kostenlos",
   "GRATUIT",
   "GRATIS"
  ],
  "Achievements": [
   "Megszerezhető jutalmak",
   "Erfolge",
   "Réussites",
   "Logros"
  ],
  "PLAY": [
   "JÁTÉK",
   "Spielen",
   "DÉMARRER",
   "JUGAR"
  ],
  "%1$d/%2$d unlocked": [
   "%2$d/%1$d megszerezve",
   "%1$d/%2$d erreicht",
   "%1$d/%2$d réussites déverrouillées",
   "%1$d/%2$d desbloqueados"
  ]
 },
 "newsstand": {
  "Read Now": [
   "Olvasson most",
   "Jetzt lesen",
   "À lire",
   "Leer ahora"
  ],
  "My News": [
   "Hírek",
   "Meine Nachrichten",
   "Mes actualités",
   "Mis noticias"
  ],
  "My Magazines": [
   "Saját Magazinok",
   "Meine Zeitschriften",
   "Mes magazines",
   "Mis revistas"
  ],
  "Saved": [
   "Könyvjelzők",
   "Lesezeichen",
   "Favoris",
   "Marcadores",
   "Bookmarks"
  ],
  "Explore": [
   "Felfedezés",
   "Entdecken",
   "Découvrir",
   "Explorar"
  ],
  "Search": [
   "Keresés",
   "Suche",
   "Rechercher",
   "Buscar"
  ],
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ],
  "On device only": [
   "Csak az eszközön",
   "Nur auf Gerät",
   "Sur cet appareil uniquement",
   "Solo en dispositivo"
  ]
 },
 "chrome": {
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "Navigation error suggestions": [
   "Navigálási hibákkal kapcsolatos javaslatok",
   "Vorschläge bei Navigationsfehlern",
   "Suggestions en cas d'erreur de navigation",
   "Sugerencias para errores de navegación"
  ],
  "Navigation error summary": [
   "Javaslatok megjelenítése, ha egy internetcímet nem lehet feloldani, vagy nem lehet kapcsolódni",
   "Vorschläge einblenden, wenn eine Webadresse nicht gefunden oder keine Verbindung hergestellt werden kann",
   "Afficher d'autres solutions lorsqu'une adresse Web ne peut pas être résolue ou qu'une connexion ne peut pas être établie",
   "Se muestran sugerencias cuando no se puede resolver una dirección web o no se puede establecer conexión.",
   "Show suggestions when a web address does not resolve or a connection cannot be made"
  ],
  "Search and URL suggestions": [
   "Keresési és URL-javaslatok",
   "Such- und URL-Vorschläge",
   "Suggestions de recherche et d'URL",
   "Sugerencias de URL y de búsqueda"
  ],
  "Search suggestions summary": [
   "Használjon következtetési szolgáltatást a kapcsolódó lekérdezések és népszerű webhelyek megjelenítéséhez a címsávba történő gépelés során.",
   "Während der Eingabe in die Adressleiste mithilfe eines Vervollständigungsdienstes verwandte Suchanfragen und beliebte Websites einblenden",
   "Utiliser un service de prédiction pour suggérer des requêtes associées et des sites populaires quand vous saisissez des termes dans la barre d'adresse",
   "Usar un servicio de predicción para mostrar consultas relacionadas y sitios web populares a medida que escribes en la barra de direcciones",
   "Use a prediction service to show related queries and popular websites as you type in the address bar"
  ],
  "Network action predictions": [
   "Hálózati műveletekkel kapcsolatos várható kifejezések",
   "Prognose von Netzwerkaktionen",
   "Prédictions des actions de réseau",
   "Predicciones de acciones de red"
  ],
  "Network predictions summary": [
   "Oldal betöltési idejének javítása",
   "Seiten schneller laden",
   "Améliorer les performances de chargement des pages",
   "Mejorar rendimiento de carga de páginas",
   "Improve page load performance"
  ],
  "Usage and crash reports": [
   "Használati és hibabejelentések",
   "Nutzungs- und Absturzberichte",
   "Statistiques d'utilisation et rapports d'erreur",
   "Informes de uso y de errores"
  ],
  "Always send": [
   "Mindig küldjön",
   "Immer senden",
   "Toujours envoyer",
   "Enviar siempre"
  ],
  "Only send on Wi-Fi": [
   "Csak Wi-Fin keresztül küldjön",
   "Nur bei WLAN senden",
   "Envoyer via Wi-Fi uniquement",
   "Solo enviar en Wi-Fi"
  ],
  "Never send": [
   "Soha ne küldjön",
   "Nie senden",
   "Ne jamais envoyer",
   "No enviar nunca"
  ],
  "'Do Not Track'": [
   "„Nincs nyomon követés”",
   "\"Do Not Track\"",
   "Interdire le suivi",
   "Solicitudes de no seguimiento"
  ],
  "Off": [
   "Kikapcsolva",
   "Aus",
   "Désactivé",
   "No"
  ],
  "On": [
   "Be",
   "An",
   "Activ.",
   "Sí"
  ],
  "Clear browsing data": [
   "Böngészési adatok törl.",
   "Browserdaten löschen",
   "Effacer données navigation",
   "Borrar datos de navegación"
  ],
  "Clear browsing history": [
   "Előzmények törlése",
   "Browserverlauf löschen",
   "Effacer historique navigation",
   "Borrar historial de navegación"
  ],
  "Clear the cache": [
   "Gyorsítótár ürítése",
   "Cache leeren",
   "Vider le cache",
   "Borrar la caché"
  ],
  "Clear cookies, site data": [
   "Cookie-k, webhelyek törl",
   "Cookies/Daten löschen",
   "Eff. cookies/données site",
   "Cookies y datos sitios"
  ],
  "Clear saved passwords": [
   "Mentett jelszavak törlése",
   "Passwörter löschen",
   "Eff. mots passe enregistrés",
   "Borrar contraseñas guardadas"
  ],
  "Clear autofill data": [
   "Aut. kitöltési adatok törl.",
   "AutoFill-Daten löschen",
   "Eff. données saisie auto",
   "Borrar datos de autocomp"
  ],
  "Clear": [
   "Törlés",
   "Löschen",
   "Effacer",
   "Borrar"
  ],
  "Clearing browsing data": [
   "Böngészési adatok törlése",
   "Browserdaten löschen",
   "Effacement des données de navigation en cours…",
   "Borrando datos de navegación"
  ],
  "Please wait…": [
   "Kérjük, várjon...",
   "Bitte warten...",
   "Veuillez patienter…",
   "Por favor, espera…"
  ],
  "Application version": [
   "Alkalmazás verziószáma",
   "App-Version",
   "Version de l'application",
   "Versión de la aplicación"
  ],
  "Operating system": [
   "Operációs rendszer",
   "Betriebssystem",
   "Système d'exploitation",
   "Sistema operativo"
  ],
  "Legal information": [
   "Jogi információk",
   "Rechtliche Hinweise",
   "Informations légales",
   "Información legal"
  ],
  "Cancel": [
   "Mégse",
   "Abbruch",
   "Annuler",
   "Cancelar"
  ],
  "Basics": [
   "Alapok",
   "Grundeinstellungen",
   "Général",
   "Básicos"
  ],
  "Advanced": [
   "Haladó",
   "Erweiterte Einstellungen",
   "Avancés",
   "Avanzados"
  ],
  "Search engine": [
   "Keresőmotor",
   "Suchmaschine",
   "Moteur de recherche",
   "Motor de búsqueda"
  ],
  "Autofill forms": [
   "Űrlapok automatikus kitöltése",
   "AutoFill-Formulare",
   "Form. saisie auto",
   "Autocompletar formularios"
  ],
  "Save passwords": [
   "Jelszavak mentése",
   "Passwörter speichern",
   "Enregistrer les mots de passe",
   "Guardar contraseñas"
  ],
  "Home page": [
   "Kezdőoldal",
   "Startseite",
   "Page d'accueil",
   "Página de inicio",
   "Homepage"
  ],
  "Privacy": [
   "Adatvédelem",
   "Datenschutz",
   "Confidentialité",
   "Privacidad"
  ],
  "Accessibility": [
   "Kisegítő lehetőségek",
   "Bedienungshilfen",
   "Accessibilité",
   "Accesibilidad"
  ],
  "Content settings": [
   "Tartalombeállítások",
   "Inhaltseinstellungen",
   "Paramètres de contenu",
   "Ajustes de contenido"
  ],
  "Bandwidth management": [
   "Sávszélesség kezelése",
   "Bandbreitenverwaltung",
   "Gestion bande passante",
   "Gestión de ancho de banda"
  ],
  "About Chrome": [
   "A Chrome névjegye",
   "Über Chrome",
   "À propos de Chrome",
   "Información sobre Chrome"
  ],
  "Help": [
   "Súgó",
   "Hilfe",
   "Aide",
   "Ayuda"
  ]
 },
 "gmailprefs": {
  "Settings": [
   "Beállítások",
   "Einstellungen",
   "Paramètres",
   "Ajustes"
  ],
  "General settings": [
   "Általános beállítások",
   "Allgemeine Einstellungen",
   "Paramètres généraux",
   "Ajustes generales"
  ],
  "Archive & delete actions": [
   "Műveletek archiválás és törlése",
   "Aktionen \"Archivieren\" und \"Löschen\"",
   "Actions d'archivage et de suppression",
   "Archivar y eliminar"
  ],
  "Swipe to archive": [
   "Csúsztassa ujját az archiváláshoz",
   "Zum Archivieren wischen",
   "Faire glisser pour archiver",
   "Desliza para archivar"
  ],
  "In conversation list": [
   "Beszélgetéslistában",
   "In einer Unterhaltungsliste",
   "Dans la liste des conversations",
   "En la lista de conversaciones"
  ],
  "Sender image": [
   "Küldő képe",
   "Bild des Absenders",
   "Image de l'expéditeur",
   "Imagen del remitente"
  ],
  "Sender image summary": [
   "Megjelenítés a név mellett a beszélgetések listájában",
   "Neben Namen in der Konversationsliste anzeigen",
   "Afficher à côté du nom dans la liste des conversations",
   "Mostrar junto al nombre en la lista de conversaciones",
   "Show beside name in conversation list"
  ],
  "Reply all": [
   "Válasz mindenkinek",
   "Allen antworten",
   "Répondre à tous",
   "Responder a todos"
  ],
  "Reply all summary": [
   "Használat alapértelmezettként értesítő üzenetekhez",
   "Als Standard für Antworten auf Benachrichtigungen verwenden",
   "Utiliser par défaut pour les réponses aux notifications de messages",
   "Usar como predeterminada para responder a notificaciones de mensajes",
   "Use as default for replies to message notifications"
  ],
  "Auto-fit messages": [
   "Üzenet automatikus méretezése",
   "Nachrichten autom. anpassen",
   "Ajustement auto des messages",
   "Ajuste de mensajes"
  ],
  "Auto-fit summary": [
   "Üzenetek kicsinyítése, hogy elférjenek a képernyőn.",
   "Nachrichten für die Anzeige auf dem Bildschirm verkleinern",
   "Ajuster la taille des messages à celle de l'écran",
   "Adaptar mensajes al tamaño de la pantalla",
   "Shrink messages to fit the screen"
  ],
  "Auto-advance": [
   "Automatikus léptetés",
   "Automatisch fortfahren",
   "Avance automatique",
   "Avance automático"
  ],
  "Action Confirmations": [
   "Művelet megerősítései",
   "Aktionsbestätigungen",
   "Confirmations des actions",
   "Confirmaciones de acciones"
  ],
  "Confirm before deleting": [
   "Megerősítés kérése törlés előtt",
   "Vor Löschen bestätigen",
   "Confirmer avant suppression",
   "Confirmar para eliminar"
  ],
  "Confirm before archiving": [
   "Megerősítés kérése archiválás előtt",
   "Vor Archivieren bestätigen",
   "Confirmer avant archivage",
   "Confirmar para archivar"
  ],
  "Confirm before sending": [
   "Megerősítés kérése küldés előtt",
   "Vor Senden bestätigen",
   "Confirmer avant envoi",
   "Confirmar para enviar"
  ],
  "Inbox type": [
   "Postaládatípus",
   "Art des Posteingangs",
   "Type de boîte de réception",
   "Tipo de bandeja de entrada"
  ],
  "Inbox categories": [
   "Beérkező levelek kategóriái",
   "Kategorien des Posteingangs",
   "Catégories de boîte de réception",
   "Categorías de la bandeja de entrada"
  ],
  "Notifications": [
   "Értesítések",
   "Benachrichtigungen",
   "Notifications",
   "Notificaciones"
  ],
  "Inbox sound & vibrate": [
   "Hang és rezgés beérkező üzenetekhez",
   "Ton & Vibration für Posteingang",
   "Sonnerie et vibreur de la boîte de réception",
   "Vibración y sonido de Recibidos"
  ],
  "Signature": [
   "Aláírás",
   "Signatur",
   "Signature",
   "Firma"
  ],
  "Signature dialog": [
   "Aláírás",
   "Signatur",
   "Signature",
   "Firma",
   "Signature"
  ],
  "Not set": [
   "Nincs beállítva",
   "Nicht festgelegt",
   "Non définie",
   "Sin configurar"
  ],
  "Data usage": [
   "Adathasználat",
   "Datenverbrauch",
   "Consommation des données",
   "Uso de datos"
  ],
  "Sync Gmail": [
   "Gmail szinkronizálása",
   "Gmail synchronisieren",
   "Synchroniser Gmail",
   "Sincronizar Gmail"
  ],
  "Days of mail to sync": [
   "Ennyi nap leveleinek szinkronizálása",
   "E-Mails: zu synchronisierende Tage",
   "Nombre de jours à synchroniser",
   "Días para sincronizar correo"
  ],
  "Manage labels": [
   "Címkék kezelése",
   "Labels verwalten",
   "Gérer les libellés",
   "Administrar etiquetas"
  ],
  "Download attachments": [
   "Mellékletek letöltése",
   "Anhänge herunterladen",
   "Télécharger les pièces jointes",
   "Descargar adjuntos"
  ],
  "Download attachments summary": [
   "Mellékletek automatikus letöltése az üzenetekbe Wi-Fin keresztül",
   "Anhänge neuer Nachrichten automatisch über WLAN herunterladen",
   "Télécharger automatiquement les pièces jointes aux messages récents via Wi-Fi",
   "Descargar automáticamente adjuntos de mensajes recientes por Wi-Fi",
   "Auto-download attachments to recent messages via Wi-Fi"
  ],
  "Primary": [
   "Elsődleges",
   "Allgemein",
   "Principale",
   "Principal"
  ],
  "Primary summary": [
   "Személyek közötti beszélgetések és üzenetek, amelyek nem jelennek meg más kategóriákban. Ha minden levelét egyetlen beérkező levelek mappában szeretné megkapni, törölje a jelet a többi négyzetből.",
   "Private Konversationen und Nachrichten, die nicht in anderen Kategorien erscheinen. Wenn Sie nur einen Posteingang nutzen möchten, deaktivieren Sie alle anderen Optionen.",
   "Les conversations et les messages privés ne figurant dans aucune autre catégorie. Pour n'utiliser qu'une seule boîte de réception, décochez toutes les autres.",
   "Conversaciones y mensajes entre dos personas que no aparecen en otras categorías. Para recibir todos los mensajes en una única carpeta Recibidos, desactiva el resto de opciones.",
   "Person-to-person conversations and messages that don't appear in other categories. To receive all mail in one inbox, uncheck all others."
  ],
  "Social": [
   "Közösségi",
   "Soziale Netzwerke",
   "Rés. sociaux",
   "Social"
  ],
  "Social summary": [
   "Üzenetek közösségi hálózatokból, médiafájl-megosztó webhelyekről és online társkeresőkből",
   "Nachrichten von sozialen Netzwerken, Foto- und Videoplattformen und Online-Partnerbörsen",
   "Messages provenant de réseaux sociaux, de sites de partage de fichiers multimédias et de sites de rencontre",
   "Mensajes de medios sociales, sitios donde se comparte contenido multimedia y servicios de citas online",
   "Messages from social networks, media sharing sites, online dating services"
  ],
  "Promotions": [
   "Promóciók",
   "Werbung",
   "Promotions",
   "Promociones"
  ],
  "Promotions summary": [
   "Akciók, ajánlatok és más marketing jellegű e-mailek",
   "Angebots- und andere Werbe-E-Mails",
   "Promotions, offres et autres e-mails commerciaux",
   "Promociones, ofertas y otros mensajes de publicidad",
   "Deals, offers, and other marketing email"
  ],
  "Updates": [
   "Frissítések",
   "Benachrichtigungen",
   "Mises à jour",
   "Notificaciones"
  ],
  "Updates summary": [
   "Személyes, automatikusan generált frissítések, például visszaigazolások, nyugták, számlák és kimutatások",
   "Automatisch erzeugte Statusinformationen persönlicher Art, zum Beispiel Bestätigungen, Belege, Rechnungen oder Kontoauszüge",
   "Mises à jour personnelles générées automatiquement telles que les confirmations, reçus, factures et relevés",
   "Notificaciones personales generadas automáticamente: confirmaciones, recibos, facturas y extractos de cuentas",
   "Personal, auto-generated updates, including confirmations, receipts, bills, and statements"
  ],
  "Forums": [
   "Fórumok",
   "Foren",
   "Forums",
   "Foros"
  ],
  "Forums summary": [
   "Üzenetek online csoportoktól, vitafórumokból és levelezőlistákból",
   "Nachrichten aus Online-Gruppen, Diskussionsforen und Mailinglisten",
   "Messages provenant de groupes en ligne, de forums de discussion et de listes de diffusion",
   "Mensajes de grupos online, grupos de debate y listas de distribución",
   "Messages from online groups, discussion boards, and mailing lists"
  ],
  "Include starred in Primary": [
   "Csillagozott üzenetek az Elsődleges lapon",
   "Markierte Nachrichten im Bereich \"Allgemein\" anzeigen",
   "Messages suivis dans \"Principale\"",
   "Mostrar destacados en Principal"
  ],
  "Starred category": [
   "A módosítások a szinkronizálás után jelennek meg",
   "Änderungen erscheinen nach der Synchronisierung.",
   "Modifications prises en compte après synchro.",
   "Los cambios aparecerán después de sincronizar",
   "Changes appear after sync"
  ],
  "Changes appear after sync": [
   "A módosítások a szinkronizálás után jelennek meg",
   "Änderungen erscheinen nach der Synchronisierung.",
   "Modifications prises en compte après synchro.",
   "Los cambios aparecerán después de sincronizar"
  ],
  "Default Inbox": [
   "Normál levelek",
   "Standard-Posteingang",
   "Boîte de réception par défaut",
   "Bandeja de entrada predeterminada"
  ],
  "Priority Inbox": [
   "Fontos levelek",
   "Sortierter Eingang",
   "Prioritaire",
   "Prioritarios"
  ],
  "Newer": [
   "Újabb",
   "Neuer",
   "Conversation précédente",
   "Más reciente"
  ],
  "Older": [
   "Korábbi",
   "Älter",
   "Conversation suivante",
   "Más antigua"
  ],
  "Conversation list": [
   "Beszélgetéslista",
   "Konversationsliste",
   "Liste des conversations",
   "Lista de conversaciones"
  ],
  "About Gmail": [
   "A Gmail névjegye",
   "Über Gmail",
   "À propos de Gmail",
   "Acerca de Gmail"
  ],
  "Message text size": [
   "Üzenet szövegének mérete",
   "Nachrichtentextgröße",
   "Taille du texte des messages",
   "Tamaño de texto del mensaje"
  ],
  "Message actions": [
   "Üzenetműveletek",
   "E-Mail-Aktionen",
   "Actions relatives aux messages",
   "Acciones de mensajes"
  ],
  "Show archive only": [
   "Csak az archiválás megjelenítése",
   "Nur \"Archivieren\" anzeigen",
   "N'afficher que le bouton \"Archiver\"",
   "Mostrar solo archivar"
  ],
  "Show delete only": [
   "Csak a törlés megjelenítése",
   "Nur \"Löschen\" anzeigen",
   "N'afficher que le bouton \"Supprimer\"",
   "Mostrar solo eliminar"
  ],
  "Show archive & delete": [
   "Archiválás és törlés megjelenítése",
   "\"Archivieren\" und \"Löschen\" anzeigen",
   "Afficher les boutons \"Archiver\" et \"Supprimer\"",
   "Mostrar archivar y eliminar"
  ],
  "Tiny": [
   "Apró",
   "Sehr klein",
   "Très petite",
   "Muy pequeño"
  ],
  "Small": [
   "Kicsi",
   "Klein",
   "Petite",
   "Pequeño"
  ],
  "Normal": [
   "Normál",
   "Normal",
   "Normale",
   "Normal"
  ],
  "Large": [
   "Nagy",
   "Groß",
   "Grande",
   "Grande"
  ],
  "Huge": [
   "Óriási",
   "Sehr groß",
   "Très grande",
   "Enorme"
  ],
  "Always show": [
   "Mindig látszik",
   "Immer anzeigen",
   "Toujours afficher",
   "Mostrar siempre"
  ],
  "Only show in portrait": [
   "Megjelenítés csak álló tájolásban",
   "Nur im Hochformat anzeigen",
   "Afficher uniquement en mode Portrait",
   "Mostrar solo en modo vertical"
  ],
  "Don't show": [
   "Ne jelenjen meg",
   "Nicht anzeigen",
   "Ne pas afficher",
   "No mostrar"
  ]
 }
};
