"""Writes versions/<v>/alarm-strings.js: the DeskClock strings of the ringing alarm (AlarmAlert / AlarmActivity) as
that factory image words them, with its Hungarian, German, French and Spanish translations (from
_aosp/<device>/strings-index.json). Keys a release does not have are left out.
    python docs/alarm-strings.py             -> 4.0.4, 4.3, 4.4.4, 5.1.1"""
import json, sys
ROOT = __file__.replace('\\', '/').rsplit('/docs/', 1)[0] + '/'
DEVICES = {'maguro': '4.0.4', 'mako': '4.3', 'hammerhead': '4.4.4', 'shamu': '5.1.1'}
KEYS = """alarm_alert_snooze_text alarm_alert_dismiss_text default_label""".split()
OPTIONAL = """description_direction_left description_direction_right alarm_alert_snoozed_text alarm_alert_off_text
alarm_alert_snooze_until alarm_alert_snooze_set""".split()


def main(device):
    version = DEVICES[device]
    index = json.load(open(f'{ROOT}_aosp/{device}/strings-index.json', encoding='utf-8'))
    found = {}
    for en, rows in index.items():
        for apk, name, tr in rows:
            if apk.startswith('DeskClock') and (name in KEYS or name in OPTIONAL):
                found[name] = {'en': en, **{k: v for k, v in tr.items() if v}}
    missing = [k for k in KEYS if k not in found]
    if missing: sys.exit(f'{device}: missing {missing}')
    table = {k: found[k] for k in KEYS + OPTIONAL if k in found}
    js = (f'/* Generated by docs/alarm-strings.py from the {version} factory image DeskClock: the ringing alarm texts. */\n'
          f'window.AlarmStrings = {json.dumps(table, ensure_ascii=False, separators=(",", ":"))};\n')
    open(f'{ROOT}versions/{version}/alarm-strings.js', 'w', encoding='utf-8', newline='\n').write(js)
    print(version, len(table), 'strings')


if __name__ == '__main__':
    for d in sys.argv[1:] or DEVICES: main(d)
