"""Builds a version's boot animation from its factory image's /system/media/bootanimation.zip: one WebP sprite sheet per
part (the frames cropped to what any frame ever draws on the black background, scaled for a 2x screen at most) and
versions/<v>/boot-animation.js with desc.txt's size, fps and parts (p / c, count, pause), which global-actions.js plays
as that release's BootAnimation::movie() does.
    python docs/bootanimation.py crespo      -> versions/2.3.6
    python docs/bootanimation.py maguro      -> versions/4.0.4
    python docs/bootanimation.py mako        -> versions/4.3
    python docs/bootanimation.py hammerhead  -> versions/4.4.4
    python docs/bootanimation.py shamu       -> versions/5.1.1"""
import io, json, math, os, re, sys, zipfile
from PIL import Image

ROOT = __file__.replace('\\', '/').rsplit('/docs/', 1)[0] + '/'
# device: (version, display width x height in px, release whose parser reads desc.txt)
DEVICES = {'crespo': ('2.3.6', (480, 800), 'p'), 'maguro': ('4.0.4', (720, 1280), 'p'), 'mako': ('4.3', (768, 1280), 'pc'),
           'hammerhead': ('4.4.4', (1080, 1920), 'pc'), 'shamu': ('5.1.1', (1440, 2560), 'pc')}
TARGET = 780        # px across a 390 px wide phone screen at 2x
BUDGET = 16e6       # decoded pixels for all sheets together


def main(device):
    version, (dw, dh), kinds = DEVICES[device]
    z = zipfile.ZipFile(f'{ROOT}_aosp/{device}/system/media/bootanimation.zip')
    desc = z.read('desc.txt').decode().splitlines()
    aw, ah, fps = map(int, desc[0].split()[:3])
    parts = []
    for line in desc[1:]:
        m = re.match(r'\s*([pc])\s+(\d+)\s+(\d+)\s+(\S+)', line)
        # Releases before 4.3 read only "p" lines (sscanf "p %d %d %s").
        if not m or m.group(1) not in kinds: continue
        kind, count, pause, path = m.group(1), int(m.group(2)), int(m.group(3)), m.group(4)
        names = sorted(n for n in z.namelist() if n.startswith(path + '/') and n.lower().endswith(('.png', '.jpg')))
        parts.append({'path': path, 'complete': kind == 'c', 'count': count, 'pause': pause, 'names': names})
    frames = {n: Image.open(io.BytesIO(z.read(n))).convert('RGB') for p in parts for n in p['names']}
    sw, sh = next(iter(frames.values())).size
    # Every frame is drawn at desc.txt's size, centred on the display, over black.
    box = None
    for im in frames.values():
        b = im.convert('L').point(lambda v: 255 if v > 8 else 0).getbbox()
        if b: box = b if not box else (min(box[0], b[0]), min(box[1], b[1]), max(box[2], b[2]), max(box[3], b[3]))
    cw, ch = box[2] - box[0], box[3] - box[1]
    shown = aw / sw * 390 / dw                       # css px per source px on a 390 px wide screen
    scale = min(1, TARGET / 390 * shown)
    total = len(frames) * cw * ch
    scale = min(scale, math.sqrt(BUDGET / total))
    fw, fh = max(1, round(cw * scale)), max(1, round(ch * scale))
    out_parts = []
    for i, p in enumerate(parts):
        n = len(p['names'])
        cols = max(1, min(n, math.ceil(math.sqrt(n * fh / fw))))
        rows = math.ceil(n / cols)
        sheet = Image.new('RGB', (cols * fw, rows * fh))
        for j, name in enumerate(p['names']):
            im = frames[name].crop(box).resize((fw, fh), Image.LANCZOS)
            sheet.paste(im, ((j % cols) * fw, (j // cols) * fh))
        file = f'boot-{p["path"]}.webp'
        sheet.save(f'{ROOT}versions/{version}/assets/{file}', 'WEBP', quality=82, method=6)
        out_parts.append({'sheet': f'assets/{file}', 'frames': n, 'cols': cols, 'rows': rows, 'complete': p['complete'],
                          'count': p['count'], 'pause': p['pause']})
        print(version, file, n, 'frames', f'{cols}x{rows}', sheet.size, os.path.getsize(f'{ROOT}versions/{version}/assets/{file}') // 1024, 'KB')
    # The cropped box in display px, as fractions of the display (the power layer covers the whole screen).
    k = aw / sw
    x0, y0 = (dw - aw) / 2 + box[0] * k, (dh - ah) / 2 + box[1] * k
    data = {'fps': fps, 'box': [round(x0 / dw, 5), round(y0 / dh, 5), round(cw * k / dw, 5), round(ch * k / dh, 5)], 'parts': out_parts}
    js = ('/* Generated by docs/bootanimation.py from the factory image\'s /system/media/bootanimation.zip ('
          f'{aw}x{ah} at {fps} fps on the {dw}x{dh} display). */\n'
          f'window.BootAnimationData = {json.dumps(data, separators=(",", ":"))};\n')
    open(f'{ROOT}versions/{version}/boot-animation.js', 'w', encoding='utf-8', newline='\n').write(js)
    print(js)


if __name__ == '__main__':
    for d in sys.argv[1:] or DEVICES: main(d)
