"""Writes versions/4.0.4/calendar-timezones.js for the 4.0.4 Calendar editor: the time zones
of the Galaxy Nexus image's CalendarGoogle (res/values*/arrays.xml timezone_values and timezone_labels, which
ICS's TimezoneAdapter lists as "(GMT+1:00) Amsterdam") as window.CalendarTimezones = [[id, en, hu, de, fr, es], ...]
in the array's order. 4.3, 4.4.4 and 5.1.1 have TimeZonePickerDialog instead (docs/timezonepicker.py).
    python docs/calendar-timezones.py"""
import json
from loguru import logger; logger.remove()
from androguard.core.apk import APK
ROOT = __file__.replace('\\', '/').rsplit('/docs/', 1)[0] + '/'
res = APK(f'{ROOT}_aosp/maguro/system/app/CalendarGoogle.apk').get_android_resources()
pkg = [name for name in res.get_packages_names() if name != 'android'][-1]
def array(name):
    out = {}
    for config, entry in res.get_res_configs(res.get_res_id_by_key(pkg, 'array', name), None):
        lang, region = config.get_language(), config.get_country()
        if region and '\x00' not in region: continue
        lang = '' if '\x00' in lang else lang
        if lang in out: continue
        out[lang] = [res.get_resolved_res_configs(v.data)[0][1] if v.data_type == 1 else v.format_value() for _, v in entry.item.items]
    return out
ids, labels = array('timezone_values')[''], array('timezone_labels')
rows = [[zone] + [(labels.get(lang) or labels[''])[i] for lang in ('', 'hu', 'de', 'fr', 'es')] for i, zone in enumerate(ids)]
USERS = {'4.0.4': "its Calendar's TimezoneAdapter"}
for v, user in USERS.items():
    js = (f'/* Generated by docs/calendar-timezones.py from CalendarGoogle.apk of the maguro image (timezone_values, timezone_labels) for {user}: [id, en, hu, de, fr, es]. */\n'
          f'window.CalendarTimezones = {json.dumps(rows, ensure_ascii=False, separators=(",", ":"))};\n')
    open(f'{ROOT}versions/{v}/calendar-timezones.js', 'w', encoding='utf-8', newline='\n').write(js)
print(len(rows), 'zones', rows[20])
