"""Writes versions/<v>/chrome-pak.js: the New Tab page texts Chrome keeps in its locale .pak files (the chrome://newtab
page of Chrome 27 / 32 and the incognito page), read from each factory image's Chrome.apk in English, Hungarian, German,
French and Spanish, and copies the page's own images out of resources.pak. The string ids differ between builds, so
each text is found by its English value in en-US.pak. Run from the repository root:
    python docs/chrome-pak.py"""
import base64, gzip, json, re, struct, zipfile
ROOT = __file__.replace('\\', '/').rsplit('/docs/', 1)[0] + '/'
VERSIONS = {
    '4.4.4': {'apk': '_aosp/hammerhead/system/app/Chrome.apk', 'build': '32.0.1700.99', 'prefix': 'c32-',
              'strings': {'otr': "<strong>You've gone incognito.</strong>", 'sync': '<p>\n          Tabs you have opened in Chrome on your other devices',
                          'mobile': 'Mobile bookmarks'},
              'page': 'ntp_android'},
}
LANGS = ['en-US', 'hu', 'de', 'fr', 'es']
def pak(apk, name):
    b = zipfile.ZipFile(ROOT + apk).read('assets/' + name)
    version = struct.unpack('<I', b[:4])[0]
    count, off = (struct.unpack('<I', b[4:8])[0], 9) if version == 4 else (struct.unpack('<H', b[8:10])[0], 12)
    entries = [struct.unpack('<HI', b[off + i * 6: off + i * 6 + 6]) for i in range(count + 1)]
    out = {}
    for i in range(count):
        d = b[entries[i][1]:entries[i + 1][1]]
        if d[:2] == b'\x1f\x8b': d = gzip.decompress(d)
        out[entries[i][0]] = d
    return out
def clean(html):
    # One line, the "Learn more" / "Enable sync" links as plain text (the simulator has no help or sync pages).
    html = re.sub(r'\s+', ' ', html.decode('utf-8')).strip()
    html = re.sub(r'<a [^>]*>(.*?)(</a>|</p>)', r'<span class="chr-link">\1</span>', html)
    return html
for version, cfg in VERSIONS.items():
    en = pak(cfg['apk'], 'en-US.pak')
    ids = {}
    for key, start in cfg['strings'].items():
        hits = [rid for rid, d in en.items() if d.startswith(start.encode())]
        assert hits, (version, key)
        ids[key] = hits[0]
    data = {key: [] for key in ids}
    for lang in LANGS:
        p = pak(cfg['apk'], lang + '.pak')
        for key, rid in ids.items(): data[key].append(clean(p[rid]))
    # The NTP page's images (data: URIs in resources.pak): the 2x document / folder favicon boxes, the default
    # thumbnail and the incognito icon.
    res = pak(cfg['apk'], 'resources.pak')
    page = next(d.decode('utf-8', 'replace') for d in res.values() if b'most_visited_list' in d and b'incognito_container' in d)
    css = ''.join(re.findall(r'<style>(.*?)</style>', page, re.S))
    def uri(selector, media=None):
        part = css
        if media: part = css[css.index(media):]
        m = re.search(re.escape(selector) + r'\s*\{[^}]*url\((data:image/png;base64,[^)]+)\)', part)
        return base64.b64decode(m.group(1).split(',', 1)[1])
    images = {'ntp-document': uri('.favicon-box.document', '(-webkit-min-device-pixel-ratio: 2.0)'),
              'ntp-folder': uri('.favicon-box.folder', '(-webkit-min-device-pixel-ratio: 2.0)'),
              'ntp-thumbnail': uri("body[device='phone'] #most_visited_list .thumbnail"),
              'ntp-incognito': base64.b64decode(re.search(r'id="incognito_container".*?src="data:image/png;base64,([^"]+)"', page, re.S).group(1))}
    for name, png in images.items(): open(f"{ROOT}versions/{version}/assets/{cfg['prefix']}{name}.png", 'wb').write(png)
    out = (f"/* Generated by docs/chrome-pak.py from Chrome {cfg['build']}'s locale .pak files (en-US, hu, de, fr, es). Do not edit. */\n"
           f"window.ChromePak = {json.dumps(data, ensure_ascii=False, indent=1)};\n")
    open(f'{ROOT}versions/{version}/chrome-pak.js', 'w', encoding='utf-8', newline='\n').write(out)
    print(version, {k: v for k, v in ids.items()}, list(images))
