"""Builds versions/<v>/dtp.js and dtp.css (AOSP frameworks/opt/datetimepicker in each image's Calendar) from
docs/datetimepicker.template.js and the CSS below, with the image's own Done text colour, scale and translations.
    python docs/datetimepicker.py"""
import json
ROOT = __file__.replace('\\', '/').rsplit('/docs/', 1)[0] + '/'
VERSIONS = {
    # version: (app, image, 1 dp in px, done_text_color_normal)
    '4.3': ('CalendarGoogle 201306090', 'Nexus 4 JWR66Y', .8516, '#333333'),
    '4.4.4': ('CalendarGoogle 201308023', 'Nexus 5 KTU84P', .906, '#333333'),
    '5.1.1': ('Google Calendar 5.0.1', 'Nexus 6 LMY48Y', .906, '#000000'),
}
# done_label (Calendar) and time_picker_dialog_title (framework), as the images translate them.
STRINGS = {'Done': ['Kész', 'Fertig', 'OK', 'Listo'], 'Set time': ['Idő beállítása', 'Uhrzeit festlegen', "Définir l'heure", 'Establecer hora']}
CSS = """/* datetimepicker (dtp.js) of %(app)s, %(image)s; 1 dp = %(d)spx. Generated by docs/datetimepicker.py. */
.dtp{--d:%(d)spx;position:absolute;z-index:26;left:50%%;top:50%%;transform:translate(-50%%,-50%%);width:calc(270 * var(--d));max-width:94%%;background:#f2f2f2;box-shadow:0 6px 24px #0009;font-family:Roboto,RobotoICS,sans-serif;color:#999;user-select:none}
.dtp button{font-family:inherit;cursor:pointer}
.dtp-header{height:calc(30 * var(--d));display:flex;align-items:center;justify-content:center;background:#999;color:#fff;font-size:calc(14 * var(--d))}
.dtp-selected{display:flex;flex-direction:column;align-items:center;height:calc(125 * var(--d));background:#fff}
.screen .dtp-md,.screen .dtp-year{display:flex;flex-direction:column;align-items:center;padding:0;border:0;background:none;color:#999;line-height:1}
.screen .dtp-md.on,.screen .dtp-year.on{color:#33b5e5}
.screen .dtp-md:active,.screen .dtp-year:active{color:#0099cc}
.dtp-md span{margin-top:calc(6 * var(--d));font-size:calc(30 * var(--d))}
.dtp-md b{font-weight:400;font-size:calc(75 * var(--d));margin:calc(-6 * var(--d)) 0 calc(-8 * var(--d))}
.screen .dtp-year{font-size:calc(30 * var(--d))}
.dtp-animator{height:calc(270 * var(--d));overflow:hidden}
.dtp-month{height:100%%;display:flex;flex-direction:column;touch-action:none}
.dtp-month-title{flex:none;display:flex;align-items:center;justify-content:center;height:calc(50 * var(--d));color:#999;font-size:calc(16 * var(--d))}
.dtp-letters,.dtp-days{display:grid;grid-template-columns:repeat(7,1fr);padding:0 calc(8 * var(--d))}
.dtp-letters span{text-align:center;font-size:calc(10 * var(--d));color:#999}
.dtp-days{flex:1;grid-auto-rows:calc(34 * var(--d));align-items:center;padding-top:calc(4 * var(--d))}
.screen .dtp-days button{position:relative;height:100%%;padding:0;border:0;background:none;color:#999;font-size:calc(16 * var(--d))}
.screen .dtp-days button.today{color:#33b5e5}
.screen .dtp-days button.sel::before{content:"";position:absolute;left:50%%;top:50%%;width:calc(32 * var(--d));height:calc(32 * var(--d));transform:translate(-50%%,-50%%);border-radius:50%%;background:#33b5e53c}
.dtp-years{height:100%%;overflow-y:auto;scrollbar-width:none}
.screen .dtp-years button{display:block;width:100%%;height:calc(64 * var(--d));padding:0;border:0;background:none;color:#999;font-size:calc(22 * var(--d))}
.screen .dtp-years button.sel{color:#33b5e5;background:radial-gradient(circle at 50%% 50%%,#33b5e53c calc(30 * var(--d)),transparent calc(30.5 * var(--d)))}
.dtp-line{display:block;height:1px;background:#ccc}
.screen .dtp-done{display:block;width:100%%;min-height:calc(48 * var(--d));padding:0;border:0;background:#fff;color:%(done)s;font-size:calc(14 * var(--d))}
.screen .dtp-done:active{background:#33b5e566}
.dtp-theader{display:flex;align-items:center;justify-content:center;height:calc(96 * var(--d));background:#fff;color:#8c8c8c;font-size:calc(60 * var(--d))}
.dtp-theader span{padding:0 calc(4 * var(--d));line-height:1}
.screen .dtp-theader button{padding:0;border:0;background:none;color:#8c8c8c;font-size:calc(60 * var(--d));line-height:1}
.screen .dtp-theader button.on{color:#33b5e5}
.screen .dtp-theader .dtp-ampm-label{align-self:flex-end;margin:0 0 calc(22 * var(--d)) calc(6 * var(--d));font-weight:700;font-size:calc(16 * var(--d))}
.dtp-face{height:calc(270 * var(--d));display:flex;justify-content:center;background:#f2f2f2}
.dtp-radial{height:100%%;aspect-ratio:1;cursor:pointer}
.dtp-radial text{fill:#8c8c8c;text-anchor:middle;dominant-baseline:central;font-family:Roboto,RobotoICS,sans-serif;pointer-events:none}
.dtp-hand{stroke:#33b5e5;stroke-width:.6}
.dtp-sel{fill:#33b5e5;fill-opacity:.24}
.dtp-dot{fill:#33b5e5}
.dtp-ampm{fill:#fff}
.dtp-ampm.on{fill:#33b5e5}
.dtp-radial text.dtp-ampm-t.on{fill:#fff}
"""
template = open(ROOT + 'docs/datetimepicker.template.js', encoding='utf-8').read()
for v, (app, image, d, done) in VERSIONS.items():
    js = template.replace('__STRINGS__', json.dumps(STRINGS, ensure_ascii=False)).replace('__APP__', app).replace('__IMAGE__', image).replace('__DONE__', done)
    open(f'{ROOT}versions/{v}/dtp.js', 'w', encoding='utf-8', newline='\n').write(js)
    open(f'{ROOT}versions/{v}/dtp.css', 'w', encoding='utf-8', newline='\n').write(CSS % {'app': app, 'image': image, 'd': d, 'done': done})
    print(v, 'ok')
