"""Writes versions/<v>/dc-cities.js: the world clock cities of that image's DeskClock (res/values*/cities.xml:
cities_id, cities_tz and cities_names with the Hungarian, German, French and Spanish names) as
window.DeskClockCities = [[id, timeZone, en, hu, de, fr, es], ...] in the APK's order.
    python docs/dc-cities.py             -> 4.3, 4.4.4, 5.1.1"""
import glob, json, sys
from loguru import logger; logger.remove()
from androguard.core.apk import APK
ROOT = __file__.replace('\\', '/').rsplit('/docs/', 1)[0] + '/'
DEVICES = {'mako': '4.3', 'hammerhead': '4.4.4', 'shamu': '5.1.1'}


def arrays(apk, name):
    r = apk.get_android_resources(); pkg = r.get_packages_names()[-1]
    out = {}
    for config, entry in r.get_res_configs(r.get_res_id_by_key(pkg, 'array', name), None):
        lang = (config.get_qualifier() or '').split('-')[0]
        if lang and lang not in ('hu', 'de', 'fr', 'es'): continue
        items = []
        for _, value in entry.item.items:
            if value.data_type == 1:
                key = r.get_resource_xml_name(value.data).split('/')[-1]
                items.append(('@', key))
            else: items.append(value.format_value())
        out.setdefault(lang, items)
    return out


def strings(apk, lang):
    r = apk.get_android_resources(); pkg = r.get_packages_names()[-1]
    return r


def main(device):
    version = DEVICES[device]
    path = glob.glob(f'{ROOT}_aosp/{device}/system/**/DeskClock*.apk', recursive=True)[0]
    apk = APK(path)
    ids, tzs, names = arrays(apk, 'cities_id')[''], arrays(apk, 'cities_tz')[''], arrays(apk, 'cities_names')
    assert len(ids) == len(tzs) == len(names['']), (len(ids), len(tzs), len(names['']))
    rows = []
    for i, (cid, tz) in enumerate(zip(ids, tzs)):
        row = [cid, tz, names[''][i]]
        for lang in ('hu', 'de', 'fr', 'es'):
            local = names.get(lang)
            row.append(local[i] if local and len(local) == len(ids) else names[''][i])
        rows.append(row)
    js = (f'/* Generated by docs/dc-cities.py from the {version} image\'s DeskClock (cities.xml): [id, time zone, en, hu, de, fr, es]. */\n'
          f'window.DeskClockCities = {json.dumps(rows, ensure_ascii=False, separators=(",", ":"))};\n')
    open(f'{ROOT}versions/{version}/dc-cities.js', 'w', encoding='utf-8', newline='\n').write(js)
    print(version, len(rows), 'cities', rows[0], rows[len(rows) // 2])


if __name__ == '__main__':
    for d in sys.argv[1:] or DEVICES: main(d)
