"""Generates versions/2.3.6/gb-strings-music.js from the Nexus S GRK39F image's MusicGoogle.apk (Music 2.3.6, the AOSP
Music classes in Google's build), in English, Hungarian, German, French and Spanish. Run from the repository root with
the image extracted (see _aosp/extract_image.py):
    python docs/gb-music-strings.py
The output keeps the docs/gb-strings.py shape, window.GBStrings.music = {strings: {key: {en, hu, ...}}, plurals: {key:
{en: {one, other}, ...}}}; music.js, the dialogs in simulator.js and the search settings read it."""
import json, re
from loguru import logger; logger.remove()
from androguard.core.apk import APK
LANGS = ['en', 'hu', 'de', 'fr', 'es']
QUANTITY = {0x01000004: 'other', 0x01000006: 'one'}
KEYS = '''musicbrowserlabel search_hint search_settings_description goto_start party_shuffle party_shuffle_off delete_item shuffle_all
nowplaying_title partyshuffle_title artists_title albums_title tracks_title playlists_title search_title no_tracks_title ringtone_menu
ringtone_menu_short play_selection add_to_playlist queue new_playlist new_playlist_name_template create_playlist_create_text
create_playlist_overwrite_text remove_from_playlist shuffle_on_notif shuffle_off_notif repeat_all_notif repeat_current_notif
repeat_off_notif emptyplaylist browse_menu albums_menu tracks_menu playlists_menu unknown_artist_name unknown_album_name onesong
albumsongseparator recentlyadded recentlyadded_title podcasts_listitem play_all save_as_playlist clear_playlist durationformatshort
delete_playlist_menu edit_playlist_menu rename_playlist_menu playlist_deleted_message
'''.split()
PLURALS = ['Nalbums', 'Nsongs', 'Nsongscomp', 'NNNtrackstoplaylist']
a = APK('_aosp/crespo/system/app/MusicGoogle.apk'); r = a.get_android_resources(); pkg = r.get_packages_names()[0]
def clean(v): return re.sub(r'\\(["\'])', r'\1', v).replace('\\n', '\n')
strings, plurals = {}, {}
for key in KEYS:
    rid = r.get_res_id_by_key(pkg, 'string', key)
    if rid is None: raise SystemExit(f'missing string {key}')
    vals = {}
    for cfg, v in r.get_resolved_res_configs(rid):
        q = cfg.get_qualifier() or 'en'
        if q in LANGS: vals[q] = clean(v)
    strings[key] = {q: vals.get(q, vals['en']) for q in LANGS}
for key in PLURALS:
    rid = r.get_res_id_by_key(pkg, 'plurals', key)
    if rid is None: raise SystemExit(f'missing plurals {key}')
    vals = {}
    for cfg, entry in r.get_res_configs(rid):
        q = cfg.get_qualifier() or 'en'
        if q not in LANGS: continue
        vals[q] = {QUANTITY[k]: clean(r.stringpool_main.getString(item.data)) for k, item in entry.item.items if k in QUANTITY}
    plurals[key] = {q: vals.get(q, vals['en']) for q in LANGS}
out = '/* Generated by docs/gb-music-strings.py from the Nexus S GRK39F image (MusicGoogle.apk 2.3.6). Do not edit. */\n'
out += 'window.GBStrings = window.GBStrings || {};\n'
out += 'window.GBStrings["music"] = ' + json.dumps({'strings': strings, 'plurals': plurals}, ensure_ascii=False, indent=0) + ';\n'
open('versions/2.3.6/gb-strings-music.js', 'w', encoding='utf-8', newline='\n').write(out)
print(len(strings), 'strings,', len(plurals), 'plurals')
