"""Generates versions/2.3.6/gb-strings-<app>.js from AOSP android-2.3.6_r1 string resources (en, hu, de, fr, es).
Each output defines window.GBStrings[<app>] = {strings: {key: {en, hu, de, fr, es}}}.
Usage: python docs/gb-strings.py contacts   (see APPS below for the sources and keys)."""
import re, sys, json, html, urllib.request

LANGS = ['', '-hu', '-de', '-fr', '-es']
APPS = {
    'contacts': {
        'sources': ['https://raw.githubusercontent.com/aosp-mirror/platform_packages_apps_contacts/android-2.3.6_r1/res/values%s/strings.xml'],
        'keys': '''dialerIconLabel recentCallsIconLabel contactsIconLabel contactsFavoritesLabel favoritesFrquentSeparator noContacts noContactsHelpText
noFavoritesHelpText recentCalls_empty recentCalls_callNumber recentCalls_editNumberBeforeCall recentCalls_addToContact recentCalls_removeFromRecentList
recentCalls_deleteAll clearCallLogConfirmation_title clearCallLogConfirmation type_incoming type_outgoing type_missed callBack callAgain returnCall
callDetailTitle call_mobile call_home call_work call_other sms_mobile sms_home sms_work sms_other menu_search menu_newContact menu_displayGroup menu_accounts
menu_import_export menu_addStar menu_removeStar menu_editContact menu_deleteContact menu_share menu_call menu_sendSMS menu_sendEmail add_2sec_pause
add_wait searchHint viewContactTitle starredList frequentList dialer_addAnotherCall dialer_useDtmfDialpad dialer_returnToInCallScreen
callDetailsDurationFormat menu_viewContact email_home email_work email_other email email_custom'''.split(),
    },
}


def clean(value):
    value = re.sub(r'<xliff:g[^>]*>(.*?)</xliff:g>', r'\1', value, flags=re.S)
    value = re.sub(r'<[^>]+>', '', value).strip()
    if value.startswith('"') and value.endswith('"'):
        value = value[1:-1]
    value = value.replace("\\'", "'").replace('\\"', '"').replace('\\n', '\n').replace('\\u2026', '…')
    return html.unescape(re.sub(r'[ \t]*\n[ \t]*', '\n', value))


def build(name):
    app, out = APPS[name], {}
    for lang in LANGS:
        code = lang[1:] or 'en'
        for source in app['sources']:
            try:
                text = urllib.request.urlopen(source % lang).read().decode('utf-8')
            except Exception:
                continue
            for key in app['keys']:
                m = re.search(r'<string name="%s"(?: product="default")?[^>]*>(.*?)</string>' % re.escape(key), text, re.S)
                if m and code not in out.get(key, {}):
                    out.setdefault(key, {})[code] = clean(m.group(1))
    missing = [k for k in app['keys'] if k not in out]
    js = ('/* Generated by docs/gb-strings.py from AOSP android-2.3.6_r1 strings (values, -hu, -de, -fr, -es). Do not edit. */\n'
          'window.GBStrings = window.GBStrings || {};\n'
          'window.GBStrings[%s] = %s;\n' % (json.dumps(name), json.dumps({'strings': out}, ensure_ascii=False, indent=0)))
    open('D:/xampp/htdocs/android-simulator/versions/2.3.6/gb-strings-%s.js' % name, 'w', encoding='utf-8').write(js)
    print(name, 'keys', len(out), 'missing', missing)


if __name__ == '__main__':
    for name in sys.argv[1:] or APPS:
        build(name)
