"""Writes versions/2.3.6/gb-timezones.js: the time zones of the Nexus S image's Settings ZoneList
(res/xml*/timezones.xml) as window.GBTimeZones = [[id, en, hu, de, fr, es], ...] in the file's order.
    python docs/gb-timezones.py"""
import json, re
from loguru import logger; logger.remove()
from androguard.core.apk import APK
from androguard.core.axml import AXMLPrinter
ROOT = __file__.replace('\\', '/').rsplit('/docs/', 1)[0] + '/'
apk = APK(f'{ROOT}_aosp/crespo/system/app/Settings.apk')


def zones(path):
    if path not in apk.get_files(): return {}
    xml = AXMLPrinter(apk.get_file(path)).get_xml().decode('utf-8')
    return dict(re.findall(r'<timezone id="([^"]+)"[^>]*>([^<]*)</timezone>', xml))


base = zones('res/xml/timezones.xml')
local = {lang: zones(f'res/xml-{lang}/timezones.xml') for lang in ('hu', 'de', 'fr', 'es')}
rows = [[zid, name] + [local[lang].get(zid, name) for lang in ('hu', 'de', 'fr', 'es')] for zid, name in base.items()]
js = ('/* Generated by docs/gb-timezones.py from the Nexus S image\'s Settings (timezones.xml): [id, en, hu, de, fr, es]. */\n'
      f'window.GBTimeZones = {json.dumps(rows, ensure_ascii=False, separators=(",", ":"))};\n')
open(f'{ROOT}versions/2.3.6/gb-timezones.js', 'w', encoding='utf-8', newline='\n').write(js)
print(len(rows), 'zones', rows[30])
