"""Writes versions/2.3.6/gb-voice-settings.js: Voice Search 2.1.3's settings texts (VoiceSearch.apk of the Nexus S
GRK39F image: English, German, French and Spanish; the APK has no Hungarian, so a Hungarian phone shows English) and
its languageCodes / languageNames arrays (English names only), for Settings > Voice input & output > Voice recognizer
settings (VoiceSearchPreferences, res/xml/preferences.xml). Run from the repository root:
    python docs/gb-voice-settings.py"""
import json
from loguru import logger; logger.remove()
from androguard.core.apk import APK
APK_PATH = '_aosp/crespo/system/app/VoiceSearch.apk'
KEYS = ['serviceLabel', 'voiceSearchPreferences', 'prefTitle_language', 'prefDialogTitle_language', 'prefDefaultTitlePrefix_language',
        'prefTitle_safeSearch', 'prefDialogTitle_safeSearch', 'prefSummary_safeSearchOff', 'prefSummary_safeSearchModerate',
        'prefSummary_safeSearchStrict', 'prefSummary_safeSearchSuffix', 'prefTitle_profanityFilter', 'prefSummary_profanityFilter',
        'personalization_header', 'personalization_settings_message', 'manage_personalization', 'manage_personalization_message',
        'personalization_popup_first_time_header', 'personalization_popup_message', 'personalization_popup_disable_message',
        'personalization_more_info', 'ok', 'cancel']
LANGS = ['', 'de', 'fr', 'es']
res = APK(APK_PATH).get_android_resources(); pkg = res.get_packages_names()[0]
def by_lang(rid):
    out = {}
    for cfg, value in res.get_resolved_res_configs(rid):
        q = cfg.get_qualifier() or ''
        if q in LANGS: out[q or 'en'] = value
    return out
strings = {key: by_lang(res.get_res_id_by_key(pkg, 'string', key)) for key in KEYS}
def array(name):
    rid = res.get_res_id_by_key(pkg, 'array', name)
    out = {}
    for cfg, entry in res.get_res_configs(rid, None):
        q = cfg.get_qualifier() or ''
        if q in LANGS: out[q or 'en'] = [res.get_resolved_res_configs(it.data)[0][1] if it.is_reference() else res.stringpool_main.getString(it.data) for _, it in entry.item.items]
    return out
safe = array('prefEntries_safeSearch')
codes, names = array('languageCodes')['en'], array('languageNames')['en']
data = {'strings': strings, 'safeSearch': safe, 'languages': list(zip(codes, names))}
out = ('/* Generated by docs/gb-voice-settings.py from VoiceSearch.apk 2.1.3 of the Nexus S GRK39F image. Do not edit. */\n'
       '(() => {\n  const data = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n'
       "  // The APK's text in the phone's language; English where it has none (Hungarian, LINK markers dropped).\n"
       "  const text = (lang, key) => { const row = data.strings[key] || {}; return String(row[lang] ?? row.en ?? key).replace(/START_LINK|END_LINK/g, '').replace(/NEW_LINE ?/g, '\\n'); };\n"
       "  const safeSearch = lang => data.safeSearch[lang] || data.safeSearch.en;\n"
       "  window.GBVoiceSettings = {text, safeSearch, languages: data.languages};\n})();\n")
open('versions/2.3.6/gb-voice-settings.js', 'w', encoding='utf-8', newline='\n').write(out)
print(len(strings), 'strings,', len(codes), 'languages')
