"""Builds versions/<v>/contact-editor.js and contact-editor.css (the Contacts editor of each 4.x image) from
docs/holo-contact-editor.template.js, with the image's Contacts / framework texts (docs/apk-strings.py) and scale.
    python docs/holo-contact-editor.py"""
import subprocess, sys
ROOT = __file__.replace('\\', '/').rsplit('/docs/', 1)[0] + '/'
VERSIONS = {'4.0.4': ('maguro', 'the Galaxy Nexus image (IMM76I)', .85), '4.3': ('mako', 'the Nexus 4 image (JWR66Y)', .8516), '4.4.4': ('hammerhead', 'the Nexus 5 image (KTU84P)', .906)}
CSS = """/* Contacts editor (contact-editor.js) of %(image)s; 1 dp = %(d)spx. Generated by docs/holo-contact-editor.py. */
.hce{--d:%(d)spx;flex:1;min-height:0;overflow-y:auto;background:#fff;color:#000;font-family:Roboto,RobotoICS,sans-serif}
.hce button{font-family:inherit;cursor:pointer}
.hce-account{display:flex;align-items:center;min-height:calc(48 * var(--d));padding:calc(8 * var(--d)) calc(28 * var(--d)) calc(8 * var(--d)) calc(16 * var(--d));background:#eee;font-size:calc(18 * var(--d))}
.hce-account span{flex:1;min-width:0}
.hce-account b{font-weight:400}
.hce-account img{width:calc(12 * var(--d));height:calc(12 * var(--d));align-self:flex-end}
.hce-head{display:flex;align-items:flex-start;padding-top:calc(8 * var(--d))}
.hce-name{flex:1;min-width:0;display:flex;align-items:flex-start}
.hce-fields{flex:1;min-width:0;display:flex;flex-direction:column;padding-left:calc(16 * var(--d))}
.hce-field{width:100%%;min-height:calc(48 * var(--d));padding:calc(10 * var(--d)) calc(4 * var(--d)) calc(6 * var(--d));border:0;border-bottom:1px solid #b5b5b5;background:none;color:#000;font:400 calc(18 * var(--d)) Roboto,RobotoICS,sans-serif;outline:0;box-sizing:border-box}
.hce-field:focus{border-bottom:calc(2 * var(--d)) solid #33b5e5}
textarea.hce-field{resize:none;min-height:calc(64 * var(--d))}
.screen .hce-round{flex:none;display:flex;align-items:center;justify-content:center;width:calc(48 * var(--d));height:calc(48 * var(--d));padding:0;border:0;background:none;margin-right:calc(2 * var(--d))}
.hce-round img{width:calc(16 * var(--d));height:calc(16 * var(--d))}
.screen .hce-photo{flex:none;width:calc(48 * var(--d));height:calc(48 * var(--d));margin:0 calc(8 * var(--d)) 0 0;padding:0;border:0;background:#ddd;overflow:hidden}
.hce-photo img{width:100%%;height:100%%;object-fit:cover;display:block}
.hce-kind-title{margin:calc(8 * var(--d)) calc(8 * var(--d)) 0;padding:0 calc(8 * var(--d));min-height:calc(26 * var(--d));display:flex;align-items:flex-end;border:0 solid transparent;border-width:0 0 calc(2 * var(--d));border-image:url('assets/ce-list_section_divider_holo_custom.png') 3 5 60 6 fill / 0 0 calc(2 * var(--d)) 0 stretch;color:#33b5e5;font-weight:700;font-size:calc(14 * var(--d));text-transform:uppercase}
.hce-row{display:flex;align-items:flex-end}
.screen .hce-type{flex:none;width:calc(100 * var(--d));height:calc(48 * var(--d));padding:0 calc(10 * var(--d)) 0 0;border:0;background:none;color:#000;font-size:calc(12 * var(--d));text-transform:uppercase;text-align:left;box-shadow:inset 0 calc(-1 * var(--d)) #b5b5b5}
.screen .hce-type::after{content:"";display:inline-block;margin-left:calc(4 * var(--d));border:calc(4 * var(--d)) solid transparent;border-bottom-color:#999;border-right-color:#999;vertical-align:bottom}
.screen .hce-add{display:block;width:100%%;min-height:calc(40 * var(--d));padding:0 calc(16 * var(--d));border:0;background:none;color:#999;font-size:calc(18 * var(--d));text-align:left}
.screen .hce-add:active,.screen .hce-type:active,.screen .hce-round:active,.screen .hce-photo:active{background:#33b5e566}
.screen .hce-more{display:block;margin:calc(16 * var(--d)) auto calc(32 * var(--d));padding:calc(10 * var(--d)) calc(24 * var(--d));border:1px solid #c8c8c8;border-radius:calc(2 * var(--d));background:#f0f0f0;color:#000;font-size:calc(16 * var(--d))}
.screen .hce-more:active{background:#33b5e5;color:#fff}
.hce-group{display:flex;align-items:center;gap:calc(10 * var(--d));min-height:calc(48 * var(--d));padding:0 calc(16 * var(--d));font-size:calc(18 * var(--d))}
.hce-group input{width:calc(22 * var(--d));height:calc(22 * var(--d));accent-color:#33b5e5}
.hce-dialog .hce-list{display:flex;flex-direction:column;margin:0 -16px -16px}
.screen .hce-dialog .hce-list button{min-height:48px;padding:0 16px;border:0;border-top:1px solid #3a3a3a;background:none;color:#f2f2f2;font-size:16px;text-align:left}
.screen .hce-dialog .hce-list button:active{background:#33b5e566}
.hce-photos{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;max-height:60vh;overflow-y:auto}
.screen .hce-photos button{aspect-ratio:1;padding:0;border:0;background:#222}
.hce-photos img{width:100%%;height:100%%;object-fit:cover;display:block}
.people-header .people-done{display:flex;align-items:center;gap:calc(8 * %(d)spx);font-weight:700;font-size:calc(12 * %(d)spx);text-transform:uppercase}
.people-header .people-done img{width:calc(32 * %(d)spx);height:calc(32 * %(d)spx)}
.people-star img{width:calc(32 * %(d)spx);height:calc(32 * %(d)spx);display:block}
.people-portrait-photo{width:calc(96 * %(d)spx);height:calc(96 * %(d)spx);object-fit:cover}
.hce-label-input{width:100%%;padding:6px 2px;border:0;border-bottom:2px solid #33b5e5;background:none;color:#fff;font-size:16px;outline:0}
"""
for v, (device, image, d) in VERSIONS.items():
    tmp = ROOT + f'docs/.hce-{device}.template.js'
    open(tmp, 'w', encoding='utf-8', newline='\n').write(open(ROOT + 'docs/holo-contact-editor.template.js', encoding='utf-8').read().replace('__IMAGE__', image))
    r = subprocess.run([sys.executable, ROOT + 'docs/apk-strings.py', device, 'Contacts', tmp.replace(ROOT, ''), f'versions/{v}/contact-editor.js'], cwd=ROOT, capture_output=True, text=True, encoding='utf-8')
    import os; os.remove(tmp)
    if r.returncode: sys.exit(r.stderr)
    open(f'{ROOT}versions/{v}/contact-editor.css', 'w', encoding='utf-8', newline='\n').write(CSS % {'image': image, 'd': d})
    print(v, r.stdout.strip())
