"""Writes versions/<v>/lock-strings.js: the Settings.apk strings of the screen lock setup (ChooseLockGeneric,
ChooseLockPattern, ChooseLockPassword and the Confirm screens) as that factory image words them, with its Hungarian,
German, French and Spanish translations (from _aosp/<device>/strings-index.json).
    python docs/lock-strings.py              -> 4.0.4, 4.3, 4.4.4, 5.1.1"""
import json, sys
ROOT = __file__.replace('\\', '/').rsplit('/docs/', 1)[0] + '/'
DEVICES = {'maguro': '4.0.4', 'mako': '4.3', 'hammerhead': '4.4.4', 'shamu': '5.1.1'}
KEYS = """lock_settings_picker_title unlock_set_unlock_off_title unlock_set_unlock_none_title unlock_set_unlock_biometric_weak_title
unlock_set_unlock_pattern_title unlock_set_unlock_pin_title unlock_set_unlock_password_title
lockpassword_choose_your_pattern_header lockpassword_choose_your_pin_header lockpassword_choose_your_password_header
lockpassword_confirm_your_pattern_header lockpassword_confirm_your_pin_header lockpassword_confirm_your_password_header
lockpassword_confirm_pins_dont_match lockpassword_confirm_passwords_dont_match lockpassword_pin_too_short
lockpassword_password_too_short lockpassword_continue_label lockpassword_cancel_label lockpassword_ok_label
lockpattern_recording_intro_header lockpattern_recording_inprogress lockpattern_recording_incorrect_too_short
lockpattern_pattern_entered_header lockpattern_need_to_confirm lockpattern_need_to_unlock lockpattern_need_to_unlock_wrong
lockpattern_pattern_confirmed_header lockpattern_retry_button_text lockpattern_continue_button_text
lockpattern_confirm_button_text""".split()
OPTIONAL = ['lockpattern_tutorial_cancel_label', 'lockpattern_tutorial_continue_label']  # 5.1 ConfirmLockPassword buttons


def main(device):
    version = DEVICES[device]
    index = json.load(open(f'{ROOT}_aosp/{device}/strings-index.json', encoding='utf-8'))
    found = {}
    for en, rows in index.items():
        for apk, name, tr in rows:
            if apk == 'Settings' and (name in KEYS or name in OPTIONAL):
                found[name] = {'en': en, **{k: v for k, v in tr.items() if v}}
    missing = [k for k in KEYS if k not in found]
    if missing: sys.exit(f'{device}: missing {missing}')
    table = {k: found[k] for k in KEYS + OPTIONAL if k in found}
    js = (f'/* Generated by docs/lock-strings.py from the {version} factory image\'s Settings.apk: the screen lock setup texts. */\n'
          f'window.LockStrings = {json.dumps(table, ensure_ascii=False, separators=(",", ":"))};\n')
    open(f'{ROOT}versions/{version}/lock-strings.js', 'w', encoding='utf-8', newline='\n').write(js)
    print(version, len(table), 'strings')


if __name__ == '__main__':
    for d in sys.argv[1:] or DEVICES: main(d)
