"""Writes versions/5.1.1/lp-cacerts.js: the system CA certificates of the Nexus 6 LMY48Y image (/system/etc/security/
cacerts, read from _aosp/shamu/system.raw.img) for Settings > Security > Trusted credentials. Run from the repository
root: python docs/lp-cacerts.py
Each entry follows TrustedCredentialsSettings.CertHolder: with an O the primary subject is O and the secondary CN (or
OU without a CN); without an O it is CN (or the whole DN) alone; the list is sorted on them, ignoring case. The
details are what SslCertificate.inflateCertificateView shows: issued to and by (CN, O, OU), the validity dates and the
SHA-256 / SHA-1 fingerprints (upper-case hex pairs joined by colons)."""
import json, hashlib, warnings, ext4
warnings.simplefilter("ignore")
from ext4.inode import Directory
from cryptography import x509
from cryptography.x509.oid import NameOID
from cryptography.hazmat.primitives.serialization import Encoding
IMAGE = '_aosp/shamu/system.raw.img'
def part(name, oid):
    values = name.get_attributes_for_oid(oid)
    return values[0].value if values else ''
def names(name):
    return {'cn': part(name, NameOID.COMMON_NAME), 'o': part(name, NameOID.ORGANIZATION_NAME), 'ou': part(name, NameOID.ORGANIZATIONAL_UNIT_NAME)}
certs = []
with open(IMAGE, 'rb') as fh:
    volume = ext4.Volume(fh); folder = volume.inode_at('/etc/security/cacerts')
    for dirent, _ in folder.opendir():
        file = dirent.name_bytes.decode()
        if file in ('.', '..'): continue
        data = volume.inodes[dirent.inode].open().read()
        cert = x509.load_pem_x509_certificate(data[data.index(b'-----BEGIN CERTIFICATE-----'):])
        to, by = names(cert.subject), names(cert.issuer)
        if to['o']: primary, secondary = to['o'], to['cn'] or to['ou']
        elif to['cn']: primary, secondary = to['cn'], ''
        else: primary, secondary = cert.subject.rfc4514_string(), ''
        der = cert.public_bytes(Encoding.DER)
        digest = lambda h: ':'.join(f'{b:02X}' for b in h(der).digest())
        certs.append({'p': primary, 's': secondary, 'to': to, 'by': by,
                      'from': cert.not_valid_before_utc.strftime('%Y-%m-%d'), 'until': cert.not_valid_after_utc.strftime('%Y-%m-%d'),
                      'sha256': digest(hashlib.sha256), 'sha1': digest(hashlib.sha1), 'file': file})
certs.sort(key=lambda c: (c['p'].lower(), c['s'].lower()))
out = ('/* Generated by docs/lp-cacerts.py from the Nexus 6 LMY48Y image\'s /system/etc/security/cacerts. Do not edit. */\n'
       'window.LPCaCerts = ' + json.dumps(certs, ensure_ascii=False, separators=(',', ':')) + ';\n')
open('versions/5.1.1/lp-cacerts.js', 'w', encoding='utf-8', newline='\n').write(out)
print(len(certs), 'certificates')
