"""Generates versions/5.1.1/lp-email-strings.js: the texts lp-email.js draws for Email 7.0 (PrebuiltEmailGoogle) and
Gmail 5.0.2 (PrebuiltGmail) in English, Hungarian, German, French and Spanish, each from its own APK in the Nexus 6
LMY48Y image (both are UnifiedEmail builds, but their translations differ from AOSP 4.4 Email's and from each other).
Run from the repository root with the image extracted (see docs/lp-strings.py):
    LMY48Y_SYSTEM=_aosp/shamu/system python docs/lp-email-strings.py
Each entry maps the key lp-email.js passes to T() to a resource name; 'plurals:name:quantity' takes that quantity."""
import json, os, re, sys
from loguru import logger; logger.remove()
from androguard.core.apk import APK
SYSTEM = os.environ.get('LMY48Y_SYSTEM') or sys.exit('set LMY48Y_SYSTEM')
APPS = {'email': 'app/PrebuiltEmailGoogle/PrebuiltEmailGoogle.apk', 'gmail': 'app/PrebuiltGmail/PrebuiltGmail.apk'}
LANGS = ['en', 'hu', 'de', 'fr', 'es']
QUANTITY = {'other': 0x01000004, 'one': 0x01000006}
ENTRIES = {
    # EmailProvider's mailbox display names (Gmail's own labels come from gmail.js).
    'Inbox': 'mailbox_name_display_inbox', 'Starred': 'mailbox_name_display_starred', 'Drafts': 'mailbox_name_display_drafts',
    'Outbox': 'mailbox_name_display_outbox', 'Sent': 'mailbox_name_display_sent', 'Trash': 'mailbox_name_display_trash',
    # Toolbars, menus and the drawer.
    'Compose': 'compose_title', 'Search': 'menu_search', 'Search hint': 'search_hint', 'Settings': 'menu_settings',
    'Help & feedback': 'help_and_feedback', 'Open navigation drawer': 'drawer_open', 'Navigate up': 'abc_action_bar_up_description',
    'Mark read': 'mark_read', 'Mark unread': 'mark_unread', 'Delete': 'delete', 'Archive': 'archive', 'Move to': 'menu_move_to',
    'Add star': 'add_star', 'Remove star': 'remove_star', 'Reply': 'reply', 'Reply all': 'reply_all', 'Forward': 'forward',
    'Print': 'print', 'Refresh': 'refresh', 'Empty Trash': 'empty_trash',
    # The conversation and ComposeActivity.
    'to %1$s': 'to_message_header', 'me': 'me_object_pronoun', 'Send': 'send', 'Save draft': 'save_draft', 'Discard': 'discard',
    'Discard this message?': 'confirm_discard_text', 'Message saved as draft.': 'message_saved', 'Cancel': 'cancel', 'OK': 'ok',
    'Attach file': 'add_file_attachment', 'Attach picture': 'add_photo_attachment', 'From': 'from', 'To': 'to', 'Cc': 'cc',
    'Bcc': 'bcc', '+ Cc/Bcc': 'add_cc_label', 'Subject': 'subject_hint', 'Compose email': 'body_hint',
    # ConversationListEmptyView (EmptyStateUtils) and EmptyFolderDialogFragment.
    'Empty inbox': 'empty_inbox', 'Empty search': 'empty_search', 'Empty spam': 'empty_spam_folder',
    'Empty trash': 'empty_trash_folder', 'Empty folder': 'empty_folder', 'Empty Trash?': 'empty_trash_dialog_title',
    'Will be deleted (one)': 'plurals:empty_folder_dialog_message:one', 'Will be deleted': 'plurals:empty_folder_dialog_message:other',
}
def clean(v): return re.sub(r'\\(["\'])', r'\1', v).replace('\\n', '\n')
out = {}
for app, path in APPS.items():
    a = APK(os.path.join(SYSTEM, path)); r = a.get_android_resources(); pkg = r.get_packages_names()[0]
    table = out[app] = {}
    for key, name in ENTRIES.items():
        vals = {}
        if name.startswith('plurals:'):
            _, plural, quantity = name.split(':')
            rid = r.get_res_id_by_key(pkg, 'plurals', plural)
            for cfg, entry in r.get_res_configs(rid) if rid else []:
                q = cfg.get_qualifier() or 'en'
                if q not in LANGS: continue
                items = dict(entry.item.items); item = items.get(QUANTITY[quantity]) or items.get(QUANTITY['other'])
                if item is not None: vals[q] = clean(r.stringpool_main.getString(item.data))
        else:
            rid = r.get_res_id_by_key(pkg, 'string', name)
            for cfg, v in r.get_resolved_res_configs(rid) if rid else []:
                q = cfg.get_qualifier() or 'en'
                if q in LANGS: vals[q] = clean(v)
        if 'en' not in vals: print('missing', app, name, file=sys.stderr); continue
        table[key] = [vals.get(q, vals['en']) for q in LANGS]
text = '/* Generated by docs/lp-email-strings.py from the Nexus 6 LMY48Y image (PrebuiltEmailGoogle 7.0, PrebuiltGmail 5.0.2). Do not edit. */\n'
text += 'window.LPEmailStrings = {\n' + ',\n'.join(f'  {app}: {{\n' + ',\n'.join(f'    {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}' for k, v in table.items()) + '\n  }' for app, table in out.items()) + '\n};\n'
open('versions/5.1.1/lp-email-strings.js', 'w', encoding='utf-8', newline='\n').write(text)
print({app: len(t) for app, t in out.items()})
