"""Writes versions/5.1.1/lp-sync-adapters.js: the switches Settings' AccountSyncSettings lists for a Google account on the
Nexus 6 LMY48Y image. Every APK's res/xml <sync-adapter accountType="com.google"> that is userVisible, with the label of
the content provider behind its contentAuthority (ProviderInfo.loadLabel, which falls back to the application label),
in English, Hungarian, German, French and Spanish; providers declared android:syncable="false" are left out, one row per
authority, sorted by the English label. Run from the repository root:
    python docs/lp-sync-adapters.py"""
import glob, json, os, re
from loguru import logger; logger.remove()
from androguard.core.apk import APK
from androguard.core.axml import AXMLPrinter
ROOT = __file__.replace('\\', '/').rsplit('/docs/', 1)[0] + '/'
LANGS = ['en', 'hu', 'de', 'fr', 'es']
adapters, providers, apks = [], {}, {}
def text(apk, ref):
    """{lang: value} of a @7f... reference in an APK (or the literal)."""
    if not ref.startswith('@'): return {'en': ref}
    r = apks[apk].get_android_resources()
    return {(c.get_qualifier() or 'en'): v for c, v in r.get_resolved_res_configs(int(ref[1:], 16)) if (c.get_qualifier() or 'en') in LANGS}
for path in sorted(glob.glob(ROOT + '_aosp/shamu/system/**/*.apk', recursive=True)):
    try:
        a = APK(path); m = a.get_android_manifest_axml().get_xml()
    except Exception: continue
    m = m.decode() if isinstance(m, bytes) else m
    apks[path] = a
    app = re.search(r'<application[^>]*?android:label="([^"]+)"', m)
    for tag in re.findall(r'<provider[^>]*>', m):
        auth = re.search(r'android:authorities="([^"]+)"', tag)
        label = re.search(r'android:label="([^"]+)"', tag) or app
        syncable = 'android:syncable="false"' not in tag
        for au in (auth.group(1).split(';') if auth else []):
            providers.setdefault(au, (path, label.group(1) if label else None, syncable))
    for name in a.get_files():
        if not name.startswith('res/xml/'): continue
        try: x = AXMLPrinter(a.get_file(name)).get_xml()
        except Exception: continue
        x = x.decode() if isinstance(x, bytes) else x
        if '<sync-adapter' not in x or 'accountType="com.google"' not in x or 'userVisible="false"' in x: continue
        au = re.search(r'contentAuthority="([^"]+)"', x).group(1)
        if au.startswith('@'): au = text(path, au)['en']
        adapters.append(au)
rows = {}
for au in adapters:
    if au in rows or au not in providers: continue
    path, label, syncable = providers[au]
    if not syncable or not label: continue
    values = text(path, label)
    rows[au] = [values.get(l, values['en']) for l in LANGS]
data = sorted(rows.values(), key=lambda row: row[0].lower())
out = ('/* Generated by docs/lp-sync-adapters.py from the Nexus 6 LMY48Y image: the Google account\'s sync adapters as\n'
       '   AccountSyncSettings lists them, [en, hu, de, fr, es]. Do not edit. */\n'
       'window.LPSyncAdapters = ' + json.dumps(data, ensure_ascii=False, indent=1) + ';\n')
open(ROOT + 'versions/5.1.1/lp-sync-adapters.js', 'w', encoding='utf-8', newline='\n').write(out)
print(len(data), [row[0] for row in data])
