"""Ringtones, notification sounds and alarms of the five factory images (/system/media/audio) for the simulator:
    python docs/sounds.py plan.json      -> the transcoding plan (unique files by content) and versions/<v>/sounds.js
    node docs/sounds-transcode.mjs plan.json assets/audio
Each file is named <base>-<first 8 hex of its SHA-1>, so a tone shared by several images is stored once and two
different tones with the same name stay apart. sounds.js maps each image's titles (sounds.json) and file names to these
files and names the defaults of build.prop (ro.config.ringtone / notification_sound / alarm_alert); the behaviour lives
in docs/sounds.template.js."""
import glob, hashlib, json, os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))).replace(os.sep, '/') + '/'
IMAGES = [('crespo', '2.3.6'), ('maguro', '4.0.4'), ('mako', '4.3'), ('hammerhead', '4.4.4'), ('shamu', '5.1.1')]
CATS = ['ringtones', 'notifications', 'alarms']
files = {}
template = open(ROOT + 'docs/sounds.template.js', encoding='utf-8').read()
for device, version in IMAGES:
    system = f'{ROOT}_aosp/{device}/system/'
    titles = json.load(open(f'{ROOT}_aosp/{device}/sounds.json', encoding='utf-8'))
    out = {cat: {} for cat in CATS}
    for cat in CATS:
        names = dict(titles.get(cat, []))
        for path in sorted(glob.glob(f'{system}media/audio/{cat}/*')):
            base = os.path.splitext(os.path.basename(path))[0]
            name = f'{base}-{hashlib.sha1(open(path, "rb").read()).hexdigest()[:8]}'
            files.setdefault(name, os.path.relpath(path, ROOT).replace(os.sep, '/'))
            out[cat][base] = [names.get(base, base), name]
    prop = open(system + 'build.prop', encoding='utf-8', errors='replace').read()
    # ro.* properties cannot be changed once set, so the first definition in build.prop wins (crespo lists the
    # notification sound twice: Castor, then OnTheHunt, which the image does not even ship).
    first = lambda key: re.findall(rf'^{key}=(\S+)', prop, re.M)[0].rsplit('.', 1)[0]
    defaults = {'ringtones': first('ro.config.ringtone'), 'notifications': first('ro.config.notification_sound'), 'alarms': first('ro.config.alarm_alert')}
    header = f'/* Generated by docs/sounds.py from the {device} image (/system/media/audio, sounds.json, build.prop). Do not edit. */'
    js = template.replace('__HEADER__', header).replace('__SOUNDS__', json.dumps(out, ensure_ascii=False)).replace('__DEFAULTS__', json.dumps(defaults))
    open(f'{ROOT}versions/{version}/sounds.js', 'w', encoding='utf-8', newline='\n').write(js)
json.dump({'files': files}, open(sys.argv[1], 'w'), indent=1)
print(len(files), 'files')
