"""Builds versions/<v>/stock-strings.js from docs/stock-strings.json: per app, the texts the stock Google app screens
(stock-apps.js) draw, as that version's factory image translates them in the app's own APK (hu, de, fr, es, and the
image's English when it differs from the key). stock-apps.js reads them through S(ctx, app, key) before i18n.js.
    python docs/stock-strings.py
The image's string index comes from docs/image-index.py (_aosp/<device>/strings-index.json)."""
import json, sys
ROOT = __file__.replace('\\', '/').rsplit('/docs/', 1)[0] + '/'
DEVICES = {'4.0.4': 'maguro', '4.3': 'mako', '4.4.4': 'hammerhead', '5.1.1': 'shamu'}
spec = json.load(open(ROOT + 'docs/stock-strings.json', encoding='utf-8'))
for v, apps in spec.items():
    idx = json.load(open(f'{ROOT}_aosp/{DEVICES[v]}/strings-index.json', encoding='utf-8'))
    by = {}
    for en, hits in idx.items():
        for apk, name, tr in hits: by.setdefault((apk, name), (en, tr))
    out, missing = {}, []
    for app, rows in apps.items():
        for key, ref in rows.items():
            apk, _, name = ref.partition(':')
            if (apk, name) not in by: missing.append(f'{app}: {ref}'); continue
            en, tr = by[(apk, name)]
            row = [tr.get(lang, en) for lang in ('hu', 'de', 'fr', 'es')]
            if en != key: row.append(en)
            out.setdefault(app, {})[key] = row
    if missing: sys.exit(f'{v}: missing ' + ', '.join(missing))
    body = json.dumps(out, ensure_ascii=False, indent=1)
    open(f'{ROOT}versions/{v}/stock-strings.js', 'w', encoding='utf-8', newline='\n').write(
        f'/* Generated by docs/stock-strings.py from docs/stock-strings.json and the {DEVICES[v]} factory image. Do not edit. */\nwindow.StockStrings = {body};\n')
    print(v, sum(len(r) for r in out.values()), 'strings')
